### ISSUE TITLE
Add Option to always see the tabs

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#100]
In ADS when you float one widget it hides the tab bar, as seen here:
![always_show_tabs](https://user-images.githubusercontent.com/1664301/73007712-4b79ec80-3e0d-11ea-88c0-77ffb3a4e566.gif)
It would be nice to have an AlwaysShowTabs option like KDDockWidgets:
![always_show_tabs_kddockwidgets](https://user-images.githubusercontent.com/1664301/73007775-677d8e00-3e0d-11ea-8ca2-18a96a202d74.gif)

**Comment by githubuser0xFFFF** [comment]
Why? Could you please elaborate?

**Comment by rolivav** [comment]
Oh right, now that you said that I realize it is a bit of a strange request on it's own, sorry :)

What I actually need is to be able to show a custom menu for the active dock widget instead of the toggle view menu for a group of tabs. This way I could have a standard place to put settings for the widgets, very much like Unity does in their software. I like how compact it looks!
![compact](https://user-images.githubusercontent.com/1664301/73164777-dfd89d80-40f2-11ea-96d2-6eb0fead1827.gif)
Also the look would be a bit more consistent when a widget is docked in different windows.

For this to work I would need to:
1. Add `CDockWidget::setCustomMenu`. If this custom menu is set if would display it instead of the toggle view menu.
2. Add option to always show tabs so that the menu is accessible at all times. It probably would be necessary to check if dragging a floating tab works correctly when it is alone in the dock area and opaque and non-opaque dragging is enabled.

I can fork and make a PR for both of these features if you think they make sense. I figured that the first feature is very specific for the solution I need and you might not think it is worth it to add it to your product, but the second one could make sense. Anyway let me know what you think.

**Comment by githubuser0xFFFF** [comment]
Ah, ok - now I understand your intention.

A pull request is welcome.

**Comment by githubuser0xFFFF** [comment]
i just merged your pull request - thank you.
