### ISSUE TITLE
add option to setAllowedAreas per CDockAreaWidget

### ISSUE THREAD

**Issue by mvidelgauz** [githubuser0xFFFF/Qt-Advanced-Docking-System#104]
In my application I have a special widget that is not Closable, not Movable, not Floatable and also not coverable by other widgets (yes, I need that kind of "central widget" which is conceptually removed in ADS). The first three "not"s I can achieve with DockWidget->setFeature(..., false) but then my special widget can still be covered if the user drops another widget on it's cental (creating two tabs).
To avoid it, I want to exclude CenterDockWidgetArea from a list of allowed drop areas.

![setAllowedAreas per CDockAreaWidget](https://user-images.githubusercontent.com/547740/73477637-526ca600-439d-11ea-89c6-bc019c187801.png)

I have made this mod to your library and would like to issue a pull request for you.

**Comment by githubuser0xFFFF** [comment]
Just merged your pull request - Thank you.
