### ISSUE TITLE
Difference between State and Perspective

### ISSUE THREAD

**Issue by Craftplorer** [githubuser0xFFFF/Qt-Advanced-Docking-System#11]
Hi,
can someone explain me the difference between State and Perspective?
I tried the demo but didn't really noticed any differance.
My second question would be also related to the demo. Is there is any important reason, i should consider when writing my owm application, to use this `MainWindowPrivate struct` in the demo project or just write everthing into the main window (`CMainWindow`) directly?

**Comment by githubuser0xFFFF** [comment]
The state is the current state of the docking system or the saved state. A perspective is a saved state with a name.

The struct MainWindowPrivate is just part of the pimpl idiom. You do not need to use it but Qt uses the pimpl idiom almost everywhere.

**Comment by Craftplorer** [comment]
Thank you very much.
That helped a lot.
