### ISSUE TITLE
Request: improve performance when changing perspectives

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#117]
The feature to change between saved layout works great, but somehow it is very slow. In Photoshop, Unity, Blender, Maya... you can change between layouts instantly, which makes it great to have different workspaces depending on what you are doing.
I haven't looked into it but I assume it is because the layout is removed and rebuilt entirely? I am sure there are optimizations that could be made so that it doesn't need to do that and just rebuild what is necessary.
Also I think the whole manager is doing `setVisible(false)` before restoring a layout to minimize tearing, since it is doing a clear to white. Apart from this not working for applications that block the main thread on destruction, since showing and hiding is done in an event, if the layout was restored faster it should just stop the paint updates.

**Comment by githubuser0xFFFF** [comment]
We have a complex application here that uses the Advanced Docking System with a lot of different complex dock widgets - it is the dark application you can see in the demo video on the main page of this project (https://www.youtube.com/watch?v=7pdNfafg3Qc). When we switch the perspectives, the switching needs ca. 1 - 1.3 seconds. Would be great, if you could specify what _somehow it is very slow means_ excatly means. We also noticed, that switching the whole perspective happens very seldom. Normally you do not switch the perspectives all the time. So yes, maybe it is slower then Photoshop, Unity, Blender, Maya but we never noticed this as an issue and that it is annoying.

When I developed the docking system, I spent a lot of time optimizing the performance for switching the perspectives. I exactly measured the times that it takes to insert the widgets into the splitters and to insert the splitters in other splitters. Whenever you insert a splitter into another splitter then the geometry of all widgets is updated - this causes the times. To improve this, you need to dig very deep into the Qt code and spend a lot of time measuring. 

If you volunteer to do this, then feel free to reopen this issue.

**Comment by rolivav** [comment]
I understand 👍 I see it is a difficult problem to tackle, I know first hand optimizing widget layout updates is one of Qt's worst problems.
For me changing the layout in debug in my application takes around 7 seconds, in release it is much less, 2.5 seconds or so. This is only a problem when the way you use your application has several workspaces that change in documents. 
Although I wish it was better, the performance is fine for me as it is and it does not block me in any way. I wanted to hear your thoughts on it mostly. Thanks for the explanation.

**Comment by githubuser0xFFFF** [comment]
Seven seconds is a lot. Is this an open source application - I would like to try it out. How many dock widgets are in your perspective?

**Comment by rolivav** [comment]
It is not open source, I will measure it better when I have time and come up with better numbers.
It has around 15 different widgets.
