### ISSUE TITLE
Merge your docking system with a visual studio Qt project ?

### ISSUE THREAD

**Issue by BenjaminISART** [githubuser0xFFFF/Qt-Advanced-Docking-System#122]
![image](https://user-images.githubusercontent.com/49271954/74743458-b548b300-5260-11ea-9d62-f248fa4bf4f2.png)

Hello, when I want to add your files to my project it gives me errors like that and others about DLLs (that I don't find in your files).

Is it possible to use your system with visual studio + Qt tool and not with QtCreator ?

Thank you,
Benjamin

**Comment by githubuser0xFFFF** [comment]
Yes, I think it is possible but I do not have any experience with Visual Studio and Qt and therefore can't help you.

**Comment by rolivav** [comment]
Hey @BenjaminISART you need to link it correctly to your project. This repo does not have any DLL dependencies other than Qt. I am guessing you don't generate your project using CMake, you might need to create a project in your solution and add that as a dependency, or add the source to your project and modify every single include path to match your project structure.

**Comment by stijnherfst** [comment]
Alternatively you can use a package manager such as vcpkg. I created a package for that so you can easily install this library.

`vcpkg install qt-advanced-docking-system:x64-windows`

**Comment by BenjaminISART** [comment]
Thank you all, I'll test it and come back later to tell if it worked for me ;)
