### ISSUE TITLE
Possible Tab dragging issue

### ISSUE THREAD

**Issue by githubuser0xFFFF** [githubuser0xFFFF/Qt-Advanced-Docking-System#123]
A user reported an issue with undocking when dragging in horiziontal direction out of the tab bar and then drag in Y direction for undocking.

I cannot reproduce this yet. This is how it looks if I do this in the demo application:
![Unbenannt](https://user-images.githubusercontent.com/4239304/74843931-f1e1e080-532c-11ea-9eb4-24d836e1a490.gif)

**Comment by rolivav** [comment]
Maybe it should create the preview as soon as it leaves the `CDockAreaTitleWidget` or similar container (not sure who is in charge of this anymore).

**Comment by iam-peter** [comment]
The issue I was experiencing is only happening when using `DefaultOpaqueConfig`.
![QtAds-issue-123](https://user-images.githubusercontent.com/7542157/74854080-1a72d600-533f-11ea-97d1-d8a1624776dc.gif)
I would think that as soon as the mouse leaves the `TabBar` while dragging a tab the `DockWidget` should be floating both in x and y direction. When looking at other tab implementations (e.g. Chrome) as soon as the mouse enters a `TabBar` again while dragging a floating `DockWidget` it will be inserted into the `TabBar`, which would be also a nice feature.

**Comment by githubuser0xFFFF** [comment]
Thank you. I just fixed the issue with the wrong initial position of the `CFloatingDockContainer` when using NonOpaque undocking. This was an regression caused by this commit: 418d0740d2ed0fb330dd4479bdb6bec8f2ff84d7

**Comment by githubuser0xFFFF** [comment]
I improved tab dragging (e8332575f8a6a912ce10d36d09b3a33ba0240f70). Tab position is now limited by the tabbar geometry and undocking starts as soon as the mouse leaves the tabbar.
![tabtragging](https://user-images.githubusercontent.com/4239304/74880704-10b39780-536c-11ea-845c-890ab9a3ee27.gif)
