### ISSUE TITLE
Segfault when undocking - Linux

### ISSUE THREAD

**Issue by hhslepicka** [githubuser0xFFFF/Qt-Advanced-Docking-System#124]
Hi,

When using the package with a RHEL linux system I am experiencing a segmentation fault when the detach button is pressed or when the screen is dragged.
I am trying to investigate the issue but I decided to open the issue here in case someone is able to shine some light into it.

Here is part of the backtrace:
```
#0  0x00007f70a3448edc in QWidget::isWindow() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#1  0x00007f70a34f7817 in QDockWidgetLayout::minimumSize() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#2  0x00007f70a3456024 in QLayout::totalMinimumSize() const () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#3  0x00007f70a3456c30 in QLayout::activate() () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#4  0x00007f70a346d8fe in QWidgetPrivate::setVisible(bool) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#5  0x00007f707c793b84 in ads::CDockAreaTabBar::makeAreaFloating(QPoint const&, ads::eDragState) ()
   from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQtAds-2.7.0-py3.6-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-36m-x86_64-linux-gnu.so
#6  0x00007f707c7979be in ads::CDockAreaTitleBar::onUndockButtonClicked() () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQtAds-2.7.0-py3.6-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-36m-x86_64-linux-gnu.so
#7  0x00007f70a62657b8 in QMetaObject::activate(QObject*, int, int, void**) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Core.so.5
#8  0x00007f70a34db1fe in QAbstractButton::clicked(bool) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#9  0x00007f70a34db8b7 in ?? () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#10 0x00007f70a34dc14c in ?? () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
#11 0x00007f70a34dc1e8 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /scratch/slepicka/sandbox/anaconda/mc/envs/pcds_test/lib/python3.6/site-packages/PyQt5/../../../libQt5Widgets.so.5
```

QtAds version is 3.0.0.

**Comment by githubuser0xFFFF** [comment]
Please test again with the current master and the demo application. Do you see the same error?

Do you use the python integration?

**Comment by hhslepicka** [comment]
I will give it a try with the latest.
Yes, it is with the Python integration and the same happens with the demo application.

**Comment by n-elie** [comment]
I was able to reproduce the error under Ubuntu 18.04.4. It is related to the Python bindings and working well using only the C++ version.
This seems to be related to the Linux OS, everything is working fine under Windows.

**Comment by n-elie** [comment]
The segfault occurs if we try to show a CFloatingDockContainer widget

**Comment by hhslepicka** [comment]
@n-elie that is exactly the same that we are seeing in here.
Thank you for also looking into it.

**Comment by rolivav** [comment]
Side thought, it would be nice to implement support for the official Qt python lib, Qt for Python (Pyside2) and add the shiboken bindings. To me it seems like the better option if you had to choose one of them to maintain, but both can live in unison in the repo.

**Comment by n-elie** [comment]
Of course, it would be nice. Could you point me to a good documentation on how to write a Shiboken binding?

**Comment by n-elie** [comment]
Ok, I found doc in the PySide2 sources

**Comment by rolivav** [comment]
you should have all you need in the Qt documentation https://doc.qt.io/qtforpython/shiboken2/index.html

**Comment by hhslepicka** [comment]
While PySide2 is now the official Qt python binding, PyQt is still the most used one. Also, while trying to port some code from PyQt -> PySide2 it was clear that they are still missing wrappers for the Qt library. It is for sure something that would be great to have for this great library.

**Comment by hhslepicka** [comment]
We were able to fix the code and a PR will be up soon. Just finishing tests here.
