### ISSUE TITLE
Top-level splitter is always non-opaque

### ISSUE THREAD

**Issue by nickdademo** [githubuser0xFFFF/Qt-Advanced-Docking-System#128]
When setting:
`config.setFlag(ads::CDockManager::eConfigFlag::OpaqueSplitterResize, true);`

We see that our top-level splitter is non-opaque, while the child splitters are opaque (i.e. correct).

Note:
`config.setFlag(ads::CDockManager::eConfigFlag::OpaqueSplitterResize, false);` yields the correct results (all splitters are non-opaque).

**Comment by githubuser0xFFFF** [comment]
Please tell me how to reproduce this with the demo application.

**Comment by nickdademo** [comment]
Closing this - cause was that the config was being set *after* the dock manager was created. Setting the config before dock manager creation solves it. Is this documented somewhere? (i.e. set config before dock manager creation)

**Comment by githubuser0xFFFF** [comment]
Thank you, I update the documentation in the code
