### ISSUE TITLE
Creating of floating widgets

### ISSUE THREAD

**Issue by skartashev** [githubuser0xFFFF/Qt-Advanced-Docking-System#13]
How can I properly create floating widget?

**Comment by Caprey** [comment]
i add this：
void CDockAreaWidget::setFloating()
{
    auto button = this->titleBarButton(ads::TitleBarButton::TitleBarButtonUndock);
    button->click();
}

**Comment by deanljohnson** [comment]
Is there a better way to create a new dock widget that is initially floating? I currently have something like the following:

```
m_dockManager->addDockWidget(ads::DockWidgetArea::LeftDockWidgetArea, floatingWidget);
floatingWidget->dockAreaWidget()->titleBarButton(ads::TitleBarButton::TitleBarButtonUndock)->click();
```

This works, but causes the layout of the main window to flicker before the floating widgets is shown as floating. I assume this is because the addDockWidget line immediately adjusts the layout of window.

The goal here is for the user to be able to press a button which will instantiate the widget as a floating window that can then be docked by the user if they wish.

**Comment by deanljohnson** [comment]
I think I have found a solution. It feels like a hack (and is probably vulnerable to breaking when the library is updated) but it works. I think it would be great if the library provided a simpler way of doing this in the future (if there isn't a better solution now):

```cpp
// Create the widget we want to initialize as floating
auto* dockWidget= new ads::CDockWidget("Floating");
dockWidget->setWidget(widget);

// Find a widget to 'tab' into.
// This prevents the docked widgets from having their sizes adjusted.
// Probably need to handle the case in which there are no opened DockAreas...
auto* dockAreaWidgetToTabInto = m_DockManager->openedDockAreas()[0];
// Remember the currently active index. We will need this later.
int activeIndex = dockAreaWidgetToTabInto->currentIndex();

// Add the widget as a new tab
m_DockManager->addDockWidgetTabToArea(dockWidget, dockAreaWidgetToTabInto);
// Simulate a double click on the widgets tab so that it undocks.
// This will set the active tab to the last tab, not what was
// previously active.
QMouseEvent event(QEvent::MouseButtonDblClick, QPointF(), Qt::MouseButton::LeftButton, 0, 0);
QApplication::sendEvent(dockWidget->tabWidget(), &event);

// Restore the active tab
if (activeIndex != -1)
    dockAreaWidgetToTabInto->setCurrentIndex(activeIndex);

// Now set the size of the floating window to whatever you want.
// The above code would leave the floating window the same size as the dock area
// the floating widget was tabbed in to.
// This could obviously use a non-internal implementation of findParent.
ads::internal::findParent<ads::CFloatingDockContainer*>(dockWidget)->resize(...);
```

**Comment by githubuser0xFFFF** [comment]
The dock manager now has a function **addDockWidgetFloating** that enables the creation of initial floating widgets.

The CDockWidget now also has a function **setFloating()** to make thze dock widget floating from code
