### ISSUE TITLE
Outter dock areas are missing

### ISSUE THREAD

**Issue by iam-peter** [githubuser0xFFFF/Qt-Advanced-Docking-System#130]
After hovering shortly with the mouse pointer over the `DockSplitter` the outter `DockWidgetArea` (`LeftDockWidgetArea`, `RightDockWidgetArea`, `TopDockWidgetArea`, `BottomDockWidgetArea`) indicators are no longer shown. The inner DropAreas are still visible.
![output](https://user-images.githubusercontent.com/7542157/76103692-62962780-5fd2-11ea-9014-32db2142ece1.gif)
I checked out the newest version before writing this issue.

**Comment by githubuser0xFFFF** [comment]
Sorry, what a stupid bug. Just fixxed it with this commit: 59c783831ad23238e41205a5da854a9eb39ce777
