### ISSUE TITLE
Closing a dock with CDockWidget::DockWidgetDeleteOnClose set does not emit closed() signal

### ISSUE THREAD

**Issue by nickdademo** [githubuser0xFFFF/Qt-Advanced-Docking-System#134]
As the title says:

Closing a dock with `CDockWidget::DockWidgetDeleteOnClose` set does not emit `closed()` signal.

Is this by design?

The only way to detect a dock close in this case is via: 
`CDockManager::dockWidgetRemoved`

**Comment by nickdademo** [comment]
I also assume this commented-out line can be removed: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/DockAreaWidget.cpp#L500

**Comment by githubuser0xFFFF** [comment]
I just fixed this with commit c541f2c69b519eceb76ffc54589175c9fd0da8a6

Please test, if it works now.

**Comment by nickdademo** [comment]
Fixed, thanks!

**Comment by githubuser0xFFFF** [comment]
I fixed your issues quickly, so it woul be fair, if you could support this project with a 10 Euro donation via the PayPal button on the front page. Thank you.

**Comment by githubuser0xFFFF** [comment]
Thank you very much for your donation :smiley:. If you have an application that I can show on the frontpage in the showcase section or that you would like to show, then it would be great, if you have a screenshot, where the ADS is visible and a text about your application.

Thank you again and kind regards, Uwe

**Comment by nickdademo** [comment]
> Thank you very much for your donation 😃. If you have an application that I can show on the frontpage in the showcase section or that you would like to show, then it would be great, if you have a screenshot, where the ADS is visible and a text about your application.
> 
> Thank you again and kind regards, Uwe

Definitely! Will be in touch soon :)
