### ISSUE TITLE
Can't include library in project.

### ISSUE THREAD

**Issue by Stanlyhalo** [githubuser0xFFFF/Qt-Advanced-Docking-System#135]
I'm trying to use this in my project but I can't seem to use it like the example you show, is their a good detailed explanation of adding the .lib from the build into the project and using it?

**Comment by githubuser0xFFFF** [comment]
I do not exactly know what you mean - could you please elaborate? Can you run the demo application?

**Comment by Shoopufff** [comment]
You can include the library by building the project with qmake / make and then adding that library to your .pro file for your project e.g. 

LIBS += -L/opt/Qt-Advanced-Docking-System/lib
LIBS += -lqtadvanceddocking
