### ISSUE TITLE
Includes of the lib have not the local format

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#136]
Is it possible to have the all the library includes with "" instead of <> to avoid the collisions with includes I can have with the same names in my code ?

In the cpp files it seems ok by for exemple in DockManager.h, there are those:
#include <ads_globals.h>
#include <DockContainerWidget.h>
#include <DockWidget.h>
#include <FloatingDockContainer.h>

Maybe with a subdirectory it can be good as well.

Thank you !

**Comment by githubuser0xFFFF** [comment]
Ok, I will check how to change this. I would prefer to put everything into the directory ads and then include via `<ads/DockWidget.h>`

**Comment by githubuser0xFFFF** [comment]
I just noticed, that this is a bug. Normall all includes should have  "".

**Comment by githubuser0xFFFF** [comment]
Should be fixed with commit 542618fd4eb81eb9e3fd78b55db7ccc0a3e9f41a

**Comment by IkkiNit** [comment]
Thank you, it's working fine ;)
