### ISSUE TITLE
Qt Widget Minimum Size

### ISSUE THREAD

**Issue by Shoopufff** [githubuser0xFFFF/Qt-Advanced-Docking-System#139]
I've created a custom widget and have specified a minimum size for it but when adding it to the DockManager it allows me to reduce its size below that minimum. 

Is there a way to force the DockManager to adhere to these size constraints or is this not possible?

**Comment by githubuser0xFFFF** [comment]
No, at the moment it is not implemented this way. The DockWidget reimplements the `minimumSizeHint()` function and provides a very small size to ensure that a widgets `minimumSizeHint() `will not block resizing of the dock widget. 

```c++
//============================================================================
QSize CDockWidget::minimumSizeHint() const
{
	return QSize(60, 40);
}
```


But I think, I could add this as an option when creating the dock widget to allow a dock widget to adhere the size constraints of the internal content widget.

**Comment by githubuser0xFFFF** [comment]
I just created the dev branch and implemented this feature. You can configure the minimumSizeHintMode() of a dock widget via setMinimumSizeHintMode() function now. Please test the new feature and tell me if it is ok. Then I can merge it into the master.

**Comment by Shoopufff** [comment]
I was originally using the minimum size variables instead of re-implementing minimumSizeHint for my custom widget and it did not work in that case. However, changing it to use minimumSizeHint instead worked for me. Thanks a bunch!

**Comment by githubuser0xFFFF** [comment]
Added proper minimumSizeHint() handling to CDockArea and test case to demo application and merged everything into master.
