### ISSUE TITLE
Crash while opening context-menu

### ISSUE THREAD

**Issue by XenotriX** [githubuser0xFFFF/Qt-Advanced-Docking-System#140]
When right-clicking on a tab, the application crashes instead of showing the context-menu.

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/1b6e449b4a640f04a12892b242413caa008207be/src/DockWidgetTab.cpp#L433

The problem occurs on the line above, `d->DockArea` is `0x0`. This seems to be related to the changes in 5b60e39.

**Comment by rolivav** [comment]
Mm I thought all dock widgets where always tied to a dock area. Are you getting this crash when displaying a context menu on a floating tab or something?
Although it should be on a dock area there too...

**Comment by XenotriX** [comment]
It happens in the demo. The problem is not that the dock widget is not bound to a dock area but the dock widget tab isn't anymore. `DockWidgetTabPrivate::DockArea` is set to `nullptr` in the structs' declaration but it is never updated.

**Comment by githubuser0xFFFF** [comment]
Cann you please tell me, how I can reproduce the problem in the demo application. I just tested the debug and release build on Windows an when right clicking on a tab I can see the context menu.

**Comment by XenotriX** [comment]
My bad. Seems like you already fixed this issue with 2c15d5dacd2272eb87b12646a24a026d02f28338, we need to update our fork. Sorry about that :)

**Comment by githubuser0xFFFF** [comment]
Great that I could help you. Would be fair, if you could support this project with a 10 Euro donation via the PayPal button on the frontpage.
