### ISSUE TITLE
HORIZONTAL ELLIPSIS (U+2026, Three dot) cause error: "new line in constant"

### ISSUE THREAD

**Issue by hanjianqiao** [githubuser0xFFFF/Qt-Advanced-Docking-System#141]
![image](https://user-images.githubusercontent.com/7146341/77996484-4632a400-7360-11ea-989d-861da0f2b4e1.png)
Chinese in the image is "New Line in Constant"

I get this error when compiling the example, and I'm very confused.

If I change it to three real dots, then it can be successfully compiled.

ENV: QT5.9.9, vs2017

**Comment by githubuser0xFFFF** [comment]
I have to admit, I have no idea. Changing it to three real dots is no solution because QFontMetrics uses this character for eliding the text (https://doc.qt.io/qt-5/qfontmetrics.html#elidedText)

**Comment by hanjianqiao** [comment]
I probably figure it out by comparing different build system. MSV 2017 did not recognize "…" properly. So, wirte Unicode literal "…" as anscii literal u8"\u2026" seems works fine.
