### ISSUE TITLE
Change when tab title is elided

### ISSUE THREAD

**Issue by Shoopufff** [githubuser0xFFFF/Qt-Advanced-Docking-System#142]
Is there a way to change when the title of the current tab elides?

Changing the default setElideMode from ElideRight to ElideNone inexplicably causes the tab menu to not have any text.

**Comment by githubuser0xFFFF** [comment]
Currently only ElideRight is supported properly

**Comment by githubuser0xFFFF** [comment]
Fixed `ElidingLabel` (commit dbf90a423388fba7ef6a7816322b911ec6b241f0) to properly suport `Qt::ElideNone`. You can now implement your custom `CDockComponentsFactory` to provide dock widget tabs with other elide mode.

**Comment by githubuser0xFFFF** [comment]
I fixed your issues, so it would be fair if you do a 10 Euro donation via the Donation button on the front page to support this project.
