### ISSUE TITLE
Fullscreen mode not working

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#145]
Hello,

I used on a QDockWidget the method showFullscreen and I have no problems but with ads::CDockWidget the dock is not going onto fullscreen.

my code is here:
if (!pDockWidget->isFloating())
{
	pDockWidget->setFloating();
}
pDockWidget->showFullScreen();

The dock is going floating as expected but not in fullscreen after that.

Thank you for your help !

**Comment by githubuser0xFFFF** [comment]
I fixed this in branch [bugfixing](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/bugfixing) with this commit: 1f995299f056ea6bd621d17392fb974015975544

That means your code in your previous post should work with this fix.

Please test and report if this fixes the problem.

**Comment by IkkiNit** [comment]
I think line 902 of src/DockWidget.cpp, it's Super::showNormal();

Otherwise the fix is fine to me, thank you !

**Comment by githubuser0xFFFF** [comment]
Ok, thank you. I wll fix this and then test on Linux before the merge into master.

**Comment by githubuser0xFFFF** [comment]
I just merged this into master. Please note, that if you use `showFullscreen` then your application is not really cross platform because this dose not work on Linux: https://stackoverrun.com/de/q/4338623

I added a comment to the showFullScreen() function to inform the user about this.
