### ISSUE TITLE
Changing widgets of the dock problems

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#146]
Hello,

I have a situation  where I change the widget of the dock. First I do:
`pDock->setWidget(pWidgetA);`
Later in the code I have those:
```
pDock->takeWidget();
pDock->setWidget(pWidgetB);
```
Maybe after that I will put again pWidgetA.

I have two issues with it:
1. It seems that the second time it will create a second scroll area without destroying the previous one
2. When I drag and drop somewhere else this dock, it causes a crash

Maybe the correction of the point 1 will fix the crash.

Thank you a lot for your help !

**Comment by githubuser0xFFFF** [comment]
Could you please elaborate, why you do this? I just would like to understand your use case.

**Comment by IkkiNit** [comment]
I have a properties dock widget that change its content widget when selecting something.
If the selection is an object of type A, I display a special A widget.
If the selection is an object of type B, I display a special B widget.
But the dock is always the same.

**Comment by githubuser0xFFFF** [comment]
You can easily work around that problem by inserting a QScrollArea as content widget and then replace the conten of this scroll area

**Comment by IkkiNit** [comment]
Yes of course for this problem I have work around.
It's just in order to have a better implementation of the API ;)

**Comment by githubuser0xFFFF** [comment]
I fixed this in branch [bugfixing](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/bugfixing).

Please test and report if this fixes the problem.

**Comment by IkkiNit** [comment]
This fix is perfect to me, thank you !

**Comment by githubuser0xFFFF** [comment]
Great. I fixed this issue quickly for you and I also fixed your other issue so it would be fair, if you do a 10 Euro Donation via the Donation button on the front page to support this project.

**Comment by IkkiNit** [comment]
Done.

**Comment by githubuser0xFFFF** [comment]
Thank you very much for your support
