### ISSUE TITLE
Force toggleViewInternal(true) when adding new DockWidget to Container

### ISSUE THREAD

**Issue by DatName** [githubuser0xFFFF/Qt-Advanced-Docking-System#148]
First of all, thank you for sharing this great piece of software! Really appreciate it!

I apologize in advance if I am missing something obvious (I just started digging this recently), but I have a following problem. When closing all DockWidgets via GUI, I am not able to _see_ new DockWidgets, when I am adding them programmatically. My setup is this:
```
CDockManager::setConfigFlags(CDockManager::DefaultOpaqueConfig);
CDockManager::setConfigFlag(CDockManager::DockAreaHasTabsMenuButton, false);
CDockManager::setConfigFlag(CDockManager::RetainTabSizeWhenCloseButtonHidden, true);

m_dockManager = new ads::CDockManager(parent);
```
than later I have following slot (label is "proportional" to number of previously added widgets
```
counter += 1
ads::CDockWidget* dockWidget = new ads::CDockWidget(label + QString::number(counter));
dockWidget->setWidget(myWidget); 
m_dockManager->addDockWidget(ads::TopDockWidgetArea, dockWidget);
```
Note, that I intentionally do not use ```toggelViewAction()``` provided by ```dockWidget```.
So at first, this works perfectly. But when I close all widgets via GUI close button, newly added DockWidgets are not shown in GUI. 

Adding ```toggleViewInternal(true)``` right after ```addDockArea(NewDockArea, area);``` in ```DockContainerWidgetPrivate::dockWidgetIntoContainer()``` fixes the issue for me.

I really can not tell if this is OK to forcibly toggle Open state like this or it just hides some other problem and the issue should really be fixed some other way.

**Comment by githubuser0xFFFF** [comment]
Is it possible for you to provide a minimum testcase that shows this problem?

**Comment by githubuser0xFFFF** [comment]
I just pushed a commit that should fix this issue. The demo application now also has the test action Create Docked Editor to test this. Please checkout the master and test, if the issue is fixed.
