### ISSUE TITLE
Question: QTabBar-like behavior possible?

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#153]
Currently this docking system functions similarly to a [QTabWidget](https://doc.qt.io/qt-5/qtabwidget.html) which allows each tab to have it's own child widget and automatically shows the appropriate widget.

I am curious if there is a way to use it to function more similarly to a [QTabBar](https://doc.qt.io/qt-5/qtabbar.html). That way the widget that is shown can be more finely controlled...but still keep all the docking/floating/moving behavior that this project provides.

---

My use case is as follows. I have multiple 'document' objects that are being edited (one document per tab) by the single 'editor' widget which does all the heavy work...and I do not want to create multiple editors. I would like to have only 1 editor widget.

I was previously using a `QTabBar` so that when the user clicked a different tab, I would just swap current document that the editor is working on and the editor widget itself would never actually be changed/shown/hidden at all.

As a first attempt I have tried things such as creating multiple `CDockWidget` object that have the same widget, or adding the `CDockWidget` multiple times. I was not surprised when this did not function correctly.

Any advice or tips is greatly appreciated.

**Comment by githubuser0xFFFF** [comment]
Sorry, but I don't thing, the ADS is suited fir your use case.
