### ISSUE TITLE
Prevent DockWidget being closed

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#154]
Is there a way to prevent a DockWidget being closed? I would like to prompt the user before closing a DockWidget, such as asking to save settings, a file, "are you sure" type of question but I am not sure there is any way to prevent it being closed. I am using the example code:

```cpp
    m_DockManager = new ads::CDockManager(this);

    ads::CDockWidget* dw = new ads::CDockWidget("Editor 1");
    dw->setWidget(new MyFancyEditor());
    dw->setFeature(ads::CDockWidget::DockWidgetFeature::DockWidgetDeleteOnClose, true);
    m_DockManager->addDockWidgetTab(ads::CenterDockWidgetArea, dw);

    connect(dw, &ads::CDockWidget::closeRequested, []() { qInfo("CDockWidget::closeRequested()");});
```

The `closeRequested()` signal works, but it goes ahead and closes it anyways afterwards. I am attempting to replace my usage of `QTabBar` and `QTabWidget` that both have the [tabCloseRequested(int index)](https://doc.qt.io/qt-5/qtabwidget.html#tabCloseRequested) which allows the flexibility of determining if/when to close the widget.

**Comment by nickdademo** [comment]
You need to set `CDockWidget::CustomCloseHandling` to true on the dock widget and then use the `closeRequested` signal.

**Comment by githubuser0xFFFF** [comment]
Please have a lock into the demo application. If you create editors dynamically via main menu **Tests -> Create Editor** then you will see exactly the requested behaviour.

**Comment by dail8859** [comment]
Ah thank you both for the help! I will try that.

**Comment by dail8859** [comment]
This did exactly what I needed. I guess I simply overlooked that flag. Apologies for the noise.
