### ISSUE TITLE
mainwindow with sidebar

### ISSUE THREAD

**Issue by ruddig** [githubuser0xFFFF/Qt-Advanced-Docking-System#155]
hi
first thank you for your great work!

Could you help me, how I can set up the ADS so that just yellow area will be used for docking?
![ads](https://user-images.githubusercontent.com/5494287/81005493-51d92500-8e4e-11ea-842a-871ebf0cb0e7.JPG)

**Comment by githubuser0xFFFF** [comment]
Hi, 

I just added a commit with an example that shows how to implement this. Please checkout the master branch and have a look into the examples/sidebar subfolder of the project:

![ADS_Sidebar](https://user-images.githubusercontent.com/4239304/81296148-c2ac5700-9071-11ea-97e9-5944a47db5bc.png)

**Comment by ruddig** [comment]
Great. Thank you. I did a small donation.

**Comment by githubuser0xFFFF** [comment]
Thank you for your donation.
