### ISSUE TITLE
Can you add collapse tab?

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#157]
Hi, I actually had a similar need to the [autohide feature](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/147) in my backlog.
Instead of autohide it would just be a vertical collapse, exactly the way photoshop handles it. It just hides the content of the tab.
![CollapseTabHeight](https://user-images.githubusercontent.com/1664301/81288018-131cb800-9064-11ea-8b11-2bbe37543945.gif)
Double clicking the tab collapses it, single click on it to show it if it is already collapsed.
I might implement it when I have the time.

**Comment by rolivav** [comment]
I cleared up the description to make it more clear. I added a better gif.

**Comment by githubuser0xFFFF** [comment]
Yes, this is possible. I may do this after I have implemented Auto Hide functionality.

**Comment by rolivav** [comment]
awesome @githubuser0xFFFF !

**Comment by ldng** [comment]
Stackable like in Inkscape would be interesting too :-)

**Comment by ruilvo** [comment]
> 
> 
> Stackable like in Inkscape would be interesting too :-)

Oh most definitely! That would look awesome. Also, have the devs considered tabs that are on the left/right instead of the top?

**Comment by githubuser0xFFFF** [comment]
No pull request since 3 years - closing this issue because there is no interest by many ADS users to have this feature.
