### ISSUE TITLE
Laggy undocking for last dock widget on Linux Manjaro XFCE 5.7.0

### ISSUE THREAD

**Issue by Dadoum** [githubuser0xFFFF/Qt-Advanced-Docking-System#158]
![Laggy](https://user-images.githubusercontent.com/24679280/81295811-49acff80-9071-11ea-9527-84eeb6ae074a.gif)

**My setup:** Linux, Manjaro XFCE 5.7.0-1, Qt 5.14.2, QMake 3.1

**Comment by githubuser0xFFFF** [comment]
Sorry, I cannot reproduce this with the demo application on Ubunto 19.10. Can you reproduce the problem with the demo application?

**Comment by Dadoum** [comment]
Can't do it with the demo (since there is always a window that is docked). But on the example app:
![Laggy2](https://user-images.githubusercontent.com/24679280/81300588-25085600-9078-11ea-9333-cf436afd900f.gif)
What I do here:
I drag the window out, and move a lot the window around. Just after releasing the click, I focus the console behind the window. The window returns in the background after the animation has ended.

**Comment by githubuser0xFFFF** [comment]
I looks like an issue specific to your linux system. I cannot reproduce the problem on Ubuntu 19.10, Kubuntu 19.10 and Ubuntu 14.04. 

That's the Linux world - a lot of distributions, a lot of window managers and somethings always does not work - sorry.

**Comment by Dadoum** [comment]
Will try to find a fix later, thanks

**Comment by githubuser0xFFFF** [comment]
Try to switch to opaque docking mode - maybe this works better for you.

**Comment by githubuser0xFFFF** [comment]
Did opaque docking improve the performance

**Comment by Dadoum** [comment]
I think it was a bug inside Qt, because when I updated my packages it disappeared !
