### ISSUE TITLE
Weird theme issues and artifacts on docking undocking

### ISSUE THREAD

**Issue by Dadoum** [githubuser0xFFFF/Qt-Advanced-Docking-System#159]
![Artifacts](https://user-images.githubusercontent.com/24679280/81298074-8dedcf00-9074-11ea-8347-c4092c3f6048.gif)

**My setup:** Linux, Manjaro XFCE 5.7.0-1, Qt 5.14.2, QMake 3.1

**Comment by githubuser0xFFFF** [comment]
Please provide some more information. For me everythink looks good on your animation.

**Comment by Dadoum** [comment]
There is some artifcats on the undocked title bar. The white border appears and disappear (and does not follow my theme).

**Comment by githubuser0xFFFF** [comment]
Looks some kind of style sheet issue. Try to play around with the stylsheets. I cannot see this in the demo application.

**Comment by Dadoum** [comment]
By changing theme, artifacts can be removed, but the white borders still does not follow my theme guidelines. The white color seems to be hardcoded.
