### ISSUE TITLE
Bug. When undock QDialog this dialog becomes empty. It restores back when it's docked

### ISSUE THREAD

**Issue by KerimMatlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#160]
Hi,

I just started using this library and I liked it.

Let's suppose that I have `QMainWindow` (created in QtCreator) and `QDialog` (created with QDesigner). `QDialog` has some widgets that can't be docked or undocked but the `QDialog` can be docked itself in `MainWindow`. So I wrote the code (just a example):
```
    QDialog* myDialog= new QDialog;
    ads::CDockWidget* dockWidget = new ads::CDockWidget("DialogTitle");
    dockWidget->setWidget(myDialog);
    dockManager->addDockWidgetFloating(dockWidget); // I want to create it floating
```
When I launch the application everything is fine, I can use both `MainWindow` (with its docked widgets) and `QDialog`. I can dock `QDialog` to `MainWindow`. The problems begin when I try to undock the `QDialog`. Two situations are possible:
1) If `QDialog` was tabbed in `MainWindow` then I can successfully undock it.
2) if `QDialog` was docked in free area (was not tabbed) then when I undock it I can only see the clear window instead of my `QDialog`. On the pictures attached I tried to show this situation.

Best regards,
kerim

![1](https://user-images.githubusercontent.com/43808863/81323305-dc639380-909d-11ea-8e03-06a1867f88db.png)
![2](https://user-images.githubusercontent.com/43808863/81323312-de2d5700-909d-11ea-9d9d-5efd720c9a97.png)

**Comment by githubuser0xFFFF** [comment]
You should use a QWidget instead of a QDialog.

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF I just tried rewrite QDialog to QWidget and the problem still exists...

**Comment by githubuser0xFFFF** [comment]
Try to reproduce the problem with the demo application - then I'm able to test it. Or create a small minimal test application that shows this problem. 

I use this library in a commercial product since 2 years and never had such an issue.

**Comment by KerimMatlab** [comment]
ok, few minuts

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF I'm sorry for disturbing you, I cannot reproduce this in external project. It works fine there.
There should be something wrong with my code.
