### ISSUE TITLE
Single DockArea cannot be split

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#164]
(Hopefully I am using the correct terminology)

62ce9dca5d5b702fe704dce372f8ad3b7291749e seems to have introduced a bug when there is only 1 DockArea, it cannot be split until there is a floating dock widget.

Steps to reproduce.

1. Start Demo
1. Combine all areas into a single DockArea
1. Try to split the area by dragging one of the dock areas out.
1. Observe there is no way to split it.
1. Drop the widget to create a floating widget.
1. Move it again and observe it can *now* be split.

See demo:

![splitdockarea](https://user-images.githubusercontent.com/3694843/81507652-d69fc500-92cc-11ea-9c5c-0d4b1320c6f3.gif)

**Comment by githubuser0xFFFF** [comment]
Thank you for the bug report.

I just pushed the commit aa7976dac62a1c1ff62ddac11abfe269885047a1 that should fix this issue. Please test, if it works and feel free to reopen the issue if there are still problems.
