### ISSUE TITLE
Usage of Q_OBJECT in .cpp file

### ISSUE THREAD

**Issue by jankrassnigg** [githubuser0xFFFF/Qt-Advanced-Docking-System#166]
We use ads for our game engine editor:
https://github.com/ezEngine/ezEngine

To integrate it, we copy the code into our repository and then use our own CMakeLists.txt files to set everything up. This works nicely except for one annoyance:

DockAreaTitleBar.cpp uses Q_OBJECT for local classes. DockAreaTitleBar.h also uses the macro. The fact that two files with the same name, just a different extension, must be moc'd is already a problem, as our CMake stuff tries to create the same output file for both input files.

Second, DockAreaTitleBar.cpp then #includes "DockAreaTitleBar.moc" to work around this untypical usage pattern, which again is a problem, because in our system the moc'd file has a different name.

The most "simple" way to fix this for us, currently, is to move all the classes with Q_OBJECT from the cpp into the header. This requires some fixups (adding #include<QToolbutton> and such) but then works.

It would be great, if this could be refactored such that the helper classes in DockAreaTitleBar.cpp are simply declared in a separate header, like all the other Qt code. That way you could still hide the implementation details, but not hide them in a cpp, which would play better with custom build setups.

**Comment by githubuser0xFFFF** [comment]
Please create a pull request. Thank you.

**Comment by githubuser0xFFFF** [comment]
Here are some documentation regarding th inclusion of moc file into the cpp file:

https://wiki.qt.io/Private_QObject_API
https://stackoverflow.com/questions/25250171/how-to-use-the-qts-pimpl-idiom

So I'm uncertain, that we really need to change something. Including the moc file in a cpp is a normal use case scenario that is supported by qmake and CMake. I really would like to help you solve your issues, but I'm not sure, that this is the right way. So if I read your request again:

> The fact that two files with the same name, just a different extension, must be moc'd is already a problem, as our CMake stuff tries to create the same output file for both input files.

it sounds more like a problem in your CMake build structure for me.

**Comment by jankrassnigg** [comment]
I'm not saying that it can't be done, and I probably could change our build system to work exactly like your setup. But that is the real problem. In your C++ code you rely on specific behavior of your build system. Let's put aside that Q_OBJECT is used in a cpp file and that it is used in an identically named header. Those could probably be made to work (though the latter may be tricky in some systems). You still rely on the build system generating a file with one very specific name, in a folder where you can #include files directly.

This will make most people who want to use their own build system get stuck. I am using ads in two projects, one where I control the build system and could do all the necessary changes (though it would be a non-trivial change) and one where I have zero influence on how the build system works and where there are even more quirks how the file names are generated, where the moc'd files end up etc. The fact that you #include a file that does not exist on disk until a build system decides where to put it and how to name it is a major problem for anyone with a custom build system.

And the solution is really so simple. Don't use Q_OBJECT in cpp files. I have worked with multiple different build systems, and many of them automatically detect when Q_OBJECT is used in a header and then do their magic to make it work. All the generated cpp files are added to your solution and that's it.

I will prepare a pull request, with a solution for your consideration.

**Comment by jankrassnigg** [comment]
See #167

**Comment by githubuser0xFFFF** [comment]
Hmm, I do not understand it completely. If you use ads, then you just need to build it with the given qmake or CMake files in the ads and then later add the include path and the library search path and the library to your project - thats it. Or am I wrong?

We use it in a commercial project and simply treat it as a 3rd party library. We add the header include path and link to the library. So what could be the reason to do it differently.

Sorry for all the questions, I just would like to understand the problem, why you do not use the build scripts from the project?

**Comment by githubuser0xFFFF** [comment]
Some additional notes on this subject:

> You still rely on the build system generating a file with one very specific name, in a folder where you can #include files directly.

Sorry, but I do not agree. This is not a build system topic - that is a Qt topic. Qt requires moc compiler which runs before the real compiler runs. So Qt requires an additional build step ahead of the normal compile process. So each build system, that works with Qt needs to properly support the moc compile step.

I just did a quick file search in three big Qt projects:

- Qt itself
- KDE Frameworks
- KDSoap from KDAB

All three projects include moc files at the end of cpp files. So this is not a special for this library. So does it mean, each time you use a library that uses moc this way you are going to fix the library instead of your build system? I do not think, that this works for the Qt source code or the KDE Frameworks. 

So I'm not convinced, that changing ADS is the right approach for your projects, because you will run into the same issue with other libraries.

**Comment by jankrassnigg** [comment]
It feels like I have somehow offended you, if so, I apologize. ADS is a great library, it has improved the usability in our tool significantly. I created this ticket instead of a PR to begin with, because I assumed you may want to decide how to move the code around yourself.

What you say about how it can be used is all entirely correct. So let me try to explain better where I'm coming from.

> We use it in a commercial project and simply treat it as a 3rd party library. 

Yes, if you do that, then there is no problem, at all. We use ads in two projects. I'll focus on the use case for the company where I work, because that one is very restrictive and I cannot change that. There, we must check in all code as source, no pre-compiled libraries. Everything has to be built by the company wide build system.

Of course there are exceptions. Qt and other widely used libraries are being built using their scripts and made available in pre-compiled form, but that literally involves lawyers to vet those libraries, build engineers to integrate those libraries and sign off on that and make sure all the required platforms and build targets are taken care of. Upgrading to a new version is a huge hassle.

The more common practice for smaller dependencies is to integrate every 3rd party library directly into a project and make it build with the company build system. That allows us to build everything in one solution, we can make code fixes or work arounds quickly, we don't need to involve any lawyers or build engineers (who we don't know and live on different continents) to do so. We just treat it as our own code. That makes it so much easier for us to build, debug and improve 3rd party libraries. For example #121 was done by someone on our team.

Consequently I cannot use your qmake or cmake scripts.

> Qt requires moc compiler which runs before the real compiler runs. So Qt requires an additional build step ahead of the normal compile process. So each build system, that works with Qt needs to properly support the moc compile step.

That is of course correct.

> This is not a build system topic - that is a Qt topic.

The moment you #include a file that is generated by the build system, and whose name is generated by the build system, you make it a build system topic. You embed knowledge about how your build system works directly into the source file. That is what this issue is about, I want to remove this implicit dependency, so that if a build system works differently, the code of ads can be compiled without modifications.

As far as I can tell, your cmake script automatically sets up the MOC step. So what you see in your solution is that you get a file called "DockAreaTitleBar.moc". This is being generated by the MOC compiler, which is typically integrated as a pre-build step into the Visual Studio solution. However, this pre-build step is being set up for you by cmake or qmake and that's where your build system decided that the MOC output for "DockAreaTitleBar.cpp" will be called "DockAreaTitleBar.moc". THIS is the hidden knowledge that you then embedded into "DockAreaTitleBar.cpp" by #including that file.

And that's where other build systems differ. For us, for example, the file is called "moc_DockAreaTitleBar.cpp" and it is stowed away in some out-of-source folder. So since our build system doesn't act 100% identical to yours, the code won't compile.

With my change in the PR, this problem is fixed, because most importantly it removes the need for the #include "DockAreaTitleBar.moc".

So, yes this way of doing things may be more common than I thought, but that doesn't change the underlying problem, that it ties your code to the behavior of your build system. For large projects that is often the case anyway, but for small projects like ads we can easily prevent such dependencies.

I hope that clears up the confusion.

**Comment by githubuser0xFFFF** [comment]
> It feels like I have somehow offended you

No, this is not the my feeling - I just would like to undestand the issue and protect you from doing something wrong.

I think we are getting closer.  Now I understand a little bit better what you do. But I think, you mix two things. The file `moc_DockAreaTitleBar.cpp` it created automatically from the file `DockAreaTitleBar.h`. If you look into it then you can see this:

```c++
/****************************************************************************
** Meta object code from reading C++ file 'DockAreaTitleBar.h'
**
** Created by: The Qt Meta Object Compiler version 67 (Qt 5.12.2)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "../../../src/DockAreaTitleBar.h"
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'DockAreaTitleBar.h' doesn't include <QObject>."
```

If you define `#include "DockAreaTitleBar.moc` at the end of the file `DockAreaTitleBar.cpp` then an additional file `DockAreaTitleBar.moc` is created. 

```c++
/****************************************************************************
** Meta object code from reading C++ file 'DockAreaTitleBar.cpp'
**
** Created by: The Qt Meta Object Compiler version 67 (Qt 5.12.2)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'DockAreaTitleBar.cpp' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 67
#error "This file was generated using the moc from 5.12.2. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

```

So there are two different moc files from two differnt source files:

- moc_DockAreaTitleBar.cpp from DockAreaTitleBar.h
- DockAreaTitleBar.moc from DockAreaTitleBar.cpp

The file `DockAreaTitleBar.moc` is automatically generated as soon as I add  `#include "DockAreaTitleBar.moc` at the end of the cpp file. I do not need to add anything to the .pro file. For CMake I found this documentation:

https://cmake.org/cmake/help/v3.13/prop_tgt/AUTOMOC.html

So from reading all this I would expect, that it should be possible to adjust your build script to properly build it like it is. Which build system do you use - qmake or CMake?

**Comment by eXistence** [comment]
@jankrassnigg i have basically the same setup (ADS sources are part of my source tree and everything is build from scratch). I also use CMake, but the CMakeLists.txt that comes with ADS contains a few things that don't work for my setup (like setting a binary output directory).

I just stripped down the CMakeLists.txt, so it fits my needs. Maintaining my own CMakeLists.txt is required for other dependencies as well, so its not a big deal.

**Comment by jankrassnigg** [comment]
@githubuser0xFFFF yes I know where the two moc files come from. Both CMake and QMake will autodetect those things and then add the necessary build steps for you, which call the MOC compiler etc. As I said, those tools decide for you what the file names of those auto generated files will be and by #including the one file you tie your code to how those tools work.

In the company setting, where I don't have any influence on the build system, we use neither cmake nor qmake, but something entirely custom.

**Comment by githubuser0xFFFF** [comment]
If you do not have any influence on the build system, how do you tell the build system which files to compile and to link? You do not use the the pro file and the CMakeLists.txt from the project. So you how can you build this library then?

**Comment by jankrassnigg** [comment]
I do have a way to tell it what sources to compile etc, but I do not have influence on how it generates the name for auto generated files.

**Comment by githubuser0xFFFF** [comment]
@jankrassnigg I merged the pull request but I'm neither completely happy with it nor I'm convinced that this is the right solution. I did it only as a favour to you and to help you. For me this change does not improve the library but is just a workaround for a broken custom build system that cannot handle the standard Qt features. An easy solution would be the standard way of using the library: building the library with the provided build system and link to created libs. 

So there are plenty of solutions that are simply not possible because of some special custom build system restrictions. Fixing and patching all required libraries instead of this "broken" system to build and use libraries feels completely wrong.

But anyway, I merged it because I think it does not harm the library and to help you solve this problem for you.

**Comment by rolivav** [comment]
Just wanted to point out that I had the same problem in my CMake project and did this change locally. This change will help me update ADS more frequently. 
I don't remember why (it was nearly 2 years ago when we moved from QMake to CMake) but AUTOMOC in CMake didn't work for these files even if it says so in the documentation, at least in the 3.15 version. I tried for a while to make it work but there is little information to go on except the source code of CMake. There was a bug report, but I can't find it anymore.

**Comment by rolivav** [comment]
Just checked if it was still broken for me in CMake 3.16.5. It works fine in the Windows and OSX CI, funny enough it only fails in Linux.
```
DockAreaTitleBar.moc: No such file or directory
12:44:18   680 | #include "DockAreaTitleBar.moc"
12:44:18       |          ^~~~~~~~~~~~~~~~~~~~~~
12:44:18 compilation terminated.
```
anyway the changes @jankrassnigg made work for me.
