### ISSUE TITLE
Setting dock sizes

### ISSUE THREAD

**Issue by AV9** [githubuser0xFFFF/Qt-Advanced-Docking-System#172]
Hi,

How can I set the size of the docks placed inside the dock manager?

Thanks in advance!

**Comment by githubuser0xFFFF** [comment]
The DockWidgets are normal QWidgets that are placed inside QSplitters. That means you can set the size of the DockWidgets like you would set the size of of QWidgets in a QSplitter.

**Comment by AV9** [comment]
Ok, I will investigate because I didn't know about QSplitter, thanks!

**Comment by AV9** [comment]
Hi again,

I've been trying to set the size using the QSplitter but I couldn't achieve it. Could you please write a code snippet about how would you do it?

Thanks
