### ISSUE TITLE
Minor issue where tab changes position when redocking it to the same position

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#173]
When opaque undocking is disabled, the tab should stay in the same position it was when redocking it in the same area.
![opaque_undocking](https://user-images.githubusercontent.com/1664301/82030399-b55a2280-9698-11ea-8603-95da6757549f.gif)

**Comment by githubuser0xFFFF** [comment]
Has been fixed in master with commit 516465aefb351fd1a6a9f2dabc0f469bb6fa0834

**Comment by rolivav** [comment]
awesome work :)
