### ISSUE TITLE
Could you add a setting to disable loading default stylesheet?

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#174]
Now that the qrc file is [loaded correctly](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/85626c9a2133546f2371dc5a28331915d2daeb8f), it is overriding my application stylesheet since it is initialized (as it should) on CDockManager creation.

Would be nice to have a setting to make it not load at all. That way I can change it from my main stylesheet and well, change it without having to modify the included stylesheet in the library.

**Comment by githubuser0xFFFF** [comment]
What happens if you do what is written in the CDockManager class documentation?

```c++
/**
 * The central dock manager that maintains the complete docking system.
 * With the configuration flags you can globally control the functionality
 * of the docking system. The dock manager uses an internal stylesheet to
 * style its components like splitters, tabs and buttons. If you want to
 * disable this stylesheet because your application uses its own,
 * just call the function for settings the stylesheet with an empty
 * string.
 * \code
 * DockManager->setStyleSheet("");
 * \endcode
 **/
```

**Comment by githubuser0xFFFF** [comment]
I added a Styling section to the user guide to make this more clear.

**Comment by rolivav** [comment]
I did not know that! I will try it, thanks

**Comment by naggerx** [comment]
You can also extend the stylesheet, so that all the default styles are still in place:
```
    QFile StyleSheetFile(":resources/ads_custom.css");
    StyleSheetFile.open(QFile::ReadOnly);
    m_DockManager->setStyleSheet(m_DockManager->styleSheet().append(StyleSheetFile.readAll()));
    StyleSheetFile.close();
```

**Comment by rolivav** [comment]
Cool, it worked. Thanks.
