### ISSUE TITLE
Can't redock a group in the same position

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#175]
With opaque undocking disabled, when undocking a tab you get the drop indicators and you are able to redock it in the same place, as it should be.
![tab_redocking_ok](https://user-images.githubusercontent.com/1664301/82069195-42ba6880-96d3-11ea-915f-ceebd768b8f6.gif)

However, when undocking a tab group you don't get these drop indicators and you are forced to undock it.
![group_redocking_wrong](https://user-images.githubusercontent.com/1664301/82069300-68477200-96d3-11ea-9026-0935ebdf0b86.gif)

It should work like when undocking a tab.

**Comment by githubuser0xFFFF** [comment]
This is itentionally. If you do not want to undock, you can always cancel with the Escape key.

**Comment by rolivav** [comment]
Interesting, it is not consistent with the tab docking functionality. I thought it would be much nicer if group tab redocking worked the same way, not every user has the hand on the escape key to cancel this. Actually I would say most don't :). Maybe remove the tab redocking then?
