### ISSUE TITLE
After the last dock window in single CDockAreaWidget is closed, no newly created window is visible

### ISSUE THREAD

**Issue by szymekrak** [githubuser0xFFFF/Qt-Advanced-Docking-System#177]
In my application, I am creating some dock widgets which are to be destroyed after being closed.
When I close the last one, so that the only dock area is empty, it is hidden. From this moment, new dock widgets are placed in this hidden area and are never visible.
This is my code:
```
    MyViewer *viewer = new MyViewer;
    //some initialization of MyViewer
    ads::CDockWidget *dw = new ads::CDockWidget(viewer->windowTitle(), this);
    viewer->setParent(dw);
    dw->setWidget(viewer);
    dw->setFeature(ads::CDockWidget::DockWidgetDeleteOnClose, true);
    dockManager->addDockWidgetTab(ads::CenterDockWidgetArea, dw);
```
I have traced this behavior to the removeDockWidget method in DockAreaWidget.cpp. hideAreaWithNoVisibleContent is invoked, hiding the dock area, and never showing it back. In an attempt to fix this, I modified line 451 so that the dock area is removed instead:
from
`else if (d->ContentsLayout->isEmpty() && DockContainer->dockAreaCount() > 1)`
to
`else if (d->ContentsLayout->isEmpty())`
This fixes my issue, but I am not sure if it will not break something else.
Why is a DockAreaWidget hidden when its last dock widget is removed?

**Comment by githubuser0xFFFF** [comment]
Have you tried the latest version of master branch? I just tested this with the demo application and it worked. In the demo application please modify the  line 686 this way:

```c++
d->DockManager->addDockWidgetTab(ads::CenterDockWidgetArea, DockWidget);
```

After this modification, the demo application action **Create Docked Editor** does the same like your application. It dynamically created editors that will be deleted on close.  Hide all other areas and undock the **Calendar 0** dock widget that is not closable. Now you have an empty main window.

Now create some editors and close them all with the tab close button. If you create new editors, then they are visible. So maybe something is wrong in your application?

Woule be helpfull, if you could provide a very small test application to show this issue.

**Comment by szymekrak** [comment]
Here's a one-file test application I came up with. I could reproduce the issue both on a Linux machine with Qt 5.14, and a Windows machine with Qt 5.12.
When running the code, create one or more dock windows using main window's menu.
Do not move any of the dock windows, so that no extra dock areas are created.
Then, close all the dock windows, either one by one or using the Close group button.
Then try creating a new dock window.
```
#include <QtWidgets>
#include "DockManager.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QMainWindow w;

    auto dockManager = new ads::CDockManager(&w);

    QAction *action = new QAction("new", &w);
    w.menuBar()->addAction(action);

    int i = 0;
    QObject::connect(action, &QAction::triggered, [&]() {
        auto dw = new ads::CDockWidget(QStringLiteral("test %1").arg(i++), &w);
        auto editor = new QTextEdit(QStringLiteral("lorem ipsum..."), dw);
        dw->setWidget(editor);
        dw->setFeature(ads::CDockWidget::DockWidgetDeleteOnClose, true);
        auto area = dockManager->addDockWidgetTab(ads::CenterDockWidgetArea, dw);
        qDebug() << "dock widget created!" << dw << area;
    });

    w.show();

    return a.exec();
}
```
I hope this helps.

**Comment by githubuser0xFFFF** [comment]
Thank you. I can reproduce the problem with your code and will ry to fix it.

**Comment by githubuser0xFFFF** [comment]
I fixed this in the branch [deleteonclose_fix](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/deleteonclose_fix). Please test, if it works now. I added your small test application to the examples folder.

Please not, that closing the dock area does not close the single dock widgets - it only hides them. To close a dock widget in a way that it will be deleted, you need to close the dock widget tab.

**Comment by szymekrak** [comment]
I think this fixes my issue. Thank you!

> Please note, that closing the dock area does not close the single dock widgets - it only hides them.

For now, I will just set DockAreaHasCloseButton to false. However, an option to close them, especially if they are set to be deleted on close, may be useful. In my opinion, it would make sense if the dock widgets contained some editors with unsaved changes. When I have more time, I will try to implement something like this in the future, unless it will have been already done then.

**Comment by githubuser0xFFFF** [comment]
Ok. great. Normally, if you close an editor with unsaved changes, the software asks you, if you would like to save the changes - like this is done in the demo application. If you close a dock area with multiple dock widgets with unsaved changes, then you need to find a good way to ask the user which dock areas he wants to close and wich one he wants to save.
