### ISSUE TITLE
Docking does not work with Qt5.11.2 and Visual Studio 2017 on Windows 10

### ISSUE THREAD

**Issue by ChaosOptima** [githubuser0xFFFF/Qt-Advanced-Docking-System#178]
Build with Qt5.11.2 in Visual Studio 2017
![docking_issue](https://user-images.githubusercontent.com/10622029/82441674-f55d4300-9aa6-11ea-8d5a-7a1327d842ae.gif)
Broken after 02143eac715b23adad3bc7508f026c183ab10eab

**Comment by githubuser0xFFFF** [comment]
I just compiled the latest release with MSVC17 and Qt 5.12.6 and tested on Windows 10 - docking works without issues. Please test with Qt 5.12.6 and check your compiler settings.

**Comment by ChaosOptima** [comment]
Yep it works with Qt 5.12.7, thanks.
