### ISSUE TITLE
Bug with Qt 5.9.9 when drag floating widget to be docked widget.

### ISSUE THREAD

**Issue by yjf0602** [githubuser0xFFFF/Qt-Advanced-Docking-System#180]
I have to try several times to drag floating widget to be docked widget.
Windows10 + Qt5.9.9 + QtCreator + both MinGW and MSVC
![test](https://user-images.githubusercontent.com/16937248/82516281-efba3880-9b4c-11ea-8e79-e7f9dad094bd.gif)

**Comment by githubuser0xFFFF** [comment]
Please test with Qt 5.12 - it should work. I will investigate why it does not work for Qt 5.9.9

**Comment by githubuser0xFFFF** [comment]
Hi, I just tested with Qt 5.9.9. There seems to be  a bug in Qt 5.9.9 that prevents proper reception of event `QEvent::NonClientAreaMouseButtonRelease`.

So your only option is to upgrade to Qt to a newer version if you would like to use ADS.

**Comment by githubuser0xFFFF** [comment]
I just pushed a commit into master that should fix this issue. This fix completely drops usage of Qt non clieant area mouse events like `QEvent::NonClientAreaMouseButtonRelease` and switches to native eventhandling of WM_xxxxxxx messages (like `WM_ENTERSIZEMOVE`) . After this change, it should work now with Qt 5.9.9

**Comment by yjf0602** [comment]
I tried the new code. It works with Qt5.9.9.
