### ISSUE TITLE
Proper gitignore for VS

### ISSUE THREAD

**Issue by juangburgos** [githubuser0xFFFF/Qt-Advanced-Docking-System#187]
Hi,

This is not critical of course, but when using the library as a git submodule on Windows, git always maks the repo as changed (even though no source code was changed).

![image](https://user-images.githubusercontent.com/4707341/82885690-c3842a80-9f45-11ea-88d2-21659b84cbdb.png)

Mainly because the gitignore does not ignore VS generated binaries.

![image](https://user-images.githubusercontent.com/4707341/82885865-fdedc780-9f45-11ea-9381-9ac6e00a45fb.png)

This could be fixed by appending to the existing gitignore, the contents from the following VS gitignore file:

* <https://github.com/github/gitignore/blob/master/VisualStudio.gitignore>

Thanks for this amazing lib!

**Comment by githubuser0xFFFF** [comment]
Done

**Comment by juangburgos** [comment]
Gracias!
