### ISSUE TITLE
Issue with Qt::WA_NativeWindow on a docked widget when untabbed

### ISSUE THREAD

**Issue by jdswebb** [githubuser0xFFFF/Qt-Advanced-Docking-System#189]
Hi,

If I dock a widget with QA_NativeWindow set, everything seems to work fine other than if I tab the dock and then untab it. The alignment seems to go off somehow:

https://www.youtube.com/watch?v=zDI8RPhmEGU&feature=youtu.be

This is the code I'm using for the video (I set ads::CDockManager::DefaultNonOpaqueConfig as it appeared in another issue where QA_NativeWindow was mentioned, but it did not help).

```
    m_DockManager = new ads::CDockManager(this);
    m_DockManager->setConfigFlags(ads::CDockManager::DefaultNonOpaqueConfig);

    ads::CDockWidget* DockWidget = new ads::CDockWidget("Dock 1");
    auto widget = new QWidget();
    widget->setAttribute(Qt::WA_NativeWindow);
    DockWidget->setWidget(widget);
    m_DockManager->addDockWidget(ads::CenterDockWidgetArea, DockWidget);

    ads::CDockWidget* DockWidget2 = new ads::CDockWidget("Dock 2");
    DockWidget2->setWidget(new QLineEdit("Text 1"));
    m_DockManager->addDockWidget(ads::LeftDockWidgetArea, DockWidget2);
```

I'm using Qt 5.15.0.

Thanks!

**Comment by githubuser0xFFFF** [comment]
Please try to set also the attribute `Qt::WA_DontCreateNativeAncestors` and test if this solves your issue.

Just out of curiosity, why do you activate `Qt::WA_NativeWindow`?

**Comment by jdswebb** [comment]
Thanks, that seemed to work at first but eventually I run into various crashes in the docking lib. It may only happen once you have more than 1 dock with widgets using `(WA_DontCreateNativeAncestors | WA_NativeWindow)`.

I'm using Qt::WA_NativeWindow as I'm rendering to it with DirectX/Vk which seems to require it. I'm not entirely sure of this as I'm new to Qt and just trying to evaluate if I could use it for my tool.

Example crash with rendering:

https://www.youtube.com/watch?v=Ju_4GmI9OGo&feature=youtu.be

You can see in the couple of frames before the crash, the renderer actually re-appears again having vanished as if it got hidden - perhaps some kind of clue?

![image](https://user-images.githubusercontent.com/5884019/83125985-230e4180-a0d0-11ea-9946-bd075257ad84.png)

and another crash, this time with the same setup as I posted before, only two docks now:

https://www.youtube.com/watch?v=kLjebqWA84g&feature=youtu.be

**Comment by githubuser0xFFFF** [comment]
Please send me your small test application and instructions how to reproduce the issue and I will try to investigate.

**Comment by jdswebb** [comment]
I've created a fork with a minimal DX11 widget lightly modified from https://github.com/giladreich/QtDirect3D/tree/master/examples/Direct3D11Widget:

https://github.com/jdswebb/Qt-Advanced-Docking-System

Example repro steps:

- Tab `View 1` to `Test`
- Pull out `View 1` as a floating window
- Tab `View 1` to `Test` again, observe d3d output becomes invisible
- Pull out `View 1` as floating window, observe crash

If you remove `WA_DontCreateNativeAncestors` in `QDirect3D11Widget.cpp`, moving widgets around similarly you will observe the original behavior I mentioned where the alignment seems to go off but there is no crash.

Thanks

**Comment by githubuser0xFFFF** [comment]
If I disable `WA_NativeWindow` I can still see the blue 3DX content - are you sure that you really need  to  enable Qt::WA_NativeWindow?

**Comment by jdswebb** [comment]
I think that's because native window creation is implicit if you call winId (per https://doc.qt.io/qt-5/qwidget.html#winId) which is necessary to get the handle to provide to DX for swapchain creation.

I still get the same issues occur with `setAttribute(Qt::WA_NativeWindow);` commented out.

**Comment by githubuser0xFFFF** [comment]
Ok, that is true - so `setAttribute(Qt::WA_NativeWindow)`

**Comment by jdswebb** [comment]
I found this project using ads and using WA_NativeWindow for the same purpose - https://github.com/ezEngine/ezEngine/blob/5ed02e271787f52e3cb0bf925ea1c0a18649cc33/Code/Editor/EditorFramework/DocumentWindow/Implementation/EngineViewWidget.cpp#L51.

Not sure if they're using DX or another API but I don't suppose it really matters. I'll try out using the same Qt version as them or looking into how they maybe nest the rendering widgets.

**Comment by githubuser0xFFFF** [comment]
It seems to work, if I use exactly the same 3 flags like the ezEngine. Then you app works and does not crash.

```c++
//setWindowFlags(Qt::MSWindowsOwnDC);
    //setFocusPolicy(Qt::ClickFocus);
    setAttribute(Qt::WA_PaintOnScreen);
    setAttribute(Qt::WA_NoSystemBackground);
    setAttribute(Qt::WA_NativeWindow);
```

**Comment by jdswebb** [comment]
With those flags I get the 'alignment' issue though where the dock title bars disappear:

https://www.youtube.com/watch?v=syY_xVAzY3A&feature=youtu.be

Maybe it's a version thing? I'm installing 5.13 at the moment.

**Comment by githubuser0xFFFF** [comment]
I use Qt 5.12.2 and do not see any alignment issue that you show in your video.

**Comment by jdswebb** [comment]
Yeah I see no problems with 5.13 either, so seems this is a 5.15 issue.

**Comment by jdswebb** [comment]
I'm going to switch to the older version but out of interest, since you closed this does that mean there's no plan to support anything other than ~5.12 or will there be support for future versions (not necessarily 5.15)?

Thanks for the help!

**Comment by githubuser0xFFFF** [comment]
At the moment I think, this is a bug in Qt 5.15. I would recommend you to open a bug report in Qt Bugtracker to report this issue and provide a test application - you can link to your GitHub repository. If they tell you, that it is not a Qt bug, I will reopem this issue.
