### ISSUE TITLE
Dock Widgets do not respect widget minimum size

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#190]
Widgets inserted with the flag `eInsertMode::ForceNoScrollArea` do not respect the minimum size of the widget, which is what I was expecting to happen.
You can see this functionality working by default in a QDockWidget, and to get resizing working under the minimum size you need to wrap your widget first in a QScrollArea. ADS does this by default, which is nice, but I expected setting `eInsertMode::ForceNoScrollArea` to not wrap it in a QScrollArea. Instead it seems to disable the scrollbars and that's it?
You can see a comparison here with a QDockWidget and a CDockWidget, both their widgets with a minimum width of 500.
![dockwidget_respectminimumsize](https://user-images.githubusercontent.com/1664301/83127879-f875b600-a0da-11ea-89b9-96a75be99182.gif)
The minimum size of the QDockWidget is of course respected when the widget is docked too, while the CDockWidget's one is not respected.
![dockwidget_minimumsizedocked](https://user-images.githubusercontent.com/1664301/83128482-c9ac0f80-a0db-11ea-8afc-3aba8a69de10.gif)

It would be great if this could work the same way as in a QDockWidget. The problem I see is that you would need to respect this too when showing the drop indicators when docking, it might be a big feature to implement.

**Comment by githubuser0xFFFF** [comment]
Did you notice the `eMinimumSizeHintMode` and the function `CDockWidget::setMinimumSizeHintMode(eMinimumSizeHintMode Mode);` ?

**Comment by rolivav** [comment]
I absolutely didn't notice! Will test right away, thanks.
The documentation for the dock manager settings is great, but it does not include the dock widgets options. Would be nice to have a section there for these.

**Comment by rolivav** [comment]
Works perfectly, thanks.
