### ISSUE TITLE
Saving / restoring state versioning

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#192]
Hi, I have this setup where I load the default docking state from a file. Then when the user makes any change to the layout it is saved into a different setting.

I was using the version in the state to know when the current layout saved by the user was outdated and I needed to load the default layout.
```cpp
namespace {
const int dockingVersion = 1;
}
void MainWindow::restoreState() {
	QSettings Settings("Settings.ini", QSettings::IniFormat);
	auto userState = Settings.value("mainWindow/DockingState").toByteArray());
	if (!dockManager->restoreState(userState, dockingVersion){
		// state is for an outdated version, restore default state
		Q_ASSERT(dockManager->restoreState(getDefaultState(), dockingVersion));
	}
}
```
It was working all good. Well now I had to rename some of the widgets so I increased the version to 2 and updated the default state, and after closing and opening it would always restore the default state. To my surprise the version parameter is unused by DockManager, instead it is comparing the version against a strange enum.
```cpp
bool DockManagerPrivate::restoreStateFromXml(const QByteArray &state,  int version,
	bool Testing)
{
	Q_UNUSED(version);

    if (state.isEmpty())
    {
        return false;
    }
    CDockingStateReader s(state);
    s.readNextStartElement();
    if (s.name() != "QtAdvancedDockingSystem")
    {
    	return false;
    }
    ADS_PRINT(s.attributes().value("Version"));
    bool ok;
    int v = s.attributes().value("Version").toInt(&ok);
    if (!ok || v > CurrentVersion) // In my opinion this should be  "if (!ok || v != version)"
    {
    	return false;
    }
```
Am I misunderstanding something?

**Comment by rolivav** [comment]
Basically it should work like in https://doc.qt.io/qt-5/qmainwindow.html#restoreState

**Comment by githubuser0xFFFF** [comment]
I fixed this in this in the [version_fix](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/version_fix) branch. Please test, if this works now for you. If you tell me, that it works, I will merge it into master.

**Comment by rolivav** [comment]
Hi you pushed it into the branch right? Sorry I had no time to look at it, I'll check it out now.

**Comment by rolivav** [comment]
looks good! noticed there are a lot of typos in the comments though, you might to fix them
```
 * Internal file version in case the sturture changes interbally

    // Older files do not support UserVersion but we still want to load them so
    // we first test if the attribiute exists
```
thanks!
