### ISSUE TITLE
FloatingWidgets can not be reattached on macOS

### ISSUE THREAD

**Issue by cgrep** [githubuser0xFFFF/Qt-Advanced-Docking-System#195]
Hi,

I am testing your library for the first time and stumbled upon a regression while trying the demo application.
Widgets once floating can not be reattached anymore.
Present till master (incl. current release 3.4.2), working fine with 3.3.5 and I prob. narrowed it down to 6b5f36486449e1eb5f28751704ab220a52c2e32d

System: Qt-5.12.8 on macOS 10.15.5
Thank you!
![regression-compr](https://user-images.githubusercontent.com/36212/84175749-b22c3980-aa80-11ea-9a37-817311b6871b.gif)

**Comment by githubuser0xFFFF** [comment]
Thank you. I do not have a Mac but I think I know how to fix it.

**Comment by githubuser0xFFFF** [comment]
I just pushed a fix to the branch [fix_macos_docking_issue195](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/fix_macos_docking_issue195).

Pleadse test, if this fixes the issue for you.

**Comment by cgrep** [comment]
Yes it does, thanks.

**Comment by githubuser0xFFFF** [comment]
Thank you for the detailed bug report - it helped me a lot to fix this issue. Just merged this into master
