### ISSUE TITLE
Question: Dock Widget Size

### ISSUE THREAD

**Issue by hhslepicka** [githubuser0xFFFF/Qt-Advanced-Docking-System#196]
Sorry if this is an obvious question.

I have a dock manager and a widget added to the LeftDockWidgetArea. Later on I add another dock to this widget previously added at the LeftDockWidgetArea but at its BottomDockWidgetArea.

I would like to know if there is a way to control the expansion of the bottom dock to not take 50% of the size when added. Is this an option that I can set at the dock?

**Comment by githubuser0xFFFF** [comment]
No, there is currently no way to control the expansion.

**Comment by hhslepicka** [comment]
@githubuser0xFFFF can this be reopened and become a feature request? I can change the title...

**Comment by githubuser0xFFFF** [comment]
Yes, this would be possible. Then it would be great, if you could paraphrase your request. Thatt means, which option do you ant to set on a dock widget and what exactly should this option cause. For me, at the moment it sounds, like you would control the initial size, that a dock widget gets, if it is added to a dock area for the first time. Is this right? So this would be more an option or parameter of the add function.

After you have added the dock widget, you can resize it via its parent splitter.

**Comment by stijnherfst** [comment]
@githubuser0xFFFF I have the same feature request. 

It would be helpful if we could set the QSizePolicy to Preferred for instance and change the QSplitter its stretchFactor.
