### ISSUE TITLE
Update Python Bindings

### ISSUE THREAD

**Issue by githubuser0xFFFF** [githubuser0xFFFF/Qt-Advanced-Docking-System#197]
Added `CDockFocusController` with commit c939df73fa230a7e056ecae17bef57785da3516e that requires update of Python bindings.

**Comment by githubuser0xFFFF** [comment]
Added dock widget feature flag `DockWidgetFocusable` with commit 679fa81f6dfa56d8601d3a567a19a10180e54b67 - this may require an update of Python bindings

**Comment by n-elie** [comment]
Done in #218.

**Comment by githubuser0xFFFF** [comment]
Merged, thank you.

**Comment by githubuser0xFFFF** [comment]
Just merged a pull request (see commit 8443414ae383778363f53d004763d6ee804ca09a) that added the new DockArea function `setHideSingleWidgetTitleBar()` - this may require an update of Python bindings

**Comment by n-elie** [comment]
Done in #231

**Comment by githubuser0xFFFF** [comment]
Merged, thank you.

**Comment by githubuser0xFFFF** [comment]
Added support for central widget and for native floating widget titlebars - this may require an update of the Python bindings

**Comment by n-elie** [comment]
See #249

**Comment by githubuser0xFFFF** [comment]
Thank you.
