### ISSUE TITLE
Empty dock area

### ISSUE THREAD

**Issue by stijnherfst** [githubuser0xFFFF/Qt-Advanced-Docking-System#199]
I'm trying to emulate the behaviour of Visual Studio regarding the opening of source files and the Tool windows. 
Visual Studio seems to have a dock area that can be empty, but will still retain its size even when all tabs inside have been closed. I'll call it the CentralDock. You can place tabs in or around the CentralDock and even split it into multiple parts, but you cannot move the CentralDock out of the window it was created in. I'll show some screenshots.
![image](https://user-images.githubusercontent.com/8471644/84432206-cca31600-ac2c-11ea-8802-aa5cd6a14467.png)

Note the blank area in the topright, this is the CentralDock. When we open a source file it gets opened there.
![image](https://user-images.githubusercontent.com/8471644/84432226-d167ca00-ac2c-11ea-9169-3e99eb14e866.png)
When we open another source file it gets automatically placed there as a tab
![image](https://user-images.githubusercontent.com/8471644/84432302-eb091180-ac2c-11ea-8c32-904cf7503549.png)
We can split it, but note that we can only drag the tabs out and not the actual CentralDock
![image](https://user-images.githubusercontent.com/8471644/84432343-fb20f100-ac2c-11ea-89bc-dde6837e47ff.png)
When we float another CDockArea it will take up the available space
![image](https://user-images.githubusercontent.com/8471644/84432425-155acf00-ac2d-11ea-8c74-cc909486482a.png)
I think this feature is somewhat related to #196 regarding the remaining open/autosizing.

I've donated €10 because I think the work you do on this library is awesome and would like to make another donation if you could consider adding this feature.

**Comment by githubuser0xFFFF** [comment]
Thank you for your donation. If have Visual Studio here and I think I understand your feature request. Visual Studio has a central dock area that will never go even if it is empty. This central dock area can be used by all odck widgets but code editor dock widgets are limited to this centra dock area. But the editors can be splitted and rearranged in this central dock area. So this is quite a different design to the Advanced Docking System. I think creating a central dock area that will not be deleted if it is empty would be not that hadr to implement. But a central dock area that can be splitted and and where dock widgets can be rearranged does not match very well with the current design.

Do you plan to implement a Vsisul Studio clone or some kind of IDE or code editor?

I don't want to give you high hopes that this will be implemented quickly, as I have prioritized the other feature requests higher. But I will leave it open as feature request - maybe someone jumps in.

**Comment by stijnherfst** [comment]
Only having a dock area that cannot be closed would be a big help. The splitting would be a nice extra.

Yeah I have a program called [HiveWE](https://github.com/stijnherfst/HiveWE/) with source code editor that uses this library to allow for very flexible docking.
![image](https://user-images.githubusercontent.com/8471644/84491948-aa011380-aca5-11ea-8c7f-f2f4152195dc.png)
I would indeed like the features described here to use them in this source code editor as now when you open it for the first time it is very messy. This is how it looks when you open it without having rearranged anything manually.
![image](https://user-images.githubusercontent.com/8471644/84492060-d87eee80-aca5-11ea-8faf-994a18f20c9c.png)

But most of all I want it for another system for editing game data files as that is the most important part of the custom editor.
![image](https://user-images.githubusercontent.com/8471644/84492146-ffd5bb80-aca5-11ea-93b1-22da0183f6ba.png)

On another note, is it possible to have two rows of tabs? You can see the tab row here with the icons takes up a lot of horizontal space which the treeview widget inside doesn't really need.
![image](https://user-images.githubusercontent.com/8471644/84492208-23990180-aca6-11ea-904d-ea0f16f95cdd.png)

**Comment by githubuser0xFFFF** [comment]
Ahh, I see - really nice tool. If you could create a cool sceenshot of your software where the ADS is in action (like in the screenshots in the showcase area on the project main page) - that would be really creat. I reall yould like to see this in the showcase section.

Yes, you are right - if you open it for the first time, then it looks a bit messy. What I do here in my QmixElements software is, that I created a default perspective that is loaded, if no other perspective is availabel. This way you can create a nice default layout of your dockwidgets and load it, if no opther preset is present.

This is also the way how they do in in the QtDesigner and QtCreator.

**Comment by stijnherfst** [comment]
![image](https://user-images.githubusercontent.com/8471644/88910378-b0028200-d25c-11ea-945f-1deda0ae2d02.png)
Here is a screenshot that I think you could us for the showcase section.

With a default perspective I would need to have some CDockWidget in the "empty" space right? Something like a welcome page is what I could do, but ideally it would be an empty space that also doesn't show up as a tab you can close.

**Comment by githubuser0xFFFF** [comment]
Thank you for the screen shots. 

A default perspective means, that you arrange the editors in your application via drag & and drop in a way you think is the best arrangement for a user opening the application for the first time. Then you include the saved perspective in your Qt resource file and restore it in case no other saved perspective is available.

Then it does not look messys if a user opens it for the first time. The user will see your default perspective.

**Comment by ix07** [comment]
Hm. I just posted my own entry, but I think this is exactly what we are looking for, too. Can anyone be bribed into adding this?

**Comment by heinermann** [comment]
I used a MDI widget with [setHideSingleWidgetTitleBar](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/8443414ae383778363f53d004763d6ee804ca09a) enabled to get the effect of an empty area (but not the behaviour you're looking for). Maybe you can use it as inspiration?

```cpp
 /// ~~~snip~~~ (mdi is a QMdiArea and mdi_dock is the CDockWidget)
  mdi_dock->setWidget(mdi);
  mdi_dock->setFeature(ads::CDockWidget::DockWidgetFeature::DockWidgetClosable, false);
  mdi_dock->setFeature(ads::CDockWidget::DockWidgetFeature::DockWidgetFloatable, false);
  mdi_dock->setFeature(ads::CDockWidget::DockWidgetFeature::DockWidgetMovable, false);

  auto center_dock_area = m_DockManager->addDockWidget(ads::DockWidgetArea::CenterDockWidgetArea, mdi_dock);
  center_dock_area->setAllowedAreas(ads::DockWidgetArea::OuterDockAreas);
  center_dock_area->setHideSingleWidgetTitleBar(true);
```

If it were possibly to never show the tab of a specific CDockWidget you might be able to work around it.

**Comment by nickdademo** [comment]
This is something we also would like (an empty area which does not appear tabbed).

Doing something like this:
```
    const auto dock = new ads::CDockWidget("test");
    const auto centralDockArea = dockManager()->setCentralWidget(dock);
```

Gives:
![image](https://user-images.githubusercontent.com/1648285/103304854-a025de80-4a44-11eb-974f-0e85c4af1ff3.png)

We somehow need a "dummy" dock as the central widget (i.e. which doesn't appear as a tab or in the tab group menu).

Anyone have ideas on how this could be achieved?

**Comment by githubuser0xFFFF** [comment]
@nickdademo I just added a new CDockWidget flag CDockWidget::NoTab in the branch https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/dockwidget_no_tab. With this tab, you can create a dock widget, that is not closable and movable and that has no tab widget. The **centralwidget** example shows this new flag. With this flag you can create a "dummy" dock widget taht does not appear in the tab or in the tab group menu.

Please give me feedback, if this is what you need, then I can merge this into master.

**Comment by spiderkeys** [comment]
I needed the same feature and was just temporarily ok with having the dummy widget have a tab until I got around to figuring out how to do this, but you've saved the trouble :slightly_smiling_face: 

I just tested this new branch and it works great. There is only one slight modification that needs to be made, which I discovered as I am using Qt6:

In FloatingDockContainer.cpp Line 612 you have:
```c++
QDockWidget::setFeatures(QDockWidget::AllDockWidgetFeatures);
```
but `QDockWidget::AllDockWidgetFeatures` has been removed in Qt6, so it should now be:
```c++
QDockWidget::setFeatures(QDockWidget::DockWidgetClosable | QDockWidget::DockWidgetMovable| QDockWidget::DockWidgetFloatable);
```
Thanks for working on this, and also for getting the Qt6 support in! 

As an aside, do you have a way to financially contribute/donate to your development? I've gotten enough value out of this library that I would like to show some thanks, if possible.

**Comment by githubuser0xFFFF** [comment]
@spiderkeys Thank you for testing this and thank you for pointing out the FloatingDockContainer Qt6 build issue - I will fix this.

On the project main page there is a PayPal donation button but something that would make me even happier would be a screenshot of your application showing ADS in action for my showcase setcion on the project main page. So if you have some cool screenshots where a dock overlay is visible that would be great :o=

**Comment by nickdademo** [comment]
@githubuser0xFFFF Fantastic! Thank you! Will test in the next few hours.

**Comment by nickdademo** [comment]
@githubuser0xFFFF Just tested and it works as expected - many thanks again!

Just one small thing (bug?): The first "real" dock in the central dock area will not be set as active after the area is created - I guess we need to handle the active index to skip the "fake" dock?

**Comment by githubuser0xFFFF** [comment]
Yes, I could already see this here - I will try to fix this

**Comment by spiderkeys** [comment]
@githubuser0xFFFF we haven't launched our product yet, but I would be happy to send you some screenshots for the showcase when we do. Until then, enjoy some coffees/beers on me :slightly_smiling_face:

**Comment by githubuser0xFFFF** [comment]
@spiderkeys Thank you very much for your donation - this is alot of coffee :coffee: :joy: Looking forward to seeing your product when it is launched.

**Comment by githubuser0xFFFF** [comment]
@nickdademo I just pushed a commit to the dockwidget_no_tab branch, that should fix this issue. I also added a new test case **example/emptydockarea** to show the functionality. Please test, if this fixes the problem for you and if it works properly now.

**Comment by nickdademo** [comment]
@githubuser0xFFFF works now, thanks!

**Comment by githubuser0xFFFF** [comment]
Merge this with some additonal documentation in user-guide.md into master

**Comment by nickdademo** [comment]
@githubuser0xFFFF Found one additional small bug: restoring docks state will not set the first "real" dock to active.

This is because `indexOfFirstOpenDockWidget()` in `DockManagerPrivate::restoreDockAreasIndices()` will return the index of the dummy dock.

Shall we do:

```
int CDockAreaWidget::indexOfFirstOpenDockWidget() const
{
	for (int i = 0; i < d->ContentsLayout->count(); ++i)
	{
		if (!dockWidget(i)->isClosed() && !dockWidget(i)->features().testFlag(CDockWidget::NoTab))
		{
			return i;
		}
	}

	return -1;
}
```

**Comment by githubuser0xFFFF** [comment]
Hi,

I try to reproduce this in the `emptydockarea` example but I did not succeed. Please tell me, how I can reproduce this with the `emptydockarea` example.

**Comment by nickdademo** [comment]
@githubuser0xFFFF False alarm - seems to be an issue on my side :)
