### ISSUE TITLE
Problem building and running under Windows

### ISSUE THREAD

**Issue by mvidelgauz** [githubuser0xFFFF/Qt-Advanced-Docking-System#2]
Hello,
I have downloaded sources and tried to build and run library and demo application.
Here are few problems that I had:

Build:
1. I'm using VS2012 so not all C++11 features are supported.  So I moved all initialization like " zOrderIndex;// = 0;" to constructor's initialization list
2. Although there is "DEFINES += ADS_EXPORT" in pro file, it wasn't used anywhere. So I added "ads_api.h" with ADS_EXPORT_API definition and added it to classes that are imported in "demo". Without those definition ".lib" file wasn't even created

Run
1. First attempt to drag a window resulted in crash  in "CFloatingDockContainer" code because only first constructor initialized member "d" with "new FloatingDockContainerPrivate(this)". Two other constructors didn't do it
2. Next crash happens because if I understand correctly I also need to "d->DockContainer = new CDockContainerWidget(DockManager, this);" also in other two constructors (foolowed by signal/slot connection?)

I just want to ask if my understanding of these problems is correct and I am doing correct changes in the code.
Also, will accept these changes if I commit them into my forked repository? (Currently I am only doing local changes)

Thank you!

**Comment by githubuser0xFFFF** [comment]
Hi,

1. If your compiler does not support C++ 11 like member initialization, you need to do it in constructor initialization lists - so you did it right.

2. The CFloatingDockContainer constructors uses C++ 11 constructor delegation. If your compiler does not support this feature, you need to ensure, that all constructors do the required initialisation steps, or you create a private constructor that all public constructors can call.

I would recommend to upgrade your development environment. Writing non C++ 11 code in 2017 is not the right way to go. I would even say, writing non C++ 14 code in 2017 is not the right way.

**Comment by mvidelgauz** [comment]
Thank you for your answer!
VS2012 supports C++ but not fully. Unfortunately I have to maintain a big project, which must be complied with VS2012 and gcc 4.4 and is not easy to port. So it looks like I'll need to keep doing my mods...

Thank you again!
