### ISSUE TITLE
Remember dimensions when docking if returning to previous position?

### ISSUE THREAD

**Issue by starseeker** [githubuser0xFFFF/Qt-Advanced-Docking-System#208]
Is there any option to have an undocked window, when re-docking to its previous position, remember its previous width/height?

The attached animation shows an example where a docked tree view is undocked and then re-docked, but expands its width in the process rather than retaining either its prior docked width or the width it had when undocked.  What I'd like to have happen, if possible, is to not have the docking process increase the width of the widget - is there any current way to do this?  (Apologies if I missed an obvious configuration option somewhere...)

![dock_sizing_video](https://user-images.githubusercontent.com/238416/85436778-91231880-b557-11ea-9458-b1b3c23b6510.gif)

**Comment by githubuser0xFFFF** [comment]
No sorry, this is not possible and it will not be possible. Even in Visual Studio this is not possible. Your only option is to modify the code.
