### ISSUE TITLE
Question about CDockContainerWidget::dropWidget()

### ISSUE THREAD

**Issue by cywsnlam** [githubuser0xFFFF/Qt-Advanced-Docking-System#209]
Hi,

I read from a source file (Version 3.5.0,  DockContainerWidget.cpp) and doubt if something missing or overlooked in the following method:

=================================================================
void CDockContainerWidget::dropWidget(QWidget* Widget, DockWidgetArea DropArea, CDockAreaWidget* TargetAreaWidget)
{
    CDockWidget* SingleDockWidget = topLevelDockWidget();
	if (TargetAreaWidget)
	{
		d->moveToNewSection(Widget, TargetAreaWidget, DropArea);
	}
	else
	{
		d->moveToContainer(Widget, DropArea);
	}

	CDockWidget::emitTopLevelEventForWidget(SingleDockWidget, false);
	CDockWidget* DockWidget = qobject_cast<CDockWidget*>(Widget);

	if (!DockWidget)
	{
		CDockAreaWidget* DockArea = qobject_cast<CDockAreaWidget*>(Widget);
		auto OpenDockWidgets = DockArea->openedDockWidgets();
		if (OpenDockWidgets.count() == 1)
		{
			DockWidget = OpenDockWidgets[0];
		}
	}

	window()->activateWindow();
	d->DockManager->notifyWidgetOrAreaRelocation(Widget);
}
================================================================
From the code, DockWidget is local and assigned but not used; Widget is passed in 
notifyWidgetOrAreaRelocation instead. Please confirm. Thank you.

**Comment by githubuser0xFFFF** [comment]
Good catch. I removed the superfluous code. Thank you.
