### ISSUE TITLE
restoreState requires existing CDockWidgets.

### ISSUE THREAD

**Issue by DerShokus** [githubuser0xFFFF/Qt-Advanced-Docking-System#21]
Hi. I've found in your code:
```cpp
bool DockContainerWidgetPrivate::restoreDockArea(QXmlStreamReader& s,
	QWidget*& CreatedWidget, bool Testing)
{
	...
		s.skipCurrentElement();
		CDockWidget* DockWidget = DockManager->findDockWidget(ObjectName.toString());
		if (!DockWidget || Testing)
		{
			continue;
		}
```

That means, to restore `CDockManager` I have to add all CDockWidgets with right names first, but I can't determine which widgets should I add.

Is there any functionality to get all CDockWidgets names before call `restoreState`?

**Comment by githubuser0xFFFF** [comment]
In your application you first create all your dock widgets with a unique name. The restore function does not create any dock widgets. It simply restores the position and size of all dock widgets.

**Comment by DerShokus** [comment]
The problem for me in that, I don't know the widgets set. I can get the set from `const QByteArray& state` (the first argument of `restoreState`), but it's an internal config. In the next version, the config format may be changed. Will be cool to have a functionality to retrieve all `CDockWidget` names.

**Comment by DerShokus** [comment]
I have a TextEditorWidget.
A user opened 3 instances of the widget with the following CDockWidget::objectName()s: "Editor:file1.txt", "Editor:file2.txt", "Editor:file3.txt" and closed the application (it calls `CDockManager::saveState()` before).

The user opens the application again, and it should restore those widgets. For this I have to do:

1. Add CDockWidgets with the names: "Editor:file1.txt", "Editor:file2.txt", "Editor:file3.txt".
2. Call CDockManager::restoreState to restore the positions of the widgets.

My problem in that I have to know the objectNames to create the widgets. I can find it in the config (the result of CDockManager::saveState), but I think it's an internal CDockManager's config and depends on the Qt-Advanced-Docking-System library.

Maybe I do it wrong and there is a more efficient way to do it?

Config sample:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<QtAdvancedDockingSystem Version="0" DockContainers="1">
    <DockContainerWidget Floating="0">
            <Splitter Orientation="1" Count="2">
                <Splitter Orientation="2" Count="2">
                    <DockAreaWidget Tabs="1" CurrentIndex="0">
                        <DockWidget ObjectName="Editor:File1.txt" Closed="0"/>
                    </DockAreaWidget>
                    <DockAreaWidget Tabs="1" CurrentIndex="0">
                        <DockWidget ObjectName="Editor:File2.txt" Closed="0"/>
                    </DockAreaWidget>
                    <Sizes>369 368 </Sizes>
                </Splitter>
                <Splitter Orientation="2" Count="1">
                    <DockAreaWidget Tabs="1" CurrentIndex="0">
                        <DockWidget ObjectName="Editor:File3.txt" Closed="0"/>
                    </DockAreaWidget>
                    <Sizes>369 </Sizes>
                </Splitter>
        </Splitter>
    </DockContainerWidget>
</QtAdvancedDockingSystem>


```

**Comment by githubuser0xFFFF** [comment]
Ok, now I understand what you would like to do. It's not the job of the docking system to create windows dynamically or restore dynamically created windows. The task of the docking system is, to manage the docking of existing windows and to save and restore the docking state of the application. This is exactly the same with the standard Qt docking system.

Your application needs to care about the creation of the dynamically created windows. That means, if you want to save the state, then you first need to save the names and the content of you dynamically created windows into an application specific settings file.

Later, if you restore your application, you first load the settings from you application settings file, create your editors, register the editors to the docking system and then restore the docking state.

**Comment by DerShokus** [comment]
I didn't want to add one more config for this but seems I have to.

Thanks for the answer!
