### ISSUE TITLE
Mac Issue: Docking widget at the bottom area sometimes not working

### ISSUE THREAD

**Issue by cywsnlam** [githubuser0xFFFF/Qt-Advanced-Docking-System#210]
Hi,

The following gif captures a docking issue that does not work. As shown, docking of Label 2 is ok, but label 4 widget does not. For label 4, it cannot dock to the bottom area and the last trial of dragging the title bar is not possible too.

![debug_202006273S](https://user-images.githubusercontent.com/17020413/85926641-4e549e00-b8d3-11ea-9bb4-f691f05220df.gif)

Version: 3.5.1
Pls. check. Thank you and have a nice day.

**Comment by githubuser0xFFFF** [comment]
Sorry, I cannot reproduce the problem here on Windows and I do not have a Mac do reproduce this. So I think you need to narrow the problem down by yourself. You may try to checkaout an older version to test, which version introduced the problem.

**Comment by cywsnlam** [comment]
I believe the problem is related to FloatingDockContainerPrivate()::titleMouseReleaseEvent(), but I'm not so familiar with the the code being called, so it needs time for me to get familiar with the logic flow.

**Comment by githubuser0xFFFF** [comment]
Please check if the issue also occurs in version 3.4.1. I suppose commit 6b5f36486449e1eb5f28751704ab220a52c2e32d introduced this problem because the Windows code switched to native event handling while the Mac code still uses NonClientArea mouse events.

**Comment by cywsnlam** [comment]
Just tested 3.4.1. The drag & drop process is  smoother, but the issue remains. However, I discovered one point that shares among 3.5.1 and previous versions: the drop indicators, both inner & outer cross, in this case at bottom-most area (the down arrows) may sometimes appear below the lowest container widget and partly out of it and appear at the status bar where the cursor when pointed there and drag release does not have the desired docking effect.

**Comment by githubuser0xFFFF** [comment]
It is normal that the inner cross may appear outside of the dockwidget if the dock widget size is smaller than the size of the cross - this is the same on all platforms

**Comment by cywsnlam** [comment]
>> It is normal that the inner cross may appear outside of the dockwidget if the dock widget size is smaller than the size of the cross
Right. However, there is something that I would like to point out. To make it easer to explain, I have captured an example of other's docking system for illustration:
![Screenshot_20200701-191107_1](https://user-images.githubusercontent.com/17020413/86276626-c68ace80-bc07-11ea-8a1d-2a2e43c51fc7.jpg)
(1) Both the down arrows of the inner & outer crosses do not extend beyond the most bottom border of the lowest dock container, in this case the part extended outside is at the top border of the lowest dock container.
(2) The outer down arrow is not shielded by the inner cross so that both the down arrows are clickable.

**Comment by githubuser0xFFFF** [comment]
The following screenshot shows Microsoft Visual Studio - you can see, that it works exactly the same way like ADS. The cross of the bottom dock area extends beyond the bottom border and overlays the status bar. As soon as the mouse leaves the bottom dock widget, the cross will be hidden.

![Atmel_Studio](https://user-images.githubusercontent.com/4239304/86320576-79265580-bc37-11ea-9e04-0e3e6336d2fd.png)

So after reading your last comment, I'm not sure if you really see an issue or if this is just the normal ADS behaviour. The cross is displayed, as long as your mouse is inside of  a dock widget. That means, if you cross is outside of your dock widget, then your need to resize the dock widget slightly before you can dock another one. Normally this only happens for very small dock widgets on the border of a window and is not really an issue for a big application.

So can you fix the issue by resizing the bottom dock widget before dropping the next one?

**Comment by cywsnlam** [comment]
I have not installed Visual Studio in Mac, so I don't known how it handle this issue. As you show this docking system is target to work like as VS Docking System. It is better to adhere to the same behaviour. Initially, I consider this an implementation issue, but under further consideration, I agree this is just a taste of operation behaviour. In this regard, this issue can be closed. Thank you for your prompt explanation. ;)
