### ISSUE TITLE
Add opportunity to set focusable some CDockWidget and disable it for others

### ISSUE THREAD

**Issue by KerimMatlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#215]
Hi,

Is it possible to add such feature? For example I have five `CDockWidget` and only three of them should be focusable (those three should be highlited by blue and be focused when user click on them and others `CDockWidget` are not).
I already tried to set :
`dockWidget->setFocusPolicy(Qt::NoFocus);`
but that doesn't work.

I'm sorry that I didn't ask you for this feature earlier

**Comment by githubuser0xFFFF** [comment]
Yes, this would be possible. Maybe you could elaborate a little bit more, why you need this feature.

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF sure
I have an application with one tree model and multiple windows where the checkable items could be displayed. Those windows should be able to cath focus. 
When user checks the item from model then the the focused window display it. User can see with wich plottable window he is working with (it is highlighted with blue color). But what if focused window is not plottable? Then user can see the highlighted window wich can't plot anything and he can't understand if he checks the item then where it should appear.
See picture:
![image](https://user-images.githubusercontent.com/43808863/86370709-bbc44e00-bc88-11ea-8f8a-a5a9037d759c.png)

**Comment by githubuser0xFFFF** [comment]
Please test the branch https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/focusable. There is the new `CDockWidget` feature `DockWidgetFocusable`

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF thank you very much!
I just tested it and no matter whether dock widget is stacked/tabbed/floatable everything works fine: if `dockWidget->setFeature(ads::CDockWidget::DockWidgetFocusable, true);` then it get focus when I click on it and if `dockWidget->setFeature(ads::CDockWidget::DockWidgetFocusable, false);` then it never becomes focused (as I needed)

**Comment by githubuser0xFFFF** [comment]
Merged into master
