### ISSUE TITLE
Can't tabify after close floating widget

### ISSUE THREAD

**Issue by skartashev** [githubuser0xFFFF/Qt-Advanced-Docking-System#22]
1. Run ads_example
2. Undock "Label 2" widget - make it floatable
3. Close "Label 2" by pressing "Close window" button
4. Raise "Label 2" by pressing "View->Label 2"
Now "Label 2" can't be docked anywhere.

Workaround to fix this is to call hide() inside closeEvent(): 
```
void CFloatingDockContainer::closeEvent(QCloseEvent *event)
{
    d->setState(DraggingInactive);
    hide();
    event->ignore()
}
```

**Comment by skartashev** [comment]
It named just "example" in QtCreator project

**Comment by yozka** [comment]
Yes. there is such a problem.
But the above code does not solve it.

`void CFloatingDockContainer::closeEvent(QCloseEvent *event)
{
    d->setState(DraggingInactive);
    hide();
    event->ignore()
}`


There is another problem; you need to look at why closed windows stop working.

**Comment by githubuser0xFFFF** [comment]
This problem happens on a Linux machine?

**Comment by yozka** [comment]
The problem is reproduced on windows 10

**Comment by githubuser0xFFFF** [comment]
I'm on Windows 10 and I cannot reproduce the problem here.

**Comment by githubuser0xFFFF** [comment]
Im on Windows 10 x64, Qt 5.9.2. With the steps from above I cannot reproduce the problem. This is what I did:

1. started AdvancedDockingSystemDemo.exe
2. Undock "Label 2" widget - make it floatable
3. Close "Label 2" by pressing "Close window" button
4. Raise "Label 2" by pressing "View->Label 2"
5. "Label 2" can still be docked everywhere

**Comment by skartashev** [comment]
Looks like this is Qt-specific bug. On Qt 5.7 it works normally, but on Qt 5.11.3 in doesn't work.

**Comment by githubuser0xFFFF** [comment]
Fantastic :o(. I will install Qt 5.12 here to find out what is going on.

Thank you for testing on Qt 5.7.

**Comment by githubuser0xFFFF** [comment]
I can reproduce the prolem with Qt 5.12. After close or hide of a floating widget, the widget does not receive any non client area mouse events anymore like: QEvent::NonClientAreaMouseButtonPress, 
QEvent::NonClientAreaMouseButtonDblClick, QEvent::NonClientAreaMouseButtonRelease.

For me this looks like a Qt bug. I will create a test case and file a bug report to the Qt bugtracker.

**Comment by githubuser0xFFFF** [comment]
I created a bug report for this problem (https://bugreports.qt.io/browse/QTBUG-73295) and implemented a workaround in CFloatingDockContainer::closeEvent(QCloseEvent *event) function that seems to work on windows but needs some more testing if it has unwanted side effects. I pushed the workaround to the master branch.

```cpp
void CFloatingDockContainer::closeEvent(QCloseEvent *event)
{
    qDebug() << "CFloatingDockContainer closeEvent";
	d->setState(DraggingInactive);

    if (isClosable())
    {
#if (QT_VERSION > 0x050902)
        event->ignore();
        this->hide();
#else
        Super::closeEvent(event);
#endif
    }
    else
    {
        event->ignore();
    }
}
```
