### ISSUE TITLE
CDockWidget's closeRequested event is not emitted when closing a group

### ISSUE THREAD

**Issue by n-elie** [githubuser0xFFFF/Qt-Advanced-Docking-System#222]
When CDockWidget::CustomCloseHandling and CDockWidget::DockWidgetDeleteOnClose are enabled, the closeRequested event is emitted when the CDockWidget is closed but if you group two CDockWidget with these features enabled and try to close the group, the closeRequested event is not sent. I think this is not an expected behavior.

To reproduce this, launch the demo and create two docked editor, group them by dragging one inside the second one. Then, close this newly created group. We should see a messagebox asking if we want to close the editors but we don't.

**Comment by n-elie** [comment]
Ok, it seems it is the intended behavior as this handled in CDockAreaWidget::closeArea. Is there a reason to do hide widgets that have the DockWidgetDeleteOnClose flag set on instead of deleting them?

How about replacing this code:
```C++
void CDockAreaWidget::closeArea()
{
	// If there is only one single dock widget and this widget has the
	// DeleteOnClose feature, then we delete the dock widget now
	auto OpenDockWidgets = openedDockWidgets();
	if (OpenDockWidgets.count() == 1 && OpenDockWidgets[0]->features().testFlag(CDockWidget::DockWidgetDeleteOnClose))
	{
		OpenDockWidgets[0]->closeDockWidgetInternal();
	}
	else
	{
		for (auto DockWidget : openedDockWidgets())
		{
			DockWidget->toggleView(false);
		}
	}
}
```

by this one?
```C++
void CDockAreaWidget::closeArea()
{
    for (auto DockWidget : openedDockWidgets())
    {
        if (DockWidget->features().testFlag(CDockWidget::DockWidgetDeleteOnClose))
            DockWidget->closeDockWidgetInternal();
        else
            DockWidget->toggleView(false);
    }
}
```

**Comment by githubuser0xFFFF** [comment]
The reason is, that if the user closes a single `DockWidget`, then it is possible to ask the user if he really wants to close the widget - like it is done in the demo application. If the user closes a dock area, then this is not possible so easy. Therefore closing a dock area will hide the `DockWidgets` and closing a single `DockWidget` will delete it.

This is the current state.
