### ISSUE TITLE
How to add a widget to a tab bar via code?

### ISSUE THREAD

**Issue by Kalbra** [githubuser0xFFFF/Qt-Advanced-Docking-System#225]
Hi, 

I want to add a widget to a tab bar.
My current code:

```cpp
CDockWidget *tab1 = new CDockWidget("Tab1");
welcome->setWidget(mywidget1);

CDockWidget *tab2 = new CDockWidget("Tab2");
welcome->setWidget(mywidget2);

m_DockManager->addDockWidget(TopDockWidgetArea, tab1);
m_DockManager->addDockWidget(TopDockWidgetArea, tab2);
```
So what I have to do, that `tab2` is not a own dock, but in the tab bar of `tab1`.

Thanks in advance

**Comment by githubuser0xFFFF** [comment]
Please check the demo application to see how to do this. See `CDockMandger::addDockWidgetTab` and `CDockManager::addDockWidgetTabToArea`
