### ISSUE TITLE
Draggable QWidget that creates a CDockWidget

### ISSUE THREAD

**Issue by felipefrr** [githubuser0xFFFF/Qt-Advanced-Docking-System#226]
I created a toolbar that has draggable QWidget, what I need is when I drag the widget to the Dock Manager, it show the preview options areas like this image:
![image](https://user-images.githubusercontent.com/9751421/87860600-01ce1280-c915-11ea-9fba-0eddb42de185.png)
and create a new empty CDockWidget when I drop.
![image](https://user-images.githubusercontent.com/9751421/87860609-19a59680-c915-11ea-81bf-8778c29fcd8b.png)
Someone can tell me if it is possible? and if it is where to start?

**Comment by githubuser0xFFFF** [comment]
Sorry, but I have to admit, that I do not understand what you would like to say. Maybe you could elaborate in more detail.

**Comment by felipefrr** [comment]
I just want to create a QWidget that I drag to the CDockManager area and it show that preview possible areas [like when you drag CDockWidget and it show the possible areas where you can attach] and it creates a CDockWidget in the place I drop.
This QWidget is just an icon where one is for creating a CDockWidget for a graph and the other for creating a CDockWidget for a table.

But the CDockManager area just recognize CDockWidgets, I can't drop a QWidget there. They way we populate the dock area is via creating CDockWidget and add it using the addDockWidget command. I want to do that via drag and drop, but I don't know if it is possible.

If it is possible, can you give me some tips about how implement it, where to start or something. I hope I'm not asking to much of you.

If you still not get it, I'm happy to try explain it again, I'm new on this, I'm a working progress.

**Comment by githubuser0xFFFF** [comment]
This is not possible. You can only dock CDockWidgets and not plain QWidgets. So whenever you create a QWidget you need to add it to a CDockWidget before you can drag and drop it into a container.

**Comment by felipefrr** [comment]
Thank you, githubuser0xFFFF!
