### ISSUE TITLE
Add support for widgets with Qt::WA_NativeWindow enabled

### ISSUE THREAD

**Issue by shelomentsev** [githubuser0xFFFF/Qt-Advanced-Docking-System#232]
The error occur if you add **Qt::WA_NativeWindow** flag to any widget, save doking state and restore it. I set **Qt::WA_NativeWindow** to QLabel in **createLongTextLabelDockWidget** and after restoration all single tabbet widgets became incorrect. I used latest of version of QT 5.15.

![example](https://user-images.githubusercontent.com/7734089/89093974-8cfcdd00-d3d8-11ea-8114-a7b1ff86cbe8.png)

**Comment by shelomentsev** [comment]
Hello, I finally found error, its QT bug. [https://bugreports.qt.io/browse/QTBUG-85990].
The error occurs when re-insert CDockWidget with native window handle and If CDockWidget added to CDockAreaWidget before CDockAreaWidget was added to the CDockContainerWidget as it is done in this code.

`CDockAreaWidget* DockContainerWidgetPrivate::addDockWidgetToContainer(DockWidgetArea area,
	CDockWidget* Dockwidget)
{
	CDockAreaWidget* NewDockArea = new CDockAreaWidget(DockManager, _this);
	NewDockArea->addDockWidget(Dockwidget);
	addDockArea(NewDockArea, area);
	NewDockArea->updateTitleBarVisibility();
	LastAddedAreaCache[areaIdToIndex(area)] = NewDockArea;
	return NewDockArea;
}
`

**Comment by KondeU** [comment]
Hello~ I also fell into the hole, I think it may be a similar problem. When I used winId() to get the native window, if I put two dock windows into a tab and then dragged them out to become two dock windows, a Qt error would be triggered: QWindowsWindow ::setGeometry Unable to set geometry...

**Comment by githubuser0xFFFF** [comment]
I close it, because it is no ADS for issue
