### ISSUE TITLE
FocusHighlighting does not work when the flag is set after dockmanager declaration

### ISSUE THREAD

**Issue by Reverier-Xu** [githubuser0xFFFF/Qt-Advanced-Docking-System#237]
in the example `sidebar` when i set the flag at here, it does not work:

![image](https://user-images.githubusercontent.com/41937333/90103505-334fc780-dd75-11ea-828a-abc758a7b267.png)

Nether `CDockManager::setConfigFlag()` nor `manager->setConfigFlag()` works.

It only works when I set it before dock manager declaration:

![image](https://user-images.githubusercontent.com/41937333/90103698-86c21580-dd75-11ea-9e5f-93d57fb55540.png)

but in my own project, I use QtDesigner to directly promote the widget to dockmanager in the ui file, so I may not be able to set these flags before declaring the dockmanager.

**Comment by githubuser0xFFFF** [comment]
All flags should be set before dockmanager declaration. This is intentionally. Please adjust your code.
