### ISSUE TITLE
Can not re-attach Tab widget to previous position after floating

### ISSUE THREAD

**Issue by thuannv199** [githubuser0xFFFF/Qt-Advanced-Docking-System#238]
After I float a widget tab from example build, then re-attach it to the same old position, the action can not be performed properly. The tab have been re-attached but there was more than an empty window covered it as well. After that I had 2 separate tab with the same name and in the connection with each others. Repeat it several times and then the program was crashed!
Any one have faced the same issue? or have any idea would be the big help, thanks!

**Comment by githubuser0xFFFF** [comment]
- which example?
- system (Linux, Windows)?
- Qt version?
- ADS version?
- what is the exact procedure to reproduce it?

**Comment by thuannv199** [comment]
* System is Window 10,
* Qt 5.4
* ADS: Release 3.5.2
* "Simple" example, but others are the same 

(Sorry I can upload data from this Laptop)

Step 1: User mouse drag start on "Label 1" and float it

Step 2: User mouse drag start on "Label 1" and drag it to the middle of MainWindow (on the same previous position)

Step 3:  User mouse drag end on "Label 1" (->the empty widget appear)

Step 4:  Repeat it! 

![image](https://user-images.githubusercontent.com/58841358/90612680-92f51980-e232-11ea-8f05-96c3b241bbbe.png)

![image](https://user-images.githubusercontent.com/58841358/90612827-c59f1200-e232-11ea-915e-7c8def6ee6d7.png)

**Comment by githubuser0xFFFF** [comment]
Please test version 3.4.2 and tell me if the problem also occurs.

**Comment by thuannv199** [comment]
It's the same problem for QT 5.4, but working good with QT 5.12. So the problem is version mismatch. The bad new is almost of my application based on old Qt version. 
One other bad new is the latest ADS (3.5.2) is not working either with Qt5.12 and older. Do you have any idea?

**Comment by githubuser0xFFFF** [comment]
The SimpleExample application was broken accidentally. I just fixed this and merged the fix into master. Please checkout master and test again. It should work now.

Qt 5.4 is not supported. The oldest version is Qt 5.5.1 but I would recommend at least Qt 5.12.2 - this is my develoment version.
