### ISSUE TITLE
Blurry icons on my non-hiDPI 1080p screen

### ISSUE THREAD

**Issue by richardjdare** [githubuser0xFFFF/Qt-Advanced-Docking-System#24]
Hi,
 On my non-hiDPI 1080p monitor the "close tab"  and "detach group" icons look blurry. The "close tab" icon looks like the sizing is a bit off compared to the example images in this repo. Here's a screenshot of the demo app running on my Windows 10 machine (using Qt 5.11.1 x64):

![ads-1080px-blurry](https://user-images.githubusercontent.com/9398854/52536607-ae858700-2d54-11e9-8384-b52c65c167c0.png)

**Comment by githubuser0xFFFF** [comment]
I know the problem and will take a closer look as soon as I have time. A workaround would be to set the images using stylesheets.

**Comment by githubuser0xFFFF** [comment]
Implemented a workaround for the latest Qt version. Tested with Qt 5.12.2
