### ISSUE TITLE
Found memory leak, use Qt5.12.8+VS2017 compiler

### ISSUE THREAD

**Issue by libaineu2004** [githubuser0xFFFF/Qt-Advanced-Docking-System#247]
1.Win10 x64/Qt5.12.8/VS2017
I added memory leak detection in the code:
#if defined(_MSC_VER) && defined(_DEBUG)
     _CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);
#endif

2.My code:
`void MainWindowPrivate::initDockWidget(QWidget *widget)
{
    ads::CDockManager::setConfigFlag(ads::CDockManager::OpaqueSplitterResize, true); //分割器拖动时,是否显示内容

    // Create the dock manager. Because the parent parameter is a QMainWindow
    // the dock manager registers itself as the central widget.
    QVBoxLayout *Layout = new QVBoxLayout(widget);
    Layout->setContentsMargins(QMargins(0, 0, 0, 0));
    DockManager = new ads::CDockManager(widget);
    Layout->addWidget(DockManager);

    // Set central widget
    QWidget *center = new QWidget(widget);
    ads::CDockWidget *CentralDockWidget = new ads::CDockWidget(tr("中心区域"), widget);
    CentralDockWidget->setWidget(center);
    auto *CentralDockArea = DockManager->setCentralWidget(CentralDockWidget);
    CentralDockArea->setAllowedAreas(ads::DockWidgetArea::OuterDockAreas);

    // create left dock widgets
    QTreeView *projectTree = new QTreeView(widget);
    projectTree->setFrameShape(QFrame::NoFrame);
    QFileSystemModel *fileModel = new QFileSystemModel(projectTree);
    fileModel->setRootPath(QDir::currentPath());
    projectTree->setModel(fileModel);
    ads::CDockWidget *projectDockWidget = new ads::CDockWidget(tr("工程文件"), widget);
    projectDockWidget->setWidget(projectTree);
    projectDockWidget->resize(150, 250);
    projectDockWidget->setMinimumSize(100, 250);
    projectDockWidget->setFeature(ads::CDockWidget::DockWidgetFloatable, false);
    m_pActionViewProject = projectDockWidget->toggleViewAction();
    auto *projectArea = DockManager->addDockWidget(ads::DockWidgetArea::LeftDockWidgetArea, projectDockWidget, CentralDockArea);
    Q_UNUSED(projectArea);`

3.When the software exits, it prompts a memory leak:
Detected memory leaks!
Dumping objects ->
{556666} normal block at 0x00000153B40CF390, 64 bytes long.
 Data: <                > 01 00 00 00 00 00 00 00 05 00 00 00 CD CD CD CD 
{555514} normal block at 0x00000153B40CF710, 64 bytes long.
 Data: <                > 01 00 00 00 06 00 00 00 02 00 00 00 03 00 00 00 
{555513} normal block at 0x00000153B429BBE0, 32 bytes long.
 Data: <                > 01 00 00 00 02 00 00 00 02 00 00 00 02 00 00 00 
{555512} normal block at 0x00000153B40D0710, 64 bytes long.
 Data: <                > 01 00 00 00 06 00 00 00 04 00 00 00 04 00 00 00 
{555121} 
normal block at 0x00000153B42A56C0, 32 bytes long.
 Data: <                > 01 00 00 00 02 00 00 00 00 00 00 00 01 00 00 00 
{555119} 
normal block at 0x00000153B42D78E0, 16 bytes long.
 Data: <                > 00 00 00 00 00 CD CD CD 84 06 00 00 00 00 00 00 
{555110} normal block at 0x00000153B3FC4210, 256 bytes long.
 Data: <         P- S   > A8 B3 BE B8 FC 7F 00 00 E0 50 2D B4 53 01 00 00 
{555109} normal block at 0x00000153B42D50E0, 16 bytes long.
 Data: < <       B  S   > 90 3C E6 B8 FC 7F 00 00 10 42 FC B3 53 01 00 00 
{555105} normal block at 0x00000153B42D6170, 16 bytes long.
 Data: <                > 00 00 00 00 01 CD CD CD 9C 04 00 00 00 00 00 00 
{555104} normal block at 0x00000153B40ABCB0, 128 bytes long.
 Data: <                > 01 00 00 00 05 00 00 00 06 00 00 00 CD CD CD CD 
{555103} normal block at 0x00000153B429B700, 32 bytes long.
 Data: <    S           > B0 BC 0A B4 53 01 00 00 00 00 CD CD 00 00 00 00 
{555102} normal block at 0x00000153B3DB4A50, 72 bytes long.
 Data: <07  S   07  S   > 30 37 DB B3 53 01 00 00 30 37 DB B3 53 01 00 00 
{555101} normal block at 0x00000153B429C720, 24 bytes long.
 Data: <         j      > 01 00 00 00 CD CD CD CD 00 6A 02 CB FC 7F 00 00 
{555100} normal block at 0x00000153B429B220, 24 bytes long.
 Data: <            S   > 00 00 00 00 00 00 00 00 10 07 0D B4 53 01 00 00 
{555099} normal block at 0x00000153B429BD60, 24 bytes long.
 Data: <            S   > 00 00 00 00 00 00 00 00 10 F7 0C B4 53 01 00 00 
{555098} normal block at 0x00000153B40ACF70, 120 bytes long.
 Data: <                > 02 00 00 00 00 00 00 00 00 00 00 00 CD CD CD CD 
{555097} 
normal block at 0x00000153B435A370, 176 bytes long.
 Data: < j      07  S   > 80 6A BE B8 FC 7F 00 00 30 37 DB B3 53 01 00 00 
{555096} normal block at 0x00000153B3DB3730, 72 bytes long.
 Data: <  +     p 5 S   > 90 03 2B CB FC 7F 00 00 70 A3 35 B4 53 01 00 00 
{546174} normal block at 0x00000153B40A8230, 128 bytes long.
 Data: <                > 01 00 00 00 00 00 00 00 0D 00 00 00 CD CD CD CD 
{299740} normal block at 0x00000153B3EB7040, 16384 bytes long.
 Data: <                > 01 00 00 00 00 00 00 00 A9 02 00 00 CD CD CD CD 
{251} 
normal block at 0x00000153AF9D8C60, 176 bytes long.
 Data: < j      @o  S   > 80 6A BE B8 FC 7F 00 00 40 6F 9F AF 53 01 00 00 
{250} normal block at 0x00000153AF9F6F40, 16 bytes long.
 Data: < j      `   S   > 98 6A BE B8 FC 7F 00 00 60 8C 9D AF 53 01 00 00 
{249} normal block at 0x00000153AF9CB380, 120 bytes long.
 Data: <                > 01 00 00 00 00 00 00 00 00 00 00 00 CD CD CD CD 
Object dump complete.

**Comment by libaineu2004** [comment]
I found that there are many places in the'ads' project where the source code is only new, but there is no delete or no parent class specified. Is this appropriate? Is it the cause of the memory leak?
E.g:
d->Layout = new QBoxLayout(QBoxLayout::TopToBottom);
auto Button = new QToolButton();
TitleLabel = new tTabLabel();
...

**Comment by githubuser0xFFFF** [comment]
There is always the potential risk of memory leaks, if new and delete are used. There are also many situations in Qt, where a parent is not explicitely assigned but implicitely - for example when adding a layout created with new to a widget (https://stackoverflow.com/questions/29302965/qt-parent-of-layout)  or when adding widgets to an layout (https://stackoverflow.com/questions/10195762/does-owner-of-qboxlayout-become-the-owner-of-all-layout-widgets).

So not every QObject cerated with new without an explicit parent is without a parent.

The output of the memory check is not very helpfull btw. Maybe you can play around a little bit to find out, which object is causing the memory leak. I also noticed some wrong memory leak detection in the past when using this method and when working with DLLs.
