### ISSUE TITLE
Floating window cannot dock into main window on linux desktop

### ISSUE THREAD

**Issue by helywin** [githubuser0xFFFF/Qt-Advanced-Docking-System#25]
I've test demo on ubuntu 16.04 unity、ubuntu 18.04 gnome/kde，they  all have this problem. My Qt version is 5.12.2

**Comment by githubuser0xFFFF** [comment]
Ok, thank you. I will check this

**Comment by githubuser0xFFFF** [comment]
Hi,

I tested the master branch on Kubuntu 18.04 and it dit not work very well. Also your pull request could not improve this a lot. I created a new branch linux_experimental and spent the last two days implementing inital Linux support. On Linux there are some thins missing, that are used by the Advanced Docking System (i.e. NonClientAreaMouseEvents). So it was a hard job to make it working. So if you need Linux support, you can try out the linux_experimental branch now.

**Comment by helywin** [comment]
thanks

**Comment by helywin** [comment]
FloatingWidgetTitleBar.cpp is missing

**Comment by githubuser0xFFFF** [comment]
Sorry, just fixed this
