### ISSUE TITLE
Using CMake: ads_globals.cpp:42:10: fatal error: QX11Info [missing file or directory]

### ISSUE THREAD

**Issue by fabval** [githubuser0xFFFF/Qt-Advanced-Docking-System#250]
Branch: Master
Kubuntu 19.10 (Virtual Machine)
Qt 5.15.0 installed with online installer (there is also a Qt 5.12 installed in the system).

When Ads is built using .pro and Qt 5.15.0 kit everything is fine and the demo is working as expected.

Using CMake, the compiler cannot retrieve QX11Info.

Steps to reproduce:

- Open Konsole in the root folder of ADS
> mkdir -p build
> cd build
> cmake -DCMAKE_PREFIX_PATH=/opt/Qt/5.15.0/gcc_64 ..
> cmake --build .

.../Qt-Advanced-Docking-System/src/ads_globals.cpp:42:10: fatal error: QX11Info: File o directory non esistente [missing file or directory]
   42 | #include \<QX11Info>

The references to QWidget and other GUI components are successfully retrieved

**Comment by githubuser0xFFFF** [comment]
This is right. The CMake files are a contribution from other people, so I do not know how to fix this.

**Comment by fabval** [comment]
I've fixed locally the issue:

In 

    QtAdvancedDockingSystem/src/CMakeLists.txt

replace line 62:

    target_link_libraries(qtadvanceddocking PUBLIC Qt5::Core Qt5::Gui Qt5::Widgets)

with

    target_link_libraries(qtadvanceddocking PUBLIC Qt5::Core Qt5::Gui Qt5::Widgets)
    if (UNIX)
        target_link_libraries(qtadvanceddocking PUBLIC Qt5::X11Extras)
    endif()

Now the cmake --build is working as expected and I can launch the demo without any error.

Today I cannot manage the pull request but I hope that the above hint could help

**Comment by githubuser0xFFFF** [comment]
Thank you very much. I added your fix in the last commit.
