### ISSUE TITLE
Window momentarily flashes as floating widget

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#251]
When creating a new CDockWidget it very briefly opens up as a floating widget. I observed this when I upgrade to v3.6 in one of my applications but am also able to reproduce it with one of the included examples.

### Setup
Windows 10
MSVC 2019
Qt 5.15
Advanced Docking System (v3.6 and HEAD at time of issue 48c4106b7f37bcc8aa6fe16d26bb6b40b11d3813)

### Steps to reproduce
1. Run the `deleteonclose` example. 
2. Use either of the menu options to create a new docked widget.
3. Observe there is a quick window that opens and closes. I am assuming it is showing it as floating briefly.

Recording...I have slowed it down a bit but you can see a flash at the top left of the main window.

![floatingwidget](https://user-images.githubusercontent.com/3694843/91875454-7e108100-ec49-11ea-91a4-8ba82a6a0377.gif)

**Comment by dail8859** [comment]
I used `git bisect` and it shows 703a9b3e1293b5ff89d810cb00fd00f987f38aeb was where the issue was introduced.

**Comment by dail8859** [comment]
@shelomentsev

**Comment by githubuser0xFFFF** [comment]
Thank you. I will contact the author of the patch and ask him to fix this.

**Comment by githubuser0xFFFF** [comment]
I just fixed this issue with commit 65058d3a4847c0695ec5959320cd864f60c35c2c

**Comment by dail8859** [comment]
@githubuser0xFFFF I can confirm the issue has been fixed. Thanks!
