### ISSUE TITLE
Add method getFocusedWiget() to CDockManager

### ISSUE THREAD

**Issue by KerimMatlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#252]
Hi,

It would be nice if `CDockManager` had the method wich returns focused `CDockWidget`.

**Comment by githubuser0xFFFF** [comment]
Added this function with the latest commit - is now available in master

**Comment by dail8859** [comment]
Glad to see this added as well. Needed this exact functionality recently.

**Comment by KerimMatlab** [comment]
thank you!
