### ISSUE TITLE
Add signal when CDockWidget added and about to be added

### ISSUE THREAD

**Issue by KerimMatlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#253]
Hi,

There are signals like `dockWidgetRemoved` and `dockWidgetAboutToBeRemoved`
I think it would be logically nice if there were opposite signals like `dockWidgetAdded(CDockWidget* dock)` and `dockWidgetAboutToBeAdded(CDockWidget* dock)` when the dock is going to

**Comment by githubuser0xFFFF** [comment]
Could you please elaborate about your use case so that I get an ideo why you need both signals?

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF generally I need it when I have one `QTreeView` with checkable items and many `CDockWidget`. 
When `CDockWidget` focus changes I need to reset checkstate of items in treeview (for each `CDockWidget` user can check/uncheck items independantly). 
So when new `CDockWidget` added/removed I need to prepare my items in treeview so that items have checkstate available for those windows.

**Comment by githubuser0xFFFF** [comment]
Just added the singnal `dockWidgetAdded(CDockWidget* dock)` to the dock manager. Please test, if this is ok for your application or if you need the `dockWidgetAboutToBeAdded(CDockWidget* dock)`.

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF thank you, works fine!

**Comment by KerimMatlab** [comment]
@githubuser0xFFFF I've just found that `focusedDockWidgetChanged` signal is sent before `dockWidgetAdded` when creating new `CDockWidget`. When I create new `CDockWidget` I can see that this newly created window becomes focused and only then it sends signal that the window was created.
If this is true then it logically incorrect and leads to some unexpected result.
Could you please check it and if I'm not mistaken change the order of sent signals as: `dockWidgetAdded` and only then `focusedDockWidgetChanged`.
