### ISSUE TITLE
Dock within tab

### ISSUE THREAD

**Issue by hexvenn** [githubuser0xFFFF/Qt-Advanced-Docking-System#254]
Hello.
Thank you for sharing this library.
I am working on an application that has a tabbed interface. I would like to know if it is somehow possible to dock a widget within a tab instead of the container that has dock manager put in it.

Example:
![2020-09-08 09_16_17-githubuser0xFFFF_Qt-Advanced-Docking-System_ Advanced Docking System for Qt](https://user-images.githubusercontent.com/28839675/92445675-f5e42b80-f1b4-11ea-8286-d51386b0e84f.png)
When dropping another dock to the right side we get this:
![2020-09-08 09_16_37-githubuser0xFFFF_Qt-Advanced-Docking-System_ Advanced Docking System for Qt](https://user-images.githubusercontent.com/28839675/92445858-43609880-f1b5-11ea-9744-da2376e63e9a.png)
and instead, if it were possible to do this (much like with the floating containers as they are, but nested within the main window):
![dockExample](https://user-images.githubusercontent.com/28839675/92446238-d13c8380-f1b5-11ea-9c4b-552695b8d609.png)
This would allow for a tabbed interface with different layout inside each tab.
Now, I figured out that similar behavior is possible by creating dock managers inside the tab page areas. But then widgets cannot be "transferred" across the different tabs.

I would like to know if it is possible to achieve this. Using the tab system of this library is desirable due to the ability to rearrange and float the tabs.

**Comment by githubuser0xFFFF** [comment]
Hi, this is not possible currently and it is not the intended usage of this library. So for this special usecase I'm afraid you need to implement your own solution.
