### ISSUE TITLE
FindChild/FindChildren/Children not working as with QDockWidget

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#255]
With QDockWidget, when we use FindChild/FindChildren/Children methods the objects returned can be in hidden or tabbed under another widget.

In CDockWidget, when a dock is tab in under another dock or hidden, the widget won't be returned by those methods.

Is it possible to make it working like in Qt (find or return all parented objects, not just actually in an active widget) ?

**Comment by githubuser0xFFFF** [comment]
Yes, this is right. This is how it is implemented and it is intentionally because it has a negative impact on switching perspectives if the CDockWidgets are children. So I'm adraid you need to work around this somehow.
