### ISSUE TITLE
Central widget lost when restoring state

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#256]
Seems that the central widget does not get saved when calling `CDockManager::saveState`, and when restoring the state the first thing it does is remove the central widget, without setting the central widget to what it was.

I added save state and restore state to the central widget example, to see the issue better.
![QL1BjMnujL](https://user-images.githubusercontent.com/1664301/93586228-483cfd80-f9a8-11ea-8770-782e552c7792.gif)

**Comment by rolivav** [comment]
It seems impossible to use the central widget feature and save states together right now, if you set the central widget after this it will create a new dock area at the bottom, since the central widget must be the first widget you set up.

Here you can see what happens if I reset the central widget after restoring.
![VRyZ2XwPIR](https://user-images.githubusercontent.com/1664301/93586870-47f13200-f9a9-11ea-94cd-bb205ac4f3b6.gif)
It is quite fragile at the moment.

**Comment by githubuser0xFFFF** [comment]
Just fixed this with the latest commit

**Comment by rolivav** [comment]
Great, thanks!
