### ISSUE TITLE
Python bindings available via pip/pypi?

### ISSUE THREAD

**Issue by skuep** [githubuser0xFFFF/Qt-Advanced-Docking-System#257]
Hi all,
Very nice implementation of an advanced docking system. 
We are currently developing an application with PyQt and are currently not using/requiring conda and would like to keep it that way. Was there a deliberate decision to not put the python bindings on pip/pypi repository?

Best Regards

**Comment by githubuser0xFFFF** [comment]
The Python bindings are a contribution from several users - so I cannot say anything about this.
