### ISSUE TITLE
Should not check if "UserVersion" exists in the state when restoring

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#258]
I was adding the save version feature for the docking system and to my surprise it is still not working for me.
This is due to a check that is done here:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/DockManager.cpp#L268

I do not agree with that comment, old states that did not support "UserVersion" in my opinion should fail to restore. Right now I have no way to reset the local states since this will return true. The layout will be incorrect and the application will look, for lack of a better word, like crap 😄 .

This is not blocking me, for now I'm manually checking if the state contains "UserVersion", and removing it if it doesn't, but it would be nice to be able to remove that code.

**Comment by githubuser0xFFFF** [comment]
Sorry, I cannot remove this because it breaks our application

**Comment by rolivav** [comment]
All good! I hope if anyone else has a problem with this they find my comment and my workaround :)
