### ISSUE TITLE
Question: Event on window changed from floating and back

### ISSUE THREAD

**Issue by xumepoc** [githubuser0xFFFF/Qt-Advanced-Docking-System#259]
I may missed it, but is there a signal/method which is called every time a floating window is not more (e.g. a window has been docked to it or it has been docked to some other window) and back? 

I am asking because I need to know if the window is floating or not in order to add additional elements to the window if it is single floating window.

**Comment by githubuser0xFFFF** [comment]
You can use the CDockWidget::topLevelChanged()  event for this.

**Comment by xumepoc** [comment]
Thanks :)
