### ISSUE TITLE
Crash caused by faulty central widget test

### ISSUE THREAD

**Issue by juangburgos** [githubuser0xFFFF/Qt-Advanced-Docking-System#260]
Shouldn't [this line](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/f543318232844e91136a456c649275cca6fb635b/src/DockManager.cpp#L286):

```c++
if (CentralWidget && CentralWidgetAttribute.isEmpty())
```

should read:

```c++
if (!CentralWidget || (CentralWidget && CentralWidgetAttribute.isEmpty()))
```

?

**Comment by githubuser0xFFFF** [comment]
Just fixed this.
