### ISSUE TITLE
Preferred way of serializing panel type?

### ISSUE THREAD

**Issue by xeash** [githubuser0xFFFF/Qt-Advanced-Docking-System#261]
Hi, I have 3d editor like app, with Dockable Panels, and PanelRegistry with different PanelTypes (e.g Viewport, Scene Objects Tree, Console Output and etc), and arbitrary number of Panel Instances of one of registered types opened by user.
I just want before user quit the app serialize state of opened docker panels with registered types, and restore state when user open the app again.
Whats' recommended approach of doing this? I found that,  you cannot extend serialized attributes for dockable panels (e.g I want to add "panelType" string) without modifying the library?
Or its intended that you serialize ADS state first, then iterate on panels, and store your app state?
I imagine thats very common scenario for docking system, my question is about **proper use of ADS API.**

Thanks

**Comment by githubuser0xFFFF** [comment]
When you restore you docking state, then all DockWidgets should have been created already. So you should first restore your panels and then if all dock widgets are there, you can restore the docking state.
