### ISSUE TITLE
Add a signal that indicates that the state has changed

### ISSUE THREAD

**Issue by chris-se** [githubuser0xFFFF/Qt-Advanced-Docking-System#268]
It would be great if there could be support for detecting when the state changes. This is in order to implement a "dirty" logic to be able to ask the user whether they want to save the new state when they close the main window. (Similar to how a text editor considers a document "dirty" when it has changed.)

The following state changes could happen:

- A splitter is resized due to the user explicitly resizing it
- A dock widget has changed its open/close state
- A dock widget has changed its floating/docked state
- A dock widget has been moved to a different area
- A floating dock widget has changed its size
- Tabs have switched their order
- (Maybe I'm missing something)
- A perspective has been activated
- A programmatic change has happened (dock widget created / removed, etc.)

It would be great if there could be a flag enumeration for these different kinds of changes that may occur, and a signal with this enumeration as its argument that is emitted anytime any of these things happen, so that the user can decide at what point they consider the layout "dirty".

e.g.

```
class CDockManager {
// ...
public:
// ...
enum eStateChangeFlag {
  SplitterResized = 0x001,
  // ...
};
Q_DECLARE_FLAGS(StateChangeFlags, eStateChangeFlag);
// ...
signals:
   void stateChanged(StateChangeFlags flags);
// ...
};
```

Example usage:

```
void MainWindow::on_dockManager_stateChanged(CDockManager::StateChangeFlags flags)
{
    if (flags & (... flags that are considered state change in this application ...)) {
        if (!m_isDirty) {
            m_isDirty = true;
            // + mark UI as "dirty"
        }
    }
}
```

I'd be willing to implement this but wanted to wait for feedback before starting in case you had any objections.

**Comment by githubuser0xFFFF** [comment]
> This is in order to implement a "dirty" logic to be able to ask the user whether they want to save the new state when they close the main window. (Similar to how a text editor considers a document "dirty" when it has changed.)

Why would you like to ask the users, if they want to save the new state? Normally you simply safe the state if you close the main  window and restore it later. Could you please elaborate about the use case of this feature?

**Comment by chris-se** [comment]
We have a data analysis application where we want the user to be able to configure an arbitrary amount of views for a specific project, and to be able to store how the views are arranged within the project file. If the user opens a different project file the views will change to those stored in the other project file that was loaded. But to determine if the user has changed anything in the project (such as how the views are arranged) we need to know if they did indeed rearrange something.

Hope that makes sense?

**Comment by githubuser0xFFFF** [comment]
In our application we do exactly the same but without this feature. We have a laboratory automation software, where the user can configure the views in a project. If the user switches the project, the current state of the views is saved into the current project and when the new project has been opend, the configuration form the new project will be restored - that means, you do not need to dectect if user changed anything if you simply store the view configuration whenever you close a project.

**Comment by chris-se** [comment]
For various reasons we don't want to auto-save projects.

Would you be opposed to adding this kind of signal (as I said: I'd be willing to implement this, I just wanted to wait for feedback before starting)? Any user that's not interested in this would not affected by this, as they could ignore the signal.

**Comment by githubuser0xFFFF** [comment]
Hi Chris, at the moment I would be opposed to adding this kind of signal because it will cause a lot of code changes because you need to track a lot of changes and I don't like the idea of adding a lot of complexity for a single use case that can easily be solved with another way of implementing something - sorry.

I also do not think that you should auto-save your project - you should only save the state of the GUI and the docking system if you switch your project. If you do not want to auto-save your project, then you can simply assume that your view configuration is "dirty" and then you simply do what you would do in case your "view" configuration is dirty. From the long time experience of our application I can assure you that you can safely assume the view configuration is "dirty" because splitter resize will always happen. As soon as your user will start working with a project, I is almost safe that it is "dirty".

**Comment by chris-se** [comment]
In our case a project is just a single file (this is fully intentional, so that projects are trivially portable between computers), and any time the user changes something else there is a prompt when closing the project whether to save it or not. And what kind of views can be placed depends on other things the user may change. I could hence have two situations: the user only changed views (the project not being "dirty"), in which case auto-saving the view configuration would be ok -- but if the user also changed other things then the view configuration could depend on the other things the user changed. If the user selects "yes" at the close prompt this would still be fine, but what do I do if the user selects "no" here? I can't save the current view configuration because it may depend on things that aren't there in the project still on disk; but if I don't do that, then the software reacts in two different ways when the current project is closed: if the user only changed the views these changes will be saved automatically in the background, but if the user changed other things they didn't want to save and chose "no" the view changes aren't saved at all in that case. I don't think this is a very consistent user interface.

Furthermore I actually don't want to consider simple resizes to splitters to make the project dirty (hence my approach wit the flags in the signal, so that I can choose what to react to), just rearrangements. Without being able to react to specific changes I can only serialize the current configuration and compare it, but as you said: then it could basically always be considered dirty.

I also don't think that this would require a lot of code changes. Just a couple of strategically placed 'emit' and 'connect' calls in a dozen places or so should be more than sufficient here -- my proposal doesn't want to **track** changes, it only wants to emit a signal when they happen (which is always quite local). My proposal also doesn't want to give feedback about the exact thing that changed, only the type of change that happened. (For example: "the open/close state of a dock widget has changed", but not _which_ dock widget this was.) The "dirty tracking" would still have to happen in the user application, I only provided that as an explanation for the reasoning behind the signal I'd like to add.

I hope this makes sense and you could reconsider this. (If you're still not convinced, I'll just carry a local patch that just does what I need, but I think this could also be useful for other people.)

**Comment by githubuser0xFFFF** [comment]
Ok, I'm willing to review your patch if it is small, if it does not add a lot of overhead and if it does not have a negative impact on the performance. But I cannot guarantee, that I will accept the patch.
