### ISSUE TITLE
Change DockWidgetTab icon size 

### ISSUE THREAD

**Issue by stijnherfst** [githubuser0xFFFF/Qt-Advanced-Docking-System#269]
I'm trying to change the icon size of a DockWidgetTab to something larger using either code or preferably stylesheets. It seems that the size is locked as my attempts to change it via a stylesheet didn't work. It seems they are set to a fixed size:

 `d->IconLabel->setPixmap(Icon.pixmap(style()->pixelMetric(QStyle::PM_SmallIconSize, nullptr, this)));`

Here is an example image of the icons I want to enlarge.
![image](https://user-images.githubusercontent.com/8471644/97016564-2c032200-154d-11eb-947f-be55e2a177ad.png)

Is it possible to change the icon size somehow?

**Comment by githubuser0xFFFF** [comment]
I think this is not possible at the moment.

**Comment by githubuser0xFFFF** [comment]
Added support for setting the DockWidgetTab icon size via stylesheet (see commit aedbaec4979162c7f56c4dee842be298973218fb). You can change the icon size this way:

```css
ads--CDockWidgetTab
{
	qproperty-iconSize: 32px 32px;
}
```

**Comment by stijnherfst** [comment]
Awesome! Thank you for your work.
