### ISSUE TITLE
..ld.exe: cannot find -lqtadvanceddockingd

### ISSUE THREAD

**Issue by blacksheepinc** [githubuser0xFFFF/Qt-Advanced-Docking-System#271]
Hello

I've got this error during building. 
What could be the problem?
(qt creator 4.13.2, win10)

![Capture](https://user-images.githubusercontent.com/397624/98106386-998e4700-1e99-11eb-898e-3b76f433be93.JPG)

`C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtadvanceddockingd
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Makefile.Debug:80: ../lib/AdvancedDockingSystemDemo.exe] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/demo'
mingw32-make[1]: *** [Makefile:45: debug] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/demo'
mingw32-make: *** [Makefile:77: sub-demo-make_first] Error 2
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make[2]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/centralwidget'
C:/Qt/Tools/mingw810_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/simple'
C:/Qt/Tools/mingw810_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/sidebar'
C:/Qt/Tools/mingw810_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/deleteonclose'
C:/Qt/Tools/mingw810_64/bin/mingw32-make -f Makefile.Debug
mingw32-make[3]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/simple'
g++ -Wl,-subsystem,windows -mthreads -o ..\..\lib\SimpleExample.exe debug/main.o debug/MainWindow.o debug/moc_MainWindow.o  -LC:\Users\meszarm2\Desktop\build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug\lib -lqtadvanceddockingd C:\Qt\5.15.1\mingw81_64\lib\libQt5Widgets.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Gui.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Core.a  -lmingw32 C:\Qt\5.15.1\mingw81_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
mingw32-make[3]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/deleteonclose'
g++ -Wl,-subsystem,windows -mthreads -o ..\..\lib\DeleteOnCloseTest.exe debug/main.o  -LC:\Users\meszarm2\Desktop\build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug\lib -lqtadvanceddockingd C:\Qt\5.15.1\mingw81_64\lib\libQt5Widgets.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Gui.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Core.a  -lmingw32 C:\Qt\5.15.1\mingw81_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
mingw32-make[3]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/sidebar'
g++ -Wl,-subsystem,windows -mthreads -o ..\..\lib\SidebarExample.exe debug/main.o debug/MainWindow.o debug/moc_MainWindow.o  -LC:\Users\meszarm2\Desktop\build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug\lib -lqtadvanceddockingd C:\Qt\5.15.1\mingw81_64\lib\libQt5Widgets.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Gui.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Core.a  -lmingw32 C:\Qt\5.15.1\mingw81_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
mingw32-make[3]: Entering directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/centralwidget'
g++ -Wl,-subsystem,windows -mthreads -o ..\..\lib\CentralWidgetExample.exe debug/main.o debug/mainwindow.o debug/moc_mainwindow.o  -LC:\Users\meszarm2\Desktop\build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug\lib -lqtadvanceddockingd C:\Qt\5.15.1\mingw81_64\lib\libQt5Widgets.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Gui.a C:\Qt\5.15.1\mingw81_64\lib\libQt5Core.a  -lmingw32 C:\Qt\5.15.1\mingw81_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtadvanceddockingd
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [Makefile.Debug:72: ../../lib/SimpleExample.exe] Error 1
mingw32-make[3]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/simple'
mingw32-make[2]: *** [Makefile:45: debug] Error 2
mingw32-make[2]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/simple'
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtadvanceddockingd
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [Makefile.Debug:68: ../../lib/DeleteOnCloseTest.exe] Error 1
mingw32-make[3]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/deleteonclose'
mingw32-make[2]: *** [Makefile:45: debug] Error 2
mingw32-make[2]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/deleteonclose'
mingw32-make[1]: *** [Makefile:78: sub-simple-make_first] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
mingw32-make[1]: *** [Makefile:128: sub-deleteonclose-make_first] Error 2
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtadvanceddockingd
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [Makefile.Debug:72: ../../lib/CentralWidgetExample.exe] Error 1
mingw32-make[3]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/centralwidget'
mingw32-make[2]: *** [Makefile:45: debug] Error 2
mingw32-make[2]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/centralwidget'
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtadvanceddockingd
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [Makefile.Debug:72: ../../lib/SidebarExample.exe] Error 1
mingw32-make[2]: *** [Makefile:45: debug] Error 2
mingw32-make[3]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/sidebar'
mingw32-make[2]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples/sidebar'
mingw32-make[1]: *** [Makefile:53: sub-centralwidget-make_first] Error 2
mingw32-make[1]: *** [Makefile:103: sub-sidebar-make_first] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/meszarm2/Desktop/build-ads-Desktop_Qt_5_15_1_MinGW_64_bit-Debug/examples'
mingw32-make: *** [Makefile:102: sub-examples-make_first] Error 2
12:27:49: The process "C:\Qt\Tools\mingw810_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project ads (kit: Desktop Qt 5.15.1 MinGW 64-bit)
When executing step "Make"
12:27:49: Elapsed time: 00:07.`

**Comment by githubuser0xFFFF** [comment]
I think you somehow messed up your linker search path. If I open the ADS in QtCreator I can build it with MinGW without any problems. But in your build output I can see a lot of linker search paths that I do not see whn I build the library:

- LC:\openssl\lib
- LC:\Utils\my_sql\mysql-5.7.25-winx64\lib 
- LC:\Utils\postgresql\pgsql\lib

I do not see these linker search paths here. So this does not look like a standard ADS library build for me.

**Comment by blacksheepinc** [comment]
This is a fresh Qt install, ads is untouched, just unzipped. Thats all. 
Even tried at home, different PC, fresh install etc. Same output. Are you using qt 5.15.1?

**Comment by blacksheepinc** [comment]
Changing from Debug to Release did the job, built successfully. Thanks for the quidance!
