### ISSUE TITLE
Glitch when restoring saved perspective

### ISSUE THREAD

**Issue by ttddee** [githubuser0xFFFF/Qt-Advanced-Docking-System#272]
Hi!

This docking system is great, thanks for making it!

I have a glitch after reloading a saved perspective. I might be doing it wrong though.

This is how I set up the settings to use an ini file:

```
QSettings::setPath(QSettings::IniFormat, QSettings::SystemScope, QDir::currentPath());
```

For saving the perspective:

```
void MainWindow::saveWindowLayout()
{
    QSettings settings(
                QSettings::IniFormat,
                QSettings::SystemScope,
                "settings",
                "user");
    dockManager->addPerspective("custom");
    dockManager->savePerspectives(settings);
}
```

And then loading:

```
void MainWindow::restoreWindowLayout()
{
    QSettings settings(
                QSettings::IniFormat,
                QSettings::SystemScope,
                "settings",
                "user");
    dockManager->loadPerspectives(settings);
    dockManager->openPerspective("custom");
}
```

The ini file itself looks like this after saving it:

```
[Perspectives]
size=1
1\Name=custom
1\State="@ByteArray(\0\0\x2Sx\xda}RQO\xc2\x30\x18|\xf7W4}\xc7\x8d\x89\x4\x93R\xb2\xcc\xe0\x1bj\x6\xf8\\\xd7\xcf\xd9\xd8\xb5K[@\x8d?\xdeo\x83\f$\xcc\xa7\xb6w\xf7\xdd]\xd3\xb2\xd9g\xa5\xc9\x16\x9cW\xd6L\xe9\xf0:\xa6\x4La\xa5\x32\xe5\x94\xae\x96\xf3\xc1\x84\xce\x38{\xe\xa9\xdc\nS\x80\xbc\xb7\xc5\ar\xf9\x97\xfP\x91u7H\xc9\xca\x83\xeb\xceh\x93Y\x13\x84\x32\x88\xb4t\x6&8\xa1_\x94,!L\xe9Z\xc1\xe\x1c\xe5\xac\x93\x91\xb9\xb6\"\xb4\xb9\x31\xe2y\xadU\b\b?:\x85\xa3\xc8\x34\xbe\x83\xc6wc\xd0 \xe9\xd5\xfc\xfc\xd1\xa4\xe\x4Y\x8a\xd7\x43\x8b\x8ds`\x8e\xf9$\xd5\xda\xee@6*T\xbcQl!\xcaV\xcb\xd9\xbe+Y\x88\n\x8e\x3\x99\xb6\x1e\x64\xd3\x31\xe2,j\xe6z3\x9e\x9c\xad\xc1\x5\x5\xfe\xdc\xec\x84\xb9h\x98\xabo\xf0|x{7\"7ILX\xb4\ap=\xdc\xb8\x37sa%\x90\a'\xea\xf7\xf3\xcc\x13\xe6\x9f\xcc\xf1xD\x92\xc9\xe5\xc8\xa8{+\xdc\xf7|\t~\xf5\vf,\xc3\x9d)"
```

Normally the app looks like this:

![001](https://user-images.githubusercontent.com/16922381/98157380-302a2a80-1ed1-11eb-855b-e274fe575aea.jpg)

After loading I get this doubling of the header and the borders. 
![002](https://user-images.githubusercontent.com/16922381/98157458-4a640880-1ed1-11eb-909b-a5411c352a04.jpg)

The double elements are not clickable, do I need to manually refresh something?

**Comment by githubuser0xFFFF** [comment]
I have no idea what is going wrong. I just tested the current ADS version in our software an I don't see this issue. Strange.

**Comment by ParadoxDaKo** [comment]
I am experiencing the same issue. @ttddee Were you able to find a workaround for this?

**Comment by ttddee** [comment]
No I didn't find a solution. My "workaround" has been to not use the save/restore feature.

**Comment by ParadoxDaKo** [comment]
@githubuser0xFFFF I only get this issue when I restore a dock that contains a 3D/2D rendered graphics window. In this case, it's probably the image preview, in my case it's a 3D preview.

**Comment by ParadoxDaKo** [comment]
@githubuser0xFFFF I found a workaround for this issue.

My render graphics window is inheriting QMainWindow and used the actual MainWindow of the application as its parent upon construction. Somehow this caused the aforementioned graphical issues. Assigning nullptr as the parent of my render graphics window does not create these issues upon restoring.

@ttddee Maybe this will also fix the issue on your side?
