### ISSUE TITLE
Questions regarding floating/limiting widget area 

### ISSUE THREAD

**Issue by Imagine-Programming** [githubuser0xFFFF/Qt-Advanced-Docking-System#274]
First of all, thank you for providing the Qt community with such an amazing docking system. 

When I set 

```cpp
auto dockWidget = new ads::CDockWidget(title);
dockWidget->setObjectName(id.isEmpty() ? title : id);
dockWidget->setWidget(widget);
dockWidget->setFeature(ads::CDockWidget::DockWidgetFeature::DockWidgetFloatable, false);
```

I can no longer move the widget to another area at all, while I think it should only prevent floating. Am I missing something?
Aside from that, is there a way that I could limit a specific widget to a specific area? As per example, I would like to limit Widget1, Widget2 and Widget3 to the center area exclusively, but all other widgets to any of the outer areas. Is that possible?

Thank you again.

**Comment by githubuser0xFFFF** [comment]
Ensure that you enable NonOpaqueUndocking:

```c++
CDockManager::setConfigFlags(CDockManager::DefaultNonOpaqueConfig);
```
If you use Opaque Undocking, then ou can only move dock widgets by making them floating an if this is not possible, then you can not move them. In non opaque mode, moving is possible without making the widget floating.
