### ISSUE TITLE
How to properly add a new widget to an outer area of a floating widget?

### ISSUE THREAD

**Issue by peeet** [githubuser0xFFFF/Qt-Advanced-Docking-System#278]
Aloha!

I would like to add a new widget to an OuterDockArea of a floating widget and I have tried different ways, but it leads to problems.

##### I tried it directly via DockManager:
```cpp
m_dockManager->addDockWidget(ads::RightDockWidgetArea, &newDockWidget, dockAreaOfFloatingWidget);
```
The result looks different than doing it via drag and drop. Only the new widget on the right has dock area buttons. And it also produces crashes in some circumstances.

##### I tried it via CDockContainerWidget:
```cpp
auto* container = dockAreaOfFloatingWidget->dockContainer();
container->addDockWidget(ads::RightDockWidgetArea, &newDockWidget, dockAreaOfFloatingWidget);
```
The result looks good. Just like drag and drop via mouse. But the new widget is not added to the `dockWidgetsMap` and will therefore not be destroyed when closing the app for example.

What would be the right way to do this by code?

**Comment by githubuser0xFFFF** [comment]
Hi,

I think you found a bug. I just fixed this in this branch:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/adddockwidget_fix

Now your code should work:

```c++
m_dockManager->addDockWidget(ads::RightDockWidgetArea, &newDockWidget, dockAreaOfFloatingWidget);
```

I changed the demo application and added a test for this. To test this, first create a floating editor (`Create Floating Editor`) and then create docked editors (`Create Docked Editor`). This will add the docked editors to the last created floating editor.

Please test and tell me, if I can merge this fix.

**Comment by peeet** [comment]
Yes, now with this fix it works as expected. Thank you for your quick answer!

**Comment by githubuser0xFFFF** [comment]
Ok, thank you. I just merged this into master
