### ISSUE TITLE
Floating window cannot exit normally in central widget mode

### ISSUE THREAD

**Issue by KondeU** [githubuser0xFFFF/Qt-Advanced-Docking-System#279]
In CentralWidget mode, if there are more than one floating window, only the first floating window will be closed when the main window is closed, the other windows will not exit and the process died.
1. Two floating windows:
![0001](https://user-images.githubusercontent.com/29046736/99909008-db840d80-2d20-11eb-8287-ae8443ae1d74.jpg)
2. Close the main window, only the first floating window is closed, the other windows are not closed:
![0002](https://user-images.githubusercontent.com/29046736/99909049-1b4af500-2d21-11eb-9da2-e6f01c34cb33.jpg)
3.  Manually close all floating windows, but the process did not exit:
![0003](https://user-images.githubusercontent.com/29046736/99909066-3d447780-2d21-11eb-92c2-7efaf0edfdcc.jpg)

**Comment by githubuser0xFFFF** [comment]
Hi,

I just tested this in the CentralWidgetExamples application and I cannot reproduce or confirm this. If I close the MainWindow the application is properly closed.

**Comment by KondeU** [comment]
Thanks for your reply,
I use Qt5.14.2, MSVC v141(Visual Studio 2017) and v140(Visual Studio 2015), and MinGW 7.3.0, x64 platform, this problem will appear. I think it may be the Qt version problem.
I'm going to download Qt 5.12.2 and test it again.

**Comment by githubuser0xFFFF** [comment]
Would be great, if you could also test with Qt 5.15.2. Maybe this is a bug that has been fixed in a newer version.

**Comment by KondeU** [comment]
It took me a day to compile Qt5.15.2...
I finally found the cause of the problem, not Qt or ADS, but the CentralWidgetExample demo. The CMainWindow in this demo does not override closeEvent to complete the finishing work.
![image](https://user-images.githubusercontent.com/29046736/100190883-215ff200-2f2a-11eb-8a5d-9699ecb9be5c.png)
I write "DockManager->deleteLater();" in the destructor in my project, so this problem happens:
![image](https://user-images.githubusercontent.com/29046736/100193827-836f2600-2f2f-11eb-8cfa-27ee00d74faa.png)
This function should be called in closeEvent, and it will not work if called in destructor(because the main window has been destroyed).
It would be better to fix the demo :-)

**Comment by githubuser0xFFFF** [comment]
Thank you for your help. I fixed this in master with the commit 75910e910ea60a19ec9b6044055b926e9792c514

**Comment by KondeU** [comment]
Nice!
