### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by XenotriX1337** [githubuser0xFFFF/Qt-Advanced-Docking-System#28]
I'm currently replacing the docking system for an existing application and I have a few questions:

1. From what I understand you are supposed to add all the docks at the start, right? But do I then have to hide them manually since I don't want them to be visible until the user toggles them on?

2. Lets say I'm making a photo gallery. The user can open an unlimited amount of pictures each in its own dock. In this case I would create and add the docks as requested. When the user closes a dock, is there any way to remove it?

3. Some of the docks I am working with are used to edit data. When the user tries to close a dock with unsaved changes the application used to show a pop-up letting the user choose if he wants to save the changes or not before closing it. Is there any way to mimic this behaviour with ADS?

Thanks in advance :)

**Comment by githubuser0xFFFF** [comment]
Hi,

1. This is the way I use it in my application. You have to hide them manuallly or you create a perspective and it to your resource file. Then you can load the perspective.

2. I would not recommend to use the docing system for a photo gallery. The docking system is meant for a configurabl user interface and not for displaying a number of photos. I suggest to implement the photo gallery with another technik - i.e. an MDI interface.

3. This feature is not implementd yet.

**Comment by XenotriX1337** [comment]
Thanks a lot for the answer. The gallery was just an example of a widget that can have multiple instances, so I guess the question was more about there being a way to remove a dock.
