### ISSUE TITLE
Undocking a widget containing QOpenGLWidget causes a crash

### ISSUE THREAD

**Issue by skarnproject** [githubuser0xFFFF/Qt-Advanced-Docking-System#281]
For some reason when I undo a QOpenGLWidget it crashes unable to set the uniform in the rendering loop. It means that something happens with the OpenGL context on undock.

**Comment by githubuser0xFFFF** [comment]
Thank you for the report, At the moment I do not have much time to fix this so do not expect a quick fix. If you would like to fix this quickly you can try to investigate self or you can provide a small example application like the ones in the example folder that makes it easy for me to reproduce the problem and that will help me to fix this.

**Comment by skarnproject** [comment]
I am sorry, I can't provide a sample application. But I can tell you the steps to reproduce. What happens is when docks are rearranged, the QOpenGLWidgets inside the docks get their InitializeGL() method called, which is triggered by the change of OpenGL context. That means that your OpenGL data such as buffers, textures, shaders, VAOs etc become invalid.

The call seems to happen from QT internally, it is just the way ADS works that triggers that call. So, I decided there might not be a way to avoid context recreation.

I came up with this solution, put that inside InitializeGL() of all my QOpenGLWidgets.

 connect(context(), &QOpenGLContext::aboutToBeDestroyed,
          [this]()
          
            makeCurrent();
            // Unload everything here from the dying context to be later reuploaded to GPU on the next draw to the new context.
          });

That solution has fixed the problem for me, even though uploading/unloading all the GPU data sounds like a potentially laggy procedure and I would still like to avoid that.

The problem did not vanish entirely though. While it is possible to manipulate widgets by dragging without the OpenGL issues with my fix from above, there is a problem happening when the widget is detached by a context menu of ADS that you can invoke with a right click. I am still failing to understand why connect does not work in that scenario, but works when I detach using drag.
