### ISSUE TITLE
Preserve geometry of hidden widgets

### ISSUE THREAD

**Issue by peeet** [githubuser0xFFFF/Qt-Advanced-Docking-System#282]
Aloha!

I have noticed that once you hide a widget, save and restore the state and then make it visible again, the geometry/size of the widget is not preserved.

![preserveWidgetGeom](https://user-images.githubusercontent.com/391884/100094041-b09cd500-2e58-11eb-9f0e-9841dcb0cd02.gif)

**Comment by githubuser0xFFFF** [comment]
This is right - this is the way it is implemented currently. If the state is saved, the sizes of the splitters are saved. If all dock widgets in an area are hidden, the the size in the splitter is 0. That means, if the splitter is saved if the DockArea with Label 3 and Label 5 DockWidgets is visible, then the sizes `<Sizes>92 163 92 </Sizes>` are saved. If the dock area is not visible the the sizes `<Sizes>127 225 0 </Sizes>` are saved.

If you have a nice idea how to change this  this would be welcome.
