### ISSUE TITLE
Does it not support Win7 and Qt 5.5.1?

### ISSUE THREAD

**Issue by yljxhh** [githubuser0xFFFF/Qt-Advanced-Docking-System#283]
I use Win7 os, and Qt version is 5.5.1, compile failed. There are a lot of errors. Also, Qt Creator 5.5.1 on mac os, compiled filed too.  Does my Qt version is too lower? 
Thanks!

**Comment by githubuser0xFFFF** [comment]
Yes, I'm afraid it is too old.
