### ISSUE TITLE
Focus problems

### ISSUE THREAD

**Issue by ix07** [githubuser0xFFFF/Qt-Advanced-Docking-System#284]
Hi. 

I recently had to track down a customer complaint that when doing something in our app the focus unintentionally changed.

I tracked down the cause to some code in "DockWidgetTab.cpp":

```
void CDockWidgetTab::setActiveTab(bool active)
{
    d->updateCloseButtonVisibility(active);

	// Focus related stuff
	if (CDockManager::testConfigFlag(CDockManager::FocusHighlighting) && !d->DockWidget->dockManager()->isRestoringState())
	{
		bool UpdateFocusStyle = false;
		if (active && !hasFocus())
		{
			setFocus(Qt::OtherFocusReason);
			UpdateFocusStyle = true;
		}

```
When the flag "CDockManager::FocusHighlighting" is set, this always sets the focus to the tab. A call stack when this happens looks like this:

```
qtadvanceddockingd.dll!ads::CDockWidgetTab::setActiveTab
qtadvanceddockingd.dll!ads::DockAreaTabBarPrivate::updateTabs
qtadvanceddockingd.dll!ads::CDockAreaTabBar::setCurrentIndex
qtadvanceddockingd.dll!ads::CDockAreaTabBar::insertTab
qtadvanceddockingd.dll!ads::CDockAreaWidget::insertDockWidget
qtadvanceddockingd.dll!ads::CDockAreaWidget::addDockWidget

```
Is this by design? 

Thanks.

**Comment by githubuser0xFFFF** [comment]
Yes, this is how it is impemented right now. If you see an issue with this implementation that you would like to get fixed, please describe the problem and provide a minimum test case that shows the problem. The best way is, to fork this project and then to implement a small example in the examples folder of the project, that shows this issue. Then create a pull request and then I can try to fix this for you.

**Comment by ix07** [comment]
Sorry I didn't respond sooner, but it is kinda busy at my place.

> If you see an issue with this implementation that you would like to get fixed, please describe the problem and provide a minimum test case that shows the problem.<

The problem is as follows:

In our software we have a selection tree view in which you can select a file by focussing it (like in Visual Studio when the "Preview selected files" option is active). When focussing a file the software opens a new tab in the dock manager in which the contents are displayed. When the user changes the focus in the file list, another tab is openend and so on. With the current behavior of the dock manager, if "FocusHighlighting" is active, the focus is "transferred" to the newly created dock. So imagine a user using the cursor keys to open some files - this is no longer possible, because the first created dock will "steal" the focus away.

I can make a demo video or create a small example if necessary. 

Thanks.
