### ISSUE TITLE
Some notes wrt to Qt6 porting

### ISSUE THREAD

**Issue by ryobg** [githubuser0xFFFF/Qt-Advanced-Docking-System#286]
Hello,

I'm using the new Qt 6 and by cloning and running I have run over several types of errors. By no means I think what I have done is the best way to fix them as I'm a newbie in Qt world. However, I decided to just post the patch file as you might find it useful. The biggest change is that the ActiveX module seems not to be ported yet, so I uncommented it.

[muh.patch.txt](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/5705870/muh.patch.txt)

**Comment by githubuser0xFFFF** [comment]
Thank you for these informations

**Comment by githubuser0xFFFF** [comment]
Just merged Qt6 support into master
