### ISSUE TITLE
DockWidgetArea does not include TitleBar minimumSizeHint in its SizeHint

### ISSUE THREAD

**Issue by spiderkeys** [githubuser0xFFFF/Qt-Advanced-Docking-System#287]
First, thanks so much for your work on this library; it has really added a lot in the way of flexibility and customization for our app.

I noticed today that CDockAreaWidget is not taking into account the minimum size hint of its TitleBar component, which leads to the ability to resize the splitter in such a way that you lose TitleBar->height()'s worth of pixels in the DockAreaWidget.

As a concrete example with some numbers, I have the following setup:

A floating widget with two DockWidgets:
 - The top DockWidget contains a QWidget that has a minimum size of 1920x1080, inserted with eInsertMode::ForceNoScrollArea
 - The bottom DockWidget contains a QWidget with no specific minimum size set.

In this particular scenario, both DockWidgets display their TabWidget in their respective DockArea's TitleBar. The TitleBar ends up taking up about 21 pixels height, which is what it's MinimumSizeHint returns. 

With the splitter bar dragged as far up as it will go, this yields the following actual sizes and minimum size hints:
- TopDockWidget's set QWidget: 1920x1080 (actual and hint)
- TopDockwidget: 1920x1080 (actual and hint)
- TopDockWidget Area: 1920x1101 (actual, 1080 + 21 from titlebar), 1920x1080 (hint, because only the largest DockWidget's minsizehint is used, excluding the titlebar)
- Top Splitter child size: 1920x1080 (given that this includes both the titlebar and the dockwidget, 21 pixels of the dockwidget are cut off the bottom)

I was able to fix this by modifying the following function in DockAreaWidget.cpp:
```c++
QSize CDockAreaWidget::minimumSizeHint() const
{
    if( d->TitleBar->isVisible() )
    {
        return d->MinSizeHint + QSize( 0, d->TitleBar->minimumSizeHint().height() );
    }
    return d->MinSizeHint.isValid() ? d->MinSizeHint : Super::minimumSizeHint();
}
```
I realize that this may not be the best way to address the issue, as there are likely other assumptions, features, and edge cases I am not aware of that may bear on this kind of change. It may also be that I've missed some kind of config option that controls this type of behaviour.

Let me know if I can provide any clarification or further details.

**Comment by githubuser0xFFFF** [comment]
Thank you. I just merged your fix into master. Please test, if it is ok now
