### ISSUE TITLE
[Feature request / Proposal] Delete child widgets and dockwidget when tab get closed.

### ISSUE THREAD

**Issue by kozodeevv** [githubuser0xFFFF/Qt-Advanced-Docking-System#29]
Hi, your fork of original docking system is realy great, thank you very much for pushing it further, and making new features.

I'am working on tool that can has variable amount of windows, like text/image editors. I trying to use child/parent relations for semi automatic memory handling as much as possible. At some point i found, that closed tabs/windows, are just hidden, and not realy closed/deleted. It would be realy cool to have option to pass some setting parameters into docking manager, that will define close tab behaviour. For example like that:

```
    _dockManager = new ads::CDockManager(this);
    _dockManager->setConfigFlags(CDockManager::DefaultConfig | CDockManager::DeleteWidgetOnTabClosed);
```

As i understood, main philosophy behind this docking system, is create all windows at start, and than restore state from *.ini file. My proposal may break this behaviour, cause at runtime we must always have the same list of created dock widgets, otherwise it wont work. It is ok, in some apps, but on other it is a limit.

So, what do you think about it? Is it possible to implement that behaviour, or it will requier a lot of work?

p.s. Is there some high level docs about project architecture? I may try to implement it my self, if you have no anough time...

**Comment by XenotriX1337** [comment]
`CDockManager::removeDockWidget()` was added with #32 so you could delete them manually.
You could for example use the `CDockWidget::closed` signal to remove the automatically.

**Comment by kozodeevv** [comment]
Thanks, it works.
