### ISSUE TITLE
floating container vs main window inconsistencies

### ISSUE THREAD

**Issue by PerBothner** [githubuser0xFFFF/Qt-Advanced-Docking-System#290]
ADS seems to have hard-wired a concept of "main window".  You can create floating contains which are top-level similar to the main window, but with some crucial differences: Closing the main window closes the application and all floating windows.  Only the main window has a menubar.  The title bar styling and behavior is different unless FloatingContainerForceNativeTitleBar is set.  And probably other differences.

Compare the Chrome browser, which is in some ways similar to a tab-only ADS: There can be multiple windows; each can have multiple tabs; you can drag a tab from one window to another; but closing the initial window does not close the other windows.  Is there a supported/clean way to achieve this behavior?

The most critical issue is to not close the floating windows when the initial window is closed.  I can probably figure our a work-around, like intercept Close and change it to hide the window but that doesn't seem very clean.  Different title-bar styling could be managed by using QWidget for the initial window (unless FloatingContainerForceNativeTitleBar is available). Alternatively, using custom title-bars for all windows (like Chrome does) has some advantages.

I think having CDockManager inherit from CDockContainerWidget is wrong.  The comment says: "Each window that support docking has a DockContainerWidget. That means the main application window and all floating windows contain a DockContainerWidget instance." That makes sense to me - but I think the implication is that a CDockManager manages one or more CDockContainerWidgets - but is not itself a CDockContainerWidget.  Changing that would allow creating DockManager without any windows (i.e. initially zero CDockContainerWidgets), and then (later) add/register one or more windows with the manager. The manager would be associated with the QApplication, not a specific QMainWindow. That might be more general and elegant.  However, I don't know Qt in depth, so what I'm suggesting may not be feasible.

**Comment by githubuser0xFFFF** [comment]
This is the current design how ADS is implemented. I have no plan to change this in the near future because it works exactly the way I need it for my application - so I'm happy :o). If you would like to have another design, you should have a look into the two other dockin system implementations I mention on my main page  - maybe they are better suited for your needs.
