### ISSUE TITLE
Programmatic docking versus drag and drop docking

### ISSUE THREAD

**Issue by ThomasKroes** [githubuser0xFFFF/Qt-Advanced-Docking-System#292]
First of all, thanks for a great library, it works really great!

I have some questions with respect to the docking process. I might be overlooking something, but I seem to observe different behavior when dock widgets are docked/moved into docking areas programmatically or with drag and drop.

I am developing a plugin application with my colleagues and we are using the advanced docking system. Our application consists of a persistent dock widget on the left + right and a central widget in the middle. When we create a new plugin, it is docked to the central widget (which is performed programmatically).

I am excited that you added the [empty dock area](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/master/examples/emptydockarea) example, it works really well, and is exactly what we need! I tried the example; for instance when I move the left dock widget onto the central widget, the central widget 'disappears' which is exactly what we need. The problem for us is that we were not able to reproduce this scenario when docking programmatically. When we dock programmatically, the central widget tab is still visible.

I managed to solve this issue by implementing our own function that toggles the central dock widget visibility (triggered when dock areas are added/removed and/or dock widgets are closed), but it feels like a hack. Perhaps I am overlooking something?

Once again thanks for your awesome work!

**Comment by nickdademo** [comment]
Related to your comment on the central widget visibility, I noticed this similar behaviour at app startup as well:

```
        // This is required to apply the correct tab visibility to any dummy (i.e. "NoTab") docks.
        dockManager()->restoreState(dockManager()->saveState());
```

**Comment by githubuser0xFFFF** [comment]
I enhanced the `emptydockarea` example to test programmatic docking. I could see the same issue but I fixed it by setting the central widget `NoTab` flag before adding the widget to the dock manager:

```c++
CentralDockWidget->setFeature(ads::CDockWidget::NoTab, true);
auto* CentralDockArea = DockManager->setCentralWidget(CentralDockWidget);
```
After this change, the tab is properly hidden.

If you still see an issue, then please modify this example in a way that I can reproduce the error. Please tell me, if this hint solves your issue.

**Comment by nickdademo** [comment]
@githubuser0xFFFF I can confirm that setting the feature before setting the central widget fixes the issue - thanks!

**Comment by githubuser0xFFFF** [comment]
Tanks

**Comment by ThomasKroes** [comment]
Thanks!
