### ISSUE TITLE
Qt 5.15.2 - Tab refresh problem with a QGLWidget

### ISSUE THREAD

**Issue by K4L1M3R0** [githubuser0xFFFF/Qt-Advanced-Docking-System#294]
Hi,
First of all, thank you for your project, it's really great!

We use your advanced docking system in a big project and every thing worked find until we needed to upgrade to `Qt 5.15.2` (we were using Qt 5.11.2 before).
Now, we have some widgets that shift as if there origin was the tab widget.
![AdvancedDockingSystem_widgetShift](https://user-images.githubusercontent.com/77445787/104598210-96bc8900-5676-11eb-83af-902b40ec7ae1.gif)
I managed to reduce the case, using the 'simple' exemple:
Just replace the original `MainWindow.cpp` and `MainWindow.h` by the following ones
[MainWindow.zip](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/5814771/MainWindow.zip)

Thanks in advance
Best regards

**Comment by githubuser0xFFFF** [comment]
Is this also reproducible with Qt6?

**Comment by K4L1M3R0** [comment]
I was focused on upgrading to Qt5.15 before upgrading to Qt6 so i didn't test.
I check now and i tell you.

**Comment by K4L1M3R0** [comment]
QGLWidget as been removed in Qt6, and when I use a QOpenGLWidget it works.

And i forgot to share the simple.pro:
Just need to add `QT += opengl` and `INCLUDEPATH += %QTDIR%/include/QtOpengl`

**Comment by K4L1M3R0** [comment]
Hi,
Do you have any news about this issue ?

**Comment by githubuser0xFFFF** [comment]
Sorry, I do not have any news. I do not use Qt 5.15 yet. Do you have created a bug report in the Qt bug tracker for this issue?

**Comment by K4L1M3R0** [comment]
As QGLWidget works with QDockWidgets and stop working properly when I use the Advance Docking System, I suppose they'll reject the bug and send me back here.

Any idea when you're planing to migrate?

You maybe have a clue for where to look in the meantime?

We're not in the hurry but that might come ^^.

Thanks

**Comment by githubuser0xFFFF** [comment]
According to your issue report, it worked in Qt 5.11.2 and it stopped working in Qt 5.15.2.  So there must be a change or changes in the QGLWidget  from 5.11.2 to 5.15.2. You could pull the Qt sources and look into the changes  - maybe you find the change that causes the issue. 

You could also debug into ADS to see what is different in Qt 5.11.2 and 5.15.2.

**Comment by jonaslarsson** [comment]
I'm reproducing this bug in both Qt 5.12.2 and Qt 6.1.0 using a Qt Data Visualization which is based on Q3DSurface, which has a QWindow in the bottom.

I'm creating a widget to place inside an ADS tab with QWidget::createWindowContainer(&surface)

**Comment by jonaslarsson** [comment]
I've done some more testing with different versions of Qt, here are my results


```
ADS + Q3DSurface rendering offset issue
	5.8.0 			No problem
	5.9.9			No problem
	5.11.3			No problem
	5.12.0			No problem
	5.12.5			No problem
	5.12.6			No problem
	5.12.7			Rendering offset issue
	5.12.8			Rendering offset issue
	5.12.9			Rendering offset issue
	5.12.10			Rendering offset issue
	5.15.2			Rendering offset issue
	6.1.0 beta 3		Rendering offset issue
```

According to my tests the bug first appears in Qt 5.12.7

**Comment by jonaslarsson** [comment]
I traced the bug to the following patch in Qt 5.12.7

![image](https://user-images.githubusercontent.com/16509394/115464572-94e20300-a22d-11eb-99fb-d30d181a064f.png)

When reverting this patch the bug no longer appears in Qt 5.12.7

**Comment by githubuser0xFFFF** [comment]
Hi Jonas,

great job, that you traced this poblem down to this commit. Can I reproduce the problem with the ADS examples or do I need to change something? Do you see this problem only on Windows or also on Linux?

**Comment by jonaslarsson** [comment]
I think the issue may be in Qt and not in ADS. I've left a bug report at https://bugreports.qt.io/browse/QTBUG-92979

However it may be possible to do some work-around for Qt >= 5.12.7

I don't know yet why this code causes problems, but it is in QWidget::event so it can probably be overloaded and handled differently, or filtered using installEventFilter.

**Comment by githubuser0xFFFF** [comment]
Yes, this was also my idea

**Comment by cipperly** [comment]
FWIW, I had this issue also.  I played around a bit and the only way that I was able to resolve the issue was to override event in CDockAreaWidget like so:

```cpp
bool CDockAreaWidget::event(QEvent *e)
{
    switch (e->type())
    {
    case QEvent::PlatformSurface:
        {
            return true;
        }
        break;
    default:
        break;
    }

    return QFrame::event(e);
}
```

Overriding the event method in my OpenGL widget did not help for me.

**Comment by githubuser0xFFFF** [comment]
Thas sounds like a good solution that I could implement - thank you fot his hint.

**Comment by jonaslarsson** [comment]
I can confirm cipperly's patch solves the issue for me too. Great work!

**Comment by githubuser0xFFFF** [comment]
Is this patch only required for Windows or for all platforms?

**Comment by cipperly** [comment]
I have only tested on Windows myself.  I have no other operating systems available to test on.

**Comment by githubuser0xFFFF** [comment]
@cipperly I implemented you solution and just pushed it to master - so I hope this issue is fixed and I close it now.

**Comment by IkkiNit** [comment]
Hello !
When do you think this fix will be available in a new release package ?
Thank you

**Comment by githubuser0xFFFF** [comment]
Within the next 3 months.
