### ISSUE TITLE
Usage in commercial application

### ISSUE THREAD

**Issue by hartcw** [githubuser0xFFFF/Qt-Advanced-Docking-System#296]
I'm investigating whether this docking library can be used in our commercial application.

Due you offer possibility to pay for dual/commercial license?

This will give us flexibility in how to link against the library.

**Comment by githubuser0xFFFF** [comment]
The library license is LGPL 2.1. That means, if it is linked to your application as a shared library, then you can keep the source code of your application closed. Any changes you do on the library itself needs to get open sourced.

If you would like to link statically, then we would need to talk about a payed static link license. This will not include any commercial support. In this case, I would like to ask you, to ask KDAB for a commercial license for their docking framework (https://www.kdab.com/development-resources/qt-tools/kddockwidgets/) and send me their quote. Then I have an idea how to find a gool price for this static link exception.

**Comment by LiamC12345** [comment]
Have you worked out a price for static link exception?
I am relatively new to programming and am trying to create a commercial application and would prefer
to use the advanced docking system qt project files as a base starting point to build it from

What would your pricing be?

**Comment by RomanKhv** [comment]
Hi!
Do you have any updates on commercial licensing? We are interested in static link and possibly in modification. What is the way of communication? Our department, which buys software, would probably need some kind of "official" page

**Comment by githubuser0xFFFF** [comment]
Please send a mail to uwe_kindler@web.de with your request. I'm a private person and there is no "official" page.
