### ISSUE TITLE
Feature Request: Custom titlebar on DockWidget for customization

### ISSUE THREAD

**Issue by PlasmaMichael** [githubuser0xFFFF/Qt-Advanced-Docking-System#297]
In some application, the QMainWindow is entirely customized to have his own style using a border-less style and an entirely custom title bar with own mouse control to resize and move the window to mimic like the standard window. On this case, you can set a custom title bar on QDockWidget to customize it and follow the style of the application. When you set a custom title bar widget on QDockWidget, the dock widget is then a border-less using your title bar but has the resize functionality working. The add of custom title bar in the dock widget of Qt Advanced Docking System is certainly a good add to solve this case.

The user can then inherit Qt Advanced Docking System dock widget class and set the custom title bar widget in the constructor and override the event to update the title bar widget when the title change. The user has to implement each functionality of the button like minimize, maximize and close. The resize of the window can be the responsibility of the user as well, QDockWidget manage that automatically but maybe let the user handle that is more safe to allow any behavior possible because custom title bar is an advanced feature so it's expected advanced user will use it.

**Comment by githubuser0xFFFF** [comment]
Thank you for your feaure request. I understand your need for such a feature but I will not implememnt this feature, because I don't need it. With the Qt CSS styling you have comprehensive styling possibilities. Your feature is a very "special" feature for a very small minority of users. There are other features on the featur request list, that are more important for other users.

Because I do not see, that this feature will be implemented withing the next 2 years, I will close this request now.

**Comment by PlasmaMichael** [comment]
Thank you for the fast answer! You completely right, the Qt CSS is entirely perfect for the docked title bar. I think the description missed one detail to understand better, this is when you undock the docked widget, the window is using the classical OS style where customization is missing.

**Comment by PlasmaMichael** [comment]
I think there is already a Linux custom title bar, looks like all the feature is already there but it's only needed to expose an API to be able to set custom title bar using the same flow as the Linux title bar. Maybe I miss some information that special cases can happen but looks like the Linux title bar shows the flow about it.

**Comment by zubeyir-bodur** [comment]
> In some application, the QMainWindow is entirely customized to have his own style using a border-less style and an entirely custom title bar with own mouse control to resize and move the window to mimic like the standard window. On this case, you can set a custom title bar on QDockWidget to customize it and follow the style of the application. When you set a custom title bar widget on QDockWidget, the dock widget is then a border-less using your title bar but has the resize functionality working. The add of custom title bar in the dock widget of Qt Advanced Docking System is certainly a good add to solve this case.
> 
> The user can then inherit Qt Advanced Docking System dock widget class and set the custom title bar widget in the constructor and override the event to update the title bar widget when the title change. The user has to implement each functionality of the button like minimize, maximize and close. The resize of the window can be the responsibility of the user as well, QDockWidget manage that automatically but maybe let the user handle that is more safe to allow any behavior possible because custom title bar is an advanced feature so it's expected advanced user will use it.

In [this](https://github.com/TaleWorlds/Qt-Advanced-Docking-System) fork, I am basically enabling the feature on Linux so that native window can be removed with a widget, but I unfortunately could not get to enable modifying, neither using stylesheets, or passing a custom QWidget. Hope it helps.
