### ISSUE TITLE
Python bindings for PySide (Licensing issues with PyQt  - GPL3) 

### ISSUE THREAD

**Issue by AHSauge** [githubuser0xFFFF/Qt-Advanced-Docking-System#298]
This looked very promising to me until I realised that the Python bindings uses PyQt. PyQt is a library that is available under a dual GPL and commercial license. As my intended usage would be non-compliant with GPL (but compliant with LGPL), in it's current form I would need a commercial license for PyQt. This of course also applies to any other user, including users believing this library is compatible with LGPL in it's entirety. I'm not an expert on this, but the way I see it, the Python sections of this project is unfortunately not compatible with LGPL.

To avoid the above mentioned issues, I would suggest to replace PyQt with PySide as that is actually licensed as LGPL itself.

**Comment by githubuser0xFFFF** [comment]
I have not implemented the Python bindings - this was a contribution from other Ads users. If you would like to replace these bindings with Pyside bindings, then feel free tu create a pull request.

On the main project github page you will find the contact details of the current Python bindings authors. So you should talk to them before you create your bindings for PySide

**Comment by AHSauge** [comment]
> 
> 
> I have not implemented the Python bindings - this was a contribution from other ADS users. If you would like to replace these bindings with Pyside bindings, then feel free to create a pull request.
> 
> On the main project github page you will find the contact details of the current Python bindings authors. So you should talk to them before you create your bindings for PySide

Understood. I might want to dive into this, but for the moment, this was only for technology research for a future project. I can raise the issue with the contributes of the Python bindings to get a better understanding behind the rational of using PyQt.

**Comment by n-elie** [comment]
Hello,

I originally wrote the Python binding and i am currently maintaining it. The main reason I chose PyQt over PySide is that I wanted to use Qt-Advanced-Docking-System in application I develop and that was using another lib from it's PyQt bindings.
I have no idea how to write a binding for PySide (except that it use Shiboken instead of SIP).
However I am also interested in porting Qt-Advanced-Docking-System to PySide, so if you can point me to an example lib with PySide bindings, that would really help.

**Comment by jntille** [comment]
I just wanted to express my interest in PySide2 bindings, as nearly all industry tools have migrated to PySide for the licensing reasons addressed above. Unfortunately, I currently lack the skills to contribute to the port.
If I come across some libs, I'll add them here. Maybe this is a good start: [https://blog.basyskom.com/2019/using-shiboken2-to-create-python-bindings-for-a-qt-library/](url)

**Comment by DKStudio** [comment]
[qtpydocking](https://github.com/klauer/qtpydocking)

**Comment by AHSauge** [comment]
> [qtpydocking](https://github.com/klauer/qtpydocking)

That is deprecated in favour of the current Python integration here. Ignoring the fact that qtpy doesn't support Qt6 yet, I do like the idea of using that. Since I have a bit of time left over these days, I'll take a quick dive into this. The link @jntille provided seems like quite a useful starting point.

**Comment by AHSauge** [comment]
> 
> 
> I am also interested in porting Qt-Advanced-Docking-System to PySide, but have no experience into this matter. Some more information/example to pyside bindings:
> 
>     * Utilizing Shiboken to Enhance your Qt for Python Application -> https://youtu.be/mAfEVPgHRt8 (mentioned on https://www.qt.io/qt-for-python)
> 
>     * https://github.com/qt-ps-americas/pysideqwt
> 
>     * https://github.com/sewoods/shiboken_simplegraph_example

I did actually get some progress on this in August. It was building and shiboken wasn't complaining any more, but I never got around to actually test it so I don't know if what I did was actually correct. I'll see if I can push it up later today at least. It's a starting point at least if someone else wants to make stab at it.

**Comment by AHSauge** [comment]
It probably needs a clean-up, but I've pushed up my untested attempt to https://github.com/AHSauge/Qt-Advanced-Docking-System/tree/pyside2

**Comment by herronelou** [comment]
Great to hear you're working on this, had been looking at this library and was about to give up on it because of the lack of PySide2 bindings. Good timing.

**Comment by n-elie** [comment]
Hello,

I worked on this based on AHSauge attempt and finally got something usable. At least all examples work well.
https://github.com/metgem/PySide2Ads

I also created conda-forge recipes: https://github.com/metgem/staged-recipes/tree/qtads/recipes

This is a work in progress. Tested only on Windows for now

**Comment by n-elie** [comment]
Updated examples to work with these bindings: https://github.com/n-elie/Qt-Advanced-Docking-System/tree/pyside2ads/examples

**Comment by saulthu** [comment]
I'd love for this work to progress. I normally use pyside (LGPL yay!), but have been using PyQt5 just for this docking system -- PyQt5 has a tendency to hard crash if you do anything a bit off, while pyside tends to just give a soft Python stack trace. Would much prefer to have pyside + qtads 😄

**Comment by n-elie** [comment]
Hello,
I'm trying to have my bindings for pyside2 accepted in conda forge but it not compiling without adding clangdzv dependency: https://github.com/conda-forge/staged-recipes/pull/19017
The bindings are here: https://github.com/metgem/PySide2Ads
If someone have an idea on how I can get this recipe accepted, any help would be appreciated

**Comment by mborgerson** [comment]
Hello PySide6 users,

I've also wanted to use this great docking system in a PySide6-based application. I've managed to build usable PySide6 bindings at https://github.com/mborgerson/pyside6_qtads, which is based on a combination of @cniemira, @n-elie / @AHSauge's work (thank you!).

I've published wheels built against latest PySide6 for Windows, macOS, and Linux on PyPI. Install with:

```
pip install PySide6-QtAds
```

Sample code is available here https://github.com/mborgerson/Qt-Advanced-Docking-System/tree/pyside6/examples. To run the samples, you'll also need to install [qtpy](https://github.com/spyder-ide/qtpy) from source (`pip install git+https://github.com/spyder-ide/qtpy`).

Ultimately I'd like to see our efforts for PySide bindings unified, possibly merged into this upstream repository properly to keep Python support current, and I'm happy to work with others to make that happen. In the mean time, I'll manage this independent package.

**Comment by githubuser0xFFFF** [comment]
@mborgerson Thank you for providing PySide6 bindings - that are great news. I updated the Python section in the README.md file with your PySide6 bindings and linked to this issue. If you would like to see additonal information about the Python bindings in the README.md, feel free to create a pull request.

**Comment by tu-cao** [comment]
Why I got: 
`AttributeError: Error evaluating `PySide6QtAds.ads.CDockManager.__init__`: module 'PySide6QtAds' has no attribute 'ads'`

on every examples

**Comment by divintzero** [comment]
Hi @mborgerson

Like @tu-cao I also get:AttributeError: Error evaluating PySide6QtAds.ads.CDockManager.init: module 'PySide6QtAds' has no attribute 'ads'

when importing.
