### ISSUE TITLE
Integration in QtDesigner ?

### ISSUE THREAD

**Issue by ilaroche** [githubuser0xFFFF/Qt-Advanced-Docking-System#301]
I'm looking at new technologies to use in a new Qt Application we're going to start soon. My colleagues & I have experience building Qt applications and we're quite fond of the ease of use & quick design provided by Qt Designer. From my few hours exploring the code & experimenting with it, it doesn't seem like the widgets are integrated in Qt Designer. Am I mistaken? If not, any plans to integrate them in Qt Designer in the future?

Thanks,

Isabelle

**Comment by githubuser0xFFFF** [comment]
No, this is not planned because it does not make sense.
