### ISSUE TITLE
QCoreApplication::quit ignored on floating windows

### ISSUE THREAD

**Issue by nenadl** [githubuser0xFFFF/Qt-Advanced-Docking-System#302]
It looks like there is a bug with floating windows blocking the QCoreApplication::quit event.

Steps to reproduce:
1) Start AdvancedDockingSystemDemo
2) Double-click on a tab to pop-out a dockwidget in a floating window.
3) With focus on the floating window, hit CMD+Q on the keyboard (or use the window/file menu -> quit action).
Result: floating window closes, but app is still running.
Desired result: the whole application closes

I believe this line is the culprit: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/FloatingDockContainer.cpp#L803. If you comment that out QEvent::Quit is propagated correctly and the whole application closes. I'm not sure if there are other issues with removing this line however.

P.S. I'll try this later today on Windows to confirm it there as well.

**Comment by githubuser0xFFFF** [comment]
Thank you for the bug report. I havesome questions:

- on what platform did you test this
- in Linux and in Windows there is now window entry in the floating window file menu to close the application so I guess you are on Mac?

**Comment by nenadl** [comment]
- I tested this on Mac (OSX). I can repro it there both by using Window Menu -> Quit, and also by using CMD+Q - which is the default Application Quit shortcut for Mac apps. See here for details: https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts.
    - Windows doesn't have such a shortcut as you can see in the link above. So for example when the user hits ALT-F4 on WIndows it only closes the focused window - which I believe is the correct behavior there..
- QCoreEvent::Quit is here: https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qcoreevent.h.html#QEvent::Quit. You can see it on the main application event loop when the user triggers the Quit action on the Mac.
    - This might be a red herring however. I'm not sure if that is the event that gets blocked or it's somewhere further up the stack. I'm not very familiar with the Startup/Shutdown process for Qt, which on first look seems to be fairly complicated. I can't find the definition for the QAction that triggers the Quit event on the mac in the Qt sources to confirm that this event is being sent by the action vs. coming from the OS.
    - Another possible explanation here would be that when the user triggers the Quit Action in the OSX menu, each open window gets a Close event and maybe if the Window decides to discard this event than the Quit action is also discarded. Just a guess....
- I compiled the examples against Qt5.15.2

On a separate note, any idea what the purpose of that event->ignore in FloatingDockContainer.cpp is for?

**Comment by githubuser0xFFFF** [comment]
I DockWidget has several flags that configure if the DockWidget is floatable, closable, movable... That means, a floating dock widget can only be closed, if it is closable, Therefore we ignore the event is ignored and depending of the closable flag the widget is hidden. That means, the close event never closes the window, it only hides it.

**Comment by nenadl** [comment]
Ah, I see. I can't think of a way to get past that right now.

For posterity, adding this to the application class seems to fix the issue on the Mac:
`
bool MyApp::notify(QObject* receiver, QEvent* event)
{
    if (event->type() == QEvent::Quit) {
        quit();
    }

    return QApplication::notify(receiver, event);
}
`
