### ISSUE TITLE
Changing objectName on a DockWidget doesn't update DockManager mappings

### ISSUE THREAD

**Issue by nenadl** [githubuser0xFFFF/Qt-Advanced-Docking-System#303]
I have an application where the titles/names of the Widgets shown can be changed by the user. Using ADS I naively changed the names of the DockWidgets as well when the contained widget changed name/title. This caused an issue where the internal mapping in the DockManager (DockWidgetsMap) becomes inaccurate. 

This is not a big deal for me, I can set the object name to some indirect name/ordinal, however it seems like it might be something that should be fixed in general for the system.

An easy solution could be to watch the signal: https://doc.qt.io/qt-5/qobject.html#objectNameChanged for each DockWidget.

**Comment by githubuser0xFFFF** [comment]
The QObject names should never get changed - they are used for serialization. Change the title instead.

**Comment by nenadl** [comment]
@githubuser0xFFFF I would appreciate it if you can help me with the proper "design pattern" to use here for ADS.

*Also apologies for the wall of text.*

To give an example here - imagine you are building a text editor app (e.g. atom, vscode, sublimetext).
- the app lets the user open text files, edit them and close them.
- the user can open more than one file at a time. Each file is in a separate tabbed dockwidget.
- the user can **rename** a file from the app.
- when the app closes it remembers which files are open and the position of the docked windows so that when the app opens up again the state is the same as it was when it closed.

**For such an app what would you use as the DockWidget objectName?**

I might not understand the full function of this library so pardon my ignorance, but my first inclination here would be to name each DockWidget by the name of the file that it's showing to the user. Then when the app closes I will save to disk which files are open and then serialize the state of the DockManager. When the app reopens I will reopen the files, create DockWidgets for them (with name == filename) and the restore the DockManager state. This is fairly straightforward as each DockWidget is always mapped (by name) to the file that it contains, so restoring the dockManager state is also easy.

The problem comes when the user can rename a file inside the app. Now you have a situation where the DockWidget::objectName is different from the file that its displaying. When the app closes and serializes the list of files open and the dockmanager state, it will no longer have a correct mapping from DockWidget::objectName to filename.

**Is there a different way to do this for such a "dynamic" application?** The two other ways I can think of are:
* Serialize the list of files open with an "ordinal" (number) that represent each file regardless of the filename, and then have the DockWidget::objectName be that number. This would create a level of indirection. It's not the best design, but it would work.
* Each time the user renames a file - destroy the associated DockWidget and recrete it with a new objectName. This is not optimal UX unfotunately.
* Something else?

--
I also spent some time looking at the code and I think DockManger could probably function just as well with DockWidgetsMap replaced with a QList<CDockWidget*>. Here is a list of all the functions that use this map:
- markDockWidgetsDirty() just uses the values so a List would be a direct replacement.
- restoreDockWidgetsOpenState() just uses the values so a List would be a direct replacement.
- findDockWidget(const QString& ObjectName) could iterate over the list to find the correct Widget. Since we are not really talking about thousands or 10s of thousands of DockWidgets here, the performance hit would be negligible.
- dockWidgetsMap() could generate the map on the fly when called. Again since users of this library won't have many DockWidgets, performance hit should be very small.
- setCentralWidget(CDockWidget* widget) just use the list to check if there are other DockWidgets. This would be a direct replacement.

Overall replacing the Map with a List might be a net positive because the library would no longer depend on maintaining an internal cache of objectNames that the user of the library can change at any time. This would also make the library easier to use since users don't have to know about this "idiosyncrasy" ahead of time (for example I spent a day trying to find the issue here).

If you want I can send you a pull request for this change

**Comment by githubuser0xFFFF** [comment]
You can change the title that is shown via the tab widget of a dock widget:

```c++
DockWidget->tabWidget()->setText("My Title");
```
I think changing the object name if you just would like to change the title is not the right design decision. If you set the text of a QLabel via `setText` function, then you would not chenge to qobjectName of the lable.

That means, you application needs to give the editors unique names or identifiers and manage the mapping of the title to a certain dock widget identifier.

**Comment by nenadl** [comment]
Right, I am already setting the title correctly. I'm using the objectName as the unique identifier for the DockWidget (and it's contents), and in this example my desire is to use the filepath as that unique identifier.

*"That means, if you have two source files with the same name in different directories, then which title / object name do you want to give - the complete file name including that path?"* - I think this gets straight to my point. Yes, if I were building a text editor, I would like to give the DockWidget the path as it's objectName. *I think this is where we disagree.*

*"That means, your application needs to give the editors unique names or identifiers and manage the mapping of the title to certain dock widget identifier."* - I can't think of a better unique identifier for a file than it's path. If I were to give the dockwidget a synthetic unique identified (e.g. a GUID) and than maintain a separate mapping of GUID->filepath/filename, what **benefit** would I have achieved with this additional level of indirection? Is there a downside to using the filepath as the objectName?

**Comment by githubuser0xFFFF** [comment]
You can use whatever you want as a unique ID. The only requirement for ADS is that it needs to be constant during runtime - so if your filename changes, then it won't work.

So you need to implement your own mapping from filename to object names for ADS DockWidgets or you need to adapt ADS to your needs.
