### ISSUE TITLE
How to remove top and bottom borders between CDockManager and CDockWidget?

### ISSUE THREAD

**Issue by lili2012** [githubuser0xFFFF/Qt-Advanced-Docking-System#304]
![image](https://user-images.githubusercontent.com/14124820/108489967-28a25c00-72dd-11eb-8760-c384a5b915c4.png)

ads--CDockAreaWidget {
	background: red;
	border: 0px solid white;
}

ads--CDockManager{
	background: blue;
	margin:0px;
	padding:0px;
	border: 0px solid red;
}
CDockManager and CDockWidget(dark) have top and bottom borders(blue). How to eliminate them?

**Comment by lili2012** [comment]
`CDockContainerWidget::CDockContainerWidget(CDockManager* DockManager, QWidget *parent)`
contains this line `d->Layout->setContentsMargins(0, 1, 0, 1);` so the margins are fixed.

**Comment by rolivav** [comment]
You could use Gammaray to see how that border is painted.

**Comment by lili2012** [comment]
> You could use Gammaray to see how that border is painted.
Thanks very much!!! I will learn Gammaray as soon as I am available.

**Comment by lili2012** [comment]
> You could use Gammaray to see how that border is painted.

Thanks very much!!! I will learn Gammaray as soon as I am available.
