### ISSUE TITLE
hiding a dock widget programatically

### ISSUE THREAD

**Issue by jcbenoit-opto** [githubuser0xFFFF/Qt-Advanced-Docking-System#305]
I have not been able to completely hide a dock widget programatically.
I would like to add a new Dock widget into the dock manager, but make it non visible at startup.

Tried the two following methods.

Method 1:
// action is the QAction* returned by CDockWidget::toggleViewAction()
// the action menu was unchecked, but the dock widget is still visible
action->setChecked(false); 

Method 2:
// widget is a CDockWidget* added to the CDockManager
// the dock widget child widget has been hidden, but the dock widget title bar stay visible
widget->hide();

Can you please give advice ?
Thanks

**Comment by githubuser0xFFFF** [comment]
Use `CDockWidget::toggleView(false);`
