### ISSUE TITLE
Support inner tabs enhancement

### ISSUE THREAD

**Issue by jporcher** [githubuser0xFFFF/Qt-Advanced-Docking-System#306]
It would be really nice if a widget could be docked as a tab within a tab itself. Then widgets could be grouped together in tabs:

![image](https://user-images.githubusercontent.com/19594909/113121017-7c745f00-9212-11eb-93fe-1779df02664e.png)

Consider this scenario:
- You have 6 docking widgets (as tabs in the central widget): "Label 0", "Label 1", "Label 2", "Inner 0", "Inner 1", "Inner 2"
- You float "Inner 0"
- You dock "Inner 1", "Inner 2" as central with "Inner 0"
- So now you have your main widget with 3 tabs left "Label 0", "Label 1", "Label 2" and a floating bar with 3 tabs "Inner 0", "Inner 1", "Inner 2"
- Now you drag the whole floating bar and dock it as central next to the 3 existing tabs

Today, this adds 3 new tabs and you end up with 6 tabs at the same level: "Label 0", "Label 1", "Label 2", "Inner 0", "Inner 1", "Inner 2"
It would be nice to have the possibility to have a new "group tab" be added there and it would include "Inner 0", "Inner 1", "Inner 2" as child tabs (as they were organized when floating)

**Comment by nickdademo** [comment]
We would definitely find this useful too and it is already something I am thinking about how to best implement.

Perhaps a better UI design would: Grouped tabs with a drop down menu to select the dock to show (instead of tabs within tabs). A number indicating how many docks are in the group could be useful to see in this tab as well.

**Comment by jporcher** [comment]
Good to see it was a good idea ;-)

I believe there are many ways to implement that. What you suggest is to have a kind of stacked layout within a tab and let user select the visible widget from a drop down? That would work too, but I would say tabs in tab is more convenient because you always see what views are in there without having to access a drop down. And also tabs in tabs could have depth greater than 1....if user wants to, he may tabs in tabs in tabs in tabs.....but maybe this would end up being too complicated so what you propose could be a better UI design ;-)

**Comment by githubuser0xFFFF** [comment]
I have to admit, I don't like  this idea. In my opinion it adds additional complexity to an already complex user interface. Therefore I will not going to implement this but I will leave this issue open, in case someone would like to implement this. I will only accept pull requests for this feature, if there is no negative impact on other parts of ADS.

**Comment by jporcher** [comment]
Makes sense. Woudl you accept a pull request with an example? Actually, the feature does not need to be added to ADS, one can specialize DockManager class and handle it from here. I did that and it does not work that bad. So it may be a new sample program in your releases.

**Comment by githubuser0xFFFF** [comment]
This would be great.

**Comment by jporcher** [comment]
Done changes and pull request:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/308

**Comment by githubuser0xFFFF** [comment]
Thank you - I merged your additonal example into master.
