### ISSUE TITLE
Memory leaks appear when adding tabs programatically

### ISSUE THREAD

**Issue by jporcher** [githubuser0xFFFF/Qt-Advanced-Docking-System#307]
I picked up provided simple example, compiled and run using with leak detection software (VLD). As provided, there is no memory leak.

Now, I change the code to have more than one docking widget:

```
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    // Create the dock manager. Because the parent parameter is a QMainWindow
    // the dock manager registers itself as the central widget.
	m_DockManager = new ads::CDockManager(this);

	for ( int i = 0; i != 5; ++i )
	{
		// Create example content label - this can be any application specific
		// widget
		QLabel* l = new QLabel();
		l->setWordWrap(true);
		l->setAlignment(Qt::AlignTop | Qt::AlignLeft);
		l->setText("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. ");

		// Create a dock widget with the title Label 1 and set the created label
		// as the dock widget content
		ads::CDockWidget* DockWidget = new ads::CDockWidget("Label " + QString::number(i));
		DockWidget->setWidget(l);

		// Add the toggleViewAction of the dock widget to the menu to give
		// the user the possibility to show the dock widget if it has been closed
		ui->menuView->addAction(DockWidget->toggleViewAction());

		// Add the dock widget to the top dock widget area
		m_DockManager->addDockWidget(ads::TopDockWidgetArea, DockWidget);
	}
}
```

Still, no memory leak.

Now:

- If I replace `m_DockManager->addDockWidget(ads::TopDockWidgetArea, DockWidget);` by `m_DockManager->addDockWidgetTab(ads::TopDockWidgetArea, DockWidget);` then I get memory leaks (the 5 `QLabel` and `QDockWidget` do not get destroyed)
- Or, if I change the code to use the third parameter of `addDockWidget` to group Label 0 with Label 1 and Label 2 with Label 3 as below:

```
ads::CDockAreaWidget* previous = NULL;
for ( int i = 0; i != 5; ++i )
{
    // Create example content label - this can be any application specific
    // widget
    QLabel* l = new QLabel();
    l->setWordWrap(true);
    l->setAlignment(Qt::AlignTop | Qt::AlignLeft);
    l->setText("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. ");

    // Create a dock widget with the title Label 1 and set the created label
    // as the dock widget content
    ads::CDockWidget* DockWidget = new ads::CDockWidget("Label " + QString::number(i));
    DockWidget->setWidget(l);

    // Add the toggleViewAction of the dock widget to the menu to give
    // the user the possibility to show the dock widget if it has been closed
    ui->menuView->addAction(DockWidget->toggleViewAction());

    // Add the dock widget to the top dock widget area
    auto added = m_DockManager->addDockWidget(ads::CenterDockWidgetArea, DockWidget, previous);
    if ( previous )
        previous = NULL;
    else
        previous = added;
}
```

Again the 5 `QLabel` and `QDockWidget` do not get destroyed on close.

Note: Adding the code below in MainWindow fixes the leak, but I suppose user is not expected to do that:

```
std::vector<ads::CDockAreaWidget*> areas;
for ( int i = 0; i != m_DockManager->dockAreaCount(); ++i )
{
    areas.push_back( m_DockManager->dockArea(i) );
}
for ( auto area : areas )
{
    for ( auto widget : area->dockWidgets() )
        delete widget;
		
    delete area;
}
```

**Comment by githubuser0xFFFF** [comment]
The OS keeps track of all the memory allocated to a process, and will free it when that process terminates. So if the widgets are not destroyed on application close, then there will be no memory leak.

**Comment by jporcher** [comment]
Hello,

Os keeping track of all memory allocated and releasing it automatically...this is in Java, in C++, the developer has to free the memory he allocated, he's not supposed to wait for the OS to do it, otherwise it's called a memory leak. That's why there's so many leak detection tools for C++.

One may argue that it's pointell to free memory when app closes (but that's questinable anyway, see https://softwareengineering.stackexchange.com/questions/140483/is-it-a-waste-of-time-to-free-resources-before-i-exit-a-process/140599).

But, your app may also create/destroy DockManagers on demand (based on any external trigger or user request), like below:

```
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

	ui->menuFile->addAction( "Setup GUI", this, SLOT(setupGui()) );

	m_DockManager = NULL;
	setupGui();
}

void MainWindow::setupGui()
{
	delete m_DockManager;
	ui->menuView->clear();

	static int index = 0;
	++index;

	{
		m_DockManager = new ads::CDockManager(this);

		// ... fill m_DockManager
	}
}

MainWindow::~MainWindow()
{
    delete ui;
}
```

Then, every time `setupGui()` is invoked, new memory will be allocated, and the OS won't release it untill the app closes. If user makes `setupGui()` be called many times in the end, the OS may end up unable to allocate more memory and the app will crash.

This code is perfectly valid in terms of memory management (as `m_DockManager` parent is `MainWindow`, it gets deleted when `MainWindow` closes), however, the fact that `ads::CDockManager` does not delete its children (`ads::CDockWidget`) introduces memory leaks.

Adding following code to `DockManager`'s destructor should fix the problem:

```
std::vector<ads::CDockAreaWidget*> areas;
for ( int i = 0; i != m_DockManager->dockAreaCount(); ++i )
{
    areas.push_back( m_DockManager->dockArea(i) );
}
for ( auto area : areas )
{
    for ( auto widget : area->dockWidgets() )
        delete widget;
		
    delete area;
}
```

**Comment by githubuser0xFFFF** [comment]
Yes, you are right. If you create and destroy DockManagers on demand, then you will have a memory leak. But this is not the indented use of the DockManager. Normally you create one single dock manager at the application start and thats it. At the moment I don't know any application that creates dock managers at demand so the risk of memory leaks is very low.

But anyway, it would be great, if you could create a pull request that fixes this issue properly.

Thank you for your help finding and fixing this issue.
