### ISSUE TITLE
CDockManager::loadPerspectives() does not emit perspectiveListChanged() when the perspective list has changed

### ISSUE THREAD

**Issue by ParadoxDaKo** [githubuser0xFFFF/Qt-Advanced-Docking-System#309]
Hi,

we are currently using the Qt-ADS for UI docking. Great work!

While implementing perspective handling, I realized that ```CDockManager::loadPerspectives()``` does not emit ```perspectiveListChanged()``` after it modifies the perspective list.
It even calls ```d->Perspectives.insert()``` just like ```CDockManager::addPerspective()```, which does emit ```perspectiveListChanged()``` afterwards.

Is this design intended or an oversight?

How about a new signal ```perspectiveListLoaded()```?

**Comment by githubuser0xFFFF** [comment]
I fixed this in master and added the perspectiveListLoaded() signal
