### ISSUE TITLE
Perspectives - fully regenerate all dock widgets?

### ISSUE THREAD

**Issue by ParadoxDaKo** [githubuser0xFFFF/Qt-Advanced-Docking-System#310]
Hi again,

thank you for your work on #309. 👍 After working some more on perspectives, I found another peculiarity.

Following use case: We are working on a GUI program where the user can create as many custom dock widgets as they want in a single DockManager, starting from an initial set of widgets. 

Now, all these custom widgets should be saved and restored after restarting the program. I thought ```DockManager::saveState()```/```DockManager::restoreState()``` (and the respective ```addPerspective()```/```openPerspective()``` methods) would do just that - but they just restore the state of widgets that have already been created before (around line 1050 in DockContainerWidget.cpp).

This means that after restarting the program, the dock widgets that are not the initially created widgets do not get recreated and restored, despite having been serialized. To go even further: Not creating any initial widgets, then trying to restore the state leaves an empty screen.

Is this design intended and are we supposed to program some extra housekeeping for user-created widgets? Or can there be a ```regeneratePerspective()``` method that recreates all serialized Dock widgets?

Or am I missing a detail somewhere?

**Comment by githubuser0xFFFF** [comment]
This is the way it is implemented currently. The **restoreState()** function restores the state of existing widgets, but does not create non existing widgets. So you need to create a second list that you can save and load that will create your widgets before the state is restored.
