### ISSUE TITLE
[Question] "reversing" the sidebar example

### ISSUE THREAD

**Issue by ruilvo** [githubuser0xFFFF/Qt-Advanced-Docking-System#312]
Can `Qt-Advanced-Docking-System` be used to have a sidebar with dockable widgets but a right (centre) area that's fixed? Basically the opposite of what's provided in the sidebar example.

Other question: Can one make different docking areas that only certain widgets "glue" to?

**Comment by githubuser0xFFFF** [comment]
1. Yes, I think so.
2. No, that is not possible without modifications
