### ISSUE TITLE
"emptydockarea" example crashes on start

### ISSUE THREAD

**Issue by ruilvo** [githubuser0xFFFF/Qt-Advanced-Docking-System#316]
The "emptydockarea" example crashes immediately on start.

Here is the screenshot from Qt Creator on Debug mode:
![imagem](https://user-images.githubusercontent.com/8402646/116143543-2db3cb00-a6d3-11eb-8a8f-36a296860808.png)

Seems that `int index = TargetAreaSplitter ->indexOf(TargetDockArea);` is trying to dereference a nullptr. You can see that TargetAreaSplitter has value 0. 

Tried on master branch, latest commit at the time of writing.

**Comment by githubuser0xFFFF** [comment]
Thank you for this bug report. I just fixed this in master.
