### ISSUE TITLE
[Question] Evenly split docking

### ISSUE THREAD

**Issue by ruilvo** [githubuser0xFFFF/Qt-Advanced-Docking-System#318]
Hey!

On the "Demo" example, the "Create docked editor" button adds a new "Editor" to that row in the layout, evenly spacing the widgets. This is pretty cool. The thing is, if one undocks any of them, it's not possible to get them back to that way. 

Do you think it would be possible to create a dropping region that spans the whole row of the layout as a whole, and make docking behave like the creation does? 

My idea would like have a sidebar where one could dock widgets and they would get evenly split in height, maybe even adding a scrollbar if there's a large amount of them. 

Just to clarify, this is what happens in creation, that I like a lot: 

https://user-images.githubusercontent.com/8402646/116214998-2c1fec80-a73f-11eb-9404-3d4e40b820c4.mp4

But it's impossible to do with drag and drop:

https://user-images.githubusercontent.com/8402646/116215309-7739ff80-a73f-11eb-9102-23e866f9e2da.mp4

Do you think what I'm saying would be possible?

PS: Thanks for the bugfix, and thanks for this library!

**Comment by githubuser0xFFFF** [comment]
Yes, I think technically it would be possible to implement this.

**Comment by ruilvo** [comment]
Cool, thanks! But so it's not a feature that I might be able to do out of the box, is it? Like a signal that is fired when docking happens so that widgets could be re-laid out.

Also, I had this idea for an UI... It might be too out of mind, but tell me what you think and if it could be achieved. So, I'm imagining a sidebar on an application, where the elements of the sidebar can be undockable. 

I'm making an open source application for SDR and it has a main display and lots of controls for the hardware and the DSP, and I imagined like that would be a cool solution. That would allow users to have a main space uncluttered while being able to dock out important controls and hide away the sidebar... 

That's why I made this first question. But even further, how about something like this:
![gui_idea](https://user-images.githubusercontent.com/8402646/116605363-37357100-a927-11eb-9279-5724765fdb92.png)

(amazing paint skills I know)

The idea is that docked widgets do *not* fill the sidebar, and if there are too many the sidebar could even scroll down...

Ideally they would be resizeable while docked and dock with the height they had before docking (only adjusting horizontally).

What do you think?

**Comment by githubuser0xFFFF** [comment]
Please have a look into the examples - the sidebar example is quite close to the thing that yout would like to have. The dock widgets will fill the sidebar - so it is not exactly what you want. But you have a static GUI on the right and a dock area on the left.

If this fits your needs, the  it is good. If this does not fit your needs, I think you are need to implement something by yourself.
