### ISSUE TITLE
Porting from QDockWidgets

### ISSUE THREAD

**Issue by brandoncall** [githubuser0xFFFF/Qt-Advanced-Docking-System#320]
I love your Advanced Docking System.  It is fantastic.  

I am trying to port over from the stock QDockWidgets and it wasn't clear to me which path was the easiest.  My application has a UI file with a bunch of docks and each dock has a bunch of child widgets.  My team uses Qt Creator to drag and drop new widgets when changes are neeed.  This is very helpful for us and reduces development time.  It looks like your examples are made programmatically.  I saw that your CDockWidget inherits from QFrame so I tried to add a bunch of QFrames to my ui and move the contents of the existing docks into the QFrames and use promotion to make the QFrames CDockWidgets.  This almost worked, but the system expects to be able to provide the parent widget as the first constructor parameter and the CDockWidget requires a title.  The CDockWidgets would fit into the Qt ecosystem better if they had a setTitle(QString) function instead of having the title required in the constructor.

At this point it looks like I have to separate out each existing dock into a different UI file and then put those in CDockWidgets and then change all my code to use the widgets with different names in different places, or forget my ui file and generate my UI programmatically.  Is there a better way to port over?  Or is there a way to use CDockWidgets in the graphical designer?

**Comment by githubuser0xFFFF** [comment]
ADS has no Qt Designer plugin and hence does not support graphical configuration. You can create your widgets with the Qt Designer and then create the user interface programmatically by creating your dock widgets and then setting your dock widget content to the widgets created with the Qt Designer. This is how we do it in our application.

So yes, you are right: you have to separate out each existing dock into a different UI file. When we first added ADS to our software, we supported both docking systems: ADS and the default docking system. If you go this way, it should be not that hard to switch from Qt Docking System to ADS or to support both docking systems.

**Comment by brandoncall** [comment]
Thanks!

Brandon Call
