### ISSUE TITLE
Qt6 removes X11Extra API required by Linux

### ISSUE THREAD

**Issue by Bueddl** [githubuser0xFFFF/Qt-Advanced-Docking-System#324]
Qt6 removed X11Extra which is currently required for building for, and running on, Linux (therefore it is not possible to build for Linux using Qt6).

See in particular: 
* https://code.qt.io/cgit/qt/qtx11extras.git/commit/?id=6037ece5e4c0d290ae4ebf75c0d9bce0de55ed85 (commit of module-removal)
* https://code.qt.io/cgit/qt/qtx11extras.git/diff/README?id=6037ece5e4c0d290ae4ebf75c0d9bce0de55ed85 (updated README)
* https://github.com/qt/qtbase/commit/edceff30b4093e2bef6e80c7552edf595134f351 (commit of integration as a *private* API in QtGui)
* https://bugreports.qt.io/browse/QTBUG-83251?focusedCommentId=544133 (assigned Issue)

Apparently parts of the functionality are about to be exposed with a different API, but I am not sure on how this is progressing.

**Comment by githubuser0xFFFF** [comment]
Just merged a fixed that should solve this issue
