### ISSUE TITLE
Qt 5.15.2 + KDE: Setting QAbstractScrollArea border to 1px with QSS breaks eliding

### ISSUE THREAD

**Issue by RigoLigoRLC** [githubuser0xFFFF/Qt-Advanced-Docking-System#325]
As described, if I set `QAbstractScrollArea {border:1px solid}` as global stylesheet (`qApp->setStyleSheet`), eliding goes wrong.

![image](https://user-images.githubusercontent.com/49363666/120912594-1f3dd380-c6c3-11eb-93f9-ba1ba4c37f10.png)

![image](https://user-images.githubusercontent.com/49363666/120912633-70e65e00-c6c3-11eb-9295-91be87a03794.png)

I know ADS is using stylesheet for customization, but a `CDockWidgetTab` should be derived from `QFrame`, which is also the parent class of `QAbstractScrollArea`. Setting style on `QAbstractScrollArea` should not affect this.

**Comment by githubuser0xFFFF** [comment]
Does this happen only if you change the stylesheet during runtime - that means if the tab is already visible or does this also happen, if you set the stlyheet initially at the start of the application?

**Comment by RigoLigoRLC** [comment]
setting it when the application is in initialization or runtime will both
cause the sliding problem. One thing I should note is that if the border is
very thick (like 8px), everything is squeezed into the center and won't
expand. I wonder if it's related to Qt internals.

**Comment by githubuser0xFFFF** [comment]
The tabs are embedded into a `CDockAreaTabBar` wich is derived from `QScrollArea`. The border that you see if you set it for `QAbstractScrollArea` is not around 'CDockWidgetTab' but around `CDockAreaTabBar`. So if you set a border for `QAbstractScrollArea` you need to ensure to disable the border for `CDockAreaTabBar`.
