### ISSUE TITLE
two docks in the same container have different height

### ISSUE THREAD

**Issue by jie414341055** [githubuser0xFFFF/Qt-Advanced-Docking-System#327]
Let's say we create a CDockWidget called A, and add it to the dockManager using 
```mDockManager->addDockWidgetTab(A, ads::CenterDockWidgetArea);```

Then, we add another CDockWidget called B and do this:
```mDockManager->addDockWidgetTabToArea(B, A->dockAreaWidget());```

Now, when you switch between tab-A and tab-B, the height of dock will  always be 2-pixels different.

**Comment by githubuser0xFFFF** [comment]
Sorry, I cannot reproduce this issue.
