### ISSUE TITLE
LNK1104: cannot open file qtadvanceddocking.lib

### ISSUE THREAD

**Issue by rocketmay** [githubuser0xFFFF/Qt-Advanced-Docking-System#328]
On a fresh install of QT Creator 6.2.0 and a fresh pull from the Qt-Advanced-Docking-System repo, attempting to build any .pro file in the project gives the error: LNK1104: cannot open file qtadvanceddocking.lib

In addition I also get the alert "Project WARNING: Install Prefix not set"

**Comment by githubuser0xFFFF** [comment]
Have you found a way to fix this?

**Comment by rocketmay** [comment]
No, I'm unfortunately stuck and unable to get the project running on QT.

**Comment by githubuser0xFFFF** [comment]
Just fixed this in master an tested with Qt6.2 and MSVC 2019 - works now

**Comment by rocketmay** [comment]
I can confirm that this works for me now! Thank you!
