### ISSUE TITLE
Custom icons don't work

### ISSUE THREAD

**Issue by daniel-sso** [githubuser0xFFFF/Qt-Advanced-Docking-System#329]
Hi there.

I can't get custom icons to show up using the `CIconProvider`. They seem to be overriden by the internal qrc/stylesheet.
Only when I remove the `setStyleSheet` call in the `CDockManager` constructor, my custom icons start working.

It doesn't seem to be possible to disable the stylesheet w/o modifying the source/build, so the feature seems broken.
Or is there a different way?

This was tested on 3.7.1

**Comment by githubuser0xFFFF** [comment]
Please read the section Styling in the documentation.

**Comment by daniel-sso** [comment]
Thanks a lot, totally missed that. Sorry about that.

It would be great if it was possible to use custom icons while still using the internal stylesheet. The only reason I can't use the icons is that the qt build I'm working with lacks svg support. Admittedly that might be a bit too specific for my use case though.
