### ISSUE TITLE
Dragging tab to new dock breaks rendering

### ISSUE THREAD

**Issue by ParadoxKG** [githubuser0xFFFF/Qt-Advanced-Docking-System#330]
Dragging a tab from one dock onto the "new dock in lower half" icon creates a dock with broken/inactive rendering. Resizing the dock restores rendering. Observed Version 3.7 with Qt 5.15.2 on Windows 10.

How to reproduce
- Use a layout with multiple tabs in one Dock
- Drag one tab into another dock, onto the "add as lower part" icon
- => New dock is created and Tab is moved but its rendering is broken
  - it shows a weird "screenshot" of multiple views with a strange offset
  - it does not update if clicked, however the clicks and selection work and update other views
- Resizing the dock restores proper rendering

See attached video

https://user-images.githubusercontent.com/74646583/125050025-df8f5080-e0a1-11eb-9390-5fe97e1a3acd.mp4

Application code on https://github.com/GENIVI/ramses-composer

**Comment by githubuser0xFFFF** [comment]
I just tried to reproduce the problem with the ADS demo application with your steps given in the text above bud I could not reproduce the problem. Maybe it is a issue specific to you application?:


https://user-images.githubusercontent.com/4239304/125072814-5b49c700-e0bb-11eb-96e7-9fb8f0ca0496.mp4
