### ISSUE TITLE
Empty window after  undock/dock

### ISSUE THREAD

**Issue by obivan43** [githubuser0xFFFF/Qt-Advanced-Docking-System#335]
So this issue happens if I completely undock something, like in the video, and then dock to any place. If I try to dock element without undocking all works fine. In example project also all works fine for me

https://user-images.githubusercontent.com/14957416/126476316-3c36685b-c47d-4a19-9b16-92581f3f2b99.mp4

**Comment by githubuser0xFFFF** [comment]
Please send me your demo project, then I can look into it

**Comment by obivan43** [comment]
@githubuser0xFFFF hello you can find it on
https://github.com/obivan43/pawnengine

- But you probably need to have VS2019(Comunity or etc.)
- QtVsTools
- And when you add qt folder to qt vs tools call it "default_qt"

And I'm using Qt 6.1.2

P.S Thanks for help

**Comment by githubuser0xFFFF** [comment]
@obivan43 I just tested the ADS demo with Qt 6.2.0 and VS2019 and could not reproduce the issue so I think the problem is most likely in your application.

**Comment by obivan43** [comment]
@githubuser0xFFFF BTW yeah issue was in my code, I was not calling QApplication::exec, but it's a bit unfortunate that you can't handle properly event with processEvents, fixed by moving my game update code to another thread
