### ISSUE TITLE
Question: How to programaticallty resize a docking widget?

### ISSUE THREAD

**Issue by ruilvo** [githubuser0xFFFF/Qt-Advanced-Docking-System#336]
So, I have this:
![imagem](https://user-images.githubusercontent.com/8402646/127005916-242d9a63-12dd-4290-a9ab-d05d2f24b14f.png)

`resize` isn't making the docking area wider... How do you actually resize a docking area that already exists programmatically?

**Comment by githubuser0xFFFF** [comment]
I think this should be possible via the DockWidget parent splitter:

```c++
CDockSplitter* Splitter = internal::findParent<CDockSplitter*>(area);
```

If you have the splitter, then it should be possible to resize the widget with the splitter functions.

**Comment by meishen** [comment]
CDockAreaWidget* pExportAreaWidget = m_pAdsDockManager->addDockWidget(BottomDockWidgetArea, m_pExportAdsDockWnd);
	CDockSplitter* Splitter = internal::findParent<CDockSplitter*>(pExportAreaWidget);

error C2440: “初始化”: 无法从“ads::CDockAreaWidget *”转换为“const QWidget *”

The parameter type is not correct.
