### ISSUE TITLE
Mistake in QT ADS 5.7.0? 

### ISSUE THREAD

**Issue by Sgoloskov** [githubuser0xFFFF/Qt-Advanced-Docking-System#337]
It's not changes. I can't file -lqtadvanceddocking from ads.pri. I have used QT ADS previously with out problems. QT Creator 4.0.2. for QT 5.7.0. Best Regards!

**Comment by githubuser0xFFFF** [comment]
Sorry, I do not understand what you mean.

**Comment by Sgoloskov** [comment]
I have used QT ADS in Qt crearor with out problem. Now QT ADS 5.7.0 open source QT 4.0.2. , Manjaro. Maybe after reinstall I can't use QT ADS because in file ads.pri used     ladvanceddocking    , probably library, which missing. This is the mistake, about which appears when debuggian any example. Best regards!

**Comment by Sgoloskov** [comment]
I have used QT ADS in Qt crearor with out problem. Now QT ADS 5.7.0 open
source QT 4.0.2. , Manjaro. Maybe after reinstall I can't use QT ADS
because in file ads.pri used ladvanceddocking , probably library, which
missing. This is the mistake, about which appears when debuggian any
example. Best regards!

сб, 31 июл. 2021 г. в 17:37, githubuser0xFFFF ***@***.***>:
