### ISSUE TITLE
control dockwidget size

### ISSUE THREAD

**Issue by meishen** [githubuser0xFFFF/Qt-Advanced-Docking-System#340]
`CDockSplitter* Splitter = internal::findParent<CDockSplitter*>(area);`

Can you give me an example of this? 

`CDockAreaWidget* pSubClipAreaWidget = m_pAdsDockManager->addDockWidget(RightDockWidgetArea, pSubClipDockWnd, pExportAreaWidget);
QWidget* p = (QWidget*)pSubClipAreaWidget;
QSplitter* Splitter = internal::findParent<QSplitter*>(p);
Splitter->resize(300, 300);`

This is mine, but it doesn't work.

thanks！

**Comment by githubuser0xFFFF** [comment]
Please check the demo application. I added a test to show how to do this. In the main menu click the menu item **Tests->Resize Calendar 1** to test it. In the code you can see how it works.
