### ISSUE TITLE
[Question] What determines re-docking size?

### ISSUE THREAD

**Issue by ruilvo** [githubuser0xFFFF/Qt-Advanced-Docking-System#343]
Hello there!
Sorry for keeping nagging you with questions.

I noticed that when things are removed and re-docked they don't keep the same size:

https://user-images.githubusercontent.com/8402646/128527404-0c527b29-664a-4dd7-83c3-f88c000e6708.mp4

What defines the size after docking? Can the size (width) be kept constant on docking? 

Thanks

**Comment by githubuser0xFFFF** [comment]
What should be the size of a dock widget after it has been docked?

**Comment by ruilvo** [comment]
I'm not suggesting any particular answer. I'm just asking what's the mechanism behind if, and if it's controllable. For example, when the right panel is re-docked, is there a signal I can connect to?

**Comment by githubuser0xFFFF** [comment]
QSplitter determines the docking size. The widget is just inserted into a QSplitter.
