### ISSUE TITLE
Ability to add/replace Tab context menu

### ISSUE THREAD

**Issue by DexterMagnific** [githubuser0xFFFF/Qt-Advanced-Docking-System#346]
Dear developer,

Thank you a lot for this wonderful software. Works like a charm !

I'd like to submit a feature request: I'd like to add actions or maybe replace the dock tab context menu by my own menu/actions.
I now there is already setTitleBarActions(), but this creates a button which enlarges the tab height.
As there is already a built-in context menu in the tab itself, I'd like to add new actions or replace the whole menu.

Usage example: My dock widgets show plots. I'd like to add actions for "screenshot", "export to CSV", ....

Thanks

**Comment by rolivav** [comment]
Hey @DexterMagnific 
You can already do this using a `CDockComponentsFactory`.
You can implement
```
	virtual CDockWidgetTab* createDockWidgetTab(CDockWidget* DockWidget) const;
```
Make a subclass of `CDockWidgetTab` and override `contextMenuEvent`. Then you can implement your own context menu.
Cheers.

**Comment by DexterMagnific** [comment]
Yes I know I can reimplement by subclassing. The point was to provide something like tab->addActions() so we don't need to subclass. Rationale is that we are not changing behavior, so no need to take the heavy way.

**Comment by githubuser0xFFFF** [comment]
Feel free to provide a pull request
