### ISSUE TITLE
Resizing QMainWindow in Tab

### ISSUE THREAD

**Issue by nmiglio** [githubuser0xFFFF/Qt-Advanced-Docking-System#347]
Hi and thanks for this amazing software!

I'm trying to put a QMainWindow on a tab and my problem is that when the tab is resized, the status bar and the menu are hidden and I need to scroll the tab to see them. Is there a way to avoid this? 
How can I have only the part between the menu and status bar to shrink in case it is needed? (the WMainWindow contains a table that might or might not fit inside the tab.. so no predefined size).

**Comment by githubuser0xFFFF** [comment]
Which value do you use for the `InsertMode` parameter of the  DockWidget `setWidget` function if you assign the QMainWindow?
