### ISSUE TITLE
Perfomance issue on undock tab

### ISSUE THREAD

**Issue by DimaKoltun** [githubuser0xFFFF/Qt-Advanced-Docking-System#353]
Hi!
QtADS has perfomance issue on undocking dock widget from tab bar with several tabs with flags:

`
	ads::CDockManager::setConfigFlag(ads::CDockManager::OpaqueUndocking, true);
`

On the video we can see that sometimes undocked widget can finish dragging while mouse pressed.

https://user-images.githubusercontent.com/83829508/133455916-91aa0f33-57ac-4776-ba99-fa283bc8ca1f.mp4

Why it's happening and what i can do with this?

**Comment by githubuser0xFFFF** [comment]
I have no idea.

**Comment by githubuser0xFFFF** [comment]
Switch to non opaque docking to avoid this issue

**Comment by delins** [comment]
@DimaKoltun Could you check if the issue is still there with the latest commit? #401 fixed a similar issue

**Comment by OpenJeDi** [comment]
I added a remark about MacOS on the original issue #350

The issue on MacOS seems to be different than this particular example: in my case the docking overlay gets "stuck" just like in the original issue. In this example, the dragging just seems to stop and you are able to resume dragging?

**Comment by githubuser0xFFFF** [comment]
It is exactly like in the video above.

**Comment by enjoysmath** [comment]
Run your code in Release mode without debugging (the non-filled in play button in Visual Studio), and docking / undocking is about 10x faster. :)

**Comment by githubuser0xFFFF** [comment]
Closed because `OpaqueUndocking` is no longer supported since release 4.0.2
