### ISSUE TITLE
Is it planned to develop smarter version of save/restore layout?

### ISSUE THREAD

**Issue by DimaKoltun** [githubuser0xFFFF/Qt-Advanced-Docking-System#356]
https://user-images.githubusercontent.com/83829508/134506820-70aad30d-d0a6-4e01-b274-7726eba532db.mp4

ADS fine restore sizes of panel if it was closed and then opened. But, if we close panel and create perspective, then when we restore state to this perspective closed panels will be restored with default sizes, is it possible to fix it?

**Comment by githubuser0xFFFF** [comment]
At the moment no further developments are planned. The library works reliable in our application and it is in maintenance state.

But pull requests are possible.
