### ISSUE TITLE
How to add floating window into taskbar?

### ISSUE THREAD

**Issue by tarhan** [githubuser0xFFFF/Qt-Advanced-Docking-System#358]
I've read in some issue that minimize button has been disabled because floating (undocked) window do not added to OS taskbar (at least in Windows).  
That is ok for multi screen solutions. In my case main window consists of telemetry tables with data (on one screen) and floating windows are plots (on second screen).  
But when I undock plots on laptop I could not see plots window ever again. I could not even switch between main window and floating windows using Alt+Tab shortcut.  
Is it possible to mark floating window to be visible on taskbar or accessable using Alt+Tab at least.

**Comment by githubuser0xFFFF** [comment]
This is not planned for the near future.
