### ISSUE TITLE
How to resize a dock widget via code?

### ISSUE THREAD

**Issue by JosephCoppola-FW** [githubuser0xFFFF/Qt-Advanced-Docking-System#36]
Hello, 

This might be a stupid question, but how would you go about resizing a dock widget via code? 

Thanks,

Joe

**Comment by githubuser0xFFFF** [comment]
Do you mean a docked dock widget or a floating dock widget?

**Comment by JosephCoppola-FW** [comment]
Either or.

**Comment by githubuser0xFFFF** [comment]
This is not possible
