### ISSUE TITLE
Linux: focusedDockWidgetChanged not fired on main window

### ISSUE THREAD

**Issue by BenjaminSchulte** [githubuser0xFFFF/Qt-Advanced-Docking-System#362]
When Q_OS_LINUX is defined the focusedDockWidgetChanged signal won't be fired by the CDockFocusController.

The early return in line 160 of DockFocusController.cpp prevents the remaining to from being executed.

My simple hotfix was to modify the code to:

    #ifdef Q_OS_LINUX
      // This code is required for styling the floating widget titlebar for linux
      // depending on the current focus state
      if (FloatingWidget != NewFloatingWidget)
      {
        if (FloatingWidget)
        {
          updateFloatingWidgetFocusStyle(FloatingWidget, false);
        }
        FloatingWidget = NewFloatingWidget;

        if (FloatingWidget)
        {
          updateFloatingWidgetFocusStyle(FloatingWidget, true);
        }
      }
    #endif

**Comment by githubuser0xFFFF** [comment]
Thanks for the tip. I have fixed the error in the master.
