### ISSUE TITLE
Two screens with different HDPI

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#367]
Hello,

There are some problems with high DPI option Qt::AA_EnableHighDpiScaling when the two screen have not the same HDPI value.
For example, with a 4K monitor at 150% scaling in Windows and HD monitor at 100%. (Could be reproduce also with two HD monitors, one at 150% and the other at 100%)

![Screen1](https://user-images.githubusercontent.com/33324685/138060080-17d408e0-f992-41db-b406-8524f44fbc36.png)
![Screen2](https://user-images.githubusercontent.com/33324685/138060086-b7fa7dc0-511b-413d-a27d-895395b67521.png)

All the tests has been done by using the Advanced Docking System Demo.

The problems are:
- When launching the application on HD screen and then move it to the 4K screen, the UI have a refresh problem. Resizing the window, fix the problem ?
![bug1](https://user-images.githubusercontent.com/33324685/138061032-36016689-140c-4b43-bac1-71cdc9a9188f.png)

- Put the main window in the 4K screen and click on the Save State button. Move the main window to the HD screen. Click on the Restore State button. The result is the window has twice the size from the initial state. (with the problem of refresh from the first bug)

- Sometimes when I undock a dock from the main window to the other screen, I have a crash (not 100% reproductible)

Thank you for your help !

**Comment by IkkiNit** [comment]
None are problems that can be fixed with stylesheets, QtADS doesn't take on account the HDPI in some cases.
I have exactly same problems with a tuned app. I just repro the bugs in the sample for you in order to debug the cases easily.

**Comment by githubuser0xFFFF** [comment]
What do you exactly mean with "QtADS doesn't take on account the HDPI in some cases"?
