### ISSUE TITLE
Application crash when closing Floating Editor and Docked Editor in Demo

### ISSUE THREAD

**Issue by gorec323** [githubuser0xFFFF/Qt-Advanced-Docking-System#368]
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-38-generic
OS Type: 64-bit
Graphics Platform: X11

Steps:

1. Run AdvancedDockingSystemDemo
2. Create Docked Editor
3. Click to close created Docked Editor
4. Application crash after calling the QApplication::focusWindowChanged signal handler  CDockFocusController::onFocusWindowChanged. The dynamic property "FocusedDockWidget" refers to an already deleted object.

**Comment by gorec323** [comment]
I've already fixed the bug. I'm just going to figure out how to make a merge request.

**Comment by githubuser0xFFFF** [comment]
Fixed in master
