### ISSUE TITLE
DockWidgetFloatable will not work when double click titlebar

### ISSUE THREAD

**Issue by helywin** [githubuser0xFFFF/Qt-Advanced-Docking-System#37]
Hi:
    I disable DockWidgetFloatable feature, but when I double click the titlebar, the widget will be floating. It's on "linux_experimental" branch and my Qt version is 5.12.3.

**Comment by githubuser0xFFFF** [comment]
Hi,

I just verified this in master and could reproduce the problem. I just properly implemented support for the DockWidgetFloatable flag for master and will try to git this into linux_experimental branch.

**Comment by githubuser0xFFFF** [comment]
Hi,
 
I just merged the changes from master into linux_experimental so DockWidgetFloatable feature should work now.

**Comment by helywin** [comment]
Thanks

**Comment by githubuser0xFFFF** [comment]
Hi,

I just merged the linux_experimental branch into master so the Linux functionality is now available in master branch.
