### ISSUE TITLE
Debug Versions cannot be built for QT5.15

### ISSUE THREAD

**Issue by ix07** [githubuser0xFFFF/Qt-Advanced-Docking-System#374]
Hi.

Since one of the latest changes (probably this one: @githubuser0xFFFF, githubuser0xFFFF committed on Oct 22) the debug versions of ADS can no longer be built with QT version 5.15.1.

:-1: error: LNK1104: cannot open file 'qtadvanceddocking.lib'

- Release versions compile and build fine
- Reverting to the ".pri"-file before the change also works

But maybe I am just doing something wrong?

Thanks.

**Comment by githubuser0xFFFF** [comment]
Thank you for reporting this issue, I close it for now because of a lack of information.

The link in your issue report does not bring me to any commit and I have no idea, which compiler you use on which system.

Feel free to reopen this issue with improved information.
