### ISSUE TITLE
Unclosable dock widget is still closeable using middle mouse button

### ISSUE THREAD

**Issue by stijnherfst** [githubuser0xFFFF/Qt-Advanced-Docking-System#377]
On version 3.8.0 a dock widget with DockWidgetClosable set to false is still closeable when MiddleMouseButtonClosesTab is set using the middle mouse button.

**Comment by githubuser0xFFFF** [comment]
Already fixed in master

**Comment by stijnherfst** [comment]
Ok, thank you for your excellent work.
