### ISSUE TITLE
Crash when restoring a floating container's state to a non-floating container

### ISSUE THREAD

**Issue by BenHetherington** [githubuser0xFFFF/Qt-Advanced-Docking-System#379]
It seems like, in an application that has a dynamic number of non-floating dock containers (e.g. to have one full-screen dock container per monitor), running `restoreState()`, passing an XML file containing fewer non-floating dock containers than there currently are in the application and at least one floating widget, will cause the library to crash.

This seems to be because `ads::CDockContainerWidget::RestoreState()` will unconditionally assume `this` is floating if the XML has the `Floating` boolean set, and will dereference `floatingWidget()`. If `this` *isn't* floating, `floatingWidget()` will return `nullptr`, leading to a crash when it's subsequently used.

---

I've opened this as an issue rather than submitting a PR since I'm not 100% sure how you'd prefer to fix this.

The simplest fix would be to just add a check around the use of `floatingWidget()`, e.g.
```cpp
if (!Testing)
{
    CFloatingDockContainer* FloatingWidget = floatingWidget();
    if (FloatingWidget)
    {
        FloatingWidget->restoreGeometry(Geometry);
    }
}
```
which will lead to the first floating dock container's contents to be deserialised into one of the non-floating containers. This is potentially unexpected, but at least the contents of that dock container are still accessible, and the application won't crash.

Alternatively, we could add additional code to ensure that floating containers are always deserialised to floating containers. Arguably, this *feels* more intuitive to me from a user's perspective, but I don't currently see a simple way to accomplish this in code.

**Comment by githubuser0xFFFF** [comment]
Hi Ben, thank you reporting this issue. Could you please provide some instructions to reproduce this issue with some simple steps. I'm not sure I completely understand what is going wrong from your description.

**Comment by BenHetherington** [comment]
Sorry for the delay, [I've just pushed up a repro](https://github.com/BenHetherington/Qt-Advanced-Docking-System/tree/issue-379-repro) to try and help demonstrate this issue.

This repro hacks the central widget example to add serialisation, and the option to add an extra dock container (which is contrived in this app, but serves to demonstrate the issue).

To reproduce the issue using this branch:
1. Run the central widget example app, with the `AddExtraDockContainer` boolean (at the top of `mainwindow.cpp`) set to `false`
2. Drag a dock widget out of the main window, so that there's at least one floating container
3. Save out the dock widgets' state to a file, using File > Save
4. Close the example app, change `AddExtraDockContainer` to `true`, and then re-compile and re-run it
5. Load the state that was saved earlier - Qt Advanced Docking System should crash as reported

If things are still unclear then let me know 🙂

**Comment by githubuser0xFFFF** [comment]
Ok, thank you for this information. I'm just trying to understand the use case. Why would someone create non floating dock containers if you can get the same result with a floating dock container. You can simply drag the floating container to a different monitor.

**Comment by BenHetherington** [comment]
Fair enough, I appreciate that the repro isn't particularly indicative of my use case!

The use case is an application which runs in full-screen on a pre-configured set of monitors, so without window chrome or title bars, and without allowing the user to move it. If the user wants to undock certain widgets and have them floating in a custom location, that's fine, but the 'main window(s)' should cover these monitors.

From what I understand, using a floating container for each monitor's 'main window' doesn't *feel* like the right solution to me for this particular use case, since floating containers are designed to allow the user to freely move them around. For this purpose, they're great, and I agree that they'd fulfil multi-monitor needs for most windowed applications by allowing the user to put them where they'd like on any monitor, but that's not quite what I'm after in this full-screen use case.

With that in mind, the best way I could find to accomplish this seemed to be to create full-screen window(s) myself, and then add a dock container (of which the dock manager is one) to each monitor's widget. This setup also allows dock widgets to be dragged between monitors, and docked into sections of a different monitor if desired (which wouldn't be possible with two dock managers, for example).

Hopefully this makes more sense. Does this still seem like a misuse of the library? As far as I can tell, the part that's causing trouble here is the ability to configure the number of monitors, and thus, the number of dock containers in the application?

**Comment by githubuser0xFFFF** [comment]
Thank you for this detailed explanation. I think your use case is very special and it makes more sense to maintain these changes in your own fork.

**Comment by BenHetherington** [comment]
OK, well, thanks for your time.

Personally, use case aside, I still think that the 'simple fix' suggested here is worthwhile, from the perspective that the deserialisation code currently is making an implicit assumption that could cause crashes, and the behaviour of this fix seems reasonable enough. I appreciate it's often not possible to defend against *all* input data, but this seems more akin to a logic error to me.

But it's up to you; I'd prefer to upstream bug fixes and the like where possible, but if you think a fork's the way to go (e.g. if you think I'm likely to encounter more issues like this), then I'll look into it.

**Comment by githubuser0xFFFF** [comment]
This proposed solution would be fine for me - so please feel free to create a pull request

```c++
if (!Testing)
{
    CFloatingDockContainer* FloatingWidget = floatingWidget();
    if (FloatingWidget)
    {
        FloatingWidget->restoreGeometry(Geometry);
    }
}
```
