### ISSUE TITLE
Hide the DockManager does not hide the floating widgets

### ISSUE THREAD

**Issue by jporcher** [githubuser0xFFFF/Qt-Advanced-Docking-System#380]
When you call `hide()` on the  `ads::CDockManager` while some childs are floating, you would expect them to be hidden as well, but they remain visible.

**Comment by githubuser0xFFFF** [comment]
Sorry, but this is not a bug. It is not intended that hiding the CDockManager hides floating widgets.

**Comment by jporcher** [comment]
I'm surprised because, for the end user, they remain childs of the CDockManager.
If I want to have this behaviour, would you accept it (through a pull request) if it's disabled by default and enabled through a new config flag (eConfigFlag)?

**Comment by githubuser0xFFFF** [comment]
I don't like the idea to add more complexity for a very special corner case and I also don't like the idea that hiding the dock manager hides the floating - widgets. I don't even have an idea why someone would like to hide the dick manager.

So I'm sorry but I'm not convinced and will not accept a pull request.

**Comment by jporcher** [comment]
@githubuser0xFFFF  "I don't even have an idea why someone would like to hide the dock manager."

This may be relevant when your application has a welcome widget. Basically, you store the welcome widget and the main widget (a dock manager) in a QStackedLayout. And you then show either the welcome widget when no project/file is opened and the main widget when a project is opened. So then, you would expect the floating widgets to be hidden when moving back to the welcome view after user closed its project/file.

An alternative to using eConfigFlag would be to add a "hideManagerAndFloatingWidgets" function to CDockManager that would simply hide the floating widgets and remember them to be shown back when QShowEvent is executed.

But I won't insist, this is your lib, if you don't want that we will implement it on our side. Just let me know.

**Comment by githubuser0xFFFF** [comment]
You can create a clean pull request. I would prefer the `hideManagerAndFloatingWidgets` solution. If the changes are small, clean and have no negative performance impact, I may merge it.
