### ISSUE TITLE
Controls in tabs not rendering/invisible.

### ISSUE THREAD

**Issue by Neumann-A** [githubuser0xFFFF/Qt-Advanced-Docking-System#385]
![image](https://user-images.githubusercontent.com/30894796/145733242-baf89642-ea80-44da-b8c8-8eefbec3d597.png)

Qt: 6.2.2
Version: 3.8.1
(static build)

Any ideas how to solve that or what might be the issue? (The normal QDockWidget renders as expected)

**Comment by Neumann-A** [comment]
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#disabling-the-internal-style-sheet

DockManager->setStyleSheet(""); .....

**Comment by Neumann-A** [comment]
After checking the what is actually used I saw that *.svg files are used. 
Maybe mention somewhere that linking against `Qt::Svg` is required for the defaults or make it an interface dependency.

**Comment by githubuser0xFFFF** [comment]
Thank you for this hint.
