### ISSUE TITLE
ADS Commercial License and Pricing

### ISSUE THREAD

**Issue by LiamC12345** [githubuser0xFFFF/Qt-Advanced-Docking-System#389]
I have no idea how to link the ADS to another application project that I've begun working on as a shared library, as well as what to do to ensure I accidentally don't do anything that supposedly breaches the LGPL 2.1 license throughout my journey of creating a commercial app.

I would quite prefer to just use the ADS project files as a base foundation starting point to build an application upon from there. I know that doing this would very likely mean that I would need to work out a commercial license with you for using the ADS in this way

If the price is reasonable I would gladly do a one-time payment for a commercial license if that is an option
What would your pricing be?

Kind Regards,
Liam

**Comment by githubuser0xFFFF** [comment]
I have not sold any static link exception so far, but I would say 2900,- $ would be ok.

**Comment by LiamC12345** [comment]
There is a way you could be making lots of sales with this and I'll tell you how as I have taken several courses in business
throughout my years before beginning to program:

Firstly the vast majority of people don't purchase things directly from random people on a website message chat - you will need to setup an actual website that automates the sales process for you where people can just click purchase and SECURELY enter their credit card details via paypal and such. From my standpoint as of now, there is no guarantee that you'll send me a commercial license document or anything at all for that matter if I direct deposit you any amount of money. 

You need to setup a trustworthy/approved website that people can purchase commercial licenses from. The benefits for you is that the process is automated so you don't even have to be there to make do the deal and you make money while you sleep.

Secondly, $2900 is way too high and off-putting for your target market. Most people here would probably run a mile seeing that figure. Another reason sales haven't been made for you yet for such a great product/service is that the barrier for entry is way too high. Most people cannot afford that.
Would you rather sell 1 or 2 copies at $2900
Or would you rather sell 50 copies at $497 ($24,850)

I myself wouldn't pay any more than $497, which is the price I would recommend for you to sell this at.

If you can setup a website to sell commercial licenses for this docking system, you will make a small fortune my friend.
But its up to you. Countless sales at a lower price is far better than next to no sales at a higher price.

Setting up a commercial website with Wordpress is a little bit of work but its easy and well worth it, I would recommend doing that. You may as well churn a profit from all this hard work and development you've put into this but it's a 'Not Yet' for me just at this stage.

**Comment by githubuser0xFFFF** [comment]
Ok, I understand this. So you can use the shared library version for free to fulfill the LGPL license requirements. If you do any changes to the ADS source code, then you need to ensure that you make these changes available. Do you plan any changes?

**Comment by LiamC12345** [comment]
I don't plan to make any changes other than the stylesheets to customize my own look, surely stylesheets such as the default.css can be altered right?

Upon opening ads.pro in Qt, Am I able to delete the example, erase the code out of demo so it's literally like starting a new empty document project from scratch and then just build my application from there using JUST src as a shared library?

All I'd need is src. Demo and example I don't need at all. 

All I'm looking to do is touch nothing in src which is ACTUALLY where your Advanced Docking System exists, but use it as you have quoted "A Shared Library" to incorporate a functioning dock from by simply calling functions from it in my application project (which was 'demo' but is renamed & replaced by a blank slate for writing an app from scratch).

I don't intend to change any of the functionality or alter any features in the Advanced Docking System aside from the default.css stylesheet because as you've probably seen in my other forum post, trying to set Style sheets programmatically doesn't work - unless you have a solution for that?

I don't want to annoy you with all these questions but it is a little confusing as to what I can and can't do - there seems to be a blurred grey area with this LGPL license as I'm not exactly altering anything in demo or example, I'm just simply not using it whatsoever - I'm only incorporating one part of ads.pro which is src and touching nothing in it other than the stylesheet as it seems to be literally the only way to customize an App's unique look/design.

I tried adding ads.pro as an additional project beside my already existing initial app setup but unfortunately mine was in CMake and your docking system is in Qmake so that didn't work.
And when I tried opening up that same project later (even though they aren't' compatible), ads.pro doesn't open WITH my initial app project and thus it feels like the two aren't actually incorporated into one project - you have to re-open ads.pro each time and I'm not sure whether the two projects are actually incorporated together for latter when I go to export the App in it's complete and final form.

This is my first time building an app with Qt and if I'm going to do the shared library LGPL thing - then I guess What I want to really know is:
What are steps for including ads.pro as a shared library? Is there a feature or right-click button in Qt that says "Add Shared Library to Project" or is it simply opening ads.pro AFTER having already opened a seperate App Project (That is also in Qmake for compatibility)?

The last thing anyone wants to do is something that accidentally breaches the license and then suddenly there's lawsuits and shit.

**Comment by githubuser0xFFFF** [comment]
If you use ADS in your project, then you first need to build the ADS  shared library. If you build this ADS project, then you fill find the DLL `qtadvanceddocking.dll` in your build folder.

Then you can create a new Qt project and link to the shared library.

Because of the LGPL you are not allowed to link statically to the ADS library - you need to use a shared library. 

For oll other questions you need to read the relevant documentation and learn how to create an Qt application and how to use shared libraries. The ADS demo application shows how to use the shared ADS library.

**Comment by LiamC12345** [comment]
Yeah ok, I'll give that a shot and do some research on shared libraries
Thanks for your response

**Comment by LiamC12345** [comment]
But what of the stylesheets? Can we customize our own look by making changes to the default.css file?
If not - Do you have a solution for changing the dock stylesheets programatically in my Project's .cpp files?

The following code below doesn't work in my Project's .cpp files:
m_dockmanager->setStyleSheet(""); and newRandomDock->setStyleSheet("random styleSheet change");

How do I change stylesheets WITHOUT altering ads.pro resources such as the default.css text file?

**Comment by LiamC12345** [comment]
Now that I think of it, I guess it won't really matter if I alter the default.css stylesheet to fit my app's unique design and look so long as I simply make the changed .css code available for people to see (Not that anyone would care to view it I guess but anyway).

All good, sorry for the million questions but I'm definitely starting to get my head around how all this works
Thanks Again :)
