### ISSUE TITLE
Python Bindings?

### ISSUE THREAD

**Issue by cherryleafroad** [githubuser0xFFFF/Qt-Advanced-Docking-System#39]
Would be useful for people who use Python

**Comment by githubuser0xFFFF** [comment]
Yea, this is a great idea. Pull requests for Python bindings are very welcome.

**Comment by klauer** [comment]
While not bindings, I have a basically-working conversion of @githubuser0xFFFF's fork to Python 3.6+: https://github.com/klauer/qtpydocking. It doesn't include the recent Linux support changes just yet.

Python bindings of the C++ version would be much more performant with all of the event filters used in the project. Pure Python stuff - in my opinion - is just much more fun to work with though!

**Comment by cherryleafroad** [comment]
@githubuser0xFFFF In fact I thought about it, looked into it, and would love to do it. Unfortunately however, I don't know C, so my own skills aren't up to par. :(

**Comment by githubuser0xFFFF** [comment]
If someone would like to implement pyhton bindings, then any contribution is welcome. I will not do this so I close this issue.
