### ISSUE TITLE
UI styling

### ISSUE THREAD

**Issue by ioanachelaru** [githubuser0xFFFF/Qt-Advanced-Docking-System#390]
I'm looking for a way to alter the color of the overlay frame that appears when dragging a `CDockWidget`, as well as the preview of the splitter that appears when trying to reposition it. I did find the documentation for customizing the `CDockOverlayCross` and assumed the style of other elements may be system-dependent, but I see that the products presented in the readme file managed to customize those features. 
Can you offer me some guidance in this matter?

**Comment by LiamC12345** [comment]
I could be wrong but I think it could be possible to customize that via the stylesheets. If you access the default.css file (in the src/stylesheets folder) and edit the desired changes there by opening it in a text program and then saving those changes before rebuilding your project, then I think you might have some luck.

Bare in mind any changes you make to the original ADS code including stylesheets must then go open source and those said changes must be available to the public (According to the LGPL License).

**Comment by githubuser0xFFFF** [comment]
Please have a look into the code that paints the overlay to learn how to style it:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/e6fc1c14bd272133d6953335a866d3f2442e5c12/src/DockOverlay.cpp#L470-L507

The code uses QPalette for the colors.

**Comment by ioanachelaru** [comment]
Thanks a lot! What about the preview of the splitter, where can I find it?

**Comment by githubuser0xFFFF** [comment]
ADS uses standard QSplitters - QPalette is your friend

**Comment by zubeyir-bodur** [comment]
It seems it is not possible to change the highlight palette color from stylesheet. However, if we change the snippet to following:

```cpp
void CDockOverlay::paintEvent(QPaintEvent* event)
{
    //...
    QColor Color = palette().color(QPalette::Active, QPalette::Window); // Use Window color (background-color) instead of Highlight
    //...
}
```
Then we can change the overlay and preview colors from stylesheets using background-color property:

```css
ads--CFloatingDragPreview
{
	background-color: #8bc34a;
}

ads--CDockOverlay
{
	background-color: #8bc34a;
}
```
Therefore, in order to give a styling for that, the change above needs to be done.
