### ISSUE TITLE
minimumSizeHint Implementation (A Feature not explained in the ADS documentation)

### ISSUE THREAD

**Issue by LiamC12345** [githubuser0xFFFF/Qt-Advanced-Docking-System#392]
How exactly is minimumSizeHint meant to be implemented for it to take affect? Because it's not working for me.
Below is my code with comments //

//Set the Mode to Content so that Widgets inside the dock dictate the minimum distance the dock is
//allowed to be from the edge of the screen.
testDock->setMinimumSizeHintMode(ads::CDockWidget::MinimumSizeHintFromContent);

//Create an example Label Widget to insert into dock with a set minimum width constraint of 500.
QLabel *testLabel = new QLabel(this);
testLabel->setText("Hello");
testLabel->setAlignment(Qt::AlignCenter);
testLabel->setMinimumSize(500, 500);
testDock->setWidget(testLabel, ads::CDockWidget::ForceNoScrollArea);

In spite of the code above, the dock still doesn't respect the minimum size of 500 that I set the label to be.

Everything is technically correct here according to other posts in the forum regarding minimumSizeHint:
1) I set the minimumSizeHintMode to Content
2) And I set a minimum size constraint of 500 upon the Label Widget.

I can't tell if this is an ADS thing or another issue on my end.
One things for sure though, I always do a ton of research before coming to the forum

**Comment by githubuser0xFFFF** [comment]
Please read the Qt documentation to learn the difference between the `setMinimumSize()` and `minimumSizeHint()` function of `QWidget`.

**Comment by LiamC12345** [comment]
I did
setMinimumSize() sets the minimum size of the widget. It takes two values: (int minw, int  minh)
minimumSizeHint() simply holds the recommended width and height value of the widget.

The value for minimumSizeHint() is set by setMinimumSize() and I have Proof below:

When I output the following to return and verify the value of minimum size hint:
qInfo() << "Label Minimum Size Hint: " << testLabel->minimumSizeHint();
qInfo() << "DOCK Minimum Size Hint: " << testDock->minimumSizeHint();

The Application Output says:
Label Minimum Size Hint:  QSize(500, 500)
DOCK Minimum Size Hint:  QSize(500, 500)

IF I change the minimumSizeHintMode of the dock to DockWidget:
testDock->setMinimumSizeHintMode(ads::CDockWidget::MinimumSizeHintFromDockWidget);

Then the Appication Output says:
Label Minimum Size Hint:  QSize(500, 500)
DOCK Minimum Size Hint:  QSize(60, 40)

The MinimumSizeHintMode (Emphasis on the MODE) is a feature that you created, and it's not working.

In spite of correctly setting the minimumSizeHint of the Label while the dock is set to Content Mode,
the dock still does not conform to the Label's size constraints of 500, 500. 
The dock is still resizable to QSize(60, 40) EVEN THOUGH the Application Output clearly says that the Dock's Minimum Size Hint has been changed to QSize(500, 500)

Refer to: 
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/139

Also Refer to:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/190

You seemed to have solved this issue in previous posts, but my suspicion is that newer versions of ADS since those posts
may have rendered this feature buggy, for whatever reason.

I am using the latest master of ADS (literally downloaded and unzipped it yesterday).

**Comment by githubuser0xFFFF** [comment]
Please have a look into the demo application:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/e6fc1c14bd272133d6953335a866d3f2442e5c12/demo/MainWindow.cpp#L322-L342

The `CMinSizeTableWidget` has a `minimumSizeHint` that perfectly works with the docking system:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/e6fc1c14bd272133d6953335a866d3f2442e5c12/demo/MainWindow.cpp#L143-L156

So it seems you are doing something wrong.

Regarding the documentation. This is the source code documentation:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/e6fc1c14bd272133d6953335a866d3f2442e5c12/src/DockWidget.h#L198-L211

Do you really think, that there is some documentation missing?

**Comment by LiamC12345** [comment]
I see, thanks for getting back to me again
Yes I just checked out the demo now, the floating table widget does in fact work with the way you have implemented minimumSizeHint. 

I won't lie, I don't exactly understand all the code in the demo in spite of reading Qt Documentation all the time but at least now I know for absolute certainty that studying up from the ADS Demo is where to go if I get stuck from here on.

My new years resolution is to try to avoid the forum haha 

I'm not doubting your abilities, or the standard that your documentation is at, It really is fantastic.

And EVEN IF minimumSizeHint wasn't working, I would still think the ADS is the coolest thing on my mind at the moment.

Clearly you are a far better programmer than I am.
I'm merely just doing my best to teach myself all this Qt C++ stuff all by myself (not an easy undertaking).
I literally just started learning to code 2 months ago, which you've probably gathered.

But I appreciate you getting back to me even though I'm probably that one annoying guy you find on every forum haha
Believe it or not, your answers have actually helped a lot because it's steered me in the right direction

If ever I thought that there was some documentation missing, I definitely don't now
Thanks again - I hope you enjoy your Christmas :)
