### ISSUE TITLE
Feature Request: RemoveAllDockWidgets(); (A simple feature that would indirectly lead to Instant Dock Layout Templates - Read On)

### ISSUE THREAD

**Issue by LiamC12345** [githubuser0xFFFF/Qt-Advanced-Docking-System#393]
I know it's a bit of a read but it's worth it.

Would it be possible to add a dock manager function that simply removes all docks simultaneously from the main window upon being called - without deleting the contents/widgets contained within each dock?

For example:
m_DockManager->removeAllDockWidgets();

Notice also how this hypothetical function would take no Parameters/Arguments, purposefully, for scope reasons as
I will explain further on.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Quick Note: I'm also Not talking about m_DockManager->hide(); or m_DockManager->hideManagerAndFloatingWidgets();
It needs to be Remove, because hide() doesn't actually remove the docks in the same way that removeDockWidgets does.
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

You might be asking why? Why do this?
What added benefit would this have?
Why add this function/feature when there is already m_DockManager->removeDockWidget(dockWidget); ?
Why not call removeDockWidget one at a time for each dock?

The Reason being is that right now, it is currently impossible to trigger the adding or removal of specified docks in the main window via a QAction Signal linked to a void function Slot - and the reason for this as I said before is Scope.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
NOTE that the docks I'm trying to do this with are minimumSizeHint Docks, which are implemented in the same
way as seen in the demo, which means Creating and Defining new docks derived from the MainWindowPrivate struct looks like this:

auto dockWidgetTestOne = d->dockWidgetTest();
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Because Slots don't take void functions that have parameters, there is no way of adding or removing docks via Slot Void function calls, because their scope doesn't allow the created Dock 'dockWidgetTestOne' (as mentioned above) to be recognized when trying to add or remove it it in a Slot function, because of scope, like so:

void MainWindow::slotFunction()
{
m_dockManager->removeDockWidget(dockWidgetTestOne);
}

dockWidgetTestOne is defined/created in the MainWindow::MainWindow function with the code:
'auto dockWidgetTestOne = d->dockWidgetTest();'

And trying to call m_dockManager->removeDockWidget(dockWidgetTestOne); from a separate function doesn't work because the definition of dockWidgetTestOne is not in the same scope.

"auto dockWidgetTestOne = d->dockWidgetTest();" Cannot be implemented globally either because Widgets cannot be created outside outside a function in the .cpp file because the creation of QApplication must come first not QWidgets. Basic variables like int and string can be made global (defined outside of functions), but not Widgets.

Therefore IF we had a removeAllDockWidgets() function, it would be parameterless, ergo there would be no scope issue and developers could then use this workaround to get any amount of specified docks they wanted to open and disappear from the main Window at the click of a PushButton or a Toolbar Button or a Menubar Button or whatever button the QAction Signal / Void Function Slot is linked to.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

It means you could do something awesome like this:

//This Function sets up a layout of Three Specific Docks in the main window,
//while rendering other docks to be closed/removed from view
void MainWindow::slotFunctionOne() 
{
m_DockManager->removeAllDockWidgets(); //Clears the Main Window of Docks from previous layout setup
auto dockWidgetOne = d->dockWidgetTestOne(); //Re-Draws Dock One as shaped in the MainWindowPrivate struct
auto dockWidgetTwo = d->dockWidgetTestTwo(); //Re-Draws Dock Two as shaped in the MainWindowPrivate struct
auto dockWidgetThree = d->dockWidgetTestThree(); //Re-Draws Dock Three as shaped in the MainWindowPrivate struct
m_DockManager->addDockWidget(ads::TopDockWidgetArea, dockWidgetTestOne); //Places Dock One in Window
m_DockManager->addDockWidget(ads::BottomDockWidgetArea, dockWidgetTestTwo); //Places Dock Two in Window
m_DockManager->addDockWidget(ads::LeftDockWidgetArea, dockWidgetTestThree); //Places Dock Three in Window
}

//This Function sets up a different layout consisting of Four Docks in the main window
void MainWindow::slotFunctionTwo()
{
m_DockManager->removeAllDockWidgets(); //Clears the Main Window of Docks from previous layout setup
auto dockWidgetOne = d->dockWidgetTestOne();
auto dockWidgetTwo = d->dockWidgetTestTwo();
auto dockWidgetThree = d->dockWidgetTestThree();
auto dockWidgetFour = d->dockWidgetTestFour();
m_DockManager->addDockWidget(ads::TopDockWidgetArea, dockWidgetTestOne);
m_DockManager->addDockWidget(ads::BottomDockWidgetArea, dockWidgetTestTwo);
m_DockManager->addDockWidget(ads::LeftDockWidgetArea, dockWidgetTestThree);
m_DockManager->addDockWidget(ads::RightDockWidgetArea, dockWidgetTestFour);
}

//This Function sets up yet another layout consisting of Two Specified Docks in the main window
void MainWindow::slotFunctionThree()
{
m_DockManager->removeAllDockWidgets(); //Clears the Main Window of Docks from previous layout setup
auto dockWidgetTwo = d->dockWidgetTestTwo();
auto dockWidgetFour = d->dockWidgetTestFour();
m_DockManager->addDockWidget(ads::TopDockWidgetArea, dockWidgetTestTwo);
m_DockManager->addDockWidget(ads::BottomDockWidgetArea, dockWidgetTestFour);
}

And thus Dock Layout Combinations for the Main Window are setup instantly at the click of a button.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
The Following Video shows the closest visual example of what I'm talking about for visual reference
I.E  changing dock layouts according to button, but this video doesn't mean I succeeded.
It's actually failing to delete the previous layout when I click the second button and bugs up.
Hence the need for removeAllDockWidgets()

https://user-images.githubusercontent.com/96278032/147759831-47260adc-6c7e-4057-8bf0-935fe4255959.mp4

As you can also see, all docks here implement minimumSizeHint
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

The only potential obstacle to this plan is this:
It means you'd have to re-state the following code upon each Slot/Function call, as seen in the examples above:

auto dockWidgetOne = d->dockWidgetTestOne();

But hopefully the widgets and settings/states that each dock contains are stored safely in the MainWindowPrivate struct.
I have a feeling they would be, but you would know for sure. Either way, I hope this idea serves as some good food for thought
to help to make the ADS potentially even more Awesome, regardless of whether this idea succeeds or not.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

I did have a go at trying to add/code this myself in the src .cpp/.h files in order to come back here with a Pull Request, but it turns out I'm not experienced enough with Qt yet (or the complexity of understanding your docking system) to actually get it working, although I did have a very good try. You are way more familiar with how the ADS works and connects together than I, since you're it's creator.

So I was wondering if this was something that could be easily coded and added to the ADS as a workaround for allowing QActions to trigger dock template layouts at the click of a button

Kind Regards,
Liam

**Comment by githubuser0xFFFF** [comment]
Thank you for your feature request. I will close this request for now because of the following reasons:

- I'm not convinced of the use case and do not understand it completely
- it is a very special feature that has not been requested before
- there are many other open feature requests that have a higher priority
- I think the requested functionality can be easily added in your application

**Comment by LiamC12345** [comment]
Thanks for getting back to me
I will try to get this feature working on my end and inform you if I manage to succeed with it

But your odds of succeeding are far far greater and quicker I would imagine, as I am just a noob.
A smart noob, however, just not as experienced as you are just yet.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
If you do happen to change your mind and decide to give it a crack I'll just Simplify here below what removeAllDockWidgets()
would mean for the ADS:

Some programs such as the 3D Animation Program Blender have ToolBar/Menu buttons up top that instantly change the dock layout - Like so:

https://user-images.githubusercontent.com/96278032/147811273-d5367238-73b7-459c-8f5e-1f46ee282c9e.mp4

removeAllDockWidgets() essentially opens the door for the ADS to have that same ability.
To change a program's workspace in an instant.

This would be particularly useful for programs that require the user to regularly flick back and forth between many different workspace layouts to accomplish tasks that are interconnected. Animation is big on this!

It saves a lot of time and prevents the interruption of the user's workflow/creativity as they won't have to think about constantly manually re-setting up their dock layouts for different purposes, the buttons just does it for them :)

**Comment by githubuser0xFFFF** [comment]
This is already possible with perspectives. See the Video on the main page.

**Comment by LiamC12345** [comment]
Well I'll be damned....

I never cease to astonish myself with my own stupidity

I'm checking it out right now

Thankyou githubuser0xFFFF
You're truly a Legend!
