### ISSUE TITLE
How do I programmatically add a dock widget to a dock container widget?

### ISSUE THREAD

**Issue by BenHetherington** [githubuser0xFFFF/Qt-Advanced-Docking-System#394]
Hope you don't mind me posing this as a question.

I'm using ADS in a full-screen multi-monitor app, and to allow dock widgets to be docked into each monitor, I've set it up so that a `CDockContainerWidget` is created for each monitor, passing the dock manager into its constructor[^1].

This works great for letting the user dock widgets into each monitor, but I'm struggling to work out how to programmatically add dock widgets to these containers, in order to add a 'default' widget for each monitor.

<details>
<summary>What I've tried thus far, in case it helps</summary>

- `CDockContainerWidget::addDockWidget()` seems to be the obvious API to do this, and it indeed works, except that the dock manager's map of docked widgets isn't updated to include the new one, causing, e.g. deserialisation to break.
- The only place that seems to update this map (and emit a `dockWidgetAdded()` signal) is `CDockManager::addDockWidget()` (and its related methods within the same class). However, this defaults to using the dock manager as the container, which can only be overridden by passing it a `CDockAreaWidget` that already exists inside the intended container – and as no dock widgets have been added to the container yet, the container doesn't contain any dock area widgets yet, and so I don't have one available to pass in.
    - Additionally, this method just forwards on to `CDockContainerWidget::addDockWidget()`, which makes me unsure if the method on `CDockContainerWidget` is intended to be used publicly…
- I tried working around this by calling `CDockManager::addDockWidgetFloating()` followed by `CDockContainerWidget::addDockWidget()` with the same dock widget, which will add it to the map, and add it to the dock container, deleting the floating dock container in the process. However, this apparently causes memory-related bugs within the library (namely, a pointer within `d->UninitializedFloatingWidgets` becomes dangling, potentially crashing the application inside `CDockManager::showEvent()`). While this *feels* like a bug within the library to me, this kind of workaround is bound to be fragile, so I'd rather not have to do something like this if it's possible.
    - Honestly, this is the approach I had implemented, until I became aware of the memory bug; in hindsight, I probably should've instead posed this question sooner, but ah well 🤦
</details>

Hopefully I've not missed something, but is there an intended way to add dock widgets to a dock container, such that the dock manager is made aware of the added dock widget? Or if there isn't currently one, is it worth adding a new `addDockWidget()`-style method to `CDockManager` that allows you to specify the container that the widget should be added to?

[^1]: Technically, as `CDockManager` is a subclass of `CDockContainerWidget`, one of the monitors uses the `CDockManager` as its container, but I digress…

**Comment by githubuser0xFFFF** [comment]
You should only use the DockManger functions for adding dock widgets because the DockManager only knows about the dock widgets that it manages if you use the DockManager.

I think it should be possible, to add a dock widget via CDockManager::addDockWidgetFloating() and then move the floating widget to the second monitor. Then you have the main windows on your first monitor and a floating dock widget on your second monitor.

**Comment by githubuser0xFFFF** [comment]
Sorry, but I do not completely understand the request.  If you create the floating widget the way I described, then you can easily move it programatically to your second monitor.

**Comment by BenHetherington** [comment]
Ah, I hadn't considered programmatically moving a floating widget, sorry I missed your meaning there.

I can look into that when I get a chance, but I can think of a few concerns compared to using `CDockContainerWidget` directly:
- It's possible for the library to close the floating widgets, e.g. during deserialisation even if widgets on that monitor are set to not be user-closable, whereas I think this application wants to keep dock containers present on all monitors even in that situation, instead of showing the desktop behind
- It creates asymmetry between how one monitor's widget is created, compared to the others
- Personally, it feels a bit janky to take a floating dock container that's created and managed by the library, and then to programmatically move it and apply borderless flags to it ourselves

That said, I get the impression that you're trying to dissuade the usage of dock container widgets directly. Is the intention that they're just an implementation detail of the dock manager and floating widgets, rather than the impression I was under, which is that they are a usable widget that also happens to underpin these?

**Comment by githubuser0xFFFF** [comment]
I'm not trying to dissuade the use of dock container widgets directly. At the moment it is simply not a use case that has been considered and properly implemented by the library so I cannot tell if this works. So before something is changed in the library source code, I would try to solve it with the tools the library provides. If this does not work for you and if this is not the solution that fits you best, then you can try to changed the library.

So if you create a pull request, then I can try to review it but there is no gurantee, that it will be merged. If the changes have no negative inpact on the performance and a small and good to review, then it will likely be merged.

**Comment by BenHetherington** [comment]
Sorry for taking a while before coming back to this, and thanks for explaining your perspective on this (and for suggesting a solution).

I think because of the concerns I mentioned above, I feel that using containers directly would still be preferable for me, so I'll submit a small pull request to add the method on `CDockManager` I mentioned above. Hopefully it's a small enough addition that you're happy to include it 🙂
