### ISSUE TITLE
QOpenGLWidget and QWidgets that contain QOpenGLWidgets in tabs

### ISSUE THREAD

**Issue by adisuciu** [githubuser0xFFFF/Qt-Advanced-Docking-System#397]
I'm having an issue when implementing QOpenGLWidgets and QWIdgets that contain QOpenGLWidgets in tabs. It looks like the update does not go all the way through to the children. What I mean by this is that 

When QOpenGLWidget is directly added to a tab everything works as expected.
If QWidget which contains a QOpenGLWidget is added to the tab, the QOpenGLWidget requires a separate update() / repaint() event in order to correctly render. I've hacked together QTs examples hellogl2 - https://doc.qt.io/qt-5/qtopengl-hellogl2-example.html and your demo to demonstrate this - video

https://user-images.githubusercontent.com/8676912/151782797-a87c3bc5-04b6-43a4-bfe5-4d12a54baa37.mp4

I can provide code for this issue, it is reproducible with both Qt5.15 and Qt6. Do you have any idea what might cause this ? 
-Adrian

**Comment by githubuser0xFFFF** [comment]
Please check if issue is related to #294

**Comment by adisuciu** [comment]
It doesn't seem related to that issue. I just tested with versions 5.12.2 and 5.9.9 and the results are the same. Also the suggested workaround (Remove the #ifdef so CDockWidgetArea will override the event() method)  - doesn't do anything for me.

**Comment by githubuser0xFFFF** [comment]
If have no idea but I dont think that this is an ADS bug because I do not use any special features.

**Comment by adisuciu** [comment]
The reparenting that occurs when docking/undocking and changing tabs will destroy the OpenGL context in which the rendering happens. My OpenGLWidget correctly calls cleanup and initializeGL but there is no subsequent paintGL call. I don't know if this is caused by some stuff in ADS or in the Qt library.

https://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup

 A workaround for this issue.
`QApplication::setAttribute(Qt::AA_ShareOpenGLContexts,true);`
https://doc.qt.io/qt-5/qopenglwidget.html#context-sharing

I just posted this here as it may help somebody else having a similar issue.

**Comment by githubuser0xFFFF** [comment]
Thank you very much for your help. I will add this information to the documentation.

**Comment by virtuozo007** [comment]
> The reparenting that occurs when docking/undocking and changing tabs will destroy the OpenGL context in which the rendering happens. My OpenGLWidget correctly calls cleanup and initializeGL but there is no subsequent paintGL call. I don't know if this is caused by some stuff in ADS or in the Qt library. Also this only happens on the widget that contains QOpenGLWidget. The tab that contains QOpenGLWidget directly does not have this problem. I think this is some kind of race condition in QT but I don't know how to reproduce it in an easy manner to report it to Qt. Either that or I don't understand QOpenGLWidget's documented limitation's in this case.
> 
> https://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup
> 
> A workaround for this issue. `QApplication::setAttribute(Qt::AA_ShareOpenGLContexts,true);` https://doc.qt.io/qt-5/qopenglwidget.html#context-sharing
> 
> I just posted this here as it may help somebody else having a similar issue.

That really helps me, Thanks!
