### ISSUE TITLE
DockWidget->toggleViewAction() doesn't show dockWidget

### ISSUE THREAD

**Issue by nitramr** [githubuser0xFFFF/Qt-Advanced-Docking-System#400]
I faced an issue in the "sidebar" example.

**Steps to reproduce**
1. Run sidebar project from master
2. Close "Editor 1" dock widget
3. Go to View menu and check checkbox of Editor 1
BUG: it doesn't show the dock

If you toggle dock widget of "Label 1" there is no issue.

https://user-images.githubusercontent.com/15112256/156752107-e42cdd37-85c0-426b-8de8-5d7633fc0a5f.mp4

**Comment by githubuser0xFFFF** [comment]
Thank you. I  fixed this in master.

**Comment by nitramr** [comment]
Thanks, I can confirm the fix.
