### ISSUE TITLE
CMake Script broken - debug and release version have identical names

### ISSUE THREAD

**Issue by klein-j** [githubuser0xFFFF/Qt-Advanced-Docking-System#406]
When using the CMake script to compile and install the library, both the debug and release version have the same name. That makes it impossible to install both versions, since the files get overwritten (as they are also installed to the same directory).

Fix: Add a postfix, e.g. "_D"

Possible implementation:
`SET_PROPERTY(TARGET ${PROJECT_NAME} PROPERTY DEBUG_POSTFIX "D")`

**Comment by githubuser0xFFFF** [comment]
Ok, thank you - I may consider thus

**Comment by klein-j** [comment]
What confuses me a bit is, why was the ticket closed then?

Looking at the history, it was not implemented yet.
Looking at your comment, the idea was not rejected as "we won't do this" (ideally followed by an "and here is why").

Therefore the ticket should not be closed because the issue is not resolved yet.

**Comment by klein-j** [comment]
I installed it today on a new machine and ran again into the same problem.
Why is it still not fixed? If I submit a patch, will you merge it? Any reasonable arguments against my suggestion?

**Comment by githubuser0xFFFF** [comment]
It is not fixed because there was no pull request to fix it - that means nobody fixed it. It seems like other users do not consider it as broken.
