### ISSUE TITLE
Seems a bug on deleteonclose demo

### ISSUE THREAD

**Issue by lanmanck** [githubuser0xFFFF/Qt-Advanced-Docking-System#407]
5.14.1+vs2017+win10 on examples\deleteonclose.
Modify QTextEdit to this:
`
class TextEdit : public QTextEdit
{
public:
    TextEdit(const QString &text, QWidget *parent = nullptr):QTextEdit(text,parent){

    }
    ~TextEdit(){
        qDebug() <<"txt edit end";
    }
};
`
and replace QTextEdit to TextEdit on main.cpp, and RUN, just click Toggle [DeleteContentOnClose] ,the output is:

![微信截图_20220406105729](https://user-images.githubusercontent.com/3500166/161886753-ea250072-4cd7-450f-833e-da637ab64c18.png)

We can see , on the first time hide the dock, the TextEdit did not be freed. will it lead to memory leak?

**Comment by githubuser0xFFFF** [comment]
Sorry, but I cannot reproduce the problem here. I did the same like you and this is the output:

![grafik](https://user-images.githubusercontent.com/4239304/162404475-7397f07f-b822-434c-942f-eef0b253edb0.png)

You can see, the TextEdit is always deleted. So I have no idea what is wrong on your side.

**Comment by lanmanck** [comment]
I also test under 5.15.2+vs2019+ win7, it acts the same.
what's your enviroment ?
the code is called but delete not happened:
`
void DockWidgetPrivate::hideDockWidget()
{
    TabWidget->hide();
    updateParentDockArea();

    if (Features.testFlag(CDockWidget::DeleteContentOnClose))
    {
        Widget->deleteLater();
        Widget = nullptr;
        qApp->processEvents(); // add here but no change
    }
}`
