### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by grotius-cnc** [githubuser0xFFFF/Qt-Advanced-Docking-System#408]
In clone dir i did : qmake && make

DockWidget.cpp:71:30: error: ‘FactoryFunc’ in ‘class ads::CDockWidget’ does not name a type
   71 |                 CDockWidget::FactoryFunc createWidget;
      |                              ^~~~~~~~~~~
DockWidget.cpp: In member function ‘bool ads::DockWidgetPrivate::createWidgetFromFactory()’:
DockWidget.cpp:266:31: error: ‘struct ads::DockWidgetPrivate::WidgetFactory’ has no member named ‘createWidget’
  266 |         QWidget* w = Factory->createWidget(_this);
      |                               ^~~~~~~~~~~~
DockWidget.cpp: At global scope:
DockWidget.cpp:348:6: error: variable or field ‘setWidgetFactory’ declared void
  348 | void CDockWidget::setWidgetFactory(FactoryFunc createWidget, eInsertMode insertMode)
      |      ^~~~~~~~~~~
DockWidget.cpp:348:36: error: ‘FactoryFunc’ was not declared in this scope
  348 | void CDockWidget::setWidgetFactory(FactoryFunc createWidget, eInsertMode insertMode)
      |                                    ^~~~~~~~~~~
DockWidget.cpp:348:62: error: ‘eInsertMode’ was not declared in this scope
  348 | void CDockWidget::setWidgetFactory(FactoryFunc createWidget, eInsertMode insertMode)

**Comment by githubuser0xFFFF** [comment]
I just did exactly the same here, qmake && make, and everything compiled perfectly without errors. So there must be something wrong or broken on your system.
