### ISSUE TITLE
Documentation - Configuration Flags and CDockManager creation 

### ISSUE THREAD

**Issue by ARSanderson** [githubuser0xFFFF/Qt-Advanced-Docking-System#409]
in the documentation it is noted:

_You should set the configuration flags before you create the dock manager instance. That means, setting the configurations flags is the first thing you do, if you use the library._

With my implementation I was creating the CDockManager as part of the constructor initializer list then setting the configuration flags. On OS X this sequence would cause a hard crash on start up of the app. I discovered that while trying to sort out an issue that if the CDockManager is part of the constructor initializer list and with no configuration flags being set that no dock widgets would be exposed. That is the CDockManager creation must come AFTER the ui is setup.

As such, there is a very specific order that must be followed, setup the ui, set dock configure flags, create the dock manager:
```
MyMainWindow:: MyMainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui:: MyMainWindow)
{
    ui->setupUi(this);

    // Must be set before the dock manager is created.
    ads::CDockManager::setConfigFlag(ads::CDockManager::OpaqueSplitterResize, true);

    // Create the dock manager. Must be done after the ui setup and setting the configuration flags.
    // Because the parent parameter is a QMainWindow the dock manager registers itself as the central widget.
    myDockManager = new ads::CDockManager(this);
}

```

The following will crash on start up:
```
MyMainWindow:: MyMainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui:: MyMainWindow),
    myDockManager(new ads::CDockManager(this))
{
    ui->setupUi(this);
    ads::CDockManager::setConfigFlag(ads::CDockManager::OpaqueSplitterResize, true);
}

```
Without setting docks flags no docked windows will appear:
```
MyMainWindow:: MyMainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui:: MyMainWindow),
    myDockManager(new ads::CDockManager(this))
{
    ui->setupUi(this);
}

```

As such, the documentation should note:

The configuration flags must be set before creating the dock manager instance, otherwise the manager will not be created correctly and may crash upon startup. Further, because the dock manager registers itself as the central widget it must be created after the ui is setup, otherwise dock widgets will not be displayed.

**Comment by githubuser0xFFFF** [comment]
Thank you. Please create a pull request for this change.
