### ISSUE TITLE
Can not set the splitter size as expected with a CentralWidget

### ISSUE THREAD

**Issue by ARSanderson** [githubuser0xFFFF/Qt-Advanced-Docking-System#411]
I have two docking windows, one on the left and on the right that I want to have 1/4 and 3/4 of the screen space. If they are both docking I am able to set the sizes as I would like via the splitter:

```
    ads::CDockAreaWidget *dockArea =
        mDockManager->addDockWidget(ads::LeftDockWidgetArea, leftDockWidget);
    mDockManager->addDockWidget(ads::RightDockWidgetArea, rightDockWidget, dockArea);

    ads::CDockSplitter* splitter = ads::internal::findParent<ads::CDockSplitter*>(dockArea);
    int width = splitter->width();
    splitter->setSizes({width*1/4,width*3/4});
```

However, if the first window is a central widget, then in order to get what I want I have to use splitter sizes that are negative and greater than the width. Namely, -width*5/4 and width*9/4. Note when summed together it equals the width.

```
    ads::CDockAreaWidget *dockArea = mDockManager->setCentralWidget(leftDockWidget);
    dockArea->setAllowedAreas(ads::DockWidgetArea::OuterDockAreas);
    mDockManager->addDockWidget(ads::RightDockWidgetArea, rightDockWidget, dockArea);

    ads::CDockSplitter* splitter = ads::internal::findParent<ads::CDockSplitter*>(dockArea);
    int width = splitter->width();
    splitter->setSizes({-width*5/4,width*9/4});  // Negative value and value greater than the width!
```

I have been able to duplicate this behavior with the central widget example by the following:
-  after the first two dock widgets are created adding splitter code at line ~61 in the CMainWindow
-  not creating the last two dock widgets, comment out everything after line ~61 except the call to createPerspectiveUi.

In order to get the windows to be equally (50/50) split I must set the splitter sizes to width*6/4 and -width*2/4. Again a value greater than the width and a negative value. 

Full code from the Central Widget example:

```
CMainWindow::CMainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::CMainWindow)
{
    ui->setupUi(this);
    CDockManager::setConfigFlag(CDockManager::OpaqueSplitterResize, true);
    CDockManager::setConfigFlag(CDockManager::XmlCompressionEnabled, false);
    CDockManager::setConfigFlag(CDockManager::FocusHighlighting, true);
    DockManager = new CDockManager(this);

    // Set central widget
    QPlainTextEdit* w = new QPlainTextEdit();
	w->setPlaceholderText("This is the central editor. Enter your text here.");
    CDockWidget* CentralDockWidget = new CDockWidget("CentralWidget");
    CentralDockWidget->setWidget(w);
    auto* CentralDockArea = DockManager->setCentralWidget(CentralDockWidget);
    CentralDockArea->setAllowedAreas(DockWidgetArea::OuterDockAreas);

    // create other dock widgets
    QTableWidget* table = new QTableWidget();
    table->setColumnCount(3);
    table->setRowCount(10);
    CDockWidget* TableDockWidget = new CDockWidget("Table 1");
    TableDockWidget->setWidget(table);
    TableDockWidget->setMinimumSizeHintMode(CDockWidget::MinimumSizeHintFromDockWidget);
    TableDockWidget->resize(250, 150);
    TableDockWidget->setMinimumSize(200,150);
    auto TableArea = DockManager->addDockWidget(DockWidgetArea::LeftDockWidgetArea, TableDockWidget);
    ui->menuView->addAction(TableDockWidget->toggleViewAction());

    ads::CDockSplitter* splitter = ads::internal::findParent<ads::CDockSplitter*>(CentralDockArea);
    if (splitter)
    {
        int width = splitter->width();
        splitter->setSizes({width*6/4,-width*2/4});  // value greater than the width and negative value!
    }

    createPerspectiveUi();
}
```

It seems as though the central widget "owns" more screen space than what the splitter thinks.

**Comment by githubuser0xFFFF** [comment]
Please replace the line `int width = splitter->width();` with `int width = this->width();` and check if this helps. So your code should like this:

```c++
    ads::CDockSplitter* splitter = ads::internal::findParent<ads::CDockSplitter*>(CentralDockArea);
    if (splitter)
    {
        int width = this->width();
        splitter->setSizes({width*1/4,width*3/4});
    }
```

**Comment by ARSanderson** [comment]
Thanks I see the error in that one needs the whole window width. That does now work for correctly for the simple central widget example. For my actual implementation it does not when the layout is left-right. However it does work correctly when the layout is top-bottom, to a point. If I try to make the widget smaller it will not. That is 7/8, 1/8 works but 1/8, 7/8 does not.

I thought  the issue is that in my particular case my child widget when a central widget is saying it can not be made smaller but it really can be. However, I tried other widgets with similar results. So something with a central widget with a complex child widget. I have work around.

**Comment by githubuser0xFFFF** [comment]
Ok, this does not sound like an ADS issue

**Comment by ARSanderson** [comment]
If it would help, I am happy to share my actual code. It is not yet in a public git hub repo but will let you know when it is available.

BTW the ADS is great. It is a simple wrapper around my initial windows and otherwise plug and play.  It helped me learn a dew other Qtisms. So thank you very much. Danke.
