### ISSUE TITLE
Switch Fullscreen / Normal mode

### ISSUE THREAD

**Issue by stickrip** [githubuser0xFFFF/Qt-Advanced-Docking-System#414]
Hi there!

First of all, big thanks for your work and for the great functionalities this library provides :)

When coming back from a widget's fullscreen mode (exit fullscreen action requested by the user), I would like it to be properly docked back to its original container.
I was looking for a way to do this programmatically using the interface of the DockManager, but I couldn't find proper methods to do this precisely, they exist in the API but are not reachable by the client code side. The only workaround I found for now is to use a temporary backup perspective:

```
const char* TEMP_FULLSCREEN_BACKUP_LAYOUT = "TempFullscreenBackupLayout";

void SetFullscreen(ads::CDockWidget* pDockWidget, bool bFullScreen)
{
	ads::CDockManager* pDockManager = pDockWidget->dockManager();

	if (bFullScreen)
	{
		// Backup perspective before entering fullscreen
		pDockManager->addPerspective(TEMP_FULLSCREEN_BACKUP_LAYOUT);

		if (!pDockWidget->isFloating())
		{
			pDockWidget->setFloating();
		}

		pDockWidget->showFullScreen();
	}
	else
	{
		pDockWidget->showNormal();

		// Reload perspective after exiting fullscreen
		pDockManager->openPerspective(TEMP_FULLSCREEN_BACKUP_LAYOUT);
		pDockManager->removePerspective(TEMP_FULLSCREEN_BACKUP_LAYOUT);
	}
}
```

This solution works well but is quite heavy/expensive for such an operation that should be lighter and much more precise as it only concerns a single DockWidget to insert back into a particular slot.
I'm new to this lib and may be missing something important in the interface, in any case please let me know how I could improve this ;)

Cheers,
Nicolas

**Comment by githubuser0xFFFF** [comment]
There is currently no support for such an operation. To implement this, a dock widget would need to store its last docked location to properly restore it later. This is currently not implemented.
