### ISSUE TITLE
addDockWidgetTab doesn't create tabbed area

### ISSUE THREAD

**Issue by luelista** [githubuser0xFFFF/Qt-Advanced-Docking-System#415]
If you call addDockWidgetTab multiple times with the same area, I expect tabbed widgets in that area to be created. However, with an example as [this](https://gist.github.com/luelista/c0f4dfed72f4d443e7353ee8e51d8528), this results:

<img width="1199" alt="Bildschirmfoto 2022-05-02 um 21 50 10" src="https://user-images.githubusercontent.com/388142/166316312-c435db6e-2db2-41d3-85b0-0ddebb646daa.png">

Expected result would be:

<img width="798" alt="Bildschirmfoto 2022-05-02 um 21 47 07" src="https://user-images.githubusercontent.com/388142/166316328-7a34583e-2faf-4f69-8399-5a1703f11c1f.png">

I fixed it by removing line 861-864 in DockManager.cpp

	else if (!openedDockAreas().isEmpty())
	{
		return addDockWidget(area, Dockwidget, openedDockAreas().last());
	}

... or is this somehow expected behavior and I'm using addDockWidgetTab in the wrong way?

**Comment by githubuser0xFFFF** [comment]
Fixed by pull request #416
