### ISSUE TITLE
Possible memory leak issue when closing a delete on close dockwidget

### ISSUE THREAD

**Issue by tedlinlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#419]
I am trying out the delete on close feature, however, memory leak was detected at DockAreaWidget.cpp:183:0 using valgrind memcheck.
This only happened when I closed a dockwidget set to `CDockWidget::DockWidgetDeleteOnClose`.   
Please have a look, thanks in advanced!

Tested on Ubuntu 20.04

![Screenshot from 2022-05-04 17-13-09](https://user-images.githubusercontent.com/80113576/166653852-2cf8b3bf-7144-4e46-98d1-7ad21d0367fb.png)
![image](https://user-images.githubusercontent.com/80113576/166654004-b071f29d-6d64-474c-ac15-b0115867af08.png)

**Comment by tedlinlab** [comment]
Somehow, setting FloatWidget to null pointer after deletelater in DockWidget.cpp fixed the issue. (show in picture below)
However, I am not sure if this is the actual cause, and it seems odd that this fixed the issue since I never let the dock widget "float" during the memory test.
 
![image](https://user-images.githubusercontent.com/80113576/166663072-1c458eb2-dd29-412d-b02b-44b4e52606b7.png)

**Comment by tedlinlab** [comment]
Also, regarding the implementing the delete on close feature, instead of deleting the widget with `deleteLater()`
```c++
widget->deleteLater();
widget = nullptr;
```
Maybe consider setting the delete-on-close flag on creation of the dockwidget and let Qt take care of deleting it
``` c++
widget->setAttribute(Qt::WA_DeleteOnClose, true);
```

**Comment by githubuser0xFFFF** [comment]
Thank you for this hint. You can easily check if dock widgets or floating widgets are not properly deleted by putting debug messages in the destructor.

Please feel free to reopen this issue if you find a real memory leak.
