### ISSUE TITLE
Floating docks title doesn't update

### ISSUE THREAD

**Issue by Womps** [githubuser0xFFFF/Qt-Advanced-Docking-System#420]
Hi,

I think this might be a little bug. When a dock is floating undocked from the mainwindow, if you call setWindowTitle on the dock widget instance, the title of the floating window will actually not be updated, and will actually stay to the default title we gave at the instanciation of the dock widget.

```
m_dockManager = new ads::CDockManager(this);
m_dockWidget = new ads::CDockWidget("Test", this);
m_dockManager->addDockWidget(ads::CenterDockWidgetArea, m_dockWidget);

```
During the execution of the program...

`m_dockWidget->setWindowTitle("Test 1");`

If m_dockWidget is floating, not docked to the QMainWindow, when we call setWindowTitle("Test 1"), the title will stay at "Test" and not be updated to "Test 1"

**Comment by githubuser0xFFFF** [comment]
Thank you for reporting this issue. Should be fixed in master now.
