### ISSUE TITLE
Question: saveState/restoreState issue

### ISSUE THREAD

**Issue by roebst** [githubuser0xFFFF/Qt-Advanced-Docking-System#421]
Hi,
I have an application based on the central widgets concept from the examples.
But I need following extension. I have some, lets say, global widgets (like settings...) and some project widgets, that belong to a loaded project, If I now save the state of the dockmanager it saves logically all widgets in the same settings. But what I need is a way to separate globals and project settings. I default Qt I did that using a QMainWindow as central widget and could use its save/restoreState for the project widgets. Is there any way to achive this with this lib?

Best regards

**Comment by githubuser0xFFFF** [comment]
I have no idea how to achieve this. ADS stores the complete QSplitters hierarchy and I have no glue how to separately save the settings - sorry.
