### ISSUE TITLE
Add docking affinity support

### ISSUE THREAD

**Issue by delins** [githubuser0xFFFF/Qt-Advanced-Docking-System#422]
The `allowedAreas` works well, but I have several use cases where I need more control over what widgets can dock where. For one of those, I have a central area where one or more editor widgets are shown, and tool widgets are docked around it. This is essentially the _centralwidget_ example, but instead of having a single central widget, I want to be able to display multiple, say, `QTextEdit` widgets next to each other, or tabbed, or both, etc. These should be rearrangeable, so a simple `QSplitter` or `QTabWidget` won't do.

This is already possible with ads if you don't use a central widget, but that means that the central widgets will be able to dock next to the tool widgets, which would make the interface a mess. So I want the central widgets to only be able to dock in the central area.

I'd also like to be able to take one or more of the centrally docked widgets out and dock them somewhere else. That rules out using multiple `CDockManager`s as done by #96 and #308, where the use of multiple managers creates different scopes and once added to one manager, they can't be docked in the realm of another manager (not by dragging anyway). Also, since the library is built around the idea of having one manager, I dislike the idea of instantiating multiple.

I think many, if not all, of my use cases could be implemented if ads implements an "affinity" system like [KDDockWidgets](https://github.com/KDAB/KDDockWidgets) has. In KDDockWidgets' implementation, I would set the central area's affinity to "MyCentralAreaAffinity" which only allows dockwidgets with the same affinity to be docked, and no others. Similarly, as the outer dock areas don't have any affinity and my central widgets do, the central widgets cannot be docked there. This helps the user keep a clean interface while giving them more freedom to arrange widgets in a way that makes sense. Adding strings for affinity isn't the only option and there are more flexible designs possible, but I think it's the easiest both to implement and to use.

As far as I can tell, this probably won't require fundamental changes. The relevant widgets will need sets of `addAffinity`, `removeAffinity`, etc. `CDockOverlayCross::reset` and similar will need to take the affinities into account. Every time a different widget is made to float, all dock areas need to re-evaluate whether the dockwidget that is currently being dragged can dock there. This should probably be the intersection of the allowed areas and affinities. In terms of runtime performance I think the impact is limited: only when a new floating dock widget is selected do the docking areas need to re-evaluate, which is cheap and happens once per area. Also, it may be possible to implement it in such a way that no re-evaluation is triggered if users of ads don't ever set any affinities.

I'd like to give implementing this a go, but first I'd like to know if you're interested in accepting a pull request for this. And if so, do you agree which the approach or is there a better one?

**Comment by githubuser0xFFFF** [comment]
@delins I would accept a such a pull request. The feature should not have any performance impact on users that do not use it. Maybe adding a DockManager flag like `FocusHighlighting` to completely disable affinities by default would be a good idea.

Please keep the pull request small an clean. Do not mix the changes of the affinity system with any other changes and fixes. Please provide a small example app in the examples folder to demonstrate the feature.

**Comment by delins** [comment]
I see that using the dockareas and dockwidgets to set the affinities only gets me halfway where I want to be. I still believe it will support the example I gave in the first paragraph, but it won't support an interface like this:

![usingburp_usingburpsuite_3](https://user-images.githubusercontent.com/4976257/172196097-31df233c-36f7-4006-b92d-a104993c2c55.png)

I'd want for instance to be able to have the "Target" tab and "Proxy" tab open next to each other instead of only one at a time. Imagine that you can undock the "Proxy" widget and move it to the right of the "Target" widget. You now have two widgets, each with their own "subdocks". It seems like nesting `CDockContainerWidget`s would be the best way to achieve this. There's some work to be done though because ads assumes you don't nest these. I'm willing to tackle that as well.

1. do you agree with the proposal to make `CDockContainerWidget` nestable?

Making the affinity system a thing between `CDockContainerWidget` and `CDockWidget` instead of `CDockAreaWidget` and `CDockWidget` if more powerful: the former allows you to do what you could do with the latter, and more. The only downside I've come up with so far is that dropping widgets can get finnicky when containers are nested, because the top container may obstruct drop locations of the one below it.

2. The affinity system could possibly be made to work with all three classes, which would allow ads users to choose, or use both. I'm trying to avoid cluttering the current code base more than necessary though, and I'm not yet sure how many locations in the code these changes would touch. What are your thoughts?

**Comment by delins** [comment]
I agree it will get more complex, but it's a tradeoff. The problem that I'm trying to solve is complex itself and a flexible user interface would make the job a lot easier. To continue the image example I posted above, if the "Target" tab and "Proxy" tab were to contain data that you'd like to compare to each other, I'd gladly accept the added complexity of the UI if it allowed me to show them side by side so that I don't have to tab between them constantly. The intended end users are also people who are willing and able to invest the time to familiarize themselves with the interface.

I'll try to make a nice example

**Comment by githubuser0xFFFF** [comment]
CLosed the issue because I do not want to have a lot of open issues.

**Comment by cackaroach** [comment]
I'm looking for an example of CDockContainer or API document, but I couldn't.
@delins, can you show me any of these?

**Comment by jeremyong** [comment]
I am interested in this functionality as well and may have cycles to spare to help with a PR, either from scratch or perhaps starting where @delins left off.

One thing I was considering was not trying to support the notion of widget and dock area affinity based on a declarative interface, which I could see getting complicated quickly. What I was imagining instead was a hook the dock manager invokes when considering each dock area. If a hook is installed, the manager asks, "is the active widget dockable in this area?" and the user can programmatically respond with "yes" or "no." This approach is inherently "opt-in," but gives a fair bit of flexibility (with some tradeoffs of course).

As for the use case, I'm using Visual Studio as a primary reference here. Editor widgets are dockable with editor widgets, but not over areas containing tool widgets. The inverse is not true however. Tool widgets *may* be docked with editor widgets and other tool widgets. This uni-directional dockability is awkward at first, but becomes somewhat intuitive for the user over time, and makes organization of a layout with many hundreds of widgets more tractable.

**Comment by githubuser0xFFFF** [comment]
The idea of a hook sounds interesting because if no hook is installed, the whole system would function like before and so the impact of this change would be very low. You can crate a pull request for this. Please also provide an example or modify the demo application to show and test this feature. I cannot give any guarantee that I will merge the pull request, but if it works well and the changes are small I will likely merge it.

**Comment by delins** [comment]
I've unfortunately not been able to invest more time on this. The idea of hooks sounds interesting. 

I'm concerned though that it will be hard to provide enough context in this hook call to allow the hooked code to make a good assessment. For instance, iirc dock areas can be created dynamically by ads when the user docks a widget by mouse. If your code doesn't get notified of this new area instance, it can become hard to decide whether a widget should be dockable in it. Or you'd perhaps need to iterate through its parents and siblings, which could quickly become bug prone.

This could perhaps be somewhat solved by also creating a `hasDocked` and `hasUndocked` hook (if it doesn't already exist?), where the new dock area instance is given as an argument, if applicable.

**Comment by jeremyong** [comment]
Thanks for weighing in both. I think I'd have to try it out to understand where the complexity would lie. I agree that you'd likely want to have a hook/callback that is invoked if/when a widget drag results in a new dock area (registered on the dock manager). You can imagine creating a dockable widget parent class which you could use to understand the "type" of widget that is about to be docked, and classify the dock area that way. After classification (which could be just a `map` maintained in userspace), you could then either accept or reject subsequent dock requests. I suspect that issues will turn up over the course of implementation though, so if there are other considerations worth keeping in mind, I'm open to any/all feedback.
