### ISSUE TITLE
help me，about splitter

### ISSUE THREAD

**Issue by CrawLovers** [githubuser0xFFFF/Qt-Advanced-Docking-System#423]
I wanted to change the splitter's style so that it could change colors over mouse clicks, but when I wrote the code below, it didn't work.
![1652090131170](https://user-images.githubusercontent.com/39448006/167386422-6b6465ba-c59e-4920-ba8f-94aebe061663.jpg)

**Comment by githubuser0xFFFF** [comment]
I close this issue because it is not ADS related
