### ISSUE TITLE
How do I disable widget floating operations?

### ISSUE THREAD

**Issue by singlebear** [githubuser0xFFFF/Qt-Advanced-Docking-System#426]
I want to be able to drag the widget to customize the layout only in Edit mode, and then the widget cannot be dragged or floated in work mode. How to achieve? I didn't find any instructions in the header file or example. thank you!

**Comment by githubuser0xFFFF** [comment]
You will find the information in the documentation

**Comment by singlebear** [comment]
> You will find the information in the documentation

Hello, I still can't find any option to keep the window fixed and inoperable. I also tried flags in all settable enumerations “eConfigFlag”. Which document is it in?
Maybe you misunderstand what I mean. I want to disable manual dragging of widgets in the interface, just like normal widgets in QT's default layout cannot drag their positions  and float them.

**Comment by singlebear** [comment]
I also tried using the feature "DockWidgetMovable".But it didn't work.

TableDockWidget->setFeature(ads::CDockWidget::DockWidgetMovable,false);

**Comment by delins** [comment]
I think you're looking for `DockWidgetFloatable`, or possibly both it and `DockWidgetMovable` in this instance. You could call "floating" a form of moving too so disabling `DockWidgetMovable` would make sense, but floating specifically has its own flag.
