### ISSUE TITLE
Question: docks inner state save/restore

### ISSUE THREAD

**Issue by paceholder** [githubuser0xFFFF/Qt-Advanced-Docking-System#428]
Hello!

Thanks for this project.

As I understood it, there is no way right now to store the inner state of each displayed CDockWidget, we are able to store just the positions and sizes of sub-widgets.

Imagine, we have a QTextEdit where a user could write some text.
I'd like to be abble to save the text to some QByteArrray and add it to the final xml file.
Upon restoring we'd create QTextEdit again and put the data back to the widget.

I'am looking for something like this:

```
virtual QByteArray CDockWidget::saveState() const;

virtual CDockWidget::restoreState(QByteArrary const &bytes);
```

This is abstract enough to let the user implement own saving and restoring mechanisms.
For example, we could put some json structure to this QByteArray. 
Or we colud store some meta-information to let the plugin system re-create the widgets.

Thanks in advance for any suggestions.

Best,

Dmitry

**Comment by githubuser0xFFFF** [comment]
Hi,

I'm not sure, that I understand your question correctly. I'm not sure, what you mean with "inner state" of each displayed CDockWidget. Do you mean the state of the content widget that is inside of the CDockWidget? The state of the content widget would be application specific.

I also do not completely understand what you mean with "sub-widgets". The ADS stores the splitter hierarchy with all CDockWidgets. The task of the ADS is to place and manage CDockWidgets.

So if you implement an application, then the save and restore functions of ADS should care about the placement of CDockWidgets and you should implement the storage of your widget state separately.

**Comment by paceholder** [comment]
Hello,

yes, by "inner state" I meant, for example, a text stored in a widget embedded into a CDockWidget. And yes it is very application specific.

What would be then the right way to access all the CDockWidgets for extracting/storing the app-specific information before the CDockWidgets placement is saved by `ads`?
Sholud I separately track all the instances of the created CDockWidgets?
And the other way round, when restoring, how to associate app-created widgets with a saved placement configuration?

Maybe a couple of line in the documentation could help.

Thanks a lot for your hints.
