### ISSUE TITLE
When a floating window is already open but obscured raise it when CDockWidget::toggleView is called

### ISSUE THREAD

**Issue by ARSanderson** [githubuser0xFFFF/Qt-Advanced-Docking-System#429]
When a dock widget is open and docked in a tab but that tab is not the current tab calling 

void CDockWidget::toggleView(bool Open)
{
      ...
    else if (Open && d->DockArea)
	{
        d->DockArea->setCurrentDockWidget(this);
    }
}

will make that tab the current tab. However, if the dock widget is open and floating but obscured by other windows calling

d->DockArea->setCurrentDockWidget(this);

just makes the dock widget the current tab and the dock widget is still obscured  by other windows. If the window is floating is should be raised.

A possible fix: when already open add a call to showDockWidget

void CDockWidget::toggleView(bool Open)
{
      ...
    else if (Open && d->DockArea)
	{
        //d->DockArea->setCurrentDockWidget(this); // no longer needed done in showDockWidget
        **d->showDockWidget();**
    }
}

In the showDockWidget if a floating widget add a call to raise it. 

void DockWidgetPrivate::showDockWidget()
{
    ...
		if (Container->isFloating())
		{
			CFloatingDockContainer* FloatingWidget = internal::findParent<
					CFloatingDockContainer*>(Container);
            FloatingWidget->show();
            **FloatingWidget->raise();**
        }
    ...
}

I made these additions and I get the behavior I would expect. When a dock widget is already opened it is raised and can be seen. However, my additions may not be the right path.

**Comment by githubuser0xFFFF** [comment]
Should be fixed in master with commit bedd25021c36819cb6bc5e888e3e0701da23af79. Please test.

**Comment by ARSanderson** [comment]
Danke/Thanks for the quick look and addition of the raise. I have tested and the behavior I would expect.
