### ISSUE TITLE
State Changed Signal

### ISSUE THREAD

**Issue by juangburgos** [githubuser0xFFFF/Qt-Advanced-Docking-System#43]
Hi,

Is there a `stateChaged` (and/or `perspectiveChanged`) signal? The use case is that either if we keep track of perspectives internally (using the existing perspective API) or externally (saving and loading state externally), it would be neat to be able to track the changes in state for reasons:

- To implement undo/redo stack
- To put a star `*` in the current perstective to mark it as dirty, until the perspective state is saved again.

If there is something in the API I can use for that please let me know, or if you could give me some pointers on where in the source code I could start hacking to implement such signal, would be apreciated.

Thanks,

**Comment by githubuser0xFFFF** [comment]
Here are the signals from DockManager class. I think stateRestored() is the signal your are looking for:

```c++
signals:
	/**
	 * This signal is emitted if the list of perspectives changed
	 */
	void perspectiveListChanged();

	/**
	 * This signal is emitted if perspectives have been removed
	 */
	void perspectivesRemoved();

	/**
	 * This signal is emitted, if the restore function is called, just before
	 * the dock manager starts restoring the state.
	 * If this function is called, nothing has changed yet
	 */
	void restoringState();

    /**
     * This signal is emitted if the state changed in restoreState.
     * The signal is emitted if the restoreState() function is called or
     * if the openPerspective() function is called
     */
    void stateRestored();

    /**
     * This signal is emitted, if the dock manager starts opening a
     * perspective.
     * Opening a perspective may take more than a second if there are
     * many complex widgets. The application may use this signal
     * to show some progress indicator or to change the mouse cursor
     * into a busy cursor.
     */
    void openingPerspective(const QString& PerspectiveName);

    /**
     * This signal is emitted if the dock manager finished opening a
     * perspective
     */
    void perspectiveOpened(const QString& PerspectiveName);
```

**Comment by juangburgos** [comment]
Not really because that only tells me when a specific perspective has been restored. What I am looking for is a signal for any minim change in the current state. 

E.g. when a user moved a dock widget to another position. At that point the state does not match any of the currently saved perspectives. So I want to somehow let the user know that the current state has not been saved yet, like displaying a star next to the altered perspective name.

**Comment by githubuser0xFFFF** [comment]
What is your definition of a "minimum/small" change? 

- if the user moves a slider to change the size of a dock widget?
- if the user toggles visibility of a dock widget?
- if the user moves a dock widget?

**Comment by juangburgos** [comment]
I guess my definition would be whatever makes the return value of `CDockManager::saveState` change such that:

```c++
auto byteState1 = my_manager->saveState();

// any "minimum" change

auto byteState2 = my_manager->saveState();

Q_ASSERT(byteState1 != byteState2);
```

**Comment by githubuser0xFFFF** [comment]
Ok, in this case the DockManager needs to detect Move, Resize and Hide / Show events of the DockWidgets. That means, almost every minimum user invention will make the current perspective "dirty". 

Maybe it is better, to say, a perspective is "dirty" if a DockWidget changes its position, docking state or visibility. I would not include any slider movement.

**Comment by juangburgos** [comment]
Yes, of course it would not be wise to continuously emit events while a dockwidget is being dragged, but just once when a new position is settled.
