### ISSUE TITLE
Problem building Debug version of demo and examples on Windows, Qt 6.3.1

### ISSUE THREAD

**Issue by richardjdare** [githubuser0xFFFF/Qt-Advanced-Docking-System#433]
When I try and do a debug build of the project I get the following error 8 times:

LNK1104: cannot open file 'qtadvanceddocking.lib'

I am testing on a fresh, untouched clone of the project running on a new install of Qt 6.3.1 and Qt Creator 7.0.2 on Windows 10, using MSVC2019 64bit Kit. (from Visual C++ 2022)

The Release version works great.

The library does build, but the resulting debug lib is called qtadvanceddockingd.lib. The generated makefiles for the demo and examples all refer to qtadvancedocking.lib without the 'd' on the end.
Here is the relevant part of the generated makefile.DEBUG for the demo application:
```
#############################################################################
# Makefile for building: AdvancedDockingSystemDemo
# Generated by qmake (3.1) (Qt 6.3.1)
# Project:  ..\..\Qt-Advanced-Docking-System\demo\demo.pro
# Template: app
#############################################################################

MAKEFILE      = Makefile.Debug

...

LIBS          = qtadvanceddocking.lib /LIBPATH:D:\projects\build-ads-Desktop_Qt_6_3_1_MSVC2019_64bit-Debug\lib 
QMAKE         = D:\Qt\6.3.1\msvc2019_64\bin\qmake.exe
```

As you can see LIBS is referring to qtadvanceddocking.lib when I think it should be referring to qtadvanceddocking**d**.lib

I tried manually renaming the lib and dll and then building the demo and it worked. 
I will keep looking into this, but I am not an expert on Qmake.

**Comment by githubuser0xFFFF** [comment]
I fixed this in master for you
