### ISSUE TITLE
Add option to update widget minimum size

### ISSUE THREAD

**Issue by tothambrus11** [githubuser0xFFFF/Qt-Advanced-Docking-System#435]
After instantiating a CDockWidget, it's size will be captured and I didn't find any way to tell the dockWidget when the inner widget has a new minimum size. It would be nice to write something like this:
```cpp
myWidget->setMinimumHeight(500);
myDockWidget->updateMinimumSizeHint();
```

**Comment by githubuser0xFFFF** [comment]
Could you please explain your use case? Why would you update the minimum size hint of the dock widget?

Have you checked the `eMinimumSizeHintMode` enum?

```c++
    /**
     * The mode of the minimumSizeHint() that is returned by the DockWidget
     * minimumSizeHint() function.
     * To ensure, that a dock widget does not block resizing, the dock widget
     * reimplements minimumSizeHint() function to return a very small minimum
     * size hint. If you would like to adhere the minimumSizeHint() from the
     * content widget, then set the minimumSizeHintMode() to
     * MinimumSizeHintFromContent.
     */
    enum eMinimumSizeHintMode
    {
    	MinimumSizeHintFromDockWidget,
    	MinimumSizeHintFromContent
    };
```

**Comment by tothambrus11** [comment]
I tried overriding the minimumSizeHint() method in my floating widget's class like this:
```cpp

QSize BuildAndDeploy::minimumSizeHint() const {
    if(collapsed){
        return {600, 150};
    }
    return {600,400};
}
```
My custom widget itself seem to correctly hold it's minimum size at 600x400 after expanding the section because the bottom margin area goes outside of the window's border when I resize the window to a smaller size.

**Comment by tothambrus11** [comment]
Is there an option to set a window widget's size manually?

**Comment by githubuser0xFFFF** [comment]
So you would like to have a minimum size for your dock widget? Normally it is recommended to not use a minimum size to avoid blocking the splitter resizing in ADS.

Could you please provide a small sample app that shows what you want? Just create a branch and create a sample app in the examples folder and then create a pull request.

**Comment by tothambrus11** [comment]
Oh, you are right, setting the minimum height may not be the best option. Making things simpler, it would be enough if I could set the floating window's current size programmatically. It could be resized smaller - that's not a big problem, but at least the window would be resized automatically to contain the expanded section.

**Comment by githubuser0xFFFF** [comment]
I close this issue because I will not going to implement it.
