### ISSUE TITLE
nonfunctional feature: CDockWidget::DockWidgetFeature::CustomCloseHandling

### ISSUE THREAD

**Issue by bjb-work** [githubuser0xFFFF/Qt-Advanced-Docking-System#436]
The enum `CDockWidget::DockWidgetFeature`'s variant `CustomCloseHandling` doesn't seem to work as intended. The CDockWidget does not emit the signal specified in the documentation when closing (signal: `CDockWidget::closeRequested`).

To reproduce:
```
dock_widget->setFeatures(ads::CDockWidget::DockWidgetClosable | ads::CDockWidget::CustomCloseHandling);
QObject::connect(dock_widget, &ads::CDockWidget::closeRequested, []{qDebug() << "signal closeRequested emitted properly";});
```
build, run, close the dock widget. It does not print the message

**Comment by githubuser0xFFFF** [comment]
The demo application uses custom close handling - could you test if it works in the demo application?

**Comment by bjb-work** [comment]
hmmm, that one does seem to work. Let me try to figure out what's wrong with my test program I made... One minute

**Comment by bjb-work** [comment]
I found the difference that makes my example work.

`CDockWidget::DockWidgetFeature::DockWidgetDeleteOnClose` must also be set for the signal to be emitted.

I wouldn't think that's intended behavior, but at the very least it'd be nice to have that mentioned in the comment for the `CustomCloseHandling` variant
