### ISSUE TITLE
closeRequested not emit'ed without DockWidgetFeature::DockWidgetDeleteOnClose

### ISSUE THREAD

**Issue by bjb-work** [githubuser0xFFFF/Qt-Advanced-Docking-System#437]
If you want to implement custom close handling via setting the CDockWidget feature `CDockWidget::DockWidgetFeature::CustomCloseHandling`, you must also set the feature `CDockWidget::DockWidgetFeature::DockWidgetDeleteOnClose`. Without `DockWidgetDeleteOnClose`, the signal `CDockWidget::closeRequested` is not emit'ed.

**Comment by githubuser0xFFFF** [comment]
Thank you for this tip. Please create a pull request to get this into the documentation.
