### ISSUE TITLE
CustomCloseHandling: how stop CFloatingDockContainer to close ?

### ISSUE THREAD

**Issue by stephanebertrand** [githubuser0xFFFF/Qt-Advanced-Docking-System#440]
hi,

i can decide to close or not a CDockWidget with CustomCloseHandling flag and closeRequested connection.

But with a floating CDockWidget, when i close the widget/CFloatingDockContainer, the signal is emit, but i can stop to hide ( or destroy ? ) the window.

Thx for your help

**Comment by githubuser0xFFFF** [comment]
Should be fixed now in master with commit a0f0640c9f487bf9643ea5ee486d1a1ce9c15a1b
