### ISSUE TITLE
Icon on floating window

### ISSUE THREAD

**Issue by OgreTransporter** [githubuser0xFFFF/Qt-Advanced-Docking-System#441]
When I start the demo project on Windows, the calendar tabs all have an icon. When I drag a tab away as a floating window, the icon disappears. It would be helpful if the floating window takes either the icon of the application, the one of the tab or if you can set it yourself somehow.

<img width="993" alt="adsdemo" src="https://user-images.githubusercontent.com/8941090/182608239-ca123b2d-5ae3-4f7f-9987-b7550cf1b089.png">

**Comment by githubuser0xFFFF** [comment]
Please have a look into the documentation regarding this issue: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#floatingcontainerhaswidgeticon
