### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by ShalokShalom** [githubuser0xFFFF/Qt-Advanced-Docking-System#442]
Hi - the marketplace has version 3.0 as the latest release, you might wanna look into this. 

https://marketplace.qt.io/products/advanced-docking-system

There is no update since 2020, as you can see:

Thanks a lot for your work!

**Comment by githubuser0xFFFF** [comment]
Thank you. I know this and already requested an update but the Qt team is apparently not able to update that.

**Comment by ShalokShalom** [comment]
I wrote them an email, let`s see if anything comes back. Pretty crude, thanks.
