### ISSUE TITLE
Main window shows frame buffer artifacts when moving a dock widget across floating dock widget border

### ISSUE THREAD

**Issue by iam-peter** [githubuser0xFFFF/Qt-Advanced-Docking-System#445]
I found an issue on Linux and Windows (didn't test it on macOS) that when dragging a DockWidget across the borders of a floating DockWidget there is one frame where the rendering of the main window is wrong (see the second image frame00153). I found this while testing QtDesignStudio. In there the flickering is more noticeable probably because the rendering of the main window takes longer than the one in the demo application.

I use Qt 6.3.1.

How to reproduce:

1. Open the demo
2. Drag the floating dock widget (My Calender 2) on top of the main window as seen in the screenshots
3. Grab one of the main window dock widgets (Calender 0)
4. Hold it on top of the floating widget
5. Move it outside (on top of the main window) and inside (on top of the floating widget) repeatedly

While moving across the floating widget border the flickering should happen.

I found a fix for it. In `CDockOverlay::showOverlay` before resizing the overlay it needs to be hidden by calling `hide()`.

![frame00152](https://user-images.githubusercontent.com/7542157/184651581-b4a75763-e05d-43bc-8fd6-329648f895b0.jpg)
![frame00153](https://user-images.githubusercontent.com/7542157/184651587-0a17cdf4-fc64-403b-b49b-68fb9fc91ad3.jpg)
![frame00154](https://user-images.githubusercontent.com/7542157/184651589-209fbaf3-38d5-43d5-a59a-10882baf7aa8.jpg)

**Comment by githubuser0xFFFF** [comment]
Thank you Henning for reporting this.  I will try to fix this.

**Comment by iam-peter** [comment]
You saw that the fix is already included in the issue?

In `CDockOverlay::showOverlay` before resizing the overlay it needs to be hidden by calling `hide()`.
```
// Move it over the target.
hide();
resize(target->size());
```
Just making sure you're not gone that as much time on it as I did :)

**Comment by githubuser0xFFFF** [comment]
I just tested with MinGW and Qt 5.15 and could not reproduce the proplem. I will now try 6.3.1.

**Comment by githubuser0xFFFF** [comment]
I could not reproduce the problem with Qt 6.3.1 and MSVC 2019 but I implemented your proposed patch.
