### ISSUE TITLE
Is the ABI expected to be broken with each release?

### ISSUE THREAD

**Issue by dkogan** [githubuser0xFFFF/Qt-Advanced-Docking-System#448]
Hi. I'm packaging this for Debian. Looking at the latest release (3.8.3) currently. The build is set up to use the full version "3.8.3" in the SONAME in the shared object. This implies that the ABIs are expected to be completely unstable, and that binaries built against 3.8.3 will not run against 3.8.4. Is this what's intended. The usual case tries to preserve stability, and the major version signifies ABI breaks; if that's the intent, then the SONAME should contain "3" as the version, not "3.8.3". Can you please clarify?

Thanks

**Comment by githubuser0xFFFF** [comment]
I'm on Windows and therefore I have to admit that I did not care about this until your question.  The Cmake files are a third party contribution.

**Comment by dkogan** [comment]
I can patch the build if you tell me what the ABI stability goal is. All 3.x releases are supposed to have a stable ABI. And API. Right?

**Comment by githubuser0xFFFF** [comment]
No, currently there is no ABI and API stability guarantee. Every pull request or fix may change ABI and API.

**Comment by dkogan** [comment]
Thanks for clearing that up. Would you consider tightening that at some point? Stable interfaces reduce the maintenance burden placed on the users of the library.

**Comment by githubuser0xFFFF** [comment]
Yes,  I would consider this. Could you please explain,  how this works?  That means,  when is it allowed to change ABI an API?

**Comment by dkogan** [comment]
Hi. The API is the human interface to the library. If I write a program that can be built with QADS 3.8.3, and the API is then broken for 3.8.4, then my program won't build anymore, and I have to then fix it. If the API didn't break, then I, as a user, don't care: I can still build against the later version of QADS.

The ABI is similar, but for built binaries and dynamic linking. If the ABI didn't break between 3.8.3 and 3.8.4, then my binary executable will be able to run with the newer version of the library, and I don't have to rebuild. The way the QADS cmake build is set up currently, even if you didn't break the ABI, existing binaries STILL won't be runnable against a later version of the library: the SONAME is currently set to "3.8.3" and not "3", so a library update will produce a mismatched SONAME. The SONAME is supposed to indicate an ABI version: same SONAME, compatible ABI.

Note that this isn't a Linux-specific thing. Windows and all the others have this all too, but with different names for things.

There are tools to check for ABI breakage: abi-compliance-checker for instance. Also, I just packaged and pushed QADS 3.8.3 into Debian as it is. If you officially stabilize the interfaces for the next release, that'd be awesome.

**Comment by githubuser0xFFFF** [comment]
But when can I break the ABI?  When I go from 3.8.3 to 3.8.4 or when I go from 3.8 to 3.9 or when I go from 3 to 4? And when can I break API?

**Comment by dkogan** [comment]
Hi. The usual convention is that the major version (the "3" in 3.8.4 or the "5" in Qt5) is the ABI version used in the soname, and both the ABI and API are stable within that major version. You can add stuff to the interfaces without breaking anything, but you cannot change existing interfaces, because somebody might be using them. C++ makes it easy to break your interfaces by accident, so the abi-compliance-checker tool becomes very useful.
