### ISSUE TITLE
bspwm: docking indicators not showing / cannot dock

### ISSUE THREAD

**Issue by Tectu** [githubuser0xFFFF/Qt-Advanced-Docking-System#451]
Hi,

I'm experiencing an issue when using QtADS within the [bspwm](https://github.com/baskerville/bspwm) window manager: When I start dragging a dock, the indicators which show where the dock will be docked to (the area where you drop it into) do not show up. This does not appear to be only a visual issue as even if I try really hard to "eyeball" where the being-dragged dock needs to be dropped I can't get it to dock.
I can successfully undock a dock by dragging it but I can never re-dock it anywhere.

While this issue seems to be specific to using bspwm as the window manager I'd like to understand what is going on and potentially fixing the issue (either on QtADS side or the bspwm side - depending on what is going wrong).

This is a bit of an open question but: Does anybody have any idea what could be going on or point me towards a rough direction where I should start digging?

**Comment by githubuser0xFFFF** [comment]
The bspwm window manager is not supported. Only vanilla Ubuntu 18.04 and 20.04 is currently supported

**Comment by Tectu** [comment]
> Linux is really a mess tired_face

I'm not using Linux but yes - I fully agree; -)

> The bspwm window manager is not supported yet. 

I understand. I would be very open to help getting this sorted out. I was hoping that you could point me towards specific pieces of codes involved in this mechanism so I could try figuring out whether this issue needs fixing on the QtADS or bspwm side.

**Comment by githubuser0xFFFF** [comment]
There are two functions that handle the update of the drop overlays and that find out the drop container. If you drag floating widget, then this is handled in the `CFloatindDockContainer::updatedeDropOverlays` function:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/FloatingDockContainer.cpp#L511-L585

If you drag a docked widget, then this is handled in the function `CFloatingDragPreview::updateDropOverlays`:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/FloatingDragPreview.cpp#L79-L174

The painting of the overlays and the drag preview icons is handled in the `CDockOverlay` class.
