### ISSUE TITLE
how to change skin

### ISSUE THREAD

**Issue by itisyang** [githubuser0xFFFF/Qt-Advanced-Docking-System#455]
my program has two skins.
when i changed skin using "m_dockmanager->setStyleSheet", nothing happened.
but "detach group" after "setStyleSheet", it works.
could you help me?

**Comment by githubuser0xFFFF** [comment]
If you would like to change the skin of your application, you should first disable the internal dock manager stylesheet:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#disabling-the-internal-style-sheet

Then you should set the stylesheet of your application:

https://doc.qt.io/qt-6/qapplication.html#styleSheet-prop
