### ISSUE TITLE
Windows: Support FloatingContainerForceQWidgetTitleBar

### ISSUE THREAD

**Issue by Axil-ww** [githubuser0xFFFF/Qt-Advanced-Docking-System#456]
Currently, non-native TitleBars are only available for Linux. Nothing prevents us from making them for other platforms as well. I tried it and it works for Windows too. (If remove the Linux-specific features under the define)

**Comment by githubuser0xFFFF** [comment]
That sounds great. Feel free to create a pull request. If you implement non-native TitleBars for Windows then please ensure that features like snapping to screen borders that are supported by native TitleBars also work with non native TitleBars.

**Comment by Axil-ww** [comment]
Yes, snapping to screen borders doesn't work. But it seems to me that the ability to make custom TitleBars is more important than those features. Moreover, it is optional and controlled by FloatingContainerForceQWidgetTitleBar flag.

I'm afraid to create pull request and break something for other platforms. I just removed some #ifdef Q_OS_LINUX in DockFocusController.cpp , FloatingDockContainer.cpp/.h and added #ifdef for Linux-specifics.

**Comment by githubuser0xFFFF** [comment]
Ok, I understand your concerns and close the issue for now. At this time I have no requests from other users for this feature.
