### ISSUE TITLE
The close button on active tab looks weird when using a qss styling file

### ISSUE THREAD

**Issue by pinojojo** [githubuser0xFFFF/Qt-Advanced-Docking-System#457]
Hi, I am using an example with qss file for styling. And also internal style is disabled with ` DockManager->setStyleSheet("")`. then I found that the close button looks a little overly large makes itself not fit in that tab area.

What I want to know is how to fix this and make it look like a normal size close button. Thanks in advance

![image](https://user-images.githubusercontent.com/83955592/198835272-22c69767-048e-4b9f-b181-21336ad6174c.png)

by the way, if not using ` DockManager->setStyleSheet("")` , the tab area looks like this
![image](https://user-images.githubusercontent.com/83955592/198835870-50510529-f7c0-4c97-888f-77630b6e5e9f.png)

**Comment by githubuser0xFFFF** [comment]
Please have a look into the internal Stylesheets to learn how to style the tab button
