### ISSUE TITLE
Tabs menu button not displayed

### ISSUE THREAD

**Issue by ma-robox** [githubuser0xFFFF/Qt-Advanced-Docking-System#461]
I have a problem where, in an area with too many tabs to display them all, the tabs menu button is not displayed.
I have seen that the problem is due to the fact that my tabs' titles are not elided, so the visualization is not triggered (CDockAreaTitleBar::markTabsMenuOutdated()).

My proposal is the following:
```c++
void CDockAreaTitleBar::markTabsMenuOutdated()
{
	if(DockAreaTitleBarPrivate::testConfigFlag(CDockManager::DockAreaDynamicTabsMenuButtonVisibility))
	{
		bool hasElidedTabTitle = false;
		bool hasHiddenTab = false;
		for (int i = 0; i < d->TabBar->count(); ++i)
		{
			if (!d->TabBar->isTabOpen(i))
			{
				continue;
			}
			CDockWidgetTab *Tab = d->TabBar->tab(i);
			if (Tab->isTitleElided())
			{
				hasElidedTabTitle = true;
				break;
			}
			if (Tab->visibleRegion().isEmpty())
			{
				hasHiddenTab = true;
				break;
			}
		}
		bool visible = (d->TabBar->count() > 1) && (hasElidedTabTitle || hasHiddenTab);
		QMetaObject::invokeMethod(d->TabsMenuButton, "setVisible", Qt::QueuedConnection, Q_ARG(bool, visible));
	}
	d->MenuOutdated = true;
}
```

**Comment by githubuser0xFFFF** [comment]
How did you disable the elided tab text?

**Comment by ma-robox** [comment]
Thanks for the input, I forgot we added a minimum character limit for the ElidingLabel, we wanted bigger tabs, ragardless of their number, because many of our windows start with the same name, so eliding them makes it difficult to tell them apart; that's why our menu button did not appear, the tabs were never elided, because in my test case, the windows titles were shorter than our minimum.

**Comment by githubuser0xFFFF** [comment]
Thank you for this information. Currently I cannot change the library, because it works as it is. If you would like to provide a eliding limit or turn eliding on and off, then please provide a pull request. 

Then in a second step, you could provide a pull request that fixes the tabs menu button issue.
