### ISSUE TITLE
programmatically inserting a tab at a given index

### ISSUE THREAD

**Issue by FelixBer** [githubuser0xFFFF/Qt-Advanced-Docking-System#462]
Hi and thanks for the great library!

I would like to insert/create a widget into a `CDockAreaWidget` at/after a given index.
Specifically I want to create a new tab next to the currently visible tab, rather than at the end, which is what `CDockAreaWidget::addDockWidget` does.
It looks like `CDockAreaWidget::insertDockWidget` might do this, but it's not exposed and cant be called directly as-is.

Is this possible with the current API? I could not find a good way.
If not I would like to implement this feature in the next weeks and would love to hear any input you might have.
Thanks!

**Comment by githubuser0xFFFF** [comment]
@FelixBer 

I implemented this functionality in [insert_tab_at](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/insert_tab_at) branch. You can insert a dockwidget with a tab index with the new function `CDockManager::insertDockWidgetTabIntoArea()`:

```c++
	/**
	 * This function will inserts the given Dockwidget to the given DockAreaWidget
	 * as a new tab at the given index.
	 * If index is out of range, the tab is simply appended. Otherwise it is inserted at the specified position.
	 */
	CDockAreaWidget* insertDockWidgetTabIntoArea(CDockWidget* Dockwidget,
		CDockAreaWidget* DockAreaWidget, int Index = -1);
```

I also added a test to the demo application. Just click the **Create Editor Tab** button in the toolbar. The new editor will be inserted as first tab.

Please test the functionality. If everything is o.k., I will merge it into master.

**Comment by githubuser0xFFFF** [comment]
@FelixBer I updated the branch according to your suggestion. Please test.

**Comment by FelixBer** [comment]
perfect! can be merged. :+1:

**Comment by githubuser0xFFFF** [comment]
Merged
