### ISSUE TITLE
Feature Request: Animated tab re-ordering

### ISSUE THREAD

**Issue by mborgerson** [githubuser0xFFFF/Qt-Advanced-Docking-System#464]
It would be nice to support dragging a tab into some particular spot in the tab bar and having other tabs animate around it, similar to Firefox, Chrome, etc.

**Comment by githubuser0xFFFF** [comment]
I will not spend any time on this - sorry

**Comment by mborgerson** [comment]
Would you accept a PR for it? If yes, keeping the issue open with a help-wanted label seems reasonable

**Comment by githubuser0xFFFF** [comment]
No - I don't think so. It adds complexity for no improvement in functionality.
