### ISSUE TITLE
Feature Request: Context menu actions to close tabs to the {left, right}

### ISSUE THREAD

**Issue by mborgerson** [githubuser0xFFFF/Qt-Advanced-Docking-System#465]
Similar to Firefox, it would be nice to have context menu items to close tabs to the left or right of the current tab.

**Comment by githubuser0xFFFF** [comment]
Maybe in the future

**Comment by mborgerson** [comment]
Would you accept a PR for it? If yes, keeping the issue open with a help-wanted label seems reasonable

**Comment by githubuser0xFFFF** [comment]
Yes, I will accept a pull request but I close the issue because I do not want to have a lot of open issues nobody cares about.
