### ISSUE TITLE
How to get DockWidgetArea? 

### ISSUE THREAD

**Issue by Axil-ww** [githubuser0xFFFF/Qt-Advanced-Docking-System#472]
Hi, it's me again with questions.

In my project, the panels are dynamic. I do saveState/restoreState when closing/opening the application. But this is not all that is needed. It is necessary that each dynamic panel save its side and size after closing this panel, and restore it later.
I'm trying to make that the side of the docking (DockWidgetArea) and the size are remembered (in map) for the panels by their title.
But I can't do it.

- CDockWidget knows nothing about doking side and does not send a signal about its change.
- CDockManager does not send any signal that some panel has changed side (the user moved the panel).

**Comment by githubuser0xFFFF** [comment]
Hm, I think this is not possible yet - sorry.
