### ISSUE TITLE
ads::CDockManager::saveState() sporadically leads to crash

### ISSUE THREAD

**Issue by oddcitizenape** [githubuser0xFFFF/Qt-Advanced-Docking-System#476]
It's not entirely clear to me what makes the error intermittent, but every now and then the method crashes the application because a nullptr is accessed by the CAutoHideSideBar::tabCount() method. The call looks like this:

1   ads::CAutoHideSideBar::tabCount AutoHideSideBar.cpp     322 0x7ff736aa64fe 
2   ads::DockContainerWidgetPrivate::saveAutoHideWidgetsState DockContainerWidget.cpp 911  0x7ff736a4a8c2 
3   ads::CDockContainerWidget::saveState DockContainerWidget.cpp 1788 0x7ff736a46839 
4   ads::CDockManager::saveState DockManager.cpp         720  0x7ff736a69ea3 
5   Dashboard::storeSettingsToFile dashboard.cpp           185  0x7ff73674585d 
<...>

According to the debugger, at the time of the crash, the pointer to CAutoHideSideBar in the DockContainerWidgetPrivate::saveAutoHideWidgetsState(QXmlStreamWriter& s) method is null
So here: 

```
DockContainerWidgetPrivate::saveAutoHideWidgetsState(QXmlStreamWriter& s)
{
for (const auto sideTabBar : SideTabBarWidgets.values())
    {
		if (!sideTabBar->tabCount())
		{
			continue;
		}

		sideTabBar->saveState(s);
    }
}
```

Should the method look like this?

```
DockContainerWidgetPrivate::saveAutoHideWidgetsState(QXmlStreamWriter& s)
{
for (const auto sideTabBar : SideTabBarWidgets.values())
    {
		if (!sideTabBar || sideTabBar->tabCount())
		{
			continue;
		}

		sideTabBar->saveState(s);
    }
}
```

**Comment by githubuser0xFFFF** [comment]
@oddcitizenape  I just had a quick look into the source code, and I I have now idea how this could happen. The SideTabBarWidgets are created in the `CDockContainerWidget::createSideTabBarWidgets()`.

```c++
//============================================================================
void CDockContainerWidget::createSideTabBarWidgets()
{
	if (!CDockManager::testAutoHideConfigFlag(CDockManager::AutoHideFeatureEnabled))
	{
		return;
	}

	{
		auto Area = SideBarLocation::SideBarLeft;
        d->SideTabBarWidgets[Area] = new CAutoHideSideBar(this, Area);
		d->Layout->addWidget(d->SideTabBarWidgets[Area], 1, 0);
	}

	{
		auto Area = SideBarLocation::SideBarRight;
        d->SideTabBarWidgets[Area] = new CAutoHideSideBar(this, Area);
		d->Layout->addWidget(d->SideTabBarWidgets[Area], 1, 2);
	}

	{
		auto Area = SideBarLocation::SideBarBottom;
        d->SideTabBarWidgets[Area] = new CAutoHideSideBar(this, Area);
        d->Layout->addWidget(d->SideTabBarWidgets[Area], 2, 1);
	}

	{
		auto Area = SideBarLocation::SideBarTop;
        d->SideTabBarWidgets[Area] = new CAutoHideSideBar(this, Area);
        d->Layout->addWidget(d->SideTabBarWidgets[Area], 0, 1);
	}
}
```

The parent of each `CAutoHideSideBar` is the dock container widget. That means, only if the dock container widget is deleted, the side bar widgets will get deleted. There is no other place in the code, that deletes the SideTabBarWidgets. So maybe something is wrong in your application.

You could set a breakpoint into the  `CAutoHideSideBar` destructor to find out, when a CAutoHideSideBar will get deleted.
