### ISSUE TITLE
Dock in dock floating problem

### ISSUE THREAD

**Issue by manaf2525** [githubuser0xFFFF/Qt-Advanced-Docking-System#479]
https://user-images.githubusercontent.com/7190406/212890244-4fbfb8d4-aa0a-4d23-9a10-237a36412c32.mp4

when float 2 group widgets side by side it will create new window. on centos linux this window cannot be closed.

**Comment by manaf2525** [comment]
can i set some config flags in a way that top level widgets only dock in center area?

**Comment by githubuser0xFFFF** [comment]
The dock in dock feature is a very exotic feature requestet and imlemented by a user. That means it is not very well tested and not very often used so it may have some issues (see #308). Maybe you can ask the implementer jporcher about this issue.

Regarding centos - this is not a supported platform. Only Windows, Ubuntu and MacOs are supported currently.

> can i set some config flags in a way that top level widgets only dock in center area?

No, there is no such flag
