### ISSUE TITLE
Keep one area open impossible

### ISSUE THREAD

**Issue by stijnherfst** [githubuser0xFFFF/Qt-Advanced-Docking-System#48]
I would like to emulate the exact behaviour that Visual Studio has in that opening a file will always open it in the same area and just adds tabs there. I tried emulating this behaviour, but CDockAreaWidgets seem to close or be deleted once all the tabs are removed from it. 

	if (dock_area == nullptr) {
		dock_area = dock_manager->addDockWidget(ads::RightDockWidgetArea, dock_tab, dock_area);
	} else {
		dock_manager->addDockWidget(ads::CenterDockWidgetArea, dock_tab, dock_area);
	}

It seems like it's impossible to have this behaviour.

**Comment by githubuser0xFFFF** [comment]
Yes, this is right. If all dock widgets are removed from a dock area, the dock area will be deleted. If you just close the dock widget, then the dock area will only be closed and the dock widget will be opened in the same position.

**Comment by stijnherfst** [comment]
Would you consider this feature again seeing as how it would work well with the newly introduces `DockWidgetDeleteOnClose` to make this library perfect for source code editors. I tried making some changes myself in the source and had some progress, but ended up hitting some problem with signals that I couldn't debug. Would be much appreciated!
