### ISSUE TITLE
Mac: Floating widgets don't stay on top of the main window

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#480]
Pulled latest changes to try them out and without touching anything I can see it is broken.
There are extra overlay indicators in the middle of the demo application that should't be there, because they don't match any widget bellow them. Trying to dock on them makes the widgets disappear completely.
![Kapture 2023-01-17 at 13 22 42](https://user-images.githubusercontent.com/1664301/212919598-593f6109-4251-4171-ba03-83e2c451efed.gif)
This is reproducible in mac. It doesn't happen on the windows build and I haven't tried linux.

**Comment by rolivav** [comment]
In contrast this is how it looks on the version that I have currently on my project (commit de05ddd20391d64ae6b31ed9d9259e79fdafc75f ).
![Kapture 2023-01-17 at 16 25 00](https://user-images.githubusercontent.com/1664301/212939271-926c9f56-8ddc-428c-b02c-1ebfd55cad16.gif)

**Comment by rolivav** [comment]
I will try to hunt down the commit that introduced the issue.

**Comment by rolivav** [comment]
It is also present in 3.8.4

**Comment by rolivav** [comment]
Found it! It was introduced by 2afe62ec.

**Comment by rolivav** [comment]
So it seems that this will mostly only happen in the demo application, because of this code 
```cpp
    // Test hidden floating dock widget
    DockWidget = createLongTextLabelDockWidget();
    DockManager->addDockWidgetFloating(DockWidget);
    DockWidget->toggleView(false);

    // Test visible floating dock widget
    DockWidget = createCalendarDockWidget();
    DockManager->addDockWidgetFloating(DockWidget);
```
It seems that for some reason the overlay is interpreting that there is still a widget floating there.

**Comment by rolivav** [comment]
Aaaah the bug has nothing to do with that. It is about z ordering. The widget is actually there, but it is in behind the main window.
The problem in Mac is that the floating widgets do not stay on top of the main window.

**Comment by rolivav** [comment]
I found the custom solution you made for linux and I think a similar thing needs to be done for mac. I can try to set the Qt::WindowStaysOnTop, but from your comments I think there is a high chance that it will not work. I'll give it a spin.

**Comment by derekvantonder** [comment]
I've seen this too

**Comment by githubuser0xFFFF** [comment]
I close this issue because there seems no intense interest from any Mac user to close the issue so it does not seem to be a real issue for Max users.
