### ISSUE TITLE
Undocking an autohide dock widget does not close the AutoHideTab from the sidebar

### ISSUE THREAD

**Issue by ma-robox** [githubuser0xFFFF/Qt-Advanced-Docking-System#481]
Dragging an autohide dock widget, and undocking it, does not remove its AutoHideTab from the side bar and the  tabs opens an empty dock area.

https://user-images.githubusercontent.com/103563337/213423741-56b08d0d-f435-49f8-b160-b6ca58e2606e.mp4

**Comment by githubuser0xFFFF** [comment]
I just tested the demo application of the master branch on Windows and Ubuntu 20.04 and can not reproduce or confirm the poblem so this seems to be an problem with your application.

Have you tested the demo application?

**Comment by ma-robox** [comment]
Not yet, but I will.

**Comment by ma-robox** [comment]
I managed to reproduce my bug with these settings:
```
CDockManager::setConfigFlags(CDockManager::DefaultOpaqueConfig);
CDockManager::setConfigFlag(CDockManager::DockAreaHideDisabledButtons, true);
CDockManager::setConfigFlag(CDockManager::DockAreaDynamicTabsMenuButtonVisibility, true);
CDockManager::setConfigFlag(CDockManager::DockAreaHasCloseButton, true);
CDockManager::setConfigFlag(CDockManager::OpaqueUndocking, true);
CDockManager::setConfigFlag(CDockManager::EqualSplitOnInsertion, true);
CDockManager::setConfigFlag(CDockManager::FocusHighlighting, true);
CDockManager::setConfigFlag(CDockManager::FloatingContainerHasWidgetTitle, true);
CDockManager::setConfigFlag(CDockManager::FloatingContainerHasWidgetIcon, true);

CDockManager::setAutoHideConfigFlags(CDockManager::DefaultAutoHideConfig);
CDockManager::setAutoHideConfigFlag(CDockManager::AutoHideButtonCheckable, true);
CDockManager::setAutoHideConfigFlag(CDockManager::AutoHideButtonTogglesArea, true);
```

**Comment by githubuser0xFFFF** [comment]
Ok, I will check this - BTW. I recommend to disable this flag because ir is more userfriendly.

**Comment by githubuser0xFFFF** [comment]
Btw. could you please send me a nice screenshot (1920 x 1080) of the Robox Development Environment, that shows that it uses the Advanced Docking System. I would like to have it on my showcase section. Thank you.

**Comment by githubuser0xFFFF** [comment]
I have fixed the issue.

**Comment by ma-robox** [comment]
I'll try to send you the screenshot soon. We also decided to drop the OpaqueUndocking, it is cleaner on the user side of things.

**Comment by githubuser0xFFFF** [comment]
@ma-robox That would be great. I just removed `OpaqueUndocking` completely from ADS so it is not available anymore.

**Comment by githubuser0xFFFF** [comment]
Thank you
