### ISSUE TITLE
perspectives not working as intended?

### ISSUE THREAD

**Issue by antrwells** [githubuser0xFFFF/Qt-Advanced-Docking-System#484]
Hi,

I've tried everyway I can think of, and none of the methods I tried work.

Here is my code,

`void MainWindow::saveWindowLayout()
{
    QSettings settings(
                QSettings::IniFormat,
                QSettings::SystemScope,
                "settings",
                "user");
    dockManager->addPerspective("custom");
    dockManager->savePerspectives(settings);
}`

to save,

then,

`void MainWindow::restoreWindowLayout()
{
    QSettings settings(
                QSettings::IniFormat,
                QSettings::SystemScope,
                "settings",
                "user");
    dockManager->loadPerspectives(settings);
    dockManager->openPerspective("custom");
}`

to load,

but all that is happens is, when I load the layout, all my widgets disappear except for my toolbar, which is not one of the docked widgets anyway.

Am I missing something? I can provide more of my code if needed.

**Comment by githubuser0xFFFF** [comment]
Does perspective loading works in the demo application?

**Comment by antrwells** [comment]
I have only used your library in my own app.  Could it be that I have the DockManager used in a sub widget, not the main window? Other than that, your lib works as intended.

**Comment by githubuser0xFFFF** [comment]
Please check te demo application to learn how to save and load perspectives.
