### ISSUE TITLE
Undocking QVTKOpenGLNativeWidget error on Linux (Ubuntu 20.04 and 22.04)

### ISSUE THREAD

**Issue by kirchhoefer1288** [githubuser0xFFFF/Qt-Advanced-Docking-System#488]
We use your docking framework in combination with vtk and on windows everything works fine.

However, on linux (Ubuntu 20.04 and 22.04) we see strange things when undocking the widget containing a QVTKOpenGLNativeWidget, i.e. the previously docked widget still persists like a "burn in" in the gui but the floating widget also opens.    
After that the gui completely gets "scrumbled" when we try to resize move or dock/undock anything.

We only get the following warnings from Qt:
```
QOpenGLContext::makeCurrent() called with non-opengl surface   
QRhiGles2: Failed to make context current. Expect bad things to happen.
```

As soon as we remove this dock widget from the app everything works fine

**Comment by githubuser0xFFFF** [comment]
I have given up fixing things for Linux. Like you can see in the issues list, 90% of all reported issues are Linux issues because of the heterogeneous Linux environment with different window managers, compositors and supported features.

Would be great, if you could try to fix the issue and create a pull request for this project. I work mainly on Windows and do not have any time (and motivation) to fight with the Linux mess any longer.

Sorry

**Comment by kirchhoefer1288** [comment]
Ok

Currently it seems that the problems arise when I try to undock from the main window.  
It looks like the old "docked" window cannot be deleted properly and thus stays visible. 
The problem does not occur when I start the widget floating and then dock it.

Can you point me to the position in your code where the docked widget is deleted during undocking?

**Comment by githubuser0xFFFF** [comment]
@kirchhoefer1288 The functions `CDockContainerWidget::removeDockArea` or `CDockContainerWidget::removeDockWidget` are the functions where the dock widget is removed from its old dock area / container. If you drag the last tab of a dock area into a floating widget then `CDockContainerWidget::removeDockArea` is called and when you drag a widget from a dog area with some more visible tabs, then `CDockContainerWidget::removeDockWidget` is called.

**Comment by kirchhoefer1288** [comment]
We "solved" the problem by using a  QVTKOpenGLStereoWidget instead of  a QVTKOpenGLNativeWidget.

We do not exactly know what the real problem was, but  according to the VTK documentation the difference is that QVTKOpenGLNativeWidget is a "native widget" and QVTKOpenGLStereoWidget is not. 
https://vtk.org/doc/nightly/html/classQVTKOpenGLStereoWidget.html

This somehow seems to change the behaviour the opengl context rendering.

So, we are now fine with using QVTKOpenGLStereoWidget and I will mark the issue as closed, although we didn't find the actual cause of the problem
