### ISSUE TITLE
Have a panel start docked?

### ISSUE THREAD

**Issue by JosephCoppola-FW** [githubuser0xFFFF/Qt-Advanced-Docking-System#49]
So I have a default perspective set up to load on start if my app sees this is the first time the user has opened the app ever. I also have some panels not a part of this default perspective. 

I add all the panels on start to the docking manager, then load the default perspective. After that, if a user opens a non default panel, the panel starts floating rather than docked where I originally told it to dock in code. Is it possible to have a panel open docked the first time opening it?

Thanks,

Joe

**Comment by githubuser0xFFFF** [comment]
Currently loading a perspective means, that the complete layout will be destroyed. All dock widgets that are defined in the perspective, will be put into the right position. All dock widgets that are not defined in the perspective will be hidden and starts floating if the user shows it.

That is the current implementation state. So if you do not change the implementation, it is not possible to show a widget docked that was not part of a perspective.

**Comment by JosephCoppola-FW** [comment]
@githubuser0xFFFF 

Ok that is fine. I've noticed that I can save a perspective with the panels added but closed. So when that perspective is loaded later, and the panel is toggled open, the panel will be docked correctly. But the panel opens at a very small size, rather than the size it was when closed. Is this expected behavior?

**Comment by githubuser0xFFFF** [comment]
I have not tested this yet but I noticed the following. If I have a layout with a dock widget DockWidget1 and I load a perspective that does not contain the DockWIdget1, then the DockWidget1 will be hidden. This is the intended functionality. If I no show the DockWidget1 again via the toggleView signal, then the DockWidget1 is shown with the last size that it had in the dock layout prior to loading the perspective. Maybe this is not the best solution and it would be better to open the DockWidget1 with a default size.
