### ISSUE TITLE
Release new version of PyQt5 binding?

### ISSUE THREAD

**Issue by wuyuanyi135** [githubuser0xFFFF/Qt-Advanced-Docking-System#497]
Hi. I notice the binding hosted on Pypi's version is 3.8. Any plan to release the latest version to pypi? Thanks

**Comment by githubuser0xFFFF** [comment]
You may ask the author of the Python bindings.

**Comment by wuyuanyi135** [comment]
Well. The pypi page links the project home to this repository so I posted the issue. Anyway, I figured out how to make a wheel from the source after some troubleshooting. Refer to my fork https://github.com/wuyuanyi135/Qt-Advanced-Docking-System/blob/master/python_build.md

There is also a prebuilt wheel for PyQt5 5.15.9 in the release page.
