### ISSUE TITLE
Feature request: grouped tabs

### ISSUE THREAD

**Issue by ma-robox** [githubuser0xFFFF/Qt-Advanced-Docking-System#498]
Would it be possibile to create groups of tabs? the same way modern web browsers handle them.
Some requirements:

1. The group should be given a name by the user
2. The state of the group should be saved an restored
3. It should remember the last tab used inside the group
4. When iterating through tabs in a tab bar, by keyboard for example, it should be seen and handled as 1 tab (showing briefly the last one used)
5. To better handle the group, the inner tabs should be expanded only after a brief delay after selection
6. When drag & dropped it should keep being a group and not become a whole other area of tabs.

**Comment by githubuser0xFFFF** [comment]
@ma-robox Thank you for your detailed feature request. While grouped tabs might be a good idea for web browser, I don not think that they would improve the Advanced Docking System. I think grouped tabs would increase the complexity for the user to handle the whole docking functionality properly.  

Threrefor I will close this feature request.
