### ISSUE TITLE
Build failure on BSD

### ISSUE THREAD

**Issue by Murmele** [githubuser0xFFFF/Qt-Advanced-Docking-System#505]
Currently our BSD build fails:

```
qt_advanced_dock-src/src/linux/FloatingWidgetTitleBar.cpp:197:34: error: too many arguments to function call, expected 0, have 1
                        d->FloatingWidget->showNormal(true);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~
/usr/local/include/qt5/QtWidgets/qwidget.h:486:10: note: 'showNormal' declared here
    void showNormal();
```
This is because in the Cmake file all UNIX except APPLE --> Linux + BSD are using FloatingWidgetTitleBar.cpp (first image), but in the FloatingDockContainer only for Linux (but not BSD) showNormal(bool) is enabled.

![image](https://user-images.githubusercontent.com/10099533/232319132-b9742645-d6da-4247-8e20-b843786eddd1.png)

![image](https://user-images.githubusercontent.com/10099533/232319189-f18ffeb7-7a10-4250-944b-bb2a89ae947c.png)

**Comment by githubuser0xFFFF** [comment]
@Murmele Thank you - would be great, if you could create a pull request.
