### ISSUE TITLE
Floating window in front of active main window

### ISSUE THREAD

**Issue by boggi78** [githubuser0xFFFF/Qt-Advanced-Docking-System#506]
Hello,

we are trying to finalize our floating window behaviour. There we recognized that the main window always is in behind the floating window. In other words: even if the main window is moved (has focus) it has the z-order in behind the floating window. Is this behaviour as intended? Can it be configured differently?

Here you can see what I'm trying to do. The floating window is taken out, the focus is given to the main window in behind. I would expect the main window to come in front:

https://user-images.githubusercontent.com/122113231/232336953-fd524db7-ff4b-49cb-9371-a4c90b8c5afc.mp4

Thanks for your help,
Michael

**Comment by githubuser0xFFFF** [comment]
Hi,

Yes, this is how windows are handled in Qt. ADS just uses the default Qt implementation.
