### ISSUE TITLE
Error: module 'PySide6QtAds' has no attribute 'ads'

### ISSUE THREAD

**Issue by foongminwong** [githubuser0xFFFF/Qt-Advanced-Docking-System#508]
Hello, I got this error when running [simple main.py](https://github.com/mborgerson/Qt-Advanced-Docking-System/blob/pyside6/examples/simple/main.py) and other examples.

```
PS E:\Qt-Advanced-Docking-System\examples\simple> python .\main.py
Traceback (most recent call last):
  File ".\main.py", line 52, in <module>
    w = MainWindow()
  File ".\main.py", line 26, in __init__
    self.dock_manager = QtAds.CDockManager(self)
AttributeError: Error evaluating `PySide6QtAds.ads.CDockManager.__init__`: module 'PySide6QtAds' has no attribute 'ads'
```

I came across the previous issues https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/298 and https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/494, upgraded `PySide6-QtAds` to 4.0.1.2, and it doesn't seem to fix the error on my end...

**Environment:**
OS: Windows Server 2019 Standard
Python Version: 3.8.16
Package Version: 
![image](https://user-images.githubusercontent.com/23441795/233530008-1fdef659-4ef1-4031-a8df-e714ef0caecc.png)
![image](https://user-images.githubusercontent.com/23441795/233531069-b33449dc-cf85-4ef6-bc1e-691d6289dc2a.png)

**Relevant Information**
I also received this error when I installed the latest PySide6, am not sure if this might cause the error... Does it mean I have to downgrade ` pyside6-essentials` & `shiboken6`?
![image](https://user-images.githubusercontent.com/23441795/233532660-4608d538-a7a3-4add-b8c5-26317bde06e8.png)

**Comment by demotu** [comment]
As shown in your pip error message, PySide6-QtAds 4.0.1.2 requires PySIde6 6.4.3, but you have PySIde6 6.5.0 (and the equivalent versions for Essentials and shiboken) installed.
Yes, if you want to use PySide6-QtAds 4.0.1.2, you need to downgrade to PySIde6 6.4.3 (and when you do, it should also automatically downgrade the Essentials and Shiboken libraries).

PySide6-QtAds needs to be updated to PySide6 6.5.0, hopefully @mborgerson can do that.

Although @mborgerson also replies here, maybe for specific requests related to PySide6, we should do it at https://github.com/mborgerson/Qt-Advanced-Docking-System, this is where PySide6-QtAds is being developed.

**Comment by mborgerson** [comment]
> Hello, I got this error when running [simple main.py](https://github.com/mborgerson/Qt-Advanced-Docking-System/blob/pyside6/examples/simple/main.py) and other examples.

Apparently there is an issue when PyQt5 is also installed. Try uninstalling it: `pip uninstall PyQt5 PyQt5-sip QyQt5-Qt5` then run the sample again.

> PySide6-QtAds needs to be updated to PySide6 6.5.0, hopefully @mborgerson can do that.

Just made a release. PySide6-QtAds v4.0.1.3 should work with PySide6 v6.5.0.

> Although @mborgerson also replies here, maybe for specific requests related to PySide6, we should do it at https://github.com/mborgerson/pyside6_qtads, this is where PySide6-QtAds is being developed.

Yeah, please file PySide6-QtAds-specific issues on my pyside6_qtads fork for tracking

**Comment by foongminwong** [comment]
Thank you for the replies @demotu @mborgerson ! Just refiled the issue
