### ISSUE TITLE
Impossible to minimize a detached window

### ISSUE THREAD

**Issue by PlasmaMichael** [githubuser0xFFFF/Qt-Advanced-Docking-System#51]
Hi,
The minimize button of detached window is disabled.

**Comment by PlasmaMichael** [comment]
Simply changing like that in FloatingDockContainer is not enough apparently:
`Qt::Window | Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint | Qt::WindowCloseButtonHint`
When the detached window is minimize it's then impossible to restore it.

**Comment by githubuser0xFFFF** [comment]
The minimize button is disabled because the detached windows do not have an entry in the Windows taskbar and therefore it is not possible to get the window out of the minimized state.

**Comment by PlasmaMichael** [comment]
If you try on Visual Studio, this is a difference from this docking system, looks like a missing feature.

**Comment by githubuser0xFFFF** [comment]
It is not the intention of this Docking System to be 100% like Visual Studio. It is the intention to be better ;o)

**Comment by PlasmaMichael** [comment]
I like the idea, but having no minimize and no window on the taskbar looks to be a regression of this kind of docking system. Even the original Qt docking system contains a minimize functionality to dock where it was docked :)

**Comment by githubuser0xFFFF** [comment]
I just startet the dockwidgets example that comes with Qt and I cannot see any minimize button in the docking windows. If I right click into the titlebar then the minimize menu item is greyed in the context menu and the floating dock windows do not have an entry in the taskbar.

So could you please tell me how to enable the minimize functionality in the standard Qt docking system?

**Comment by PlasmaMichael** [comment]
Oh, my bad, you right, I had a custom titlebar and forgot that the original QDockWidget only has a close button! So yes at least this version add a maximize button, so it's just a regression from the other kind of docking system using this style, can be a design choice of course yes.
