### ISSUE TITLE
Unpinned dock is not restored where it was before the pin action

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#510]
The pin option is really useful but I found a bug when a dock is unpinned, it is not restored where it was before the pin.

It can be reproducible with those steps in AutoHideExample:
- Step 1 -> Set the layout like this:
![image](https://user-images.githubusercontent.com/33324685/234608696-a678e734-ef55-4eeb-8788-cdd39a8c4a14.png)
- Step 2 -> Pin the Table 2 widget
- Step 3 -> Unpin the Table 2 widget
- Step 4 -> The layout is not anymore like in Step 1

In Visual Studio, when a dock is unpinned, it goes back to where it was before.

**Comment by githubuser0xFFFF** [comment]
I did it differently than Visual Studio :O) - this is not a bug.
