### ISSUE TITLE
Toggle a dock in AutoHide mode does not show it

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#511]
If a dock is in AutoHide mode and the dock is actually not displayed, when we call in code:
`dock->toggleView(true);`
It doesn't show it, it stays hidden.

It seems we are doing only a `raise()` in the `CDockWidget::toggleView` method.
In this case, as it is a hidden dock, something more should be done to display it before raising it.

**Comment by githubuser0xFFFF** [comment]
Thank you for this bug report  - fixed this in master
