### ISSUE TITLE
Reasons for not supporting QML UIs?

### ISSUE THREAD

**Issue by mchistovib** [githubuser0xFFFF/Qt-Advanced-Docking-System#513]
Hello,

What are your reasons for not supporting this framework for qml?
Is it because of having to spend too much time to adopt current code to this type of UI, or it is just technically impossible to use for QML because it uses some very specific QtWidgets features?

Best regards,
Maksim CHistov

**Comment by githubuser0xFFFF** [comment]
Because I'm mainly work with widgets and because KDDockWidgets already supports QML - so no need to reinvent the wheel.

**Comment by mchistovib** [comment]
@githubuser0xFFFF unfortunately KDDockWidgets QML support is still in beta stage, there were no releases of 2.0 version still and they also promise there will be breaking changes in it before the release. So it's not something you would want to pick for any big project in it's current state.

Would you consider adding the QML support if some company would be ready to pay you for that?

**Comment by githubuser0xFFFF** [comment]
I think, if you spend your money for the people at KDAB you will get results faster. I would have to start from scratch and I think this is something you don't want to pay ;o)
