### ISSUE TITLE
Dock OpenGLWidget and use autohigh widget simultaneousely and set Qt::AA_DontCreateNativeWidgetSiblings

### ISSUE THREAD

**Issue by christoffel1989** [githubuser0xFFFF/Qt-Advanced-Docking-System#515]
i add a openglwidget to the CDockManager, to ensure the OpenGLWidget correctly display when floating, Qt::AA_DontCreateNativeWidgetSiblings is set. However Qt::AA_DontCreateNativeWidgetSiblings will make autohide dock widget  can not be operated if the docked openglwidget is underneath. At this time, if i click mouse on the autohide dock widget, the auto hide dock widget will disappear, the mouse click event will be receive by the below openglwidget.

If Qt::AA_DontCreateNativeWidgetSiblings is not set this problem will not happen. However, the openglwidget will not render if it's floating.

**Comment by githubuser0xFFFF** [comment]
Please provide a small sample application that shows this issu. I think, this is not an ADS issue but a Qt issue.

**Comment by githubuser0xFFFF** [comment]
I close the issue for now. Feel free to reopen it, if you can provide a small sample application that shows the issue
