### ISSUE TITLE
How to close everything and get the dock manager back to a clean slate?

### ISSUE THREAD

**Issue by Levi-Armstrong** [githubuser0xFFFF/Qt-Advanced-Docking-System#519]
I want know how to get the dock manager to the original state when construction `auto* dock_manager = new ads:CDockManager(this);`. Remove all dock widgets, areas, etc.

**Comment by githubuser0xFFFF** [comment]
There is no function to do this. You need to mange this by yourself.

**Comment by Levi-Armstrong** [comment]
Is it sufficient to do what is done in the CDockManager::~CDockManager [here](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/0bfee09b17ccfb1d42010daf2233a92f2f853ea0/src/DockManager.cpp#L532-L555)?

**Comment by Levi-Armstrong** [comment]
@githubuser0xFFFF is the approach above sufficient?

**Comment by githubuser0xFFFF** [comment]
Hi Levi, how much time (hours) would you like me to invest in reviewing your code? I could make you an offer.
