### ISSUE TITLE
Move a detached window gives a jump

### ISSUE THREAD

**Issue by PlasmaMichael** [githubuser0xFFFF/Qt-Advanced-Docking-System#52]
Move a detached window gives a jump on the window position. At the end of the move the window doesn't stay at the position where you released the click.

**Comment by githubuser0xFFFF** [comment]
Which operating system do you use? Linux?

**Comment by PlasmaMichael** [comment]
Windows, I didn't try another OS.

**Comment by githubuser0xFFFF** [comment]
Which Qt version do you use. I tested this with different Qt verisons (5.9 - 5.12) on different Windows version (7, 8, 10) and did not noticed any window jumping problemn.

**Comment by PlasmaMichael** [comment]
Windows 10 and Qt 5.13.0.

**Comment by githubuser0xFFFF** [comment]
Fantastic. So oviously Qt 5.13.0 introduced some new strange "bug". I will test it with Qt 5.13 to see how to fix this.

**Comment by PlasmaMichael** [comment]
Just tried now Qt 5.13.1 which got released yesterday and I have the same result.

**Comment by githubuser0xFFFF** [comment]
Hi, I  just tested the AdvancedDockingSystemDemo.exe app with Qt 5.13.1 and could not reproduce the problem. Could you please give some instructions what I need to do to see the "jump"? Maybe you could provide a video where I can se the "jump" so that I can get an idea what is going on.

**Comment by PlasmaMichael** [comment]
I compile the example and I don't have the behavior I have when I tried your code in my project.
In my project, when I tried to use your code here what I concluded:
- I get a very laggy window movement when I undock and keep clicked to move the window
- I get jump when stop moving
- A crash when I try to undock again after dock one
- I saw that stylesheet is forced to be at one location
- The minimize is not there which is a missing feature in my eyes
The last one we concluded that it's a design choice for this lib, the 3 others are more critical to me.
Looks like the demo works well, so surely the lib needs more real use case in a full application to see all this kind of bugs.
The crash when I undock is in "moveFloating" the widget is not valid yet, surely an event issue.

**Comment by PlasmaMichael** [comment]
In addition to that I didn't find a way to resize or to force the dock to use the minimum width when it's added in the dock manager, that makes difficult to create a good default layout by code. You surely have a hint for that? Maybe it's a missing feature?

**Comment by PlasmaMichael** [comment]
About the crash when undock, if I undock and dock without mouse release the crash when undock is not present. It's only present when undock, mouse release, dock and finally try to undok again.

**Comment by githubuser0xFFFF** [comment]
Hi, I cannot reproduce this problem with the demo application. We use the docking system in a big real world appplication (pictures and video of the dark themed QmixElements application). This application also does not show these problems. 

So I don't know how to fix this and I don't know what you are doing in your application - sorry.

**Comment by PlasmaMichael** [comment]
The original Docking system of Qt works perfectly so there must be something but yes difficult to say what is really happening. I tried to integrate this docking system in a full 3D engine editor which also contains a custom tabbed window like Chrome tab system, each tab contains one QMainWindow and the QMainWindow is full of dock windows. I will certainly bypass the use of this system because of the multiple things I mentioned but I have to say that this is still a great job.
