### ISSUE TITLE
How to enable setAutoHideConfigFlags in Python ?

### ISSUE THREAD

**Issue by mehdibouzit** [githubuser0xFFFF/Qt-Advanced-Docking-System#522]
Hi,
I'm using the PySide6 port of this library, and so far I've used the demo and example to activate my flags, because I can't find any documentation about it in Python.
For example, I'm using this successfully:
`QtAds.CDockManager.setConfigFlag(QtAds.CDockManager.DockAreaHasCloseButton, False)`
Now, I'd like to use the AutoHide feature in my Python application. To activate this feature in C++, you'll need to use:
`CDockManager::setAutoHideConfigFlags(CDockManager::DefaultAutoHideConfig)`
I tried to convert it to Python, without luck. I tried:
` QtAds.CDockManager.setAutoHideConfigFlags(QtAds.CDockManager.DefaultAutoHideConfig, True)`
or
`QtAds.CDockManager.setConfigFlag(QtAds.CDockManager.DefaultAutoHideConfig, True)` but I have AttributeErrors.
Thanks in advance.

**Comment by githubuser0xFFFF** [comment]
Which version of the library do you use?

**Comment by mehdibouzit** [comment]
Yes that's what I thought. The Auto-Hide example from their repos seems bogus in Python, and since the library is essentially a DLL I don't know how to check that by myself. 
The regular PyQtAds is still in 3.8.1 so I'm guessing the Auto-Hide is not ported as well.

**Comment by githubuser0xFFFF** [comment]
Please file PySide related issues to: https://github.com/mborgerson/pyside6_qtads

**Comment by mehdibouzit** [comment]
Found it, if someone is interested:
```
QtAds.CDockManager.setAutoHideConfigFlag(QtAds.CDockManager.DefaultAutoHideConfig)
```
