### ISSUE TITLE
updateDockWidgetFocusStyle() function error

### ISSUE THREAD

**Issue by hanabear** [githubuser0xFFFF/Qt-Advanced-Docking-System#527]
Hello,

This issue can be reproduced with the demo application.

1. Run ads demo application.
2. Move My Calendar 2 window to left (To select Label 1 ~ 5 widget).
3. Select Label 5 text area → Label 5 is highlighted.
4. Select Label 1 Tab area → Label 1 is highlighted.
5. Select Label 3 Tab area → Image Viewer 0 is highlighted. **(wrong behavior)**
6. Select Label 3 Tab area again, → Label 3 is highlighted.

If only tab area is selected, everything is fine. But, when view area is selected, next procedure results in unwanted behavior.

I couldn't figure out why it happens. So, I am reporting the issue in this board.

Best Regards,
hanabear

**Comment by githubuser0xFFFF** [comment]
Thank you for reporting this issue - I can reproduce it.

**Comment by githubuser0xFFFF** [comment]
Fixed in master
