### ISSUE TITLE
Empty floating widget on Linux

### ISSUE THREAD

**Issue by iam-peter** [githubuser0xFFFF/Qt-Advanced-Docking-System#529]
With the newest version of QtADS I'll always get an empty floating widget after starting the demo. I've tested it with Qt 5.15.11 and Qt 6.4.3. Have a look at the screenshot to understand what is happening.
I've already debugged into that issue and found that after running `FloatingDockContainer(DockManager *dockManager)` constructor the floating widget shows up.

I'm currently trying to integrate the newest changes into Qt Design Studio and noticed the same issue after merging all the changes. In Qt Design Studio I'll get this empty floating widget when there is a floating widget in the workspace/perspective which is set to be **closed**. Unfortunately I can't narrow down the exact line in which the empty floating apperas during the construction of `FloatingDockContainer`, because if I debug into it the empty floating widget won't show up. Only if I step over the constructor it will create the empty floating widget.
Even with setting `nativeWindow` to `false` in the constructor I get the empty floating widget, but without a window decoration.
This floating widget is also not closable via the title bar close button. Only If I use `close()` instead of `hide()` in `FloatingDockContainer::closeEvent(QCloseEvent *event)`.

Does someone else got the same issue on Linux with the demo application?

OS: Ubuntu 22.04
WM: XFCE4

![2023-06-27_16-06](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/7542157/ce65c9dc-c0cd-4b07-8fd2-a27c8f026d3e)

**Comment by githubuser0xFFFF** [comment]
Hi @iam-peter ,

I just checked out the master on a Ubuntu 20.04 VM with Gnome 3.36.8 and I do not see this issue. I used the default settings after checkout withotu changing anything.

**Comment by githubuser0xFFFF** [comment]
@iam-peter 

I just checke out the mster on a Xubuntu 22.04 VM with XFCE4 and Qt 5.15.3 and I can reproduce the problem there.

**Comment by iam-peter** [comment]
I was able to resolve it by  removing `QDockWidget::setFloating(true);` in `FloatingDockContainer.cpp` line 646.

**Comment by githubuser0xFFFF** [comment]
Yes, I can confirm, that this fixes the problem. If you do not discover any negative side effects, you can create a pull request. Thank you for solving this issue.

**Comment by Tectu** [comment]
Any news on this?

**Comment by githubuser0xFFFF** [comment]
Fixed
