### ISSUE TITLE
ads3.8.3 in Ubuntu qt5.7.1 when drag label 1 outside the mainwindow crashed

### ISSUE THREAD

**Issue by guanyu-eng** [githubuser0xFFFF/Qt-Advanced-Docking-System#531]
ads in qt5.7.1 Ubuntu.I meet one mistake .
1.run simple example.
2.drag the label 1 outside of the mainwindow to floating .it  crashed unexpectedly.
test ads in qt 5.7.1 Windows . It's ok.
test ads in qt 5.12.1 Ubuntu. it's ok.

**Comment by githubuser0xFFFF** [comment]
ADS 3.8.3 is outdated - update to latest version
