### ISSUE TITLE
When using MobaXterm to connect to a Linux server and running a Qt program, moving the DockWidget causes a black screen issue.

### ISSUE THREAD

**Issue by Jacob-z-h** [githubuser0xFFFF/Qt-Advanced-Docking-System#533]
[original state](javascript:;)
<img width="961" alt="initial" src="https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/89233509/7acf3207-b00c-4333-98fd-c90ced058e91">
move
<img width="961" alt="move" src="https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/89233509/63d0d8f8-83c7-4899-a1cf-c7a0a1e1347c">
The aforementioned phenomenon is caused by when using MobaXterm to connect to a Linux server and running a Qt program, moving the DockWidget causes a black screen issue.

**Comment by Jacob-z-h** [comment]
The black screen issue does not occur if MobaXterm is not used.

**Comment by githubuser0xFFFF** [comment]
Sorry, I close this issue because of a lack on information from your side.

**Comment by Jacob-z-h** [comment]
> 
What information , any information on this issue ? or something else

**Comment by Tectu** [comment]
This is most likely the same issue as #95
