### ISSUE TITLE
Unimplemented methods

### ISSUE THREAD

**Issue by mborgerson** [githubuser0xFFFF/Qt-Advanced-Docking-System#534]
Some method declarations were recently introduced without a definition:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/ac1879d5cba7c6b748a79831e4582359c20fd882/src/DockContainerWidget.h#L111

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/ac1879d5cba7c6b748a79831e4582359c20fd882/src/DockWidgetTab.h#L185

**Comment by githubuser0xFFFF** [comment]
Thank you, fixed this in master
