### ISSUE TITLE
Can I deserialize the dock layout to json string?

### ISSUE THREAD

**Issue by ChivenZhang** [githubuser0xFFFF/Qt-Advanced-Docking-System#535]
I want to intergrate this dock system to my editor framework which needs saving all layouts. So is it possible to convert ads layout to customized config format, such as .json, instead of Qt's state-saving ? or is it possible to foreach all the widgets hierachy according to dock layout ?
Thanks.

**Comment by githubuser0xFFFF** [comment]
No, this is not possible.
