### ISSUE TITLE
Two floating widgets show after using addDockWidgetTab three times

### ISSUE THREAD

**Issue by ChivenZhang** [githubuser0xFFFF/Qt-Advanced-Docking-System#536]
I added three widgets to DockManager using addDockWidgetTab api, and it shown two floating widgets. 
Is it wrong?

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/48938612/c1507613-c024-4d51-b874-ba104b99dcd2)
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/48938612/1d8c7e5b-407f-42a9-b76e-66e79909604c)

**Comment by githubuser0xFFFF** [comment]
Please tell me how to reproduce this with the demo application or provide a small sample application that shows this issue.

**Comment by githubuser0xFFFF** [comment]
Closing issue until new informations are available
