### ISSUE TITLE
Closing auto-hide widget accidently after clicking a closed button of dock widget

### ISSUE THREAD

**Issue by ChivenZhang** [githubuser0xFFFF/Qt-Advanced-Docking-System#537]
I created a docked widget A and an auto-hide widget B, when I closed widget A and it closed widget B by accident. Is it wrong ?

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/48938612/a1edf935-31f8-44e3-8601-eb40c271f2c8)

**Comment by githubuser0xFFFF** [comment]
Please tell me how to reproduce this with the demo application or provide a small sample application that shows this issue.

**Comment by githubuser0xFFFF** [comment]
Closing issue until new issues are available
