### ISSUE TITLE
CAutoHideDockContainer在centos7中编译不过的问题

### ISSUE THREAD

**Issue by zhangtaohbwh** [githubuser0xFFFF/Qt-Advanced-Docking-System#546]
如下标记的代码在centos7中编译不过：
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/26736905/892dbb72-e82c-4710-83ea-53c6bc3170cb)
我想应该是要改成如下方式：
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/26736905/18c7833f-de97-441b-abbb-3c7510d7f49e)

**Comment by githubuser0xFFFF** [comment]
Sorry, I cannot read and understand this language

**Comment by zhangtaohbwh** [comment]
CAutoHideDockContainer cannot be compiled in Centos7 system
The first image is where I marked the area that cannot be compiled
The marking on the second image is my solution

The following is my error prompt during compilation
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/26736905/e4185704-b8bb-4fc7-a748-86e4778a2e8c)

**Comment by githubuser0xFFFF** [comment]
Centos 7 is not supported. Only Ubuntu.

**Comment by zhangtaohbwh** [comment]
After I make some modifications, it can run in Centos7

**Comment by githubuser0xFFFF** [comment]
Maybe, but if us not supported and will not be supported in the future. Sorry, but the number of users ist too small and the number of problems too high.
