### ISSUE TITLE
PySide6QtAds ImportError: DLL Load Failed on Python 3.10

### ISSUE THREAD

**Issue by xiaobai427** [githubuser0xFFFF/Qt-Advanced-Docking-System#549]
I am experiencing an issue while trying to use the PySide6QtAds package in my Python 3.10 environment on Windows. When I attempt to import the PySide6QtAds module in my script, I receive the following error message:
ImportError: DLL load failed while importing PySide6QtAds: The specified program could not be found.
I have already tried reinstalling PySide6 and PySide6QtAds, ensuring that the required Qt libraries are installed, and verifying that the Python, PySide6, and PySide6QtAds architectures match (all 64-bit). Additionally, I have checked the system PATH to ensure it includes the directory where the required DLLs are located.

Despite these efforts, the issue persists. I would greatly appreciate any assistance or insights into resolving this DLL load failure.

Thank you!

**Comment by githubuser0xFFFF** [comment]
Closes, because Python is a 3rdparty contribution - this ia not really an issue of ADS
