### ISSUE TITLE
demo project crashed at  qrhid3d11.cpp while start demo project and debug to  mw.show()  in main.cpp line 54.  

### ISSUE THREAD

**Issue by HwangKC** [githubuser0xFFFF/Qt-Advanced-Docking-System#553]
I use Qt 6.2.4 , OS Windows 11, ADS  tag. 4.11 or main branch will crashed, tag. 3.8.0 runs well! 
 
![crached](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/11828980/ecf73743-7b98-4fc3-93a5-45d229c45d47)

 Do you have any idea what might cause this ?  thx!

-Hwang.kc

**Comment by githubuser0xFFFF** [comment]
Please uncomment or disable the following lines (574 - 577) in the demo project `MainWindow.cpp` an rebuild:

```cpp
// Create quick widget
DockWidget = createQQuickWidget();
DockWidget->setFeature(ads::CDockWidget::DockWidgetClosable, true);
DockManager->addDockWidget(ads::LeftDockWidgetArea, DockWidget);
```

Check if the crash is gone. If it is gone, then you have some kind of issues with your grafics card Open GL driver because your PC does not support creation of QQuickWidgets.

**Comment by HwangKC** [comment]
Thanks, that fixed.
