### ISSUE TITLE
Add a configuration that avoid tab label eliding

### ISSUE THREAD

**Issue by nitramr** [githubuser0xFFFF/Qt-Advanced-Docking-System#554]
If the text label of a tab is too large or the amount of tabs is not fitting in the dock container, you see an elided text label in each tab.

Please, add a setting that avoid this eliding behavior. I need a way to always read the text of a tab. If the text is too large, the tabs could be in a scroll container (like the behavior of a QTabBar).

![fusion-tabbar-truncated](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/15112256/631c172c-daae-48c7-b3b5-52f15b4c155c)

Thanks

**Comment by githubuser0xFFFF** [comment]
Why do do you need a scroll container? You already gave tabs menu.

**Comment by nitramr** [comment]
Hi, the scroll container is not needed. The tab menu is fine for overflowing content. The main point of my request is that I need tabs without eliding text.
![Bildschirmfoto vom 2023-09-06 21-30-04](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/15112256/0900b336-72a9-46ff-92af-75c93a9e2512)

It would be better if the first tab text is fully readable and the second one elided.

**Comment by githubuser0xFFFF** [comment]
Implemented in master - see configuration flag `DisableTabTextEliding`.
