### ISSUE TITLE
Intelligent Tiling

### ISSUE THREAD

**Issue by Madrich** [githubuser0xFFFF/Qt-Advanced-Docking-System#555]
Hello, I try to automatically tile some dockWidgets/Areas. Unfortunately, I dont knwo how to control its sizes.
I'd like to manage the following.
1. Having a centralDockArea add the first dockwidget with double size
2. Add the second dockWidget right to the central
3. Add the third dockwidet below the second
4. Add the forth dockwidget right to the second ... do to (2.)
Here an example:
[1 1 2 4 6]
[1 1 3 5 6]

Is there a simple way to achieve that?

**Comment by githubuser0xFFFF** [comment]
Each doch widget ist inside of a CDockSplitter. So you need to get the parent dock splitter and use it's API to resize it's containing dock widgets
