### ISSUE TITLE
The dynamic library cannot be found on ubuntu 20.04 

### ISSUE THREAD

**Issue by yapcumt** [githubuser0xFFFF/Qt-Advanced-Docking-System#560]
It prompts that libqtadvanceddocking.so.1 not found
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/55487121/38140a3a-fe4b-4d2a-93cf-251ba3b2b477)

**Comment by yapcumt** [comment]
The program can be opened and run normally using qtcreator (Qt5.12.12) on the ubuntu 20.04 system, but cannot be opened when running the program alone

**Comment by githubuser0xFFFF** [comment]
What is your build system (cmake or qmake)?

What is your ADS version? A certain version or head of master branch?

**Comment by yapcumt** [comment]
> What is your build system (cmake or qmake)?
> 
> What is your ADS version? A certain version or head of master branch?

qmake，ads version is tags of 4.1.1

**Comment by githubuser0xFFFF** [comment]
Ensure, that your the ADS library is in you linker search path or library search path.
