### ISSUE TITLE
Dock widget is not deleted if hidden when restoring dock manager state 

### ISSUE THREAD

**Issue by mehdibouzit** [githubuser0xFFFF/Qt-Advanced-Docking-System#564]
Hello,
I'm developing an application where the user can create docks, save them, and load their layout. Since I started using AutoHidden docks, I've encountered an issue where saving my workspace and then reloading it wouldn't properly delete the dock widget if it was hidden, thus instantiating it twice. If I decide to move the dock elsewhere or make it floating, in that case, a reload of the dock manager state would delete it and replace it accordingly.

Here is how I create my dock widget:
```python
w = QtAds.CDockWidget("...")
w.setWidget(some_widget)
self.dock_manager.addAutoHideDockWidget(SideBarBottom, w)
w.setFeature(CustomCloseHandling, True)
w.setFeature(DockWidgetDeleteOnClose, True)
w.closeRequested.connect(some_function)
```

Here is how I load a dock manager layout:

```python
def restore_workspace_state(self, workspace_name):
	'''
	Restores the dock manager state
	'''
	settings = QSettings("Settings.ini", QSettings.IniFormat)
	geom = settings.value(f"{workspace_name}/Geometry")
	if geom is not None:
		self.restoreGeometry(geom)

	state = settings.value(f"{workspace_name}/State")
	if state is not None:
		self.restoreState(state)

	state = settings.value(f"{workspace_name}/DockingState")
	if state is not None:
		self.dock_manager.restoreState(state)
```

Am I doing something wrong?

Thanks in advance.

**Comment by githubuser0xFFFF** [comment]
Could you please provide a very small and stripped down example application that shows this issue. Maybe you can modify the autohide example and create a pull request or you can add a new example that shows this - this would be great and would help me to fix the issue.

**Comment by githubuser0xFFFF** [comment]
I close this because of missing support from user.
