### ISSUE TITLE
dockWidgetsMap not updated on setObjectName

### ISSUE THREAD

**Issue by akdjwu** [githubuser0xFFFF/Qt-Advanced-Docking-System#569]
If I update the objectName of a CDockWidget in the DockManager, the dockWidgetsMap is not updated. The key is still the old objectName. So "removeDockWidget(CDockWidget)" does not remove a CDockWidget with a new ObjectName.

**Comment by githubuser0xFFFF** [comment]
Please do never change the object name of a dock widget because it will break loading of saved configurations, The object name is a kind of unique ID and should ne be changed,
