### ISSUE TITLE
Segmentation fault after calling the closeDockWidget()

### ISSUE THREAD

**Issue by i-and** [githubuser0xFFFF/Qt-Advanced-Docking-System#571]
A segmentation fault occurs in the DockAreaTabBarPrivate::updateTabs() method:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/55ef6ef863f21643785f71a544a3ac98934aa68f/src/DockAreaTabBar.cpp#L96-L123

and in the line:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/55ef6ef863f21643785f71a544a3ac98934aa68f/src/DockAreaTabBar.cpp#L115-L115

This happens when processing an event from the timer and immediately after programmatically closing CDockWidget by calling closeDockWidget(). It looks like this deferred call is trying to access the previously destroyed CDockWidget. How can this be fixed?

**Comment by githubuser0xFFFF** [comment]
The demo application has several places where `closeDockWidget()` is used. I tested them all and can not reproduce the problem. So there must be something wrong with your application.

**Comment by i-and** [comment]
I also failed to recreate this error using the `emptydockarea` example. I'll try to investigate the application. If there's any news, I'll let you know.
