### ISSUE TITLE
Uploading PyQtAds latest version to pypi

### ISSUE THREAD

**Issue by sisteralab** [githubuser0xFFFF/Qt-Advanced-Docking-System#575]
Actual version of QtAds is 4.1, but python binding PyQtAds is 3.8.1, could you upload actual version to pypi please

**Comment by githubuser0xFFFF** [comment]
Please contact the authors of the PyQtAds Python integration to update the actual version. The Python bindings are a 3rdparty contribution and I have no knowledge how to do this.
