### ISSUE TITLE
can't use slot function when the widget is in CDockWidget

### ISSUE THREAD

**Issue by sean-depp** [githubuser0xFFFF/Qt-Advanced-Docking-System#577]
I try to make this problem clear:
```
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    CDockManager * DockManager = new CDockManager(this);

    connect(ui->pushButton, &QPushButton::clicked, this, &MainWindow::hello);
    ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");
    DockWidget->setWidget(ui->softwareArea);

    DockManager->addDockWidget(ads::TopDockWidgetArea, DockWidget);
}
``` 
this is ok to add a slot function, but I use a layout to add my widget:
```
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    auto soft = new Software(this);
    ui->verticalLayout->addWidget(soft);
}
```
and in the sub widget constructor,
```
Software::Software(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::Software)
{
    ui->setupUi(this);

    auto mainwindow = findMainWindow();

    CDockManager * DockManager = new CDockManager(mainwindow);

    connect(ui->pushButton, &QPushButton::clicked, this, &Software::hello);
    ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");
    DockWidget->setWidget(ui->widget_top);

    DockManager->addDockWidget(ads::TopDockWidgetArea, DockWidget);
}

void Software::hello(){
    qDebug() << "hellox";
}

QMainWindow *Software::findMainWindow() const
{
    QWidget *parent = parentWidget();
    while (parent) {
        if (dynamic_cast<QMainWindow*>(parent)) {
            return dynamic_cast<QMainWindow*>(parent);
        }
        parent = parent->parentWidget();
    }
    return nullptr;
}
``` 
here, my slot function hello can't be actived
if change 
```connect(ui->pushButton, &QPushButton::clicked, this, &Software::hello);```
to 
```connect(ui->pushButton, &QPushButton::clicked, [=](){qDebug() << "hello";});```
it can be actived.

**Comment by jxgyzhang** [comment]
&amp;Software::hello&nbsp; no private slots: ?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午3:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)





 
when put my widget in CDockWidget like dockWidgetCenterRight-&gt;setWidget(ui-&gt;widget_center_right);, I found my pushbutton which is in widget_center_right can't be clicked. onnect(ui-&gt;pushButton, &amp;QPushButton::clicked, this, &amp;Software::hello); this hello method can't be actived, but anonymous function can be use connect(ui-&gt;pushButton_4, &amp;QPushButton::clicked, [=](){qDebug() << "hello4";});，so, how can I use normal method like connect(ui-&gt;pushButton, &amp;QPushButton::clicked, this, &amp;Software::hello);

**Comment by sean-depp** [comment]
&nbsp;老哥，你是中国人吧，就是我套了一层layout，然后本来可以的connect就失效了，代码大概是下面这样


&nbsp;MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&gt;setupUi(this); 
     auto soft = new Software(this);     ui-&gt;verticalLayout-&gt;addWidget(soft);
}

Software::Software(QWidget *parent) :     QWidget(parent),     ui(new Ui::Software) {     ui-&gt;setupUi(this); 
     auto mainwindow = findMainWindow();     CDockManager * DockManager = new CDockManager(mainwindow); 
     connect(ui-&gt;pushButton, &amp;QPushButton::clicked, this, &amp;Software::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&gt;setWidget(ui-&gt;widget_top); 
     DockManager-&gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); } 
 void Software::hello(){     qDebug() << "hellox"; }
如果直接在mainwindow进行连接是可以的
MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&gt;setupUi(this);     CDockManager * DockManager = new CDockManager(this); 
     connect(ui-&gt;pushButton, &amp;QPushButton::clicked, this, &amp;MainWindow::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&gt;setWidget(ui-&gt;softwareArea); 
     DockManager-&gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); }
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Nov 9, 2023 03:34 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)

&nbsp;



 &amp;amp;Software::hello&amp;nbsp; no private slots: ? 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月9日(星期四) 下午3:31 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577) 
 
 
 
 
 
   
 when put my widget in CDockWidget like dockWidgetCenterRight-&amp;gt;setWidget(ui-&amp;gt;widget_center_right);, I found my pushbutton which is in widget_center_right can't be clicked. onnect(ui-&amp;gt;pushButton, &amp;amp;QPushButton::clicked, this, &amp;amp;Software::hello); this hello method can't be actived, but anonymous function can be use connect(ui-&amp;gt;pushButton_4, &amp;amp;QPushButton::clicked, [=](){qDebug() << "hello4";});，so, how can I use normal method like connect(ui-&amp;gt;pushButton, &amp;amp;QPushButton::clicked, this, &amp;amp;Software::hello);

**Comment by jxgyzhang** [comment]
如果直接在mainwindow进行连接是可以的
MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent) , ui(new Ui::MainWindow) { ui-&amp;gt;setupUi(this); CDockManager * DockManager = new CDockManager(this);
connect(ui-&amp;gt;pushButton, &amp;amp;QPushButton::clicked, this, &amp;amp;MainWindow::hello);


直连的是mainwindow的hello


Software连接的是Software::hello


是不是software上面的hello没有private slots:的定义？
单纯的看你写的代码，不至于加个layout就会导致信号槽失效，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)





 &amp;nbsp;老哥，你是中国人吧，就是我套了一层layout，然后本来可以的connect就失效了，代码大概是下面这样 
 
 
 &amp;nbsp;MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&amp;gt;setupUi(this);  
      auto soft = new Software(this);     ui-&amp;gt;verticalLayout-&amp;gt;addWidget(soft); 
 } 
 
 Software::Software(QWidget *parent) :     QWidget(parent),     ui(new Ui::Software) {     ui-&amp;gt;setupUi(this);  
      auto mainwindow = findMainWindow();     CDockManager * DockManager = new CDockManager(mainwindow);  
      connect(ui-&amp;gt;pushButton, &amp;amp;QPushButton::clicked, this, &amp;amp;Software::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&amp;gt;setWidget(ui-&amp;gt;widget_top);  
      DockManager-&amp;gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); }  
  void Software::hello(){     qDebug() << "hellox"; } 
 如果直接在mainwindow进行连接是可以的 
 MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&amp;gt;setupUi(this);     CDockManager * DockManager = new CDockManager(this);  
      connect(ui-&amp;gt;pushButton, &amp;amp;QPushButton::clicked, this, &amp;amp;MainWindow::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&amp;gt;setWidget(ui-&amp;gt;softwareArea);  
      DockManager-&amp;gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); } 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Date: &amp;nbsp;Thu, Nov 9, 2023 03:34 PM 
 To: ***@***.***&amp;gt;;  
 Cc: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577) 
 
 &amp;nbsp; 
 
 
 
  &amp;amp;amp;Software::hello&amp;amp;nbsp; no private slots: ?  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年11月9日(星期四) 下午3:31  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)  
   
   
   
   
   
     
  when put my widget in CDockWidget like dockWidgetCenterRight-&amp;amp;gt;setWidget(ui-&amp;amp;gt;widget_center_right);, I found my pushbutton which is in widget_center_right can't be clicked. onnect(ui-&amp;amp;gt;pushButton, &amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;Software::hello); this hello method can't be actived, but anonymous function can be use connect(ui-&amp;amp;gt;pushButton_4, &amp;amp;amp;QPushButton::clicked, [=](){qDebug() << "hello4";});，so, how can I use normal method like connect(ui-&amp;amp;gt;pushButton, &amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;Software::hello);

**Comment by sean-depp** [comment]
&nbsp;之前写的public slots:,改成private slots:也还是没有反应。
    connect(ui-&gt;pushButton, &amp;QPushButton::clicked, [=](){         qDebug() << "go";     }); connect(ui-&gt;pushButton, &amp;QPushButton::clicked, this, &amp;Software::hello);
&nbsp;通过匿名函数直接调用是可以触发的，但是写成成员函数，就没反应了。
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Nov 9, 2023 04:26 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)

&nbsp;



 如果直接在mainwindow进行连接是可以的 
 MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent) , ui(new Ui::MainWindow) { ui-&amp;amp;gt;setupUi(this); CDockManager * DockManager = new CDockManager(this); 
 connect(ui-&amp;amp;gt;pushButton, &amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;MainWindow::hello); 
 
 
 直连的是mainwindow的hello 
 
 
 Software连接的是Software::hello 
 
 
 是不是software上面的hello没有private slots:的定义？ 
 单纯的看你写的代码，不至于加个layout就会导致信号槽失效， 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月9日(星期四) 下午4:13 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577) 
 
 
 
 
 
  &amp;amp;nbsp;老哥，你是中国人吧，就是我套了一层layout，然后本来可以的connect就失效了，代码大概是下面这样  
   
   
  &amp;amp;nbsp;MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&amp;amp;gt;setupUi(this);   
       auto soft = new Software(this);     ui-&amp;amp;gt;verticalLayout-&amp;amp;gt;addWidget(soft);  
  }  
   
  Software::Software(QWidget *parent) :     QWidget(parent),     ui(new Ui::Software) {     ui-&amp;amp;gt;setupUi(this);   
       auto mainwindow = findMainWindow();     CDockManager * DockManager = new CDockManager(mainwindow);   
       connect(ui-&amp;amp;gt;pushButton, &amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;Software::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&amp;amp;gt;setWidget(ui-&amp;amp;gt;widget_top);   
       DockManager-&amp;amp;gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); }   
   void Software::hello(){     qDebug() << "hellox"; }  
  如果直接在mainwindow进行连接是可以的  
  MainWindow::MainWindow(QWidget *parent)     : QMainWindow(parent)     , ui(new Ui::MainWindow) {     ui-&amp;amp;gt;setupUi(this);     CDockManager * DockManager = new CDockManager(this);   
       connect(ui-&amp;amp;gt;pushButton, &amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;MainWindow::hello);     ads::CDockWidget* DockWidget = new ads::CDockWidget("Label 1");     DockWidget-&amp;amp;gt;setWidget(ui-&amp;amp;gt;softwareArea);   
       DockManager-&amp;amp;gt;addDockWidget(ads::TopDockWidgetArea, DockWidget); }  
  ------------------&amp;amp;nbsp;Original&amp;amp;nbsp;------------------  
  From: ***@***.***&amp;amp;gt;;  
  Date: &amp;amp;nbsp;Thu, Nov 9, 2023 03:34 PM  
  To: ***@***.***&amp;amp;gt;;   
  Cc: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  Subject: &amp;amp;nbsp;Re: [githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)  
   
  &amp;amp;nbsp;  
   
   
   
   &amp;amp;amp;amp;Software::hello&amp;amp;amp;nbsp; no private slots: ?   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "githubuser0xFFFF/Qt-Advanced-Docking-System"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2023年11月9日(星期四) 下午3:31   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[githubuser0xFFFF/Qt-Advanced-Docking-System] can't use slot function when the widget is in CDockWidget (Issue #577)   
     
     
     
     
     
       
   when put my widget in CDockWidget like dockWidgetCenterRight-&amp;amp;amp;gt;setWidget(ui-&amp;amp;amp;gt;widget_center_right);, I found my pushbutton which is in widget_center_right can't be clicked. onnect(ui-&amp;amp;amp;gt;pushButton, &amp;amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;amp;Software::hello); this hello method can't be actived, but anonymous function can be use connect(ui-&amp;amp;amp;gt;pushButton_4, &amp;amp;amp;amp;QPushButton::clicked, [=](){qDebug() << "hello4";});，so, how can I use normal method like connect(ui-&amp;amp;amp;gt;pushButton, &amp;amp;amp;amp;QPushButton::clicked, this, &amp;amp;amp;amp;Software::hello);

**Comment by githubuser0xFFFF** [comment]
This problem is not releate to ADS but from reading your comments I'm afraid that you have not understand how to work with Qt and width ADS. There are some things you are doing wrong. You should learn Qt a little bit more before using ADS.
