### ISSUE TITLE
[python] window handle invalid for floating docks

### ISSUE THREAD

**Issue by RubendeBruin** [githubuser0xFFFF/Qt-Advanced-Docking-System#579]
I'm trying to include a matplotlib figure in a dock widget. This works fine until the widget is made floating (undocked).

When the dock is (un)docked the showEvent is activated which, in case of matplotlib, uses the window handle to update the plot. 

Problem is that when requesting handle an invalid handle is returned. Using it results in a "RuntimeError: Internal C++ object (PySide6.QtGui.QWindow) already deleted." error. 

Digging into this I found that the window handle seems to be invalid for any undocked dock-widget. It this intended?

Reproduce:

```python
from PySide6.QtWidgets import QPushButton
from qtpy.QtWidgets import (
    QApplication,
    QMainWindow,
)

import PySide6QtAds as QtAds

class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.dock_manager = QtAds.CDockManager(self)

        button = QPushButton('Hi')
        floating_dock = QtAds.CDockWidget("Matplotlib figure")
        floating_dock.setWidget(button)

        self.dock_manager.addDockWidget(
            QtAds.DockWidgetArea.LeftDockWidgetArea, floating_dock
        )

        floating_dock.setFloating()

        def get_handle(event):
            handle = floating_dock.window().windowHandle()
            print(handle)

        button.clicked.connect(get_handle)


if __name__ == "__main__":
    app = QApplication()

    w = MainWindow()

    w.show()
    app.exec_()

```

Clicking the button results in a "RuntimeError: Internal C++ object (PySide6.QtGui.QWindow) already deleted."

**Comment by githubuser0xFFFF** [comment]
Are you sure, that window handles are valid before the application event loop has been started? You create a test the window handle in the constructor before the event loop is started. I'm not sure, if this works. Please check, if the handle is valid after the start of the event loop.

**Comment by githubuser0xFFFF** [comment]
Dock widgets that are not visible, because they are not the active widget in a dock area, do not have a parent QWidget. They are removed completely from the layout system for preformance reasons. Have a look `CDockAreaLayout`. This could be the reason, that the window handle is not valid. 

So if you would like to get the window handle of the dock widget in a floating dock container, you should use `DockWidget->dockContainer()->windowHande()` instead.

**Comment by VitalyName** [comment]
Interesting case I have found, if split 
`handle = floating_dock.window().windowHandle()`
to 2 code lines 
`w = floating_dock.window()
 w.windowHandle()
`
It is works fine

Also it is amazing You can just add line, but keep second line, it is works fine too.
`
w = floating_dock.window()
handle = floating_dock.window().windowHandle()
`
Sleeps and print(floating_dock.window()) without creating variabale do not works

Is it event loop issue?

**Comment by VitalyName** [comment]
oh, maybe it is python wrapper issue
https://github.com/mborgerson/pyside6_qtads/issues/34
