### ISSUE TITLE
Floating windows size will shrink when moving the main window - Qt Bug 118118

### ISSUE THREAD

**Issue by LiuPeiqiCN** [githubuser0xFFFF/Qt-Advanced-Docking-System#580]
![Animation](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/7535781/aa0d98cf-7045-41e4-b18a-63d098edd505)

This issue is quite strange. I haven't encountered it before. This is the sample program, and I haven't made any modifications. I compiled it after pulling the latest code yesterday.

Env: Win11, VS2022, Qt6.6.0

**Comment by githubuser0xFFFF** [comment]
Please test with Qt 6.5.3 and report your results.

**Comment by LiuPeiqiCN** [comment]
I have installed Qt5.15.2/Qt6.5.3/Qt6.6.0 on my PC. ADS is working fine with Qt5.15.2 but causes this issue with Qt6.5.3 and Qt6.6.0.

**Comment by LiuPeiqiCN** [comment]
I upgraded from Qt6.5.3 to Qt6.6.0 a week ago, and I am sure I correctly compiled and invoked Qt6.5.3 just now. The issue persists even with the old version of ADS/Qt6.5.3 that I left behind. However, I am certain that I didn't have this problem when using ADS/Qt6.5.3 before. Could it be related to my recent system update (Windows 11, version 23H2)? I don't know what happened so strange.

**Comment by githubuser0xFFFF** [comment]
I can reproduce the prblem here with Qt 6.5.3, MinGW 11.2 and Windows 11 23H2. But the problem is not ADS. I have built and tested the `dockwidgets` example that comes with Qt 6.5.3 and I can also see the problem:

![DockWidgetError](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/4239304/158eb7e4-74e2-4bd1-a553-7b9a3b664fa3)

The next step is, to find out, if the problem is related to Windows 11 23H2 or if this problem is also reproducible on Windows 10 or earlier Windows 11 versions.

**Comment by githubuser0xFFFF** [comment]
I can  reproduce the problem also on Windows 10 with the Qt 6.5.3 application. Maybe you can test an earlier Qt version before 6.5.3.

**Comment by githubuser0xFFFF** [comment]
The problem is caused by the Qt Bug [118118](https://bugreports.qt.io/browse/QTBUG-118118). Here the text from the bugreport:


> When moving an application's main window, any floating QDockWidgets will gradually resize to their minimum size. This is easily reproduced in the dockwidgets example with no alterations. In Qt 6.5+, the example is in qtbase at tests/manual/examples/widgets/mainwindows/dockwidgets. In Qt 6.4.3, the example is in qtbase at examples/widgets/mainwindows/dockwidgets.
> 
> Steps To Reproduce:
> 
>     Build the example in Qt Creator against Qt 6.5.3+ (6.6.0 or 6.7.0 snapshot will also work).
>     Run the example.
>     Detach one or more docks so that they are floating.
>     Move the main window around.
>     Observe that the floating QDockWidgets size gradually reduces with each movement of the main window.
> 
> This did not occur in Qt 6.4.3 or Qt 6.5.2.
> 
> If you set a minimum size/width/height for the QDockWidget, it will resize down to that minimum.

To avoid the bug go back to Qt version 6.5.2.
