### ISSUE TITLE
FocusHighlighting is broken after detaching a dock widget (float)

### ISSUE THREAD

**Issue by iam-peter** [githubuser0xFFFF/Qt-Advanced-Docking-System#581]
After starting the demo application and dragging out any focusable dock widget the focus behavior is broken. In the attached video you can see me clicking on a bunch of docked dock widgets after detaching a dock widget (make it float) that not get focused (tab isn't going to turn blue).
This can be fixed clicking on a tab of any docked dock widget. Afterwards the focus behavior acts normal again.

Tested with Qt 6.4.3 and Qt 6.5.3 on Ubuntu 22.04

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/7542157/166b0489-9126-42c0-a95b-f183a5c94ce0

**Comment by iam-peter** [comment]
This issue is also present on Windows. It is about the `m_tabPressed` not being reset to `false` after dragging a tab. I fixed it by placing the reset in `CDockWidgetTab::mouseReleaseEvent` outside the switch statement. Have a look at the diff below.

```
diff --git a/src/DockWidgetTab.cpp b/src/DockWidgetTab.cpp
index 040939a..941138a 100644
--- a/src/DockWidgetTab.cpp
+++ b/src/DockWidgetTab.cpp
@@ -419,13 +419,10 @@ void CDockWidgetTab::mouseReleaseEvent(QMouseEvent* ev)
                         ev->accept();
                         d->FloatingWidget->finishDragging();
                         break;
-
-               default:
-                       if (CDockManager::testConfigFlag(CDockManager::FocusHighlighting))
-                       {
-                               d->focusController()->setDockWidgetTabPressed(false);
-                       }
-                       break; // do nothing
+               }
+               if (CDockManager::testConfigFlag(CDockManager::FocusHighlighting))
+               {
+                       d->focusController()->setDockWidgetTabPressed(false);
                }
        } 
        else if (ev->button() == Qt::MiddleButton)
```

**Comment by githubuser0xFFFF** [comment]
@iam-peter Thank you for the bug report - I can reproduce this on Windows. Thank you also for the bug fix. I will review and test it and then integrate it.
