### ISSUE TITLE
DockManager restore dockwidget function

### ISSUE THREAD

**Issue by bigRacoon** [githubuser0xFFFF/Qt-Advanced-Docking-System#584]
Hello. I have some problems with understanding of restoreState process. I can see in your Demo example that we can restore the state of our dockwidgets by pressing a button for example. But how to do this automatically? I want to do something like this: 1. Load my application. 2. Restore the state of dockwidgets automatically without pressing a button or triggering QActions in a menu. 3. Show the main window with the restored dockwidgets state. 
I just cannot understand when i should call restoreState function for my dockManager. When i do it in main.cpp after mainWindow.show() it restores all dockwidgets but floating dock widgets. I can see them showing while i try to debug the program but at some moment they just stop showing like someone made them not visible anymore. I tried to use QTimer::singleShot in my main.cpp before calling app.exec() to be sure that i am trying to restore after eventLoop started but it didn't help.
If i restore the state and minimize and then maximize the mainWindow by pressing the standards window button all restored floating widgets become visible. If i made the menu action for restoring state like in a Demo everything is work fine.
What am i missing? Thank you

**Comment by githubuser0xFFFF** [comment]
Just uncomment line 789 in the demo application and the demo application properly saves and restores its state.

```c++
...
setGeometry(QStyle::alignedRect(
    Qt::LeftToRight, Qt::AlignCenter, frameSize(),
    QGuiApplication::primaryScreen()->availableGeometry()
));

d->restoreState();
d->restorePerspectives();
...
```

**Comment by bigRacoon** [comment]
Hello. I tried. Same problem. Restored floating widgets not visible until i collapse and then expand back the main window

**Comment by githubuser0xFFFF** [comment]
Then something is wrong on your side. I do not see this problem in Windows 11 and in Ubuntu 20.04 an cannot reproduce it.
