### ISSUE TITLE
crash at  `constQObject *QMetaObject::cast(const QObject *obj) const` when close window

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [githubuser0xFFFF/Qt-Advanced-Docking-System#585]
## screenshots:
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/52443370/94f0ead4-30b7-4466-b505-2d28137022fd)

## Reproduction steps

1. open dockindock project
2. drag group1 to floating window

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/52443370/38dcc5f5-bd48-4db8-83e3-f267ca0559e6)

3. drag group1 into the top of minwindow
like this:
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/52443370/3da25820-3916-4e77-bfc9-46c3c2a95cf0)

4. close the window. It crash at `const QObject *QMetaObject::cast(const QObject *obj) const`

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/52443370/d460fcd6-9f6d-4eb0-9210-de0c9a678353)

## Env

OS: Ubuntu22.04 x11
Qt version: 5.15.2

**Comment by githubuser0xFFFF** [comment]
Thank you for your bug report - i can reproduce it. The error is not a ADS library issue but an issue with the dockindock example. The example was a third party contribution by a user (see #308). It shows some "hacked" functionality that is not part of the ADS library.

I reported the issue to the author. You have two options now: you can try to fix the example by yourself and provide a pull request or you can ask the author. If the example is not fixed within the following two weeks, I will remove it from the examples.

**Comment by githubuser0xFFFF** [comment]
The author of the dockindock example jut commited a fix for this issue to the master branch. Checkout the master branch and test if the error has been fixed.
