### ISSUE TITLE
Destruction of CDockWidget inside a CFloatingDockContainer

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#594]
Hello,

I have a problem with the destruction of the floating widgets. The destructors of CDockWidgets are not always called when the application is closed if the docks are in floating mode.
It tested it with the sample DeleteOnCloseTest.

To repro it:
- add two more docks in the app ("test 1" and "test 2")
- make the "test 1" dock a floating widget
- put the "test 2" dock inside the "test 1" floating widget (over the "test1" widget, no problem when it is on a side)
- close the app and see that only two CDockWidgets are destroyed ("test 0" and "test 2"), the third one will never be destroyed ("test 1")

See the case in the attached screenshot. Thanks

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/33324685/769e687f-4d3d-4075-8752-1f28b936d836)

**Comment by githubuser0xFFFF** [comment]
Thank you for this bug report. Please try to debug the issue in QtCreator and provide a pull request to fix the issue - thank you.

**Comment by githubuser0xFFFF** [comment]
Just fixed it for you - feel free to donate something.
