### ISSUE TITLE
Crashes when the floating widget moves to the dock manager and then tries to drag it back

### ISSUE THREAD

**Issue by artthirt** [githubuser0xFFFF/Qt-Advanced-Docking-System#597]
Systems: Windows 11 and Linux MInt 21.2.
Qt: 5.15.2 and 6.2.4

An example to reproduce
1. Run the "SimpleExample" app from examples.
![img_1](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/13047528/45a65d4c-c8e0-4fd7-a063-7762698588a8)
2. Drag the docker widget to a floating state.
![img_2](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/13047528/8e09e19c-6491-4463-a47c-65446d6e60a6)
3. Place the floating widget back in the container.
![img_3](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/13047528/a586efe9-2e0c-4b5c-a71c-a37add23ade2)
4. Try dragging this widget back to the floating state
![img_4](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/13047528/0b527113-bf0d-445c-8d68-632c0705130e)

It seems that widgets are not deleted when calling the CDockContainerWidget::dropFloatingWidget method and are deleted in the CFloatingDockContainer destructor.

Appears after the commit 7abc698d099205b424ad89d7503040f55cc8df1e

**Comment by githubuser0xFFFF** [comment]
Thank you - fixed with commit 9bdefd60550e08893f3620c2ef76e26bb43989e0
