### ISSUE TITLE
Abou topLevelChanged and Resize

### ISSUE THREAD

**Issue by cloudandzack007** [githubuser0xFFFF/Qt-Advanced-Docking-System#601]
I connect the Singnal [ads::CDockWidget::topLevelChanged]

`connect(tmp, &ads::CDockWidget::topLevelChanged, this, [&](bool topLevel) 
{
		ads::CDockWidget* dockw = ((ads::CDockWidget*)sender());
});`

I want to konw where is the dockw? left,right,bottom or top?
And if it is left or right，i want to resize dockw.
How to do it?
Thank you

**Comment by githubuser0xFFFF** [comment]
What do you mean with left or right?

**Comment by githubuser0xFFFF** [comment]
Just play around a little bit - you will find it out by yourself.
