### ISSUE TITLE
Switch between ads::CDockWidget

### ISSUE THREAD

**Issue by dawin64** [githubuser0xFFFF/Qt-Advanced-Docking-System#602]
Hi I have a question, is it possible to switch between ads::CDockWidget tabs? I couldn't find any information on this and setDockWidgetFocused does not work as i thought, it only temporarily switches the blue highlight behind the tab, but not the widget itself. The highlight reverts when the window is moved.

**Comment by githubuser0xFFFF** [comment]
Try `CDockWidget::raise`

```` c++
    /**
     * Brings the dock widget to the front
     * This means:
     * 	- If the dock widget is tabbed with other dock widgets but its tab is not current, it's made current.
     * 	- If the dock widget is floating, QWindow::raise() is called.
     * 	This only applies if the dock widget is already open. If closed, does nothing.
     */
    void raise();
```

**Comment by dawin64** [comment]
Thank you. It works for stacked tabs but not when two CDockWidget are next to each other. the blue highlight does not jump to the other CDockWidget, is this possible?
