### ISSUE TITLE
AutoHide widgets disapears when no widget is visible

### ISSUE THREAD

**Issue by n-elie** [githubuser0xFFFF/Qt-Advanced-Docking-System#604]
Hello,

When closing the last docked widget, all autohide widgets disappear.
For example, in the demo app:
![qtads](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/40382614/7cb0e13f-3aa5-4b7a-a018-1f93880080cf)
Expected behavior would to keep the autohide container visible

**Comment by githubuser0xFFFF** [comment]
Fixed in master

**Comment by n-elie** [comment]
Thank you so much
