### ISSUE TITLE
Horizontal scrolling of CDockAreaTabBar

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#607]
A user of my application suggested the possibility of scrolling through the tabs in the case there are too many to fit all at once.

Looking through the code it seems horizontal scrolling is supposed to be implemented already?

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/6b3b7750cb9c04620b2d6494c0c43188f4461cb7/src/DockAreaTabBar.cpp#L160-L172

I tested with the latest `deleteonclose` example, created several tabs, and wasn't able to scroll. I could not get any break points to hit on this method.

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/3694843/226eed40-05d9-4168-bc86-16084ad6404f)

I'm not overly familiar with Qt's event system so not sure if some other widget is eating these mouse wheel events or what.

**Comment by dail8859** [comment]
I did some testing and confirmed `CDockAreaTabBar`'s widget `TabsContainerWidget` is eating the wheel events. 

In the constructor:

```cpp
CDockAreaTabBar::CDockAreaTabBar(CDockAreaWidget* parent)
```

After the `TabsContainerWidget` is created I can set it to be transparent for mouse events:

```cpp
d->TabsContainerWidget->setAttribute(Qt::WA_TransparentForMouseEvents, true);
```

And then scrolling works for the `CDockAreaTabBar`. This is _obviously_ not the right solution as you can no longer click on tabs, but it does prove the root issue.

**Comment by githubuser0xFFFF** [comment]
Thank you for your feedback. There is no plan to implement scrolling of tabs because the user can always use the tabs menu to select a tab - this is quicker and the names are not elided so this is the recommended use. Tabs are only better if there are not many open tabs.
