### ISSUE TITLE
Question: Is it possible to have the tabbar on the side 

### ISSUE THREAD

**Issue by sunderme** [githubuser0xFFFF/Qt-Advanced-Docking-System#617]
Hi,
I am looking at a extension on texstudio GUI.
There, we have a tabbar to the left with icons only (which show tooltips of the "dock" name).
Can this be replicated with Qt Advanced docking system ? 
A tabbar on top simply takes too much space ...

**Comment by githubuser0xFFFF** [comment]
I think, this could be possible. Just try it out.
