### ISSUE TITLE
Another crush calling restoreState

### ISSUE THREAD

**Issue by vlomov** [githubuser0xFFFF/Qt-Advanced-Docking-System#619]
MSVC 19
Qt 6.6.2
Release
master branch

[patch1.txt](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/14821719/patch1.txt)

try apply this to AutoHideExample mainwindow.cpp, compile and run. Click Bug button on the toolbar at least three times.
Possible fix:
[fix.txt](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/14821755/fix.txt)

**Comment by githubuser0xFFFF** [comment]
See #618 - the same comment is valid for this bug report
