### ISSUE TITLE
Tab cannot adjust it's height with global font size

### ISSUE THREAD

**Issue by helywin** [githubuser0xFFFF/Qt-Advanced-Docking-System#62]
In example
```
#include "MainWindow.h"
#include <QApplication>
#include <QFont>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QApplication::setFont(QFont("ubuntu", 20));
    MainWindow w;
    w.show();
    return a.exec();
}
```
result:
![2019-09-12_17-20](https://user-images.githubusercontent.com/38039316/64771895-503ab400-d582-11e9-8a63-211a2a8fc823.png)

**Comment by githubuser0xFFFF** [comment]
The commit b776fc24a66eda218ce9a01e3774d0467730df42 should fix this problem. The problem was also reproducible on Windows.

**Comment by helywin** [comment]
Thanks
