### ISSUE TITLE
4.3.1 Release Request

### ISSUE THREAD

**Issue by Zadrimj** [githubuser0xFFFF/Qt-Advanced-Docking-System#620]
This isn't so much an issue as a request.

There have been a lot of nice bug fixes that have gone into master that improve stability of floating dock widgets and reordering tabs.  I have pulled these changes locally and they resolve issues my users have reported.  However I am limited in my ability to distribute source changes that do not align with a released version.

Is there a timeline for when 4.3.1 will be released? Can I request it be sooner rather than later, please?

**Comment by githubuser0xFFFF** [comment]
Just released 4.3.0. Do you have a nice application that I can add to my showcase section?

**Comment by Zadrimj** [comment]
Thank you.

> Just released 4.3.0. Do you have a nice application that I can add to my showcase section?

Sorry, but at this time, I am not permitted to release it to the public.
