### ISSUE TITLE
Workspace restoring reset configuration flags with Qt 6.7.0

### ISSUE THREAD

**Issue by nitramr** [githubuser0xFFFF/Qt-Advanced-Docking-System#623]
It seems like there is an issue with layout restoring. I reproduced the issue in demo application.

Add the following configuration flag in demo application:

CMainWindow::CMainWindow(QWidget *parent)
```
// CDockManager::setAutoHideConfigFlags({CDockManager::DefaultAutoHideConfig});
CDockManager::setConfigFlag(CDockManager::DockAreaHasCloseButton, false);
CDockManager::setConfigFlag(CDockManager::DockAreaHasUndockButton, false);
CDockManager::setConfigFlag(CDockManager::DockAreaHideDisabledButtons, true);
```
Result:
![Bildschirmfoto vom 2024-04-06 18-17-46](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/15112256/8683ed0f-361c-47ea-bd0e-5297e692fafe)

Click on "Save State" and on "Restore State" and you get this:
![Bildschirmfoto vom 2024-04-06 18-17-52](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/15112256/8c9c0870-d6aa-4d97-8b12-39b59330447a)

If `CDockManager::setAutoHideConfigFlags({CDockManager::DefaultAutoHideConfig});` is enabled, the issue is not reproducible.

Qt 6.7.0 on Ubuntu 23.10

**Comment by nitramr** [comment]
It looks like it is a QT version specific issue.

I cannot reproduce it with Qt 6.8.0

**Comment by githubuser0xFFFF** [comment]
Ok, thank you for testing. I close the issue because it is a Qt issue.

**Comment by nitramr** [comment]
Just an update, I tested with a newer version of Qt 6.8.0 (from May, previous version was from January) and I can still reproduce it. Now it is misbehaving as in Qt 6.7.0.

I tried to debug it, but unsuccessfully yet.
