### ISSUE TITLE
dockmanager savesate only save the layout of first dock area

### ISSUE THREAD

**Issue by BarryArch** [githubuser0xFFFF/Qt-Advanced-Docking-System#626]
I want to save the dock layout to a file and reload it when reopen.
the code of save dock layout :
```cpp
    QFile file("VisualLayout.ini");
	if (file.open(QIODevice::WriteOnly))
	{
		QDataStream out(&file);
		out << _dockMan->saveState();
		file.close();
	}
```
and the code of load the config file:
```cpp
 QFile file("VisualLayout.ini");
	if (file.open(QIODevice::ReadOnly))
	{
		QByteArray ba;
		QDataStream in(&file);
		in >> ba;
		file.close();
        
		if (_dockMan->restoreState(ba))
		{
			qDebug() << QString("good");
		}
		else
		{
			qDebug() << QString("failed");
		}
	}
```
but it just reload the 1st dock area layout, and totally ignored other dock area.

**Comment by githubuser0xFFFF** [comment]
Please have a look into the demo application to learn how to save and restore dock manager states.

**Comment by githubuser0xFFFF** [comment]
Does save and restore work in the demo application?

**Comment by BarryArch** [comment]
Indeed, your demo program is functioning very well. However, I feel that my method of usage has been correct and in line with your demo program. Is there perhaps some key aspect that I might have overlooked?

**Comment by BarryArch** [comment]
DockWidget must have a widget set in order to be reloaded from configuration. This note is recorded here for anyone who might encounter the same issue.
