### ISSUE TITLE
CDockWidget allowed area

### ISSUE THREAD

**Issue by Intemporel** [githubuser0xFFFF/Qt-Advanced-Docking-System#628]
Is there a way to setup an allowed area for a CDockWidget, in my case I want it to be only at the bottom of the left of the central DockWidget, I can't found anything into CDockWidget class, and the setAllowedAreas from the return CDockAreaWidget, can only control which area is available inside this widget.
Thanks you for your help

**Comment by githubuser0xFFFF** [comment]
No, this feature is not available. Please have a look into this library, I think they have that feature:

https://github.com/KDAB/KDDockWidgets
