### ISSUE TITLE
Typo in DockManager.h

### ISSUE THREAD

**Issue by char101** [githubuser0xFFFF/Qt-Advanced-Docking-System#632]
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/6e63418798f4f27783322393bc724077452a985f/src/DockManager.h#L688-L691

Closing `\code` should be `\endcode`, this causes `CDockManager` class to be missing when generating documentation using doxygen.

**Comment by char101** [comment]
Also in (missing `\endcode`)

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/6e63418798f4f27783322393bc724077452a985f/src/DockOverlay.h#L266-L271

**Comment by githubuser0xFFFF** [comment]
Thank you. Please create a pull request
