### ISSUE TITLE
Library output name breaks windeployqt.exe use due to Qt6... prefix

### ISSUE THREAD

**Issue by ThomasKroes** [githubuser0xFFFF/Qt-Advanced-Docking-System#633]
`windeployqt.exe` sees `Qt6advanceddocking.dll` as a `native Qt6 dll` and therefore searches for it in the `bin` directory of the Qt distribution instead of next to the .`exe`. The only solution to this problem is to either:
- Copy `Qt6advanceddocking.dll` to the `bin` directory
- or rename for instance to `qtadvanceddocking.dll`

Steps to reproduce:
1. Create an executable with a dependency on Qt ADS
2. Compile it, this will give you an `exe` and a `Qt6advanceddocking.dll`
3. Now run `windeployqt` on either the `exe` or the dir in which it is contained
4. `windeployqt` will complain that it cannot find `Qt6advanceddocking.dll` in `qt_bin_dir/Qt6advanceddocking.dll`

**Comment by githubuser0xFFFF** [comment]
Thank you for your bug report. What is you proposal to fix this?
