### ISSUE TITLE
Cannot round trip window state settings using the DockManager

### ISSUE THREAD

**Issue by jmarquisbq** [githubuser0xFFFF/Qt-Advanced-Docking-System#634]
So we have a feature in our program (DREAM3D NX) in which we try to restore the windows after an unexpected crash using settings/backup files. We are having a problem with the sizing of the dock widgets though after the initial window's restore. I believe I've narrowed it down to something in the call to restoreState on the CDockManager. The call to restoreState does in fact restore the window state to how it was but then if I immediately call saveState again and save that to a file. The state that is restored from _that_ byte array does not match the original.

Initial restore (layout looks correct):
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/83971431/dd3a57a1-966a-4aaf-8804-3e50ad08793c)

Restore from byte array returned from CDockManager::saveState call immediately after call to restoreState:
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/83971431/d61be6f7-7479-4fec-9d4a-b10466b6d275)

We have seen this issue occur on various different os' but I am currently debugging this on a Windows 11 machine and we are up to date with the current head of develop (as of 4/24/2024 , commit 6e63418)

**Comment by githubuser0xFFFF** [comment]
Thank you for the bug report. I will look into it within the next few weeks.

**Comment by githubuser0xFFFF** [comment]
I cannot reproduce the problem with the demo application. If I click the **Save State** button and then the **Restore State** button and then again the **Save State** and the **Restore State** button everything works find.

Please provide a pull request for the demo application or a small sample application that allows me to reproduce the issue.

**Comment by imikejackson** [comment]
@githubuser0xFFFF Since our app is pretty large, we are going to walk the Demo application code and try to see what we are doing differently. Hopefully that will shed some light on our issue. Thank you for getting back quickly.

**Comment by githubuser0xFFFF** [comment]
I will reopen the issue, if the problem is in ADS code
