### ISSUE TITLE
Under AutoHideDockWidget, the setWindowTitle method cannot be synchronized to the pop-up screen

### ISSUE THREAD

**Issue by jenifly** [githubuser0xFFFF/Qt-Advanced-Docking-System#637]
Under AutoHideDockWidget, the setWindowTitle method cannot be synchronized to the pop-up screen

**Comment by githubuser0xFFFF** [comment]
Sorry, could you please elaborate. I do not understand what you mean. I cannot find the file or class `AutoHideDockWidget`.

**Comment by jenifly** [comment]
> Sorry, could you please elaborate. I do not understand what you mean. I cannot find the file or class `AutoHideDockWidget`.

like this...
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/22962492/defe4808-8b23-4d9b-a0b9-ec8171ad4ae9)

**Comment by jenifly** [comment]
> > You cannot set the window title explicetely via `setWindowTitle` because the windows title of the dock widget is its title you give in constructor.
> 
> That way, when I switch languages, the title of the widget cannot be changed

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/22962492/f6194fea-8214-4933-8b35-637bbc4de094)

**Comment by githubuser0xFFFF** [comment]
You need to set the custom window title earlier before you add the dock widget to the DockManager:

```c++
    TableDockWidget = new CDockWidget("Table 2");
    TableDockWidget->setWindowTitle("Custom Window Title");
```

works here

**Comment by jenifly** [comment]
> You need to set the custom window title earlier before you add the dock widget to the DockManager:
> 
> ```c++
>     TableDockWidget = new CDockWidget("Table 2");
>     TableDockWidget->setWindowTitle("Custom Window Title");
> ```
> 
> works here

yes, but it's calling
```c++
DockManager->addAutoHideDockWidget(SideBarLocation::SideBarLeft, TableDockWidget);
```
Then window title of the pop-up form cannot be changed.
 How can I change this window title?

**Comment by githubuser0xFFFF** [comment]
I don't know what you mean - this is how it looks like after the after the two lines above:

![2024-05-21_15h45_13](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/4239304/f33a3df7-e641-487c-916b-ef1b6c707d39)
