### ISSUE TITLE
C1001: An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by xumepoc** [githubuser0xFFFF/Qt-Advanced-Docking-System#64]
When I try to build the code I get "C1001: An internal error has occurred in the compiler" for line 56 in ads_globals.cpp

**Comment by githubuser0xFFFF** [comment]
Here it works.

**Comment by xumepoc** [comment]
Can you tell me on what compiler and Qt version it is working. I am encountering this error for the first time :D

**Comment by githubuser0xFFFF** [comment]
You can look into the Travis CI or Appveyor build server configurations to see all tests Qt and compiler combinations:

https://travis-ci.org/githubuser0xFFFF/Qt-Advanced-Docking-System
https://ci.appveyor.com/project/githubuser0xFFFF/qt-advanced-docking-system/branch/master

**Comment by xumepoc** [comment]
Thank you. I had to do a clean install of VS again and now is working just fine :D :D
