### ISSUE TITLE
Missing signal when a widget's docking container has changed

### ISSUE THREAD

**Issue by ensisoft** [githubuser0xFFFF/Qt-Advanced-Docking-System#643]
Not sure if this exists but I haven't found such signal in any of the relevant class headers.

Basically I have multiple top level windows (QMainWindows) (since I want to be able to display menu and toolbars) and I'm adding CDockAreaWidgets to them and moving docking widgets between the main windows works as expected but there doesn't seem to be any way to detect via signal when this has happened. There's a signal "topLevelChanged"' but that only indicates when the state changes between floating/docked. 

Any thoughts? Thanks !

**Comment by githubuser0xFFFF** [comment]
There is no such signal. I just tried to implement it but it is more complex then expected so I dropped the implementation - sorry. I just cannot spend that much time for a single user.
