### ISSUE TITLE
Combobox misbehaviour after undocking [python]

### ISSUE THREAD

**Issue by RubendeBruin** [githubuser0xFFFF/Qt-Advanced-Docking-System#648]
Not sure if this is a bug in Qt-Advanced-Docking-System or the python bindings, but after upgrading from 4.1 to 4.3 I have issues with comboboxes that fail to stay open. If I click the arrow the dropdown shortly shows up but then quickly disappears again. This happens only after undocking. The original correct behavior does not return when I dock it again.
note: the .gif movie loops, the correct behavior does not return until the app is restarted.

![pycharm64_kEIPP91VV8](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/34062862/62b48d5d-abfc-4b1b-8114-36ef349c52f1)

Reproduce:
```python
from PySide6.QtWidgets import (
    QApplication,
    QMainWindow,
    QComboBox,
)
import PySide6QtAds

app = QApplication()
mw = QMainWindow()

dock_manager = PySide6QtAds.CDockManager(mw)

dock_contents = QComboBox()
dock_contents.addItems(["one", "two", "three"])

dock = PySide6QtAds.CDockWidget("Demo", mw)
dock.setWidget(dock_contents)

widget = dock_manager.addDockWidget(PySide6QtAds.DockWidgetArea.TopDockWidgetArea, dock)

mw.show()

app.exec()
```

Using:
```
PySide6_Essentials            6.7.1
PySide6-QtAds                 4.3.0.1
```

Works as intended when using:
```
PySide6-Essentials            6.6.1
PySide6-QtAds                 4.1.0.3
```

**Comment by githubuser0xFFFF** [comment]
This is not an ADS issue

**Comment by alex-tdrn** [comment]
@RubendeBruin this seems to be a bug introduced in Qt 6.7.0, unrelated to ADS
https://bugreports.qt.io/browse/QTBUG-125149
So you can probably downgrade qt and keep ADS at the latest version
