### ISSUE TITLE
Re-docking of floating docks without window decoration

### ISSUE THREAD

**Issue by Tectu** [githubuser0xFFFF/Qt-Advanced-Docking-System#649]
On window managers that don't have window decoration (i.e. no "title bar"), it's impossible to drop/dock a floating dock back into a different dock area.

Is it possible to allow dropping/docking a dock without a title bar?
Alternatively, is there a way to force showing the dock tab even if the (floating?) dock area/container only contains one dock?

**Comment by githubuser0xFFFF** [comment]
ADS only supports standard Ubuntu with default window manager.

**Comment by Tectu** [comment]
Is there a way to force showing the dock tab even if the (floating?) dock area/container only contains one dock?
