### ISSUE TITLE
Change CDockWidget objectName

### ISSUE THREAD

**Issue by tezma90** [githubuser0xFFFF/Qt-Advanced-Docking-System#65]
I need to be able to change the objectName of CDockWidget, and so the name they are "registered"with. The problem is that DockWidgetsMap inside CdockManager is private and I can not rename the entry without removing the CDockWidget (and losing its position) and re-adding it.

**Comment by githubuser0xFFFF** [comment]
Could you please elaborate a little bit more, what you would like to do and why you ned to change the objectName of CDockWidget

**Comment by tezma90** [comment]
I know now that what I was trying to do was wrong.
I know that the objectName should not change, and I should just use random unique objectName for DockWidgets. Since I need to save the state of my windows and DockWidgets I should save and restore said unique name before restoring the state from DockManger.
