### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by Ornycar** [githubuser0xFFFF/Qt-Advanced-Docking-System#650]
Hello!

I'm on debian 12 and i'm trying to link my executable statically against this lib, but i'm having this error :

**libqt5advanceddocking_static.a(ads_globals.cpp.o): undefined reference to symbol 'xcb_get_atom_name_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line**

I thought maybe it is related to this : https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/270 but it seems this issue has been fixed.

Also, i can link successfully on mac and windows.

Thank you for your help and tell me if you need more details!

**Comment by githubuser0xFFFF** [comment]
Sorry, I do not have Debian 12 here. Please try to fix this issue by yourself. Would be great if you could provide a pull request that solves the issue.
