### ISSUE TITLE
Widget not getting complete focus even after tab is clicked

### ISSUE THREAD

**Issue by manikSom** [githubuser0xFFFF/Qt-Advanced-Docking-System#652]
We are developing an application with ads and found it quiet useful. And stumbled upon an Issue. I have replicated it in demo example in the video below. 

I have just 2 dockable widgets. One Filesystem 0 and other is Calendar 0.

- Initially I mouse click on Calendar 0 on Tab title bar and it is in Focus. Then I click on a date below and with Keyboard down arrow key press I go down to other future months.
- Then I mouse click on Filesystem 0 Tab title bar and it gets the Focus highlighting. But now when I press Keyboard down arrow to go down, it happens in Calendar widget where again the dates start to down. I think an user will expect movement to happen in the Filesystem tab as they have clicked its tab title bar to activate it.

How can I make sure that the complete focus, even wrt to keyboard down arrow press event happens in the widget whose title bar has been clicked by the user (and thereby has the focus)?

(Using- Windows Qt6.5 )

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/39118847/3fccf8f3-fc80-446b-a8c1-d16c1b4fe616

**Comment by githubuser0xFFFF** [comment]
This is intentionally. But there is a dock manager signal `focusedDockWidgetChanged`. You can connect to this signal and then set the focus explicitely in the connected slot.
