### ISSUE TITLE
Wheel event on DockAreaTabBar

### ISSUE THREAD

**Issue by ma-robox** [githubuser0xFFFF/Qt-Advanced-Docking-System#654]
I don't receive the wheelEvent in DockAreaTabBar (using the simple example with many tabs as per issue #641 ). I think it is because with many tabs the event is sent to one of the tabs and not the tab bar.
To solve this I have to add a case for CDockAreaTabBar::eventFilter for QEvent::Wheel.

```cpp
bool CDockAreaTabBar::eventFilter(QObject *watched, QEvent *event)
{
    bool Result = Super::eventFilter(watched, event);
    CDockWidgetTab* Tab = qobject_cast<CDockWidgetTab*>(watched);
    if (!Tab)
    {
        return Result;
    }
    switch (event->type())
    {
    case QEvent::Hide:
        Q_EMIT tabClosed(d->TabsLayout->indexOf(Tab));
        updateGeometry();
        break;
    case QEvent::Show:
        Q_EMIT tabOpened(d->TabsLayout->indexOf(Tab));
        updateGeometry();
        break;
    // Setting the text of a tab will cause a LayoutRequest event
    case QEvent::LayoutRequest:
         updateGeometry();
         break;

    // Manage wheel event
    case QEvent::Wheel:
        wheelEvent((QWheelEvent* )event);
        break;

    default:
        break;
    }
    return Result;
}
```

Another issue I have is that while dragging a tab, and also scrolling with the mouse wheel, the dragged tab is not repainted where the mouse is, but it is dropped correctly in that position in the tab bar.

https://github.com/user-attachments/assets/f5207308-536a-44fa-b790-0aaa672fa5e4

**Comment by dail8859** [comment]
I looked into this at one time in #607 but I don't know enough about Qt's event handling to propose a solution at that time. But yes I also noticed the wheel events were not getting passed to the correct control. Just my two cents :)

**Comment by githubuser0xFFFF** [comment]
Fixed this in master. Scrolling the tab bar with the mouse wheel should work properly now. Scrolling the tabg bar is only bossible if no tab is currently dragged.
