### ISSUE TITLE
Inconsistency in TabsMenuButton after perspective changed

### ISSUE THREAD

**Issue by manikSom** [githubuser0xFFFF/Qt-Advanced-Docking-System#656]
Hallo, I found that TabsMenu button is shown after perspective change even though there is space in Tab title bar and vanishes when the splitter is moved. Shown in the Video.

These are my Config flags setting-

    ads::CDockManager::setConfigFlag( ads::CDockManager::DockAreaHasCloseButton, false );
    ads::CDockManager::setConfigFlag( ads::CDockManager::AllTabsHaveCloseButton, true );
    ads::CDockManager::setConfigFlag( ads::CDockManager::DockAreaHasUndockButton, false );
    ads::CDockManager::setConfigFlag( ads::CDockManager::DockAreaDynamicTabsMenuButtonVisibility, true );
    ads::CDockManager::setConfigFlag( ads::CDockManager::DisableTabTextEliding, true );

In the Video Example you can see that im creating Perspective A and B. When I create Perspective B there is no Tabsmenu button. But after I choose B in the combo box TabMenuButton is visible, but after I move the Splitter it goes away and reappears when I move the splitter to make the tabTitle bar really small (which is okay). I wanted to report this issue.

When the Flag DisableTabTextEliding is not set as true. This Issue doesn't occur. (Just wanted to mention it as it might help with context and is similar to the issue #653 )

-Additionally inside our application when we create new tab widgets and add to a dock area, even thought the title bar is filled the TabMenuButton isn't visible, But if we move the splitter a bit then it comes up. This has nothing to do with perspective change per say but with opening new Tab widgets alone.

https://github.com/user-attachments/assets/96e742dd-d99a-4b51-a4a7-7002adfaed6d

**Comment by githubuser0xFFFF** [comment]
Fixed in master
