### ISSUE TITLE
CDockWidget::toggleView signal not triggering when closing due to CDockManager::restoreState

### ISSUE THREAD

**Issue by juangburgos** [githubuser0xFFFF/Qt-Advanced-Docking-System#66]
The [CDockWidget::toggleView](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/664a1674abdb346d0c101028a6679bc54211d40c/src/DockWidget.h#L420) signal is not triggered with the `Open` argument to `false` when a `CDockWidget` gets closed due to a call to `CDockManager::restoreState`.

The signal is triggered correctly with the `Open` argument to `true`  for the `CDockWidget`s that get opened as a result to the `CDockManager::restoreState` call. So the issue is just for the `CDockWidget`s that get closed.

I also tried with the  `CDockAreaWidget::viewToggled` signal and the behaviour is the same. I don't know if it is supposed to work this way.

**Comment by githubuser0xFFFF** [comment]
For all dock widgets, that are not part of the perspective, this is true. That means, if the perspective contains closed dock widgets, then the **viewToggled(false)** signal will be properly emitted. If the dock widgets are not part of a perspective, then the **viewToggled** signal is not emitted. This is the relevant code:

```c++
void DockManagerPrivate::restoreDockWidgetsOpenState()
{
    // All dock widgets, that have not been processed in the restore state
    // function are invisible to the user now and have no assigned dock area
    // They do not belong to any dock container, until the user toggles the
    // toggle view action the next time
    for (auto DockWidget : DockWidgetsMap)
    {
    	if (DockWidget->property("dirty").toBool())
    	{
    		DockWidget->flagAsUnassigned();
    	}
    	else
    	{
    		DockWidget->toggleViewInternal(!DockWidget->property("closed").toBool());
    	}
    }
}
```

**Comment by juangburgos** [comment]
That might be it, because I am no using the perspectives API functionality, just using `CDockManager::restoreState` directly.

**Comment by githubuser0xFFFF** [comment]
Sorry, I mean for all dock widgets that are not part of a saved state - a perspective is just a saved state with a name. That means, if you current layout contains dock widgets, that are not in your saved state, then for these widgets the viewToggled signals is not emitted.

So you would like to react on this signal, if a dock widget gets closed by the restore functionality? Then I would need to add this functionality.

**Comment by juangburgos** [comment]
Yes, because I was trying to see the possibility of an exteral tree where some of the items would open or close `CDockWidget` instances. The tree items would have checkboxes to indicate if the `CDockWidget` is opened or closed. So I need a mechanism to sync the `CDockWidget` state with the tree item checkbox.

I thought the `CDockWidget::toggleView` would do the job, but now I cannot detect when a `CDockWidget` is closed if `CDockManager::restoreState` is closed.

For the time being I can uncheck all items using the `CDockManager::restoringState` but this might become inefficient when I have a lot of items.

**Comment by githubuser0xFFFF** [comment]
Ok, I will try to fix this

**Comment by githubuser0xFFFF** [comment]
I just pushed a commit that should fix this problem. Please test it and tell me if I can close this issue.

**Comment by juangburgos** [comment]
Yes it is fixed! Works like a charm. Thank you very much.
