### ISSUE TITLE
Fixed Non-Resizable Frame alongside Dock Manager

### ISSUE THREAD

**Issue by matinmoezzi** [githubuser0xFFFF/Qt-Advanced-Docking-System#661]
#### Description:
I am currently working with the `PyQtAds` in a PyQt5 application. Based on the examples, the `CDockManager` takes the QMainWindow as parent and utilizes the `setCentralWidget()` method of `QMainWindow` to create a dock manager that occupies the entire window. However, I need to achieve the following layout:

1. A **fixed frame** at the bottom of the window that:
   - Is **static** (cannot be docked or resized).
   - Is **non-closable**.
   - Remains pinned to the bottom of the window.

2. The **dock manager** should occupy the rest of the window above this fixed bottom frame.

#### Expected Behavior:
- The dock manager should take up all the space in the window except for the fixed area at the bottom.
- The fixed bottom frame should not be affected by the dock manager’s resizing, docking, or other interactions.
- The layout should maintain the fixed bottom frame at the bottom, regardless of the dock manager's operations.

#### Actual Behavior:
The current implementation using `CDockManager` occupies the entire window, leaving no space for the fixed bottom frame.

#### Request:
I would like to know how to implement a layout where the `CDockManager` occupies the main area of the window, and a fixed, static, non-resizable, non-closable frame is pinned to the bottom of the `QMainWindow`.

#### Additional Information:
- **Environment**: PyQt5, pyqtads==3.8.1
- **Code Example**: 
```
        container_widget = QWidget(self)
        self.setCentralWidget(container_widget)

        self.central_widget = QWidget()
        QtAds.CDockManager.setConfigFlag(QtAds.CDockManager.FocusHighlighting, True)
        self.dock_manager = QtAds.CDockManager(self.central_widget)
        self.central_widget.setLayout(self.dock_manager.layout())

        self.bottom_widget = self._init_bottom_panel()

        # Set up the layout to arrange the widgets
        layout = QVBoxLayout(container_widget)
        layout.addWidget(self.central_widget)
        layout.addWidget(self.bottom_widget)

        # Set the stretch factors
        layout.setStretch(0, 1)  # Central widget expands
        layout.setStretch(1, 0)  # Bottom widget stays fixed
```
This code doesn't work.
Any guidance or examples on how to achieve this layout would be greatly appreciated. Thank you!

**Comment by githubuser0xFFFF** [comment]
Please have a look into the Sidebar example. You just need to change the layout from horizontal to vertical.

**Comment by matinmoezzi** [comment]
Thanks!
