### ISSUE TITLE
Add the possibility to open an auto-hide dock on a drag & drop

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#663]
In the main window of the application, we have a dock with some data (in the screenshot it's the text "text").
We want to have the possibility to drag & drop the data into an auto-hide dock.

For now, when the drag & drop is done on the auto-hide dock a forbidden icon is displayed and the dock is not opened. It could be great to be able to open the auto-hide dock to be able to complete the drag & drop.

![image](https://github.com/user-attachments/assets/0dca7afb-15f3-4633-80bf-24b560d648a3)

The test has been done with the auto-hide sample

**Comment by githubuser0xFFFF** [comment]
Thank you for the feature request. If I have some time, I will try to implement this.

**Comment by TheBoje** [comment]
Hi @githubuser0xFFFF would you mind if I gave the feature request a try? I messed around and got some stuff working already.

**Comment by githubuser0xFFFF** [comment]
Implemented with pull request #667
