### ISSUE TITLE
QML

### ISSUE THREAD

**Issue by haikalsyed** [githubuser0xFFFF/Qt-Advanced-Docking-System#67]
Hi,
I would like to integrate this awesome layout that you have created into my QML project.

Do I use your code as a backend and make my QML front end or use QQuickView -> QWidget -> and add it to the dockmanager?

I tried using the latter but it seems buggy and crashes. Maybe I went wrong somewhere.

**Comment by githubuser0xFFFF** [comment]
The advanced docking system is meant for Qt widgets applications.
