### ISSUE TITLE
Is CDockManager designed to be used as a Singeleton?

### ISSUE THREAD

**Issue by zyrkiel** [githubuser0xFFFF/Qt-Advanced-Docking-System#671]
Hello,

First, thanks for your library that is quite handy!
I am developping a project that needs a dynamic organization of dockable/floating widgets and your library seems to fit the needs.

However, I have few questions/remarks about the documentation and how to use it properly. I hope you don't mind if I submit several issues. If that concerns you, please tell me, so I gather the issues into one general issue about the library mechanism.

So, my first question is: Is `CDockManager` designed to be used as a Singeleton?

I have tried to instantiate the class twice, so I can create a `CDockWidget` inside a `CDockWidget` in order to have a panel that is movable/dockable, but that is first attached to a `CDockWidget`. The purpose, in order to hide the panel with the attached `CDockWidget` when it's not focused, But the panel could be grabbed and moved outside the `CDockWidget` and placed in the central area.

I have seen that there is a DockInDock example, but it's not quite what I am looking for, since the docks from a dockindock cannot be moved to an upper level/other CDockManager area. I think [KDDockWidgets](https://github.com/KDAB/KDDockWidgets) handles this feature but not sure, and I was wondering if this feature could be envisageable?

Do you have use cases where we can manipulate safely several `CDockManager`? 
Is it planned the `CDockWidget` of different `CDockManager` interacts with each other?

**Comment by zyrkiel** [comment]
Thank you for the information!

Have you consider to document this design, in order to prevent bad use cases?  
Maybe moving the constructor to private and give access to an `instantiate`/`get` method (with the same argument as the constructor) that retums a static instance of the class could help?

**Comment by githubuser0xFFFF** [comment]
`CDockManager` is intended to be used as a singleton but it is not forbidden to use mutliple dock managers - like it is done in dockindock example. It think the demo application shows quite good how the `CDockManager` class should be used.
