### ISSUE TITLE
Add Anchor mode to AutoHide

### ISSUE THREAD

**Issue by zyrkiel** [githubuser0xFFFF/Qt-Advanced-Docking-System#672]
Hello,

I have try your AutoHide feature, and I was wondering if it could be possible to improve it with a new mode.

The current behavior of the AutoHide seems to show the target `CDockWidget` **over** the central area when clicked. I was wondering if it could be possible to have a "Anchor"(/"AutoPin") mode that, if the AutoHide target `CDockWidget` is shown, the `CDockWidget` would be shown like it is pinned (even if it is not pinned) when clicked. 
The behavior of showing the dock widget will be the same as pinning it, but without pinning it. It would be possible to combined this "AnchorMode" with "AutoHideShowOnMouseOver". So it's not quite an auto pin.
As a results, the `CDockWidget` would not appear over the other widgets when shown, but will force them to resize, even if not pinned.

I hope I have been clear enough.

Please tell if it could be feasible, or if it is already possible?

**Comment by githubuser0xFFFF** [comment]
This is not possible at the moment but I think it is feasible. I will not implement it, because I have no use case for this feature. But if you create a pull request, then I would be willing to review it to decide if it is worth merging this feature into the library,

**Comment by zyrkiel** [comment]
Thank you very much for your answer! 

I will study if this feature is really needed by our project. If so, I will propose you a PR.
