### ISSUE TITLE
Dark screen on Q3DSurface

### ISSUE THREAD

**Issue by mib383** [githubuser0xFFFF/Qt-Advanced-Docking-System#674]
Hello. I am trying to implement dock widget based on Q3DSurface. And it does not work properly. While it is docked - it works ok:
![image](https://github.com/user-attachments/assets/39dd3c9f-349d-4f94-bda1-d3805d744eb7)

But when i am trying to undock it i have a "black screen". 

![image](https://github.com/user-attachments/assets/9797ca17-5f83-4040-bcf4-f9448a8db670)

How can i solve it?
Thx

**Comment by githubuser0xFFFF** [comment]
Try to set the following in your main function before creating the QApplication object:

```c++
QApplication::setAttribute(Qt::AA_ShareOpenGLContexts); // required for dockings system when using OpenGL widgets like Coin3D viewer
```
