### ISSUE TITLE
Deployment with "qt6advanceddocking" and windeployqt is broken

### ISSUE THREAD

**Issue by nolankramer** [githubuser0xFFFF/Qt-Advanced-Docking-System#682]
# Issue Summary

`windeployqt` is a very popular tool for [deploying windows executables](https://doc.qt.io/qt-6/windows-deployment.html) that are built against Qt.

The tool itself simply scans the PE dependencies, and helps prepare a deployment directory by copying dependent libraries, assets (such as files used by .qrc), translation files, and of course the executable itself.

One flaw, is that **while scanning for dependent libraries, it assumes that ANY library starting with the name Qt5 or Qt6 is a Qt library**.
This can be seen in the `windeployqt` source code here: https://code.qt.io/cgit/qt/qtbase.git/tree/src/tools/windeployqt/main.cpp#n799

Why is this an issue at all? Because **Qt libraries will always be searched for in the Qt installation directory**. This means that if a user has included Qt-Advanced-Docking-System in their build and tries to deploy their application, `windeployqt` will go looking the wrong place.
For example, if I have a build tree:
```
MyFunExe.exe
qt6advanceddockingd.dll
... other libs and assets ...
```
And try to deploy via `windeployqt ./MyFunExe.exe`, I'll get an error similar to this:
```
Unable to find dependent libraries of C:\Qt\6.6.3\msvc2019_64\bin\qt6advanceddockingd.dll :Cannot open 'C:/Qt/6.6.3/msvc2019_64/bin/qt6advanceddockingd.dll': The system cannot find the file specified.
```

## Ok, why is it our problem?

Because of [this line](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/f2378636e2a6a7ec0f8124fbe5d0770bce5bec0f/src/CMakeLists.txt#L74) in the advanceddocking's src CMakeLists.txt:
```
set(library_name "qt${QT_VERSION_MAJOR}advanceddocking")
```

The library name will either end up prefixed with either `qt5` or `qt6`, and `windeployqt` will assume it's a Qt library.

Now you may be thinking: "Well, this seems like a `windeployqt` issue, and not my problem." And normally, you'd be right - but it's unlikely that `windeployqt` will be changing this anytime soon, _and_ the tool does need some way to differentiate Qt libraries from user libraries. I'm not saying that `windeployqt` has a mindblowingly brilliant way of doing it, but it does work (except in cases like this).

## Possible Solutions

1. Recommended - change the name to not mimic that of a Qt library. `qadvanceddocking` is great, or even `qtadvanceddocking`. The `windeployqt` code above is strictly looking for "qt{VERSION}". So anything that avoids a version number works. This avoids confusion with Qt libraries. This is fast and easy to fix.

2. Raise and issue to Qt to fix `windeployqt` by adding an option to disable searching for specific dependencies in the Qt installation path. This will likely take a long time to get fixed, if at all.

**Comment by nolankramer** [comment]
I've opened a PR linked above to resolve the issue.

Would appreciate a review @githubuser0xFFFF

**Comment by githubuser0xFFFF** [comment]
Fixed in master

**Comment by githubuser0xFFFF** [comment]
Fixed
