### ISSUE TITLE
How to add a button into the tab bar

### ISSUE THREAD

**Issue by jankrassnigg** [githubuser0xFFFF/Qt-Advanced-Docking-System#684]
I'd like to have an button inside the tab bar, so that there is an obvious way for users to initiate the creation of a new tab. Something like most browsers do these days:

![image](https://github.com/user-attachments/assets/0b03e8cf-7f33-403b-b873-bd57f370046e)

Does ADS already have a feature for this? I wasn't able to find anything.

If not, any advice on how to do this? Any way to maybe add a button into the CDockAreaTabBar ? 
I could maybe also try to hack it, by just adding another tab into it, and trying to treat the tab activation like a button click, though I assume this will run into problems once the tab bar fills up.

**Comment by githubuser0xFFFF** [comment]
Have a look into the demo application. You can use a custom `CDockComponentsFactory` to create a title bar with an additional button. In the demo this is a help button:

```c++
//============================================================================
class CCustomComponentsFactory : public ads::CDockComponentsFactory
{
public:
	using Super = ads::CDockComponentsFactory;
	ads::CDockAreaTitleBar* createDockAreaTitleBar(ads::CDockAreaWidget* DockArea) const override
	{
		auto TitleBar = new MyDockAreaTitleBar(DockArea);
		auto CustomButton = new QToolButton(DockArea);
		CustomButton->setToolTip(QObject::tr("Help"));
		CustomButton->setIcon(svgIcon(":/adsdemo/images/help_outline.svg"));
		CustomButton->setAutoRaise(true);
		int Index = TitleBar->indexOf(TitleBar->button(ads::TitleBarButtonTabsMenu));
		TitleBar->insertWidget(Index + 1, CustomButton);
		return TitleBar;
	}
};

![grafik](https://github.com/user-attachments/assets/e2c02c91-8250-41b7-8da2-b56f45f1f50a)

```

**Comment by jankrassnigg** [comment]
Thanks for the tip, I didn't know about the factory yet. I guess I can use that to replace the CDockAreaTabBar.

I've hacked around a bit and gotten CDockAreaTabBar to contain a button. This is closer in behavior to what I am imagining. See the "+" button that moves with the tabs.

https://github.com/user-attachments/assets/f77c4500-6695-4631-b948-fa5efe8ef394
