### ISSUE TITLE
QDockManager causes a crash

### ISSUE THREAD

**Issue by 0x10AF3** [githubuser0xFFFF/Qt-Advanced-Docking-System#686]
I've been trying to copy everything from the example "simple" to my own project to test it out.
m_DockManager = new ads::CDockManager(this); 
I've been getting this output related to this ^^
18:21:36: Starting \lib\SimpleExample.exe...
18:21:37: The process crashed.
all the time. I looked thru everything and found nothing, decided to use the Debugger and the cause of the crash is:
Invalid address specified to RtlFreeHeap( 00000170D1840000, 00000170D1AEAED0 )

**Comment by githubuser0xFFFF** [comment]
I looks like you are doing something wrong. Sorry, but I cannot debug your application. Try to stay at close at possible to the demo application or to the simple example.

**Comment by 0x10AF3** [comment]
@githubuser0xFFFF is there a way to contact you to give you more details about what I'm doing?

**Comment by githubuser0xFFFF** [comment]
If you would like to have a commercial support contract you can ask for an offer.
