### ISSUE TITLE
Are nested CDockManagers supported ?

### ISSUE THREAD

**Issue by jankrassnigg** [githubuser0xFFFF/Qt-Advanced-Docking-System#688]
In our project we use one top-level CDockManager for the overall docking of documents and global panels. Inside documents we have additional panels that the user should be allowed to move around and dock, but when they dock them, of course they should only be allowed to dock inside the parent window.

So far we've used QMainWidget and QDockWidget here, so that I DONT have nested CDockManagers, but as a result the docking behavior differs depending on what widget you grab.

I've made an attempt to port the inner docking to CDockManager and it kinda works, but not completely.

When I undock a nested widget, the floating widget has an incorrect frame, it doesn't show a tab bar either. When docking back into the original location, it breaks even further.

So I've done some digging and ended up at the realization, that when I have any CDockWidget whose inner widget calls "winId", then all the OTHER CDockWidgets break when I undock them. So I searched a bit around and found this ticket: #189

I was then pretty surprised to find that you actually mentioned ezEngine as an example for it working :D
So that was a bit of a misunderstanding, I guess. Somehow our previous solution of having a QMainWindow inside the CDockWidget seems to have shielded ADS from this problem.

Here is a video (GitHub doesn't like .mkv, so unzip to watch).
[ADS nested.zip](https://github.com/user-attachments/files/18168290/ADS.nested.zip)

So
1. Are nested CDockManagers generally meant to work?
2. Do you have an idea why the call to winId results in these issues?

**Comment by jankrassnigg** [comment]
So by accident I figured out that there is a regression with newer Qt versions. Though no idea what the problem is.

What you see in the video above was recorded with Qt 6.8.1.
However, ezEngine typically uses Qt 6.4.0. And with that version it seems to be working fine.

**Comment by githubuser0xFFFF** [comment]
Nested `CDockManagers` are not supported officially by the library. But there is a sample **dockindock** contributed by a user that shows how to use nested CDockManagers.
