### ISSUE TITLE
Classes not exported into DLL.

### ISSUE THREAD

**Issue by tezma90** [githubuser0xFFFF/Qt-Advanced-Docking-System#70]
I was wondering why classes: CDockAreaTabBar, CDockAreaTitleBar, CElidingLabel are not exported into the DLL.
I was trying to get ads::CDockAreaTabBar::currentTab() and found out the class is not exported into the DLL, causing linker errors.

**Comment by githubuser0xFFFF** [comment]
Jus fixed this. Thank you for your bug report.
