### ISSUE TITLE
Need way to set QIcon for dock area title bar buttons and tab close button

### ISSUE THREAD

**Issue by nickdademo** [githubuser0xFFFF/Qt-Advanced-Docking-System#74]
Currently, we do something like this after initializing the dock system at app startup:
```
void setDockAreaButtons(ads::CDockAreaWidget *dockArea)
{
    auto closeButton = dockArea->titleBarButton(ads::TitleBarButtonClose);
    closeButton->setIcon(ToolButtonSvgIcon(ICON_CLOSE));
    auto undockButton = dockArea->titleBarButton(ads::TitleBarButtonUndock);
    undockButton->setIcon(ToolButtonSvgIcon(ICON_DETACH));
    auto tabsMenuButton = dockArea->titleBarButton(ads::TitleBarButtonTabsMenu);
    tabsMenuButton->setIcon(ToolButtonSvgIcon(ICON_DOWN_ARROW));
    tabsMenuButton->setToolTip(tr("List All Tabs"));
    for (auto tabCloseButton : dockArea->findChildren<QAbstractButton*>("tabCloseButton"))
    {
        tabCloseButton->setIcon(ToolButtonSvgIcon(ICON_CLOSE));
    }
}
```
This isn't ideal as any new dock areas created during run-time will then *not* have the correct icons. Our hacky solution is to react to certain ADS signals and call the above code again for newly-created dock areas.

So it would be nice to be able to set the button icons once at startup and have them apply for all dock areas - possibly via `CDockManager`?

Also, the same applies for the tooltips.

**Comment by githubuser0xFFFF** [comment]
Is it possible to change the icons via stylesheet?

**Comment by nickdademo** [comment]
Unfortunately, like before, we are using a QIcon with a SVG icon renderer
backend.

**Comment by githubuser0xFFFF** [comment]
Ok, I will thinhk about a good solution

**Comment by githubuser0xFFFF** [comment]
Just another question to understand this requirement better. 

Normally it is possible, to assign SVG icons via stylesheets but you cannot do this, because you change the color of the icon in your software - that means you have some kind of theming with a certain highlight color and you would like to render you icons with this color - is this right?

So how do you change or assign icons to other Qt Widgets like Menu Items, Toolbar, Checkboxes and Radio Buttons? Do you explicitely set the icon for all components?

**Comment by nickdademo** [comment]
@githubuser0xFFFF That's right. If possible, we set the QIcon on the widget :)

**Comment by githubuser0xFFFF** [comment]
I just created the branch IconProvider with a possible solution. The DockManager provides a global static IconProvider that enables registration of custom icons. Just register your icons with

```c++
CDockManager::iconProvider().registerCustomIcon(TabCloseIcon, MyIcon);
```
Please test the branch, if this solution will work for you.

**Comment by nickdademo** [comment]
@githubuser0xFFFF Many thanks! This works nicely. Just one change is needed (I added a commit to the  specific line). Also, I wonder if we can do a similar thing for the button tooltips?

**Comment by nickdademo** [comment]
Here is the required change: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/3ff154aff1d911a130d98bc1bf56df54089f187c#r35601859

**Comment by nickdademo** [comment]
@githubuser0xFFFF Do you plan to merge this feature branch? :) Or do you need me to test further?

**Comment by githubuser0xFFFF** [comment]
If you send me a pull request, I will merge it

**Comment by nickdademo** [comment]
@githubuser0xFFFF Here is the PR for the changes needed to the IconProvider branch: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/84/

**Comment by githubuser0xFFFF** [comment]
I just added a the new dockAreaCreated signal to CDockManager. This signal is emitted, whenever a new DockArea has been created. You can connect to this slot, to set custom icons and tooltips fot the DockArea titlebar buttons.

Please test, if this works for you and if I can close this issue

**Comment by nickdademo** [comment]
Great! So in addition to the IconProvider, this is another way of setting custom icons for the dock area?

**Comment by githubuser0xFFFF** [comment]
Yes, because you can access the DockArea you can customize icon and tooltip - I therefore think about removing the IconProvider

**Comment by githubuser0xFFFF** [comment]
Please test, if it works for you - then I can close this issue

**Comment by nickdademo** [comment]
I think it's good to leave in the IconProvider for now :) I'll let you know
how my testing goes and and will close the issue if everything is OK.
Thanks again.

**Comment by nickdademo** [comment]
@githubuser0xFFFF Everything works as expected (IconProvider). Thanks. I think the icon provider should be left in as it is a simpler way to set the icons, especially the TabClose icon.
