### ISSUE TITLE
Ability to destroy docks with close button

### ISSUE THREAD

**Issue by Astiolo** [githubuser0xFFFF/Qt-Advanced-Docking-System#79]
For my application I need the ability to create multiple copes of a type of dock and want the close button to actually delete them and have all signals and slots disposed of. I can destroy them manually but I don't know how to tell if a dock is being hidden due to that button press or if it's for another reason.

**Comment by Astiolo** [comment]
I found a way to get it to work. I'm using the ads::CDockWidget::closed signal, but that gets emitted by floating widgets when the application loses focus. So I keep track of when the application is losing or gaining focus with the QGuiApplication::applicationStateChanged and only destroy the docks if close is emitted while the application still has focus.

On a side note the floating docks that are hidden when losing focus are not restored when regaining focus. To solve that I save and restore the layout on losing and gaining focus respectively.

**Comment by So1ange** [comment]
I am very interested in this enhancement as well. I am trying to replace MDI interface with ADS. It seems to be impossible to implement it without destroying docks.

**Comment by So1ange** [comment]
Also it is very inconvenient to get viewToggled signal on closing CDockAreaWidget. It causes an exception when trying to handle the closed signal and delete the relevant widget.

**Comment by githubuser0xFFFF** [comment]
The latest commit added the new DockWidget flag `DockWidgetDeleteOnClose`. This deletes the dock widget if the user closes a dock widget or if the user closes a floating widget that only contains one visible dock widget. See the demo for details.
