### ISSUE TITLE
Bring Existing Dock to Front

### ISSUE THREAD

**Issue by hhslepicka** [githubuser0xFFFF/Qt-Advanced-Docking-System#87]
Hi,

How can I bring an existing dock to front/set focus?
I can query the dock manager for docks with the `findDockWidget` but with the dock in hand how can I set it to be the current?

My use-case is:
- I have button that creates a dock and gives it a name...
- If I press this button again I don't want to create a new dock but instead bring to front or somehow set the active tab to be the existing dock.

Thank you!

**Comment by hhslepicka** [comment]
I ended up finding the answer...
I can reach the dockArea via the dockArea method at the dock manager and with the dockArea I can `setCurrentDockWidget` passing as an argument the `dock` that I have from the `findDockWidget` method.

**Comment by githubuser0xFFFF** [comment]
It is even easier than your solution: just call toggleView(true) of the DockWidget. This will make the DockWidget the current one in the DockArea

**Comment by hhslepicka** [comment]
Awesome! I will give it a try. Thanks
