### ISSUE TITLE
Dragging floating widgets broken in OSX

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#88]
Hi, I was trying out your docking system, amazing job.
It works perfectly in Windows, but in OSX there is this issue that while dragging floating widgets they go to the background of the application for some reason. It is a deal breaker for me. 

I recorded a video and attached it in a zip file.
[osx_issue.mov.zip](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/3955950/osx_issue.mov.zip)

I hope you can see the problem in the video recording.

**Comment by rolivav** [comment]
By the way this happens both in OSX Mojave and Catalina.

**Comment by githubuser0xFFFF** [comment]
Sorry,  I do not have access to a Mac and therefore I cannot fix this problem.

**Comment by rolivav** [comment]
Hey I fixed the issue. I tried creating a branch in this repo but it did not work. Do I need to make a fork?

**Comment by githubuser0xFFFF** [comment]
Yes, you need to create a fork, fix it in your fork and then create a pull request for this repo

**Comment by rolivav** [comment]
Done https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/88 :)

**Comment by githubuser0xFFFF** [comment]
Thank you for your help.
