### ISSUE TITLE
How do I Tabify?

### ISSUE THREAD

**Issue by offdesk** [githubuser0xFFFF/Qt-Advanced-Docking-System#9]
Thank you for your efforts; the docking system rewrite is brilliant. Can you tell me how I can Tabify?

I have two docks: <b>dockStepDetails</b> and <b>dockLib</b>. 
As you know in the original QT docking I can stack a newly created tab onto an existing one like so:
<pre>
MainWindow::tabifyDockWidget(dockLib, dockStepDetails);
</pre>

To stack the dockLib onto the existing dockSequencMan I tried to use your <b>insertDockWidget</b>:
<pre>
dockSequenceMan->dockAreaWidget()->insertDockWidget(dockSequenceMan->dockAreaWidget()->count(), dockLib, false);
</pre>
Although it initializes the docks correctly, I get an application crash if I try to drag tabs. Did I find a bug? Is this the proper way to tabify?

Thanks much

**Comment by githubuser0xFFFF** [comment]
Hi,

the example application shows how to insert a dock widget tabified. A dockwidget will be inserted tabified, if you insert it into the **CenterDockWidgetArea** of an existing **DockArea**. That means, for example, you first insert a dock widget into the **TopDockWidgetArea** via **addDockWidget()**. This function will return the created **DockArea** object. Now you can add another dock widget to this dock area tabified, by calling **addDockWidget()** with the just created DockArea and the **CenterDockWidgetArea**. The following snippet from the examples will show this:

```cpp
auto FileSystemWidget = createFileSystemTreeDockWidget(ViewMenu);
FileSystemWidget->setFeature(ads::CDockWidget::DockWidgetMovable, false);
auto TopDockArea = DockManager->addDockWidget(ads::TopDockWidgetArea, FileSystemWidget);
DockWidget = createCalendarDockWidget(ViewMenu);
DockWidget->setFeature(ads::CDockWidget::DockWidgetClosable, false);
DockManager->addDockWidget(ads::CenterDockWidgetArea, DockWidget, TopDockArea);
```

**Comment by offdesk** [comment]
Excellent. I got it working. Thanks a lot!
