### ISSUE TITLE
Possible for an opaque dock to remain in the non-opaque floating state

### ISSUE THREAD

**Issue by nickdademo** [githubuser0xFFFF/Qt-Advanced-Docking-System#91]
A bit of a corner case:

If you start dragging an non-opaque dock and then do an `Alt+Tab` while still dragging, the dock does not undock and remains in the floating non-opaque state. Pressing close on this window crashes the application at `CDockWidgetTab::mouseReleaseEvent`:
```
    case DraggingFloatingWidget:
    	 d->FloatingWidget->finishDragging(); // access violation
    	 break;
```

The cause seems to be a missing mouseReleaseEvent to finish the dragging.

**Comment by githubuser0xFFFF** [comment]
Do you mean non-opaque docking?

**Comment by nickdademo** [comment]
> Do you mean non-opaque docking?

Yup, sorry for the confusion.

**Comment by githubuser0xFFFF** [comment]
I just comitted some changes that should fix this issue - please test it.

**Comment by nickdademo** [comment]
Tested and fixed! Thanks!
