### ISSUE TITLE
Versioneer for setup.py

### ISSUE THREAD

**Issue by hhslepicka** [githubuser0xFFFF/Qt-Advanced-Docking-System#93]
Hi,

I noticed that the setup.py file has a hardcoded version string that gets out of date with the project tag.

If you agree, I would like to add a PR which adds support for Versioneer (https://github.com/warner/python-versioneer) and deals automatically with the version based on the tag and number of commits and make the proper version file.

I just don't think that it can dump as much information as there is now but users would be able to just get a reliable version string automatically and that would reduce the work for new releases.

**Comment by githubuser0xFFFF** [comment]
Please create the pull request
