### ISSUE TITLE
Performance Enhancement

### ISSUE THREAD

**Issue by jz-123** [githubuser0xFFFF/Qt-Advanced-Docking-System#98]
Hi,

I mentioned in an earlier crash report that my software is very busy, and has many signals / events occurring, which may have attributed to the crash I was seeing.  I have been doing some further investigation, and have noticed that there are two calls to qApp->installEventFilter (one in each of CFloatingDockContainer and CFloatingOverlay constructors).  In complex systems, this can cause a noticable performance hit! 

I see the comments about the release mouse event not detected when the floating widget is behind the drop overlay cross - not sure if this is specifically needed for non-windows OS (I am only testing on Windows), however I have tried a different approach as shown below:

```
void CDockWidgetTab::mouseReleaseEvent(QMouseEvent* ev)
{
   // End of tab moving, emit signal
   if (d->isDraggingState(DraggingTab) && d->DockArea)
   {
      emit moved(ev->globalPos());
   }
   // Start of my code:
   else if (d->isDraggingState(DraggingFloatingWidget))
   {
      if (d->FloatingWidget)
      {
         d->FloatingWidget->finishDragging();
      }
   }
   // End of my code:

   d->DragStartMousePosition = QPoint();
   d->DragState = DraggingInactive;
   Super::mouseReleaseEvent(ev);
}
```

and
```
void CDockAreaTabBar::mouseReleaseEvent(QMouseEvent* ev)
{
   if (ev->button() == Qt::LeftButton)
   {
      ADS_PRINT("CTabsScrollArea::mouseReleaseEvent");
      ev->accept();
      // Start of my code:
      if (d->FloatingWidget)
      {
         d->FloatingWidget->finishDragging();
      }
      // End of my code:
      d->FloatingWidget = nullptr;
      d->DragStartMousePos = QPoint();
      return;
   }
   QScrollArea::mouseReleaseEvent(ev);
}
```
I added the bolded code (and supporting code elsewhere to allow it to be called).  Notably I add the call "d->titleMouseReleaseEvent();" to the CFloatingDockContainer::finishDragging function, and add an empty "void draggingFinished() {}" call to the IFloatingWidget abstract class.

I have commented out the qApp->installEventFilter calls and I have the same behaviour as before.

Maybe there are reasons this approach will not work, but it has improved the performance for my application.

**Comment by githubuser0xFFFF** [comment]
Please test the master branch - it does not contain the qApp->installEventFilter calls

**Comment by jz-123** [comment]
Ah sorry!  Was running the last release (2.7).  Thanks!
