### ISSUE TITLE
QAxWidget added to CDockManager Causes issues.

### ISSUE THREAD

**Issue by jz-123** [githubuser0xFFFF/Qt-Advanced-Docking-System#99]
Hi,

I have been tracking down a bug with the behaviour of floating windows using ADS. There are 3 behaviours which I have noticed that are not desirable, and both are present afterdetaching a docked window. The three noted behaviours are:

1) Moving the main window caused the floating window to move.
2) Resizing the floating window causes it to move
3) Closing the floating window (click the [ X ] button), causes the float dock contents to disappear permanently (upon showing).  (note: if the window is hidden via the menu it does not display this behaviour).

It has taken me a couple weeks to narrow down the cause of the behaviour, and it is related to a QAxWidget we use.  This widget forces the use of native windows (Qt::WA_NativeWindow attribute gets set).  When this widget is added to the ads::CDockManager, the dock manager sets this, and it causes extra messages to be sent to the children widgets.  This includes some mouse move events (ie: items 1 and 2 above) as well as the hideEvent.  

I have added a QAxWidget to the test app and have it load a windows media player activeX control.  I do nothing else with it, and the demo app exhibits the behaviours mentioned above.  

You will need to add axcontainer to the demo.pro file (QT += core gui widgets axcontainer), `#include <QAxWidget>` to the MainWindow.cpp file, and of course call the function below to add the window somewhere in the app.

```
static ads::CDockWidget* createActiveXWidget(QMenu* ViewMenu, QWidget* parent = nullptr)
{
   static int ActiveXCount = 0;
   QAxWidget* w = new QAxWidget("{6bf52a52-394a-11d3-b153-00c04f79faa6}", parent);
   ads::CDockWidget* DockWidget = new ads::CDockWidget(QString("Active X %1").arg(ActiveXCount++));

   DockWidget->setWidget(w);
   ViewMenu->addAction(DockWidget->toggleViewAction());
   return DockWidget;
}
```

As a test I detach the "Filesystem" window, then test 1, 2, and 3 above.

Thanks,

Jonathan

**Comment by githubuser0xFFFF** [comment]
Hi,

I could nox exactly reproduce the problems in 1. and 2. but I could see some strange behaviour similar to your description. I could solve this problem by switching to non-opaque undocking by enabling the following line in demo main.cpp:

`CDockManager::setConfigFlags(CDockManager::DefaultNonOpaqueConfig);`

I could fix the issue 3. by changing the FloatingDockContainer close() function. You can test the branch qaxwindow. Just switch to this branch, compile and everything should work.

**Comment by jz-123** [comment]
Thanks! These updates have resolved the issues I had been seeing.
